### ISSUE TITLE
关于AttentionLayer.forward()中的view函数的问题

### ISSUE THREAD

**Issue by RootChenLQ** [zhouhaoyi/Informer2020#100]
感谢作者慷慨的公开代码和数据集！！！
有一个小问题，tensor.view函数是将张量展开为一维，然后重新设置各维度大小。
在AttentionLayer.forward()中171行，作者使用 out = out.view(B, L, -1)是否会改变破坏合并多头注意力值得目的。
是否先做permute()转换维度比较合适？
期待作者得回复！ 希望informer模型在时序预测领域发扬光大！冲冲冲

**Comment by cookieminions** [comment]
非常感谢你对我们工作的关注！
我们修复了ProbSparse Attn中存在的问题，在ProbAttention中对返回的context做了permute，再次感谢提醒！

**Comment by QuantHao** [comment]
我当时看code的时候也有同样的疑惑，感谢修复。

**Comment by cookieminions** [comment]
> 我当时看code的时候也有同样的疑惑，感谢修复。

我们最初实验的代码和github repo上的代码风格是有差别的，在重构代码的过程中还是会发生一些错误，真的非常感谢大家提醒

**Comment by QuantHao** [comment]
> > 我当时看code的时候也有同样的疑惑，感谢修复。
> 
> 我们最初实验的代码和github repo上的代码风格是有差别的，在重构代码的过程中还是会发生一些错误，真的非常感谢大家提醒

一个好汉三个帮嘛哈哈哈哈
