### ISSUE TITLE
inverse transform issue

### ISSUE THREAD

**Issue by xinli-temple** [zhouhaoyi/Informer2020#101]
Hi, Haoyi. Great research work!!

I have a little question about inverse transform. When 'inverse' = True, the data loader will return untransformed data_y. Could you help me understand why we still need to call inverse_transform(outputs) ?

Thanks.

**Comment by cookieminions** [comment]
Because the input of model is transformed and we hope the data scale between model's output and input do not differ too much, so we call inverse_transform on model's output.

**Comment by xinli-temple** [comment]
> Because the input of model is transformed and we hope the data scale between model's output and input do not differ too much, so we call inverse_transform on model's output.

Thanks for the reply. When inverse = True, decoder input (X_token) is not transformed. Will decoder outputs be in the same untransformed space as decoder input?

**Comment by cookieminions** [comment]
> > Because the input of model is transformed and we hope the data scale between model's output and input do not differ too much, so we call inverse_transform on model's output.
> 
> Thanks for the reply. When inverse = True, decoder input (X_token) is not transformed. Will decoder outputs be in the same untransformed space as decoder input?

Thanks for your remind, this is our negligence, we will fix this problem in the next update.
