### ISSUE TITLE
About the performance of Informer after the latest commit (410535e)

### ISSUE THREAD

**Issue by martinwhl** [zhouhaoyi/Informer2020#102]
Hi,

Thanks for the great work on LSTF. The latest commit solves issue #100 ; however, with the default hyperparameter settings you provided in the `scripts/` folder, it seems that the performance of the model declines after this commit. Should I change my hyperparameter settings?

Thanks in advance.

**Comment by cookieminions** [comment]
It's an interesting phenomenon, the parameters of model should change after we modify the code, and we will conduct further research on it later.

**Comment by zhouhaoyi** [comment]
We will update a hot-fix later, so there is no more discussion on this issue. I will close now.

**Comment by martinwhl** [comment]
Just a quick check... it's been a month now, I'm just wondering if there's any plan for this update.

**Comment by cookieminions** [comment]
> Just a quick check... it's been a month now, I'm just wondering if there's any plan for this update.

Please check the current code, we made a simple fix, using the correct self-attn in the encoder, and using a mixed form of self-attn in part of the generative decoder.

Experiments show that this accidental error-mixed self-attn is effective for generative decoders, and has little effect on the encoder. The reason may be that the prediction sequence is filled with zeros and it is related to the features obtained by the FNN after self-attn. We will publish this in future research.

**Comment by martinwhl** [comment]
> > Just a quick check... it's been a month now, I'm just wondering if there's any plan for this update.
> 
> Please check the current code, we made a simple fix, using the correct self-attn in the encoder, and using a mixed form of self-attn in part of the generative decoder.
> 
> Experiments show that this accidental error-mixed self-attn is effective for generative decoders, and has little effect on the encoder. The reason may be that the prediction sequence is filled with zeros and it is related to the features obtained by the FNN after self-attn. We will publish this in future research.

Thanks for your reply.
