### ISSUE TITLE
Ways to calculate mean(S)

### ISSUE THREAD

**Issue by victorxie996** [zhouhaoyi/Informer2020#103]
Hi, thank you for your very neat published code and your paper again!

I would like to raise a question in line 59,  attn.py(https://github.com/zhouhaoyi/Informer2020/blob/410535ebeb59e526a7402e0454235fe1cab83605/models/attn.py#L59), the mean(S) is calculated as torch.div(Q_K_sample.sum(-1), L_K), why not use Q_K_sample.mean(-1)[0] just like the same way we compute max(S) as Q_K_sample.max(-1)[0]?

**Comment by cookieminions** [comment]
Hi, thanks for your attention, and it's okay to use `mean` here.

**Comment by victorxie996** [comment]
Thank you for your update!
