### ISSUE TITLE
multiple time series

### ISSUE THREAD

**Issue by jwyyy** [zhouhaoyi/Informer2020#105]
Hi, I am wondering how the informer handles multiple time series. I understand that I can simply combine them and treat it as a multi-dimensional time series. However, my current problem is: (1) the total length of my time series is about 2000 (2) I have 30000+ different time series. Should I combine them and treat it as a 30000+dimensional time series of length 2000? Or is it a better idea to incorporate the difference of each 30000+ time series?

**Comment by cookieminions** [comment]
Hi, 

If each time series has only one feature, maybe you can treat all time series as one large multi-dimensional time series, and each time series is one feature of this large sequence. (in your example: 30000+features with 2000 length)

If your time series have many features, and there are spatial connections between different time series, maybe you can try to use graph convolution or graph attention with our model.

This is just a simple suggestion, hope it can help you.

**Comment by jwyyy** [comment]
That's what I was looking for! Thank you very much for your suggestion!
