### ISSUE TITLE
LSTMa and DeepAR

### ISSUE THREAD

**Issue by 0fine0** [zhouhaoyi/Informer2020#107]
Hi, may I know if you can release the codes about the LSTMa and DeepAR in your experiements?

**Comment by zhouhaoyi** [comment]
We strongly recommend you GEEKs follow the original author's code and parameter tunning, which is exactly what we did in the experiments. We are not the right person to publish that. Thanks for understanding.

**Comment by 0fine0** [comment]
Thanks for you advice :)
