### ISSUE TITLE
归一化的问题

### ISSUE THREAD

**Issue by Erickurashi** [zhouhaoyi/Informer2020#108]
您好，
我的初始数据的范围是-0.2到0.2，但预测和groundtruth输出结果的范围却是-2.5到2.5. 请问如何把输出范围还原成初始的范围？谢谢！

**Comment by zhouhaoyi** [comment]
请参考 issue #99 后半部分的一些讨论。

**Comment by Erickurashi** [comment]
> 请参考 issue #99 后半部分的一些讨论。

谢谢，dataloader里的inverse设置我都从false改为true，但是输出结果还是和之前一样，请问有什么其他设置需要更改？

**Comment by wfnian** [comment]
> > 请参考 issue #99 后半部分的一些讨论。
> 
> 谢谢，dataloader里的inverse设置我都从false改为true，但是输出结果还是和之前一样，请问有什么其他设置需要更改？

你可以在参数里面添加一项  **--inverse**

**Comment by Erickurashi** [comment]
> > > 请参考 issue #99 后半部分的一些讨论。
> > 
> > 
> > 谢谢，dataloader里的inverse设置我都从false改为true，但是输出结果还是和之前一样，请问有什么其他设置需要更改？
> 
> 你可以在参数里面添加一项 **--inverse**

您好，谢谢您的建议，请问inverse要怎么添加在参数？Dataset_Custom和Dataset_Pred中的已经有一项inverse。

class Dataset_Custom(Dataset):
    def __init__(self, root_path, flag='train', size=None, 
                 features='S', data_path='filterhigh2.csv', 
                 target='elevation', scale=True, inverse=True, timeenc=0, freq='h'):

class Dataset_Pred(Dataset):
    def __init__(self, root_path, flag='pred', size=None, 
                 features='S', data_path='filterhigh2.csv', 
                 target='elevation', scale=True, inverse=True, timeenc=0, freq='h'):

**Comment by wfnian** [comment]
> > > > 请参考 issue #99 后半部分的一些讨论。
> > > 
> > > 
> > > 谢谢，dataloader里的inverse设置我都从false改为true，但是输出结果还是和之前一样，请问有什么其他设置需要更改？
> > 
> > 
> > 你可以在参数里面添加一项 **--inverse**
> 
> 您好，谢谢您的建议，请问inverse要怎么添加在参数？Dataset_Custom和Dataset_Pred中的已经有一项inverse。
> 
> class Dataset_Custom(Dataset):
> def **init**(self, root_path, flag='train', size=None,
> features='S', data_path='filterhigh2.csv',
> target='elevation', scale=True, inverse=True, timeenc=0, freq='h'):
> 
> class Dataset_Pred(Dataset):
> def **init**(self, root_path, flag='pred', size=None,
> features='S', data_path='filterhigh2.csv',
> target='elevation', scale=True, inverse=True, timeenc=0, freq='h'):

这里我是指args参数
![image](https://user-images.githubusercontent.com/18214955/115131446-c9d23800-a02a-11eb-93c3-17ad0a17d6e8.png)

**Comment by Erickurashi** [comment]
> > > > > 请参考 issue #99 后半部分的一些讨论。
> > > > 
> > > > 
> > > > 谢谢，dataloader里的inverse设置我都从false改为true，但是输出结果还是和之前一样，请问有什么其他设置需要更改？
> > > 
> > > 
> > > 你可以在参数里面添加一项 **--inverse**
> > 
> > 
> > 您好，谢谢您的建议，请问inverse要怎么添加在参数？Dataset_Custom和Dataset_Pred中的已经有一项inverse。
> > class Dataset_Custom(Dataset):
> > def **init**(self, root_path, flag='train', size=None,
> > features='S', data_path='filterhigh2.csv',
> > target='elevation', scale=True, inverse=True, timeenc=0, freq='h'):
> > class Dataset_Pred(Dataset):
> > def **init**(self, root_path, flag='pred', size=None,
> > features='S', data_path='filterhigh2.csv',
> > target='elevation', scale=True, inverse=True, timeenc=0, freq='h'):
> 
> 这里我是指args参数
> ![image](https://user-images.githubusercontent.com/18214955/115131446-c9d23800-a02a-11eb-93c3-17ad0a17d6e8.png)

非常感谢！
