### ISSUE TITLE
Hyper-params setup for heads and value/key dimension

### ISSUE THREAD

**Issue by victorxie996** [zhouhaoyi/Informer2020#109]
Hi, I found the hyper parameter setup for number of heads and value/key dimension in ProbSparse Self-Attention Block in Table 7 from the paper is set as h=16 & d=32. The HP setup in the source code is h=8, d=64 as expected. Is the design (h=16, d=32) in the paper has a specific reason?

Thanks

**Comment by cookieminions** [comment]
Hi,

In github repo, we follow the vanilla Transformer setting and set `h=8` and `d=64`. And we can also using more heads to increase the expression diversity of multi-heads by setting a larger `h`.

**Comment by victorxie996** [comment]
Hi, just want to clearify the original question: in the github repo, both encoder attn set h=8 & d=64; while in the paper encoder sets h= 16 & d= 32, decoder attn sets h= 8 & d= 64, the hyper-params are not consistent in encoder and decoder. Is this setting in the paper due to doubling h and halving d in encoder leads to better result?

Thanks

**Comment by cookieminions** [comment]
Yes, you can also adjust the hyperparameter according to your specific data and task. For example, you can set `h=16` and `d_model=1024` to make `d_k=64`.

**Comment by victorxie996** [comment]
Thanks for your help!
