### ISSUE TITLE
修改时所遇到的问题

### ISSUE THREAD

**Issue by SSSUNSHINNING** [zhouhaoyi/Informer2020#110]
for i, (batch_x,batch_y,batch_x_mark,batch_y_mark) in enumerate(train_loader):
这句在exp_informer.py文件中，上面括号里的四个具体指的是什么，因为在train_loader原始形式中是
```
 data_loader = DataLoader(
            data_set,
            batch_size=batch_size,
            shuffle=shuffle_flag,#每次epoch开始前是否重新对数据进行排序
            num_workers=args.num_workers,
            drop_last=drop_last)
```
不知道具体返回的是什么

**Comment by cookieminions** [comment]
dataloader部分的加载可以参考代码`data/data_loader.py`

https://github.com/zhouhaoyi/Informer2020/blob/410535ebeb59e526a7402e0454235fe1cab83605/data/data_loader.py#L79-L90

batch_x指输入Encoder的序列，长度为seq_len，batch_y为输入Decoder的start token和预测序列的拼接，长度为label_len+pred_len
batch_x_mark为batch_x对应的时间戳信息，batch_y_mark为batch_y对应的时间戳信息
