### ISSUE TITLE
关于参数设置的问题

### ISSUE THREAD

**Issue by RootChenLQ** [zhouhaoyi/Informer2020#111]
Haoyi, 你好，再次感谢你们的分享。
在复现Informer的时候，使用scripts中提供的脚本，无法实现论文中的性能。作者是否可以提供论文中实验的具体参数，或者对超参数调整提供一些建议？
万分感谢！！

**Comment by cookieminions** [comment]
关于实验结果的问题请参考issue https://github.com/zhouhaoyi/Informer2020/issues/102，你可以暂时回退到上一个commit版本来测试script中的脚本，此外对于这个问题我们会在不久后就推出新的修复

**Comment by RootChenLQ** [comment]
好的，期待你们的修复。万分感谢
