### ISSUE TITLE
embed选项疑问

### ISSUE THREAD

**Issue by pxlsdz** [zhouhaoyi/Informer2020#114]
您好，time features encoding, options:[timeF, fixed, learned]，可以解释这三个选项分别代表什么吗？

**Comment by cookieminions** [comment]
这三个选项是我们在实验过程中设计的三种不同的编码方式，我们建议直接使用timeF编码，它是将时间戳拆解为月、日、周、小时、分钟等特征，然后将值缩放为[-0.5,0.5]的小数；fixed编码同样是拆解为各类特征，但是会将其对应的整数用positional encoding的方式进行编码，learned编码同样是拆解为各类特征，不过会将其对应的整数使用Embedding进行学习，在训练过程中动态调整

**Comment by pxlsdz** [comment]
好的，十分感谢您的解答！
