### ISSUE TITLE
Storing/Loading  trained model and Obtaining unscaled predictions

### ISSUE THREAD

**Issue by andresC98** [zhouhaoyi/Informer2020#115]
Hi! First of all, thanks for the amazing work done on this paper and implementation!

I have two questions I haven't been able to obtain the answer so far:

1. It is possible to save the model once trained so that later I can load it?
2. When inspecting the true/predicted series with `preds = np.load('./results/'+setting+'/pred.npy')`... a scaled version of both the predictions and the ground truth target is obtained. Is it possible to obtain the original (unscaled) ones? (in other words, where can I obtain the mean/std values for doing the inverse transformation?

Thanks in advance!

**Comment by cookieminions** [comment]
Hi, 
1. The model will be saved in folder `{args.checkpoints}/{setting}/`, you can use `--checkpoints XXX` to set `args.checkpoints` and `setting` is generated according to your experiment setting. You can refer to code `exp/exp_informer.py` line 245 to get more information about loading model

https://github.com/zhouhaoyi/Informer2020/blob/410535ebeb59e526a7402e0454235fe1cab83605/exp/exp_informer.py#L245-L246

2. You can use `dataset.inverse_transform(data)` to inverse transform scaled data, or you can use `--inverse` to run an unscaled data training experiment. Please refer to code `data/data_loader.py` and `utils/tools.py` to get more information.

https://github.com/zhouhaoyi/Informer2020/blob/410535ebeb59e526a7402e0454235fe1cab83605/data/data_loader.py#L95-L96

https://github.com/zhouhaoyi/Informer2020/blob/410535ebeb59e526a7402e0454235fe1cab83605/utils/tools.py#L56-L73

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion. I will close this issue now.
