### ISSUE TITLE
Typo in colab

### ISSUE THREAD

**Issue by kryptonite0** [zhouhaoyi/Informer2020#116]
In the `Informer.ipynb`, there seems to be a missing `e` at this line:
```
args.dvices = args.devices.replace(' ','')
```

**Comment by cookieminions** [comment]
Thank you very much for your reminder, and we have fixed this problem in colab and `main_informer.py`.

**Comment by HuiminFeng66** [comment]
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/论文/时间序列预测相关论文/Informer相关代码/Informer2020-main/main_informer.py", line 96, in <module>
    exp = Exp(args) # set experiments
  File "C:\Users\admin\Desktop\论文\时间序列预测相关论文\Informer相关代码\Informer2020-main\exp\exp_informer.py", line 23, in __init__
    super(Exp_Informer, self).__init__(args)
  File "C:\Users\admin\Desktop\论文\时间序列预测相关论文\Informer相关代码\Informer2020-main\exp\exp_basic.py", line 9, in __init__
    self.model = self._build_model().to(self.device)
  File "C:\Users\admin\Desktop\论文\时间序列预测相关论文\Informer相关代码\Informer2020-main\exp\exp_informer.py", line 57, in _build_model
    return model
UnboundLocalError: local variable 'model' referenced before assignment

can you help me to solve this problem?

**Comment by zhouhaoyi** [comment]
Please follow the colab examples. It seems that the model is missing.

**Comment by ayay-7591** [comment]
> 回溯（最近一次调用）： 文件 “C：/Users/admin/Desktop/论文/时间序列预测相关论文/Informer相关代码/Informer2020-main/main_informer.py”， 第 96 行， in exp = Exp（args） # 设置实验 文件 “C：\Users\admin\Desktop\论文\时间序列预测相关论文\Informer相关代码\Informer2020-main\exp\exp_informer.py”， 第 23 行， in **init** super（Exp_Informer， self）.**init**（args） 文件 “C：\Users\admin\Desktop\论文\时间序列预测相关论文\Informer相关代码\Informer2020-main\exp\exp_basic.py”，第 9 行，**init** self.model = self._build_model（）.to（self.device） 文件 “C：\Users\admin\Desktop\论文\时间序列预测相关论文\Informer相关代码\Informer2020-main\exp\exp_informer.py”，第 57 行，_build_model返回模型中 UnboundLocalError：局部变量 'model' 在赋值前引用
> 
> 您能帮我解决这个问题吗？
你好，请问这个问题解决了吗，我正在被这个问题困扰，我的qq为2055148501，非常感谢

**Comment by ayay-7591** [comment]
> 回溯（最近一次调用）： 文件 “C：/Users/admin/Desktop/论文/时间序列预测相关论文/Informer相关代码/Informer2020-main/main_informer.py”， 第 96 行， in exp = Exp（args） # 设置实验 文件 “C：\Users\admin\Desktop\论文\时间序列预测相关论文\Informer相关代码\Informer2020-main\exp\exp_informer.py”， 第 23 行， in **init** super（Exp_Informer， self）.**init**（args） 文件 “C：\Users\admin\Desktop\论文\时间序列预测相关论文\Informer相关代码\Informer2020-main\exp\exp_basic.py”，第 9 行，**init** self.model = self._build_model（）.to（self.device） 文件 “C：\Users\admin\Desktop\论文\时间序列预测相关论文\Informer相关代码\Informer2020-main\exp\exp_informer.py”，第 57 行，_build_model返回模型中 UnboundLocalError：局部变量 'model' 在赋值前引用
> 
> 您能帮我解决这个问题吗？
你好，请问这个问题解决了吗，我正在被这个问题困扰，我的qq为2055148501，非常感谢
