### ISSUE TITLE
预测问题

### ISSUE THREAD

**Issue by posea261** [zhouhaoyi/Informer2020#117]
您好，请问如果seq_len = 100， label_len = 100， pred_len = 100 是不是这pred_len的100个预测数据只是从之前seq_len的100个数据通过训练过的informer模型预测出来的。而训练的数值并没有用在预测中使用。不知道我理解的是否正确。 谢谢。

**Comment by cookieminions** [comment]
关于输入数据和预测数据，如果用日期举例，例如输入seq_len的数据是[2021-01-01, 2021-03-01]，那么pred_len的数据就是紧接着的[2021-03-02, 2021-04-01]（以天为单位）
对于模型来说，训练数据是用来不断优化更新模型参数，你可以理解为模型曾经见过的数据都在它的参数中储存了下来；在进行实际的预测时，其输入即便没有在训练数据中出现过，模型也能正常进行预测

**Comment by posea261** [comment]
谢谢您的回答
