### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by MLnoob128** [zhouhaoyi/Informer2020#119]
from utils.tools import StandardScaler
ModuleNotFoundError: No module named 'utils.tools'
我该怎么解决

**Comment by zhouhaoyi** [comment]
请确保整个project更新到了最新的commit。

**Comment by MLnoob128** [comment]
非常感谢，解决了！

发送自 Windows 10 版邮件应用

发件人: Haoyi
发送时间: 2021年4月27日 19:00
收件人: zhouhaoyi/Informer2020
抄送: MLnoob128; Author
主题: Re: [zhouhaoyi/Informer2020] Run Error (#119)

请确保整个project更新到了最新的commit。
