### ISSUE TITLE
长间隔单步预测问题

### ISSUE THREAD

**Issue by Jiangxuempire** [zhouhaoyi/Informer2020#120]
非常感谢作者的分享，我想用Informer来实现长间隔单步预测的问题，举个例子，比如当前为t交易日，用前10个交易日的股票的开高收低日频价格这四个特征，预测第t+5个交易日的收盘价，时间间隔为5个交易日，这个问题是不是和论文里面Ablation study中的Prediction offset类似？如果类似的话，想问一下代码中是如何实现的，我尝试修改了一下data_loader.py中的__getitem__()函数，如下图，不知道是否正确，请作者指点一下，非常感谢！
![image](https://user-images.githubusercontent.com/43981960/116334675-30fca300-a808-11eb-8132-21c4aa5b4926.png)

**Comment by cookieminions** [comment]
我们的ablation study中的间隔预测，是指encoder的输入序列与decoder的预测序列的时间存在间隔，但是decoder的输入中包含了start token，这个start token仍然是需要和预测序列相邻的。即我们能够让encoder和decoder的输入序列不再需要相邻，但是decoder本身的start token还是需要作为一个对预测序列的启发和引导，因此需要和预测序列相邻；如我们使用 [t-10,t] 作为Encoder的输入，但是decoder输入需要 [t+5-label_len, t+5]作为start token，去预测 t+5
对于你的问题，我们认为是可以通过你目前已经改动的代码实现需求的，只是在实际预测时，需要注意能够提供 t+5时刻的前label_len个时间点的数值

**Comment by Jiangxuempire** [comment]
好的，谢谢作者指点 ！

**Comment by kuraoumu** [comment]
@Jiangxuempire 您好，我也在尝试使用informer做金融相关的预测，我看到您的数据集长度应该也很短，不知您在训练模型有没有遇到过__len__() should return >= 0的问题？
