### ISSUE TITLE
Prob-SelfAttention的问题，请求大佬解答

### ISSUE THREAD

**Issue by Kuzma1998** [zhouhaoyi/Informer2020#121]
我用我的数据，用传统Transformer进行预测，取出的attention score是服从正太分布的，不符合长尾分布，但是我把Transformer的标准多头注意力机制换成informer中的Prob-selfattention之后效果好了不少，请问这是什么原因呢

**Comment by zhouhaoyi** [comment]
请务必先翻阅一下之前的issue，虽然close了，但是依然有很大参考价值。
我们的Informer的sparse机制一定程度上可以看成对于时间输入项的降噪，把一些不需要考虑的点去除掉了。同时我们的input表示对最终结果也有一定提升效果。程序里面其他的一些trick你也可以关注一下。
