### ISSUE TITLE
训练预测问题

### ISSUE THREAD

**Issue by Terrygth** [zhouhaoyi/Informer2020#122]
作者，你好！我发现，使用你提供的数据训练，每个epoch输出的val_loss和test_loss没有明显的下降，有时候还会上升。请问这是正常现象吗？还是哪里出了一些问题？
Epoch: 1, Steps: 266 | Train Loss: 0.3823095 Vali Loss: 0.6652329 Test Loss: 0.6268310
Epoch: 2, Steps: 266 | Train Loss: 0.2566502 Vali Loss: 0.6658759 Test Loss: 0.6883199
Epoch: 3, Steps: 266 | Train Loss: 0.2059148 Vali Loss: 0.6526757 Test Loss: 0.7069948
然后我自己的数据集的结果也是类似的。
谢谢你啦！

**Comment by cookieminions** [comment]
你好，这个问题在我们的上上次commit中能够得到解决，在现在这个版本的基础上你可以修改代码`models/attn.py`中的line125
https://github.com/zhouhaoyi/Informer2020/blob/2a9714cbd8151356bcf89808a434d44427352315/models/attn.py#L125
为`return context.transpose(2,1).contiguous(), attn`

当前版本的代码可能会存在只在前几个epoch时validation loss下降的问题，当然这个结果也与validation set的选择有关。这个原因是目前代码的attn部分采用了的trick，其能够增加预测准确度和画图准确度，但同时会因为位置信息的混淆导致validation loss下降存在一定问题，我们也对这个现象进行了实验和研究，并会在之后更新研究结果

**Comment by cookieminions** [comment]
我们已经更新了一版代码，对于validation loss下降问题的解决会有所帮助，当然该问题与validation的选择也有一定关系，在ETTh和ECL或ETTm数据集上的表现都会不同

**Comment by Terrygth** [comment]
请问上上次commit是哪一次呀？这个版本有点多了。谢谢！

**Comment by cookieminions** [comment]
> 请问上上次commit是哪一次呀？这个版本有点多了。谢谢！

现在可以直接使用目前更新的这版代码，在训练和测试模型时在命令行增加`--mix`参数即能在decoder部分使用正常的self-attn（即上上次commit的效果），不使用`--mix`参数则可以使用混合信息的self-attn

**Comment by Terrygth** [comment]
谢谢！
