### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by lijianxing66628** [zhouhaoyi/Informer2020#123]
你好，作者！
这是应该怎么结局
![image](https://user-images.githubusercontent.com/52347772/116807628-c11f4d00-ab66-11eb-8943-d88cae2460de.png)
谢谢。

**Comment by Terrygth** [comment]
用命令行执行，readme里面有

**Comment by zhouhaoyi** [comment]
你好请follow我们的colab example进行。在readme的usage里面有详细说明。

**Comment by lijianxing66628** [comment]
谢谢作者的辛苦解答
