### ISSUE TITLE
多产品时间序列预测问题

### ISSUE THREAD

**Issue by ykaitao** [zhouhaoyi/Informer2020#127]
您好，请问这个包支持“多ITEM时间序列预测”吗？比如，在电商环境中，有很多产品，要预测每个产品未来几个月销量，每个产品对应一条时间序列。

**Comment by cookieminions** [comment]
目前代码可以将每个产品当做一个变量（如每个产品的销量为一项特征），然后将多产品序列当做多变量序列进行预测，使用`--features M`进行预测

**Comment by ykaitao** [comment]
> 目前代码可以将每个产品当做一个变量（如每个产品的销量为一项特征），然后将多产品序列当做多变量序列进行预测，使用`--features M`进行预测

给力！很有帮助！

**Comment by hujb48** [comment]
您好，基于上述的问题想问一下，每个变量的特征可以进行高维的预测吗？例如（每个产品的价格为一项特征，每个产品的销量为一项特征）进行多变量高维预测
