### ISSUE TITLE
UnboundLocalError: local variable 'dec_inp' referenced before assignment 

### ISSUE THREAD

**Issue by Tobsige** [zhouhaoyi/Informer2020#128]
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-14-11731e9b9fc0> in <module>()
     10     # train
     11     print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
---> 12     exp.train(setting)
     13 
     14     # test

1 frames
/content/Informer2020/exp/exp_informer.py in _process_one_batch(self, dataset_object, batch_x, batch_y, batch_x_mark, batch_y_mark)
    269         elif self.args.padding==1:
    270             dec_inp = torch.ones([batch_y.shape[0], self.args.pred_len, batch_y.shape[-1]]).float()
--> 271         dec_inp = torch.cat([batch_y[:,:self.args.label_len,:], dec_inp], dim=1).float().to(self.device)
    272         # encoder - decoder
    273         if self.args.use_amp:

UnboundLocalError: local variable 'dec_inp' referenced before assignment

**Comment by cookieminions** [comment]
Please offer more information about running command.
We will add an `else` block in this part, and please use `--padding 0` or `--padding 1` to set padding type now.

**Comment by Tobsige** [comment]
> Please offer more information about running command.
> We will add an `else` block in this part, and please use `--padding 0` or `--padding 1` to set padding type now.

I'm sorry. I have just noticed the main_imformer.py updated. But I ran the Colab Examples.

**Comment by cookieminions** [comment]
Thanks for your remind, we will update colab example latter.

**Comment by ykaitao** [comment]
Whether a `else` is needed here?
Or a valid default value for `self.args.padding` is needed?

```python3
        # decoder input
        if self.args.padding==0:
            dec_inp = torch.zeros([batch_y.shape[0], self.args.pred_len, batch_y.shape[-1]]).float()
        elif self.args.padding==1:
            dec_inp = torch.ones([batch_y.shape[0], self.args.pred_len, batch_y.shape[-1]]).float()
        dec_inp = torch.cat([batch_y[:,:self.args.label_len,:], dec_inp], dim=1).float().to(self.device)
```

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion. I close now.

**Comment by qiuqiu111abc** [comment]
> > Please offer more information about running command.
> > We will add an `else` block in this part, and please use `--padding 0` or `--padding 1` to set padding type now.
> 
> I'm sorry. I have just noticed the main_imformer.py updated. But I ran the Colab Examples.



> Please offer more information about running command. We will add an `else` block in this part, and please use `--padding 0` or `--padding 1` to set padding type now.

我也遇到了UnboundLocalError的问题，请问应该怎么解决呀
