### ISSUE TITLE
关于--features MS模式下，nn.mseloss()使用目标是否合适问题

### ISSUE THREAD

**Issue by 15151874182** [zhouhaoyi/Informer2020#132]
首先感谢大佬的work！
其次在用自己数据集预测的时候，准确率很低，固仔细研究了下关于3种--features MS,S,M，他们模型输入，输出和真值，有些问题请教，我的数据集除去时间后为16维（结构与ETTm1相同，特征维度由7变为16），维度测评图如下：
![M](https://user-images.githubusercontent.com/36249659/117388243-fb993900-af1c-11eb-8ca4-a39a5e5074d0.png)
![MS](https://user-images.githubusercontent.com/36249659/117388254-0227b080-af1d-11eb-9bc8-c772fd6ce2e3.png)
![S](https://user-images.githubusercontent.com/36249659/117388260-05bb3780-af1d-11eb-844f-1d6573964e71.png)
在MS模式下，bacth_y为Tensor(32,24,1),outputs为Tensor(32,24,16),使用nn.MSELoss(outputs,bacth_y)相当于将target复制成16维，再逐元素求mseloss，相当于(oil teperature - HUFL)^2,这样做是否合适？
在M模式下，bacth_y为Tensor(32,24,16),outputs为Tensor(32,24,16),使用nn.MSELoss(outputs,bacth_y)我觉得在物理意义上是合理的，但在实际问题中我们可能更关注target这单变量的预测准确率，是否需要改成nn.MSELoss(outputs[:,:,-1],bacth_y[:,:,-1])？

**Comment by cookieminions** [comment]
你好，在使用MS模式时，需要设置 `--c_out 1`，将模型输出设置为1

**Comment by 15151874182** [comment]
> 你好，在使用MS模式时，需要设置 `--c_out 1`，将模型输出设置为1

你好，在data_parser中已经定义'MS':[16,16,1],所以模型的输出是(32,24,1),但是你的ground-truth也就是batch_y是(32,24,16)，这2个不同维度做nn.MSEloss()感觉在道理上说不通

**Comment by cookieminions** [comment]
> > 你好，在使用MS模式时，需要设置 `--c_out 1`，将模型输出设置为1
> 
> 你好，在data_parser中已经定义'MS':[16,16,1],所以模型的输出是(32,24,1),但是你的ground-truth也就是batch_y是(32,24,16)，这2个不同维度做nn.MSEloss()感觉在道理上说不通

![image](https://user-images.githubusercontent.com/18379035/117406877-4a0bff00-af40-11eb-82dd-788b522fb575.png)


你所给的图中的batch_y的shape是[32,24,1]，而outputs是[32,24,16]，说明c_out是16
而batch_y在MS模式下的数据维度一定会是1，此处由代码`f_dim = -1 if self.args.features=='MS' else 0`决定

**Comment by 15151874182** [comment]
> > > 你好，在使用MS模式时，需要设置 `--c_out 1`，将模型输出设置为1
> > 
> > 
> > 你好，在data_parser中已经定义'MS':[16,16,1],所以模型的输出是(32,24,1),但是你的ground-truth也就是batch_y是(32,24,16)，这2个不同维度做nn.MSEloss()感觉在道理上说不通
> 
> ![image](https://user-images.githubusercontent.com/18379035/117406877-4a0bff00-af40-11eb-82dd-788b522fb575.png)
> 
> 你所给的图中的batch_y的shape是[32,24,1]，而outputs是[32,24,16]，说明c_out是16
> 而batch_y在MS模式下的数据维度一定会是1，此处由代码`f_dim = -1 if self.args.features=='MS' else 0`决定

谢谢提醒，我再仔细看看
