### ISSUE TITLE
请问这里des参数具体是做什么的呢？

### ISSUE THREAD

**Issue by wfnian** [zhouhaoyi/Informer2020#133]
https://github.com/zhouhaoyi/Informer2020/blob/e4cab482ab082765109eb99a4f1db3035d556b5c/main_informer.py#L50

**Comment by llStringll** [comment]
I believe it gives the description of the test run. I feel so, because, it is being printed along with the model parameters and data parameters during a test run, so it is just a plain string giving a description of your test experiment.

**Comment by wfnian** [comment]
thanks a lot, it seems just used to be print setting at :
https://github.com/zhouhaoyi/Informer2020/blob/e4cab482ab082765109eb99a4f1db3035d556b5c/main_informer.py#L100
https://github.com/zhouhaoyi/Informer2020/blob/e4cab482ab082765109eb99a4f1db3035d556b5c/main_informer.py#L103
