### ISSUE TITLE
Is there a way to get predictions for the entire test set?

### ISSUE THREAD

**Issue by GabrielDeza** [zhouhaoyi/Informer2020#135]
Is there an easy way to get the ground truth and predictions for the entire test set? I would like to plot the entire testing length not just 1 prediction window.

**Comment by cookieminions** [comment]
If you get the test result whose shape is [samples, length, dimension], such as [2848,24,7], you can plot the entire testing length by selecting one certain point in prediction length of all samples. 

For example, you can choose the last point of all samples by using code `preds[:, -1, :]` and you will get an array with shape [samples, dimension], and in our code, the samples of test set is not shuffled, so it's a consequent prediction sequence.

**Comment by ZhangTP1996** [comment]
> If you get the test result whose shape is [samples, length, dimension], such as [2848,24,7], you can plot the entire testing length by selecting one certain point in prediction length of all samples.
> 
> For example, you can choose the last point of all samples by using code `preds[:, -1, :]` and you will get an array with shape [samples, dimension], and in our code, the samples of test set is not shuffled, so it's a consequent prediction sequence.

What is 'length' here? What is the difference between `preds[:, -1, :]` and `preds[:, -2, :]`?

**Comment by cookieminions** [comment]
The shape of test result is [samples, prediction_length, dimension]. length is set by you. You can use `--pred_len 24` to set prediction length to 24 in experiment, which means the model will output a sequence with length 24 in one forward reference.

`preds[:, -1,:]` and `preds[:, -2, :]` is the regular slicing operation in numpy. -1 means getting the last point, -2 means getting the second to last point, 0 means getting the first point.
