### ISSUE TITLE
What timefeature should I choose if I use businessday for training

### ISSUE THREAD

**Issue by xianwenleon** [zhouhaoyi/Informer2020#136]

**Comment by zhouhaoyi** [comment]
Could you please give more description on the BUSINESS day?

**Comment by xianwenleon** [comment]
Business data is only available on weekdays, holiday trading is closed (including national holidays), so we need to use the data of historical weekdays to predict the next day's trading, could you gei me some idea， thank you

**Comment by zhouhaoyi** [comment]
Please refer the Figure 6 in Appendix B. We recommend you treated specific holidays as individual embedding words in the global timestamp. For example, you can use each national holidays' name as the basic indicators, and apply the torch embedding layers, namely torch.nn.Embedding, on them. Then you can concatenate the embedding results as the holiday embedding in Figure 6.

**Comment by xianwenleon** [comment]
ok,thank you 
Excuse me,The data of holidays is not available. Do I need to make up the data of the previous working day

**Comment by zhouhaoyi** [comment]
The holiday strategy is a way to add additional information on the time stamp. If you only need to use the working days as the time stamp, you could just add the corresponding working day embedding on that. We will release a sample for the holidays later.

**Comment by xianwenleon** [comment]
ok，thanks for your help

**Comment by xianwenleon** [comment]
Excuse me, If I do the training on a daily basis without using hours, is it possible to make the following changes
return len(self.data_x) - self.seq_len- self.pred_len + 1
self.seq_len = 4days
self.pred_len = 1days
