### ISSUE TITLE
关于模型输出shape的问题

### ISSUE THREAD

**Issue by fengkoushangdeZZX** [zhouhaoyi/Informer2020#137]
作者您好，感谢您的精彩工作和代码分享，我在运行代码时遇到了个问题，就是transformer模型做预测的话，模型的输入和输出shape是一样的，比如我输入shape是[batch_size = 32,seq_len=168,dim = 8]，我想预测步长为3，那我模型的输出应该是[batch_size = 32,pre_length = 3,dim = 8]（这也是我标签的shape）,我用最原始的transformer模型做实验得到的输出shape都是[batch_size = 32,seq_len=168,dim = 8]，我应该怎么修改能让我模型输出shape和我的标签一致呢？（我做的实验的是M:multivariate predict multivariate）希望得到您的回复

**Comment by cookieminions** [comment]
如果使用我们的模型，设置参数 seq_len=168, pred_len=3 即可，可以参考colab中的实现，如果用命令行则可以在运行时使用指令`--seq_len 168 --pred_len 3`
