### ISSUE TITLE
关于抽样的参数sample factor

### ISSUE THREAD

**Issue by sanwei111** [zhouhaoyi/Informer2020#138]
两个问题：
1.一个数据集里面的数据的那个T：是不是都是一样的？还是说一个数据集里面的每条数据，存在不一样的T？（T：序列长度）
2.sample factor你们是通过从3开始依次累加，做实验得到5作为最优解吗？按照惯性思维，不是应该sample的数量越多，性能，准确率会越高吗？为什么是5呢？可以给出理性和感性分析吗。谢谢你们

**Comment by zhouhaoyi** [comment]
你好：
1. 目前的程序里面每个T如果不等长，可以用0填充。
2. 时间序列存在noise，我们的方法会比原始的transformer效果好一点，一方面也是源于于probspare对于attention的选择能力。对于sampling factor来说，也是同样的，并不是一定采样更多效果更好，我们目前的setting是通过实验经验所得。

**Comment by sanwei111** [comment]
> 需要注意的是，我们目前的数据集不存在不等长的现象。所以这个程序没有加入相关的机制。
> 我之前说的padding zero的方式，可以在这种case下使用，欢迎大家开发测试，并且提交pull requests。

好的，谢谢哥哥。

**Comment by zhouhaoyi** [comment]
不客气
