### ISSUE TITLE
关于输入序列长度（input sequence length of Informer encoder）

### ISSUE THREAD

**Issue by Yun-yj** [zhouhaoyi/Informer2020#139]
你好，
实验中输入序列长度目前看来都是定长的，现有的结构中能够修改结构设置参数实现对不定长输入序列的处理吗？谢谢！

**Comment by zhouhaoyi** [comment]
对于不等长的序列，可以设置一个最大序列长度，然后进行填0的padding操作。在issue #138 里面有简单思路讨论。
欢迎开发一个专用的dataloader并发起pull requests.
