### ISSUE TITLE
decoder时的selfself-attention 里use mask 为什么要对每个时间步的数据进行累加？

### ISSUE THREAD

**Issue by magni-ficent** [zhouhaoyi/Informer2020#140]
大佬，这里不是太懂，
  else: # use mask
            assert(L_Q == L_V) 
            contex = V.cumsum(dim=-2)  
不懂为什么要对V的按行进行累加，即把每个时间步的value加起来。

**Comment by cookieminions** [comment]
关于这一点可以参考过去的issue https://github.com/zhouhaoyi/Informer2020/issues/88 和 https://github.com/zhouhaoyi/Informer2020/issues/23
这里涉及到两点，一个是可以用求和来代替求平均，因为后续的norm操作使得这里用求和的影响不大，另一个是为什么要用cumsum，是因为这里会用到mask，不管是求和还是求平均都不能考虑被mask掉的那些数

**Comment by magni-ficent** [comment]
好的，懂了，谢谢大佬~
