### ISSUE TITLE
Time Cost of ProbSparse attention

### ISSUE THREAD

**Issue by Yogurt928** [zhouhaoyi/Informer2020#142]
你好！
我尝试使用ProbSparse替换了原始的dot-product self-attention，使用以下方式计算消耗时间
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)
start.record()
----Module for evaluation----
end.record()
torch.cuda.synchronize()
print(start.elapsed_time(end))
得到的结果是ProbSparse的耗时是比Baseline要高的，而且sequence越长越高
![image](https://user-images.githubusercontent.com/15760208/118218753-ab851e00-b4aa-11eb-8503-de81f6256f2f.png)

这里是在1个GPU上跑的结果，_prob_QK和_update_context两个函数耗时占比都比较大。
请问是测试方式有问题呢？还是实现上的原因？

</div>

</body>

</html>

**Comment by cookieminions** [comment]
你好，与实现有关系，我们也在和NVIDA合作推出ProbSparse的TensorRT和CUDA加速版本，请期待

**Comment by Yogurt928** [comment]
期待，谢谢回复
