### ISSUE TITLE
Dimensionality in training and prediction.

### ISSUE THREAD

**Issue by JotaCoves** [zhouhaoyi/Informer2020#143]
Hi, first of all, thank you for your work and for sharing it.

Why in training seq_y is:
seq_y = self.data_y[r_begin:r_begin+self.label_len].
and in prediction it is:
seq_y = self.data_y[r_begin:r_end] ?

Shouldn't training and prediction have the same dimension to be the same case?

Thanks for your time and your answer.

**Comment by kkranen** [comment]
I'm not the author, but I believe it's to mask future information from the model.

**Comment by cookieminions** [comment]
> Hi, first of all, thank you for your work and for sharing it.
> 
> Why in training seq_y is:
> seq_y = self.data_y[r_begin:r_begin+self.label_len].
> and in prediction it is:
> seq_y = self.data_y[r_begin:r_end] ?
> 
> Shouldn't training and prediction have the same dimension to be the same case?
> 
> Thanks for your time and your answer.

Hi, 

In `Data_Pred`, seq_y = self.data_y[r_begin:r_begin+self.label_len] and in `Data_Custom` or other training dataloader, seq_y = self.data_y[r_begin:r_end] = self.data_y[r_begin:r_begin + self.label_len + self.pred_len]

That's because we do not have prediction sequence when we do predict.
