### ISSUE TITLE
关于MS的问题

### ISSUE THREAD

**Issue by easonwwg** [zhouhaoyi/Informer2020#144]
你好，两个问题想咨询下
 1：您的CSV文件中的表头，HUFL,HULL,MUFL,MULL,LUFL,LULL,OT，他们七个指标在业务上是有联系的吗？谁会影响谁吗？还是说这些指标是互不干扰的。我看你默认的是OT，OT和其他指标有什么关系吗？
2：如果我csv中，有发电量，温度，风速三个指标，发电量指标和温度、风速有关系 ，是不是通过修改您的代码，使用MS，可以做模型预测
望讲解，不胜感激。

**Comment by cookieminions** [comment]
你好，
1. 关于ETT数据中这些指标的定义，在我们的[数据集repo](https://github.com/zhouhaoyi/ETDataset)中有解释，他们是有联系的，是同一台变压器自身产生的数据；此外我们在实验中也使用了其他数据集，只要有相互影响，不一定需要是同一个个体产生的多变量序列，相互影响的多个序列也可以使用我们的模型进行预测
2. 可以使用MS进行多变量对单变量的预测

**Comment by easonwwg** [comment]
谢谢 已经明白
