### ISSUE TITLE
args.inverse=True give wrong results in MS task

### ISSUE THREAD

**Issue by laviniarossimori** [zhouhaoyi/Informer2020#145]
Hi! Thank you for your model!
 I'm using informer with my data in Colab and I want to use the function inverse to know if the output makes sense. Anyway if I use MS task (I want to predict only one curve from a lot) the output is wrong, about one order of magnitude. If I use M task, but I don't want to predict all curves, the output is similar to the input. How can I solve this?
Thank you so much!

**Comment by cookieminions** [comment]
If you want to use inverse in MS task, you need to modify func `inverse_transform` of `StandardScaler` in `utils/tools.py` and make judgement before transform and use the mean and std of the target dimension to inverse transform

**Comment by laviniarossimori** [comment]
Thank you so much!
