### ISSUE TITLE
求KL散度计算过程

### ISSUE THREAD

**Issue by acmllearner** [zhouhaoyi/Informer2020#146]
emmm 首先膜拜北航大佬的工作，您使用采样手段，筛选重要注意力的同时又降低了模型计算复杂度。我有两个很low问题想问一下：
1、论文第三页 Query Sparsity Measurement 那儿的KL(q||p)散度（公式2）计算过程，您能分享一下吗？
2、有关注意力的长尾分布（附录C），这个适用于其他数据集么，比如刀具磨损和轴承退化数据。想直接用您提出的prop att替换full att试试。 就比较担心一些假设啥的不适用。

**Comment by cookieminions** [comment]
1. 关于KL散度的计算，直接使用KL散度的公式 $KL(p||q)=\sum_{i=1}^{L} p(x_i) log\frac{p(x_i)}{q(x_i)}$，在本文中p(x)用均匀分布，q(x)为softmax的分布，很容易就能推导出来
2. 关于注意力分布这一点并没有对数据集有特定要求，可以直接实验看效果

**Comment by acmllearner** [comment]
哦哦，好的。谢谢~
