### ISSUE TITLE
输入层的卷积projection相关问题

### ISSUE THREAD

**Issue by ligrire** [zhouhaoyi/Informer2020#148]
你好，感谢你们的研究，我从你们的模型中获得很大帮助
我想问一下关于输入层的kernel为3的卷积处理，在编码一个时间点的时候是结合了周围两个时间点的信息的，这方面是基于什么样的考量呢？如果在输入处不用任何网络处理，直接与位置embedding相加后进入到encoder中；或是用一个kernel为1的卷积；或是一个对当前时间点的MLP处理，得到的结果会类似吗？

**Comment by cookieminions** [comment]
你好，对输入序列进行一维卷积的主要考虑在于时间序列数据的特点与自然语言中的句子存在差别，NLP中词与词或者分隔符之间的关系是可以一一对应上并在Self-Attention时计算两者的相似度的，但是时间序列并不要求时间点的严格对应，例如过去某一个事件发生在下午14点，而同样的事件在第二天发生在下午14点30，我们不能要求后续时间点在计算Self-Attention时必须要和14点或14点30的单个时间点严格对应，因此可以通过卷积处理，让相邻时间块的数据做融合，这样在计算Self-Attention时可以认为不再是单个时间点之间的数据在计算相似度，而是时间块之间在计算相似度。

**Comment by ligrire** [comment]
非常感谢你的解答，这解决了我的疑惑，对时间序列来说比较区域而不是时间点确实是更为合理的。
我还有一个小问题，在计算input representation的的时候paper中提到会用holiday embedding来记录一些特殊的时间点，如果用卷积处理的话，特殊时间点附近融合的普通时间点的是不是会受到特殊时间点的影响，这会产生问题吗。或者对于week embedding说，第一个week结束的时间点和第二个week开始的时间点受到卷积融合，可能会导致边界的时间点有一些混淆，这个会是一个问题吗

**Comment by cookieminions** [comment]
目前我们的卷积操作只是在数值上进行操作，并没有在时间编码上使用一维卷积，因此不需要担心时间编码上的边界区分问题；关于holiday这一点，目前我们在github上的代码中并没有使用到holiday的编码，但是如果需要使用holiday编码，由于holiday会对其前后的时间点产生影响，一般会在数据加载时做处理，即holiday前后时间点的节假日编码，需要和准确的holiday时间点编码相同，这样便于控制不同时间粒度数据的节假日溢出效应

**Comment by ligrire** [comment]
感谢回复，

关于边界问题，我指的是在week1结束的时间点的数值由于卷积融合，实际上是融合了week2开始时间点的信息的，但表示的相加是week1的embedding，这可能会产生问题吗
> 即holiday前后时间点的节假日编码，需要和准确的holiday时间点编码相同

是指holiday周围两个时间点也需要加的是holiday embedding，而不是普通时间点的embedding，是这个意思吗

**Comment by cookieminions** [comment]
> 关于边界问题，我指的是在week1结束的时间点的数值由于卷积融合，实际上是融合了week2开始时间点的信息的，但表示的相加是week1的embedding，这可能会产生问题吗

一般不会有问题，如果数据特殊的话可以不使用一维卷积进行处理


> 是指holiday周围两个时间点也需要加的是holiday embedding，而不是普通时间点的embedding，是这个意思吗

没错

**Comment by ligrire** [comment]
谢谢解答，我没有更多问题了
