### ISSUE TITLE
使用freq：d的情况下的一个小bug

### ISSUE THREAD

**Issue by creamiracle** [zhouhaoyi/Informer2020#149]
**前提：embed : fixed, features : s, freq : d**       

在embed.py中，Class TemporalEmbedding中，默认添加了小时维度的embed，但是在天粒度下即freq为d的情况下，并没有小时的特征，所以会报维度错误。目前我改成了如下
```
if freq == 'h': self.hour_embed = Embed(hour_size, d_model)
```
同时在forward中改为
```
hour_x = self.hour_embed(x[:,:,3]) if hasattr(self, 'hour_embed') else 0.
```
能解决报错问题。   

修改方式比较粗暴，仅供参考。

**Comment by cookieminions** [comment]
非常感谢对我们工作的关注和改进！目前Informer的时间编码建议使用timeF编码，因此对于fixed或learned的支持并不完全，在之后的commit中我们会再次收集整理近期各个issue中提到的问题进行完善和改进，再次感谢
