### ISSUE TITLE
关于算法复杂度

### ISSUE THREAD

**Issue by Hanlard** [zhouhaoyi/Informer2020#15]
attn.py 48行：

K_expand = K.unsqueeze(-3).expand(B, H, S, L, E) 

这一步空间复杂度有点高，超过了原始的transformer ，是不是有更好的实现方式呢？

**Comment by zhouhaoyi** [comment]
请参考：https://discuss.pytorch.org/t/torch-repeat-and-torch-expand-which-to-use/27969
expand操作并没有额外的空间开销。理解应该是pytorch底层实现应该是直接指向cuda内存（待求证）。

后续我们会给出一个纯cuda kernel的实现，请期待。

**Comment by zhangyy91** [comment]
@Hanlard expand() 操作沿原Tensor的某个大小为1的维度进行展开，它仅仅创建一个新的视图，额外展开的部分**共享原有内存**，而不会申请额外的内存空间，所以空间复杂度实际上是没有变化的。



参考官方文档：https://pytorch.org/docs/stable/tensors.html#torch.Tensor.expand
