### ISSUE TITLE
关于数据集中的数据的序列长度

### ISSUE THREAD

**Issue by sanwei111** [zhouhaoyi/Informer2020#150]
你好,周导,这个论文中用了几个数据集,我想问的是,数据集里面的数据的T是不是都是T.比如说,假如数据集只有10个数据,那么这10个数据的T是不是都是一样的 or 有三个数据的T是3,三个数据的T是4,剩下4个是6呢？可以介绍下数据集的T的情况吗，周博，谢谢你

**Comment by cookieminions** [comment]
你好，
论文中使用到的数据集最初都是一个原始的时间序列，例如两年长度，数据粒度为小时，那么原始序列的长度是365*24*2
那么在将数据输入到模型前，我们需要对原始序列进行切分，即需要将序列切成一段段固定长度如720的子序列，然后输入到模型中，具体的数据操作可以参考代码`data/dataloader.py`

**Comment by sanwei111** [comment]
好的谢谢您
