### ISSUE TITLE
What does the argument parameter "args.target" sets for multivariate time series forecasting?

### ISSUE THREAD

**Issue by DebadityaRMIT** [zhouhaoyi/Informer2020#151]
Thank you for sharing the code, really helpful. However, I noticed that for multi-feature forecasting, we still need to provide a target feature, which is by default "OT". My question is does the network only why is that required? Will not the network be trained to forecast all the features?

Also, how are the multiple features passed into the network? So is it done by concatenating the multiple features from the conv layer and use that as input to the network, or something else?

**Comment by cookieminions** [comment]
Hi,
If you use mode 'MS' or 'S', `target` is required and the model will be trained to predict the target feature. And if you use mode 'M', the model will be trained to predict all features.

Data fed into model is a tensor containing multiple features (shape is [Batchsize, SequenceLength, Dimension]), and information from multi-feature data will be extract by the entire network.

**Comment by DebadityaRMIT** [comment]
Thanks for the reply. But even using "M" mode, we still need to provide a target feature from the CSV file. Why is that? Does it use it anyway?

Regarding the second question, I agree the input is (shape is [Batchsize, SequenceLength, Dimension]), but I am asking does the output of the convolutions of multiple features concatenate and then fed into the network?

**Comment by cookieminions** [comment]
1. If you use 'M' mode, `target` is not required, you can set it to any value.
2. Convolution layer is a part of the network, the input of convolution layer is a multiple feature tensor (which is also the input of the entire network), and the output of convolution layer is fed to follow-up network structures. You can refer to code `models/model.py` and `exp/exp_informer.py` to get more information.
