### ISSUE TITLE
Question about context value

### ISSUE THREAD

**Issue by Yogurt928** [zhouhaoyi/Informer2020#152]
你好，在code中对value进行了如下的初始化：
def _get_initial_context(self, V, L_Q):
        B, H, L_V, D = V.shape
        if not self.mask_flag:
            # V_sum = V.sum(dim=-2)
            V_sum = V.mean(dim=-2)
            contex = V_sum.unsqueeze(-2).expand(B, H, L_Q, V_sum.shape[-1]).clone()
        else: # use mask
            assert(L_Q == L_V) # requires that L_Q == L_V, i.e. for self-attention only
            contex = V.cumsum(dim=-2)
        return contex

以#use mask为例的话，这里为什么需要做这个contex = V.cumsum(dim=-2)累加的处理呢？好像没有在paper中找到相关的解释。
谢谢！

**Comment by cookieminions** [comment]
你好，请参考issue https://github.com/zhouhaoyi/Informer2020/issues/140

**Comment by Yogurt928** [comment]
Got it, thanks!
