### ISSUE TITLE
Target input and timefeature

### ISSUE THREAD

**Issue by laviniarossimori** [zhouhaoyi/Informer2020#153]
Hi! I'm not an expert on machine learning or time series forecasting, so I have two basics questions.
1 I was trying to understand if, in the MS task, the target is used to predict himself in the test phase. 
All the series are taken as input for MS task in the test phase or in the predict function?

2 I have the date column without a fixed interval of time, I have the precision about the hour but they are random hours (every day the number of rows and its timestamp hour changes) and sometimes all day miss. it's a problem for the model if I choose freq h? How is its behavior? Can I use a different freq for the prediction function?

Thank you.

**Comment by cookieminions** [comment]
Hi,
1. Yes, if you use 'MS' mode, the target feature will be included in the input features.
2. Our experiments are conducted on continuous time series with the same interval, and we did not test the effect of model on data without the same interval. But our model can accept such a sequence as input, you can try to use our model on your data.

**Comment by laviniarossimori** [comment]
Thank you! It will be possible not to include the target variable to do a sort of regression with predictions? (I want to use time-series  in my model mostly for the prediction task)
 If it is, could you please tell me which part of the model's code I should concentrate on?

**Comment by cookieminions** [comment]
> Thank you! It will be possible not to include the target variable to do a sort of regression with predictions? (I want to use time-series in my model mostly for the prediction task)
> If it is, could you please tell me which part of the model's code I should concentrate on?

You can modify func `_process_one_batch` in code `exp/exp_informer.py`, set input of model (`batch_x` and `dec_in`) as `batch_x[:, :, :-1]` and `dec_in[:, :, :-1]` (because the last dimension is the target feature)

https://github.com/zhouhaoyi/Informer2020/blob/f97c9e1ce59d1e45b802bd84cd850c82ba78a05e/exp/exp_informer.py#L259-L289

**Comment by laviniarossimori** [comment]
Thank you! Can I do this only in the test phase? Can I simply add an if with the flag==test?
My problem is that I don't understand from the output if the model copies the target or learns the target, so if in the test phase I don't consider the target  I will know if the model works or my task and my feature are wrong.

**Comment by cookieminions** [comment]
You should keep the parameters of the model consistent during training and testing. The model does not copy the target feature, because the input and output are in different time periods, the model will learn information from the historical sequence of target feature.

**Comment by laviniarossimori** [comment]
The plot of preds and trues curve are identical in the univariate task that I made as a sample and isn't possible to predict my target using just it. In fact, in my project, I want to check if it is possible to predict it with some features. With my tests, I can't understand it because the major trend is given by the target (proved by the univariate task test that predicts in some wrong way the target perfectly, with some copy). So I wanted to see what happened if I avoid using the target in the testing, what happened if the model doesn't have the previous values.

**Comment by cookieminions** [comment]
We did experiments on univariate forecasting and multivariate forecasting, we did not conduct experiments without target feature in the input. But it's okay to feed data without target feature into the model, and you can try this in your task.
