### ISSUE TITLE
help

### ISSUE THREAD

**Issue by niwei1997** [zhouhaoyi/Informer2020#157]
可以问一下怎么产生probsparse_intro.png的吗？  感谢

**Comment by zhouhaoyi** [comment]
您好那个attention map只是截取的之前某次实验的attention的分布。右边的为示意图，可以用任意绘图软件自行绘制。

**Comment by niwei1997** [comment]
好的， 我做时间序列分类发现产生的attention的分布图不太好，以为我弄错了

**Comment by zhouhaoyi** [comment]
可以适当调整超参数，配合具体数据。另外就是可以针对性的设计对M的定制方式，达到适配自己的数据分布。

**Comment by niwei1997** [comment]
> 可以适当调整超参数，配合具体数据。另外就是可以针对性的设计对M的定制方式，达到适配自己的数据分布。

好的  您这个模型的input的shape是？     看了有点迷惑...

**Comment by cookieminions** [comment]
> > 可以适当调整超参数，配合具体数据。另外就是可以针对性的设计对M的定制方式，达到适配自己的数据分布。
> 
> 好的 您这个模型的input的shape是？ 看了有点迷惑...

模型的输入为2个部分，其中encoder的输入为batch_x和batch_x_mark（mark代表的是时间戳数据），shape是[batch_size, seq_len, dimension]，decoder的输入为dec_in和batch_y_mark，shape是[batch_size, label_len+pred_len, dimension]
其中seq_len为encoder输入序列的长度，label_len为decoder输入中的start token的长度，pred_len为预测序列的长度

**Comment by niwei1997** [comment]
> > > 可以适当调整超参数，配合具体数据。另外就是可以针对性的设计对M的定制方式，达到适配自己的数据分布。
> > 
> > 
> > 好的 您这个模型的input的shape是？ 看了有点迷惑...
> 
> 模型的输入为2个部分，其中encoder的输入为batch_x和batch_x_mark（mark代表的是时间戳数据），shape是[batch_size, seq_len, dimension]，decoder的输入为dec_in和batch_y_mark，shape是[batch_size, label_len+pred_len, dimension]
> 其中seq_len为encoder输入序列的长度，label_len为decoder输入中的start token的长度，pred_len为预测序列的长度

dimension=7?

**Comment by cookieminions** [comment]
根据你的数据维度来，ETT数据集的batch_x维度是7，batch_x_mark的维度和时间编码粒度有关

**Comment by cookieminions** [comment]
> > 根据你的数据维度来，ETT数据集的batch_x维度是7，batch_x_mark的维度和时间编码粒度有关
> 
> TokenEmbedding 7->512 使用 conv1d ?

是
