### ISSUE TITLE
关于mask

### ISSUE THREAD

**Issue by fengkoushangdeZZX** [zhouhaoyi/Informer2020#158]
您好！再次感谢您的精彩工作。我在研究代码时遇到了点问题，就是输入到encoder层和decoder层的数据的mask是如何实现的呢？我看在参数部分还有atte_mask,请问这部分的意义是什么呢？谢谢

**Comment by cookieminions** [comment]
你好，

关于mask的定义在`utils/masking.py`中

https://github.com/zhouhaoyi/Informer2020/blob/f97c9e1ce59d1e45b802bd84cd850c82ba78a05e/utils/masking.py#L3-L24

关于mask的使用在`models/attn.py`中

https://github.com/zhouhaoyi/Informer2020/blob/f97c9e1ce59d1e45b802bd84cd850c82ba78a05e/models/attn.py#L23-L28

https://github.com/zhouhaoyi/Informer2020/blob/f97c9e1ce59d1e45b802bd84cd850c82ba78a05e/models/attn.py#L84-L86

**Comment by fengkoushangdeZZX** [comment]
您好，感谢您的回复，但是我还是不太明白，mask是对输入做的，那在data_loader.py中返回的seq_x, seq_y, seq_x_mark, seq_y_mark这几个数据具体是什么呢，这里对x，y做了mask了么？感谢您的回答

**Comment by cookieminions** [comment]
seq_x是encoder的输入序列，seq_y是decoder的start token序列和预测序列，seq_x_mark是seq_x对应的时间戳，seq_y_mark是seq_y对应的时间戳
这里并没有对x和y做mask，mask并不是对输入数据做的，而是在模型的attention部分进行

**Comment by fengkoushangdeZZX** [comment]
好的，明白了，感谢您的讲解
