### ISSUE TITLE
Question in paper..

### ISSUE THREAD

**Issue by decaf0cokes** [zhouhaoyi/Informer2020#159]
In your paper (section **_ProbSparse_ Self-attention**),

written "we only need to randomly sample **U = LK lnLQ** dot-product pairs to calculate the M(qi, K)".

However, I think **U = lnLK LQ** may be correct..

I want to know something that I misunderstood..

Thank you:)

**Comment by zhouhaoyi** [comment]
Thanks for your point. We select this U to match the overall complexity.
In practice, we usually have LK = LQ.

**Comment by decaf0cokes** [comment]
Thank you:)
