### ISSUE TITLE
Eq3

### ISSUE THREAD

**Issue by smartyfh** [zhouhaoyi/Informer2020#16]
Hi,

Thanks for the nice work. I have one question about eq3. To achieve sparsity, the proposed Probsparse attends only to the top-u queries. I am a little bit confused about this design. From my side, it's more rational to attend to partial keys for each query. Could you please elaborate more on this design? Thanks.

**Comment by zhouhaoyi** [comment]
Please refer to the READEME.md. "Why not use Top-u keys?" in the Probsparse Attention.
We already give a simple discussion on this problem.
Thanks for focusing on our work.

**Comment by zhouhaoyi** [comment]
If there is no further discussion, I will close this issue in 12h.

**Comment by smartyfh** [comment]
> If there is no further discussion, I will close this issue in 12h.

Hi,

Thanks for the reply. You have answered my question. Thanks! Nice work.

**Comment by zhouhaoyi** [comment]
You're welcome! Contact me anytime.
