### ISSUE TITLE
用户自定义数据集模型训练问题

### ISSUE THREAD

**Issue by XinWangTIM** [zhouhaoyi/Informer2020#160]
你好，我在自定义的数据集上用此模型解决预测任务(长周期品类销量预测)上碰到如下问题，渴望得到解答，关键参数：features=MS，freq = d，seq_len=84，label_len=28，pred_len=14
1、训练模型时设置train_epochs=500，patience=30，在前2个epochs会得到最优模型，之后模型的val loss和test loss就没法继续降低，早停机制发挥作用，这个如何改善
2、想问下最优模型的判断选取是在./utils/tools里的save_checkpoint函数里通过self.verbose判定吗，这块能说明一下吗？还有针对epoch设置较大时patience参数的设置有何经验
3、informer、informerstack和informerlight的区别

**Comment by cookieminions** [comment]
1. 可以尝试在训练时增加参数 --mix
2. 本代码的早停机制并没有任何特殊设计，与通用的早停机制相同
3. 请参考代码`models/model.py`，informerlight目前本代码并未提供，informerstack是在encoder部分进行不同输入长度的informer encoder的堆叠，在论文中有说明

**Comment by XinWangTIM** [comment]
> 1. 可以尝试在训练时增加参数 --mix
> 2. 本代码的早停机制并没有任何特殊设计，与通用的早停机制相同
> 3. 请参考代码`models/model.py`，informerlight目前本代码并未提供，informerstack是在encoder部分进行不同输入长度的informer encoder的堆叠，在论文中有说明

好的，针对问题1的mix参数能做进一步说明吗？我看之前版本的code并未涉及mix

**Comment by cookieminions** [comment]
请参考代码`models/attn.py`
https://github.com/zhouhaoyi/Informer2020/blob/0ae1ce405fdc6da6a839f590345dc622d2b78b6c/models/attn.py#L159-L161

使用--mix参数，将在decoder中使用标准的self-attention，而默认参数下会执行上述代码，在decoder的self-attn部分对self-attention的结果进行混合，影响后续FFN的输入特征，在一定程度上提高模型表现，具体原理我们会在后续的研究中公布

**Comment by XinWangTIM** [comment]
> 请参考代码`models/attn.py`
> https://github.com/zhouhaoyi/Informer2020/blob/0ae1ce405fdc6da6a839f590345dc622d2b78b6c/models/attn.py#L159-L161
> 
> 使用--mix参数，将在decoder中使用标准的self-attention，而默认参数下会执行上述代码，在decoder的self-attn部分对self-attention的结果进行混合，影响后续FFN的输入特征，在一定程度上提高模型表现，具体原理我们会在后续的研究中公布

您好，采取你的建议设置了mix参数后发现有一点效果，会在间隔几轮后找到最优模型，但是还是停留在10个epoch前就找到最优模型，之后训练loss不再下降，我打印出实际值和预测值进行对比，发现预测值基本是停留在一个量级，输出接近常数，这种情况有什么好的建议吗？

![image](https://user-images.githubusercontent.com/24819273/120581924-3334cb80-c45e-11eb-9182-18553bb0f001.png)

**Comment by cookieminions** [comment]
1. 尝试不使用mix参数并打印预测值，查看预测效果
2. 如果模型在10个epoch后loss不再下降，那么不需要训练那么多轮epoch

**Comment by XinWangTIM** [comment]
> 1. 尝试不使用mix参数并打印预测值，查看预测效果
> 2. 如果模型在10个epoch后loss不再下降，那么不需要训练那么多轮epoch

针对这两点都是尝试过后效果不好才做进一步改进，这个建议又倒退回去了，模型结果输出本身并没有响应到序列自身的周期性变化，会不会跟特征的选取和学习率有关系

**Comment by XinWangTIM** [comment]
此模型类别特征如何处理，我加了一些跟日期相关的特征，比如是否周末(0,1)、星期几(0,1,2,3,4,5,6)、是否工作日 (0,1)，此类特征是否对预测有大的影响

**Comment by creamiracle** [comment]
请问下用custom数据集 --inverse情况下 loss直接几百万了是为什么呢 然后预测值也有很多负数。。。

**Comment by chexianghong** [comment]
> 你好，我在自定义的数据集上用此模型解决预测任务(长周期品类销量预测)上碰到如下问题，渴望得到�解答，关键参数：features=MS，freq = d，seq_len=84，label_len=28，pred_len=14
> 1、�训练模型时设置train_epochs=500，patience=30，在前2个epochs会得到最优模型，之后模型的val loss和test loss就没法继续降低，早停机制发挥作用，这个如何改善
> 2、想问下最优模型的判断选取是在./utils/tools里的save_checkpoint函数里通过self.verbose判定吗，这块能说明一下吗？还有针对epoch设置较大时patience参数的设置有何经验
> 3、informer、informerstack和informerlight的区别

你好，你的自定义数据集可以给我看一下嘛

**Comment by cookieminions** [comment]
> > 1. 尝试不使用mix参数并打印预测值，查看预测效果
> > 2. 如果模型在10个epoch后loss不再下降，那么不需要训练那么多轮epoch
> 
> 针对这两点都是尝试过后效果不好才做进一步改进，这个建议又倒退回去了，模型结果输出本身并没有响应到序列自身的周期性变化，会不会跟特征的选取和学习率有关系

如果要调整学习率可以修改代码`utils/tools.py`中的adjust_learning_rate方法

> 此模型类别特征如何处理，我加了一些跟日期相关的特征，比如是否周末(0,1)、星期几(0,1,2,3,4,5,6)、是否工作日 (0,1)，此类特征是否对预测有大的影响

这些特征可以放在时间序列编码部分，修改数据加载代码`data/data_loader.py`和时序编码代码`utils/timefeatures.py`以及`models/embed.py`，也可以直接放在数据中，作为value的一部分，对预测应该不会有太大影响，具体效果可以通过你自己的实验来判断

**Comment by cookieminions** [comment]
> 请问下用custom数据集 --inverse情况下 loss直接几百万了是为什么呢 然后预测值也有很多负数。。。

请检查具体的数据情况和loss计算，并在使用标准化的情况下进行训练看是否存在同样的问题
