### ISSUE TITLE
About the U_part

### ISSUE THREAD

**Issue by iThronne** [zhouhaoyi/Informer2020#161]
Hi, thanks for your works. I'm confused with the `U_part` in the code now. It seems mismatching with _the Algorithm 1 ProSparse self-attention_ in the paper that _U=mln n_ which is not multiplied by the factor _c_.
```
U_part = self.factor * np.ceil(np.log(L_K)).astype('int').item() # c*ln(L_k)]
```

**Comment by cookieminions** [comment]
> Hi, thanks for your works. I'm confused with the `U_part` in the code now. It seems mismatching with _the Algorithm 1 ProSparse self-attention_ in the paper that _U=mln n_ which is not multiplied by the factor _c_.
> 
> ```
> U_part = self.factor * np.ceil(np.log(L_K)).astype('int').item() # c*ln(L_k)]
> ```

Hi, in our implementation, we set U_part to `c*m*ln(n)` to make the value of U_part not too small, so as to ensure the stability and better effect of the model.

**Comment by iThronne** [comment]
Thank you for your answer!
