### ISSUE TITLE
Informer 输入和预测序列

### ISSUE THREAD

**Issue by tkisss** [zhouhaoyi/Informer2020#162]
你好，
我比较好奇Informer 输入以及预测序列的最大长度，目前我已有的输入及预测序列长度达到几千甚至上万，Informer 可以处理这些数据吗？如果不可以的话，您对我基于transformer模型处理该类问题有什么建议吗？将序列分割？或者别的模型：reformer，performer等？

谢谢

**Comment by cookieminions** [comment]
你好，

如果序列长度非常长，如果使用informer进行处理，有如下建议：1）使用混合精度训练，使用参数--use_amp；2）减少堆叠层数，如encoder为2-3层，decoder为1-2层；3）减小batch_size，目前代码默认是32；4）使用多卡进行训练，从而保持一定的batch_size大小；5）通过特征工程减少输入长度，可以按照一些周期或季节规律，人为进行一定的分割和拼接，例如有两年的数据，对于预测序列，只取去年对应相同月份的数据等方式

我们的模型在batch_size较小并且使用混合精度时，是能够接收数千到数万的输入长度的，同样你也可以考虑其他self-attention优化的模型，如reformer，performer，linear transformer等等

**Comment by tkisss** [comment]
感谢！
