### ISSUE TITLE
args:border1s, border2s

### ISSUE THREAD

**Issue by siwang2011** [zhouhaoyi/Informer2020#164]
please tell me the args:border1s, border2s there are in the data_loader.py,
how to set the args? i don't know why you set 
[12 * 30 * 24, 12 * 30 * 24 + 4 * 30 * 24, 12 * 30 * 24 + 8 * 30 * 24]
i hope you answer my question, i really want to fit my data with you great model

**Comment by cookieminions** [comment]
Hi, you can refer to `Dataset_Custom` for better understanding:

https://github.com/zhouhaoyi/Informer2020/blob/4f1d35d152f4855694905cbd3b184fc93ffca480/data/data_loader.py#L227-L233

We use `df_data[border1s[0]:border2s[0]]` to set the range of data to be loaded. And in `border1s`, `12*30*24` means `12 months * 30 days * 24 hours`, which means one year data, and `12*30*24+4*30*24` means that the end of the data is one year and four months, which is the end of validation data.

**Comment by siwang2011** [comment]
thank you for your help

**Comment by siwang2011** [comment]
by the way, i find the arg features, S M MS, it can select the forecast tasks, but in MS task, it seemed doesn't work, you set the M and MS split same x,y data, Possibly is I understood was wrong.
