### ISSUE TITLE
自定义数据集适配

### ISSUE THREAD

**Issue by ballZing** [zhouhaoyi/Informer2020#165]
你好！我想问一下模型对于时序数据集有没有什么特定格式需求，还是只要符合有时间特征（类似空气质量、水质参数等时序数据集）都能用来跑

**Comment by cookieminions** [comment]
你好，只要符合时间特征的序列数据都可以跑，甚至没有时间特征，只是构成有前后关系的序列也可以尝试使用Informer模型

**Comment by SSSUNSHINNING** [comment]
@ballZing 您好，我有同样的问题，请问在没有时间数据情况下，您是怎样修改代码的
