### ISSUE TITLE
encorder输入包含decorder的输出嘛？

### ISSUE THREAD

**Issue by xzhuzhu** [zhouhaoyi/Informer2020#166]
您好，我想问下，encorder的输入包含decorder的输出不

**Comment by zhouhaoyi** [comment]
encoder的输入不包含decoder的输出。

**Comment by xzhuzhu** [comment]
encoder的输入和decoder的输入是一样的嘛？

**Comment by zhouhaoyi** [comment]
不一样的。你可以查阅论文的Fig.2相关部分。或者收听在线平台上的视频[\[将门\]](https://www.techbeat.net/talk-info?id=505)[\[B站\]](https://www.bilibili.com/video/BV1HX4y1G7bz)。

**Comment by xzhuzhu** [comment]
视频和图我都看过，但还是没弄明白，decoder 可以理解为 输入 0到10个点，将5到10个点的mask掉，最后输出5到10个点对吗，那encoder的输入呢，可以简单解释一下吗。

**Comment by cookieminions** [comment]
> 视频和图我都看过，但还是没弄明白，decoder 可以理解为 输入 0到10个点，将5到10个点的mask掉，最后输出5到10个点对吗，那encoder的输入呢，可以简单解释一下吗。

请参考图1
![image](https://user-images.githubusercontent.com/18379035/121346511-ca1aef80-c958-11eb-86d6-d0ae814e5faa.png)

并阅读代码`exp/exp_informer.py`和`data/data_loader.py`
https://github.com/zhouhaoyi/Informer2020/blob/4f1d35d152f4855694905cbd3b184fc93ffca480/exp/exp_informer.py#L259-L283

https://github.com/zhouhaoyi/Informer2020/blob/4f1d35d152f4855694905cbd3b184fc93ffca480/data/data_loader.py#L79-L90

Encoder的输入是长度为seq_len的历史序列，Decoder的输入分为两部分，一部分是start token，这个是是一段长为label_len的历史序列，可以是Encoder输入的最后一段，另一部分是长度为pred_len的全零序列（当然会补充一些时间编码和位置编码信息），这段序列长度和需要预测的序列长度相同，然后这两部分会拼接在一起，长度为label_len+pred_len，作为Decoder的输入

**Comment by xzhuzhu** [comment]
好的，我懂了，谢谢~
