### ISSUE TITLE
存疑

### ISSUE THREAD

**Issue by SSSUNSHINNING** [zhouhaoyi/Informer2020#167]

**Comment by SSSUNSHINNING** [comment]
您好，在数据加载文件中，
 self.data_x = data[border1:border2]
        if self.inverse:
            self.data_y = df_data.values[border1:border2]
        else:
            self.data_y = data[border1:border2]
如果inverse==0
那么data_x和data_y无差别，有何作用

**Comment by zhouhaoyi** [comment]
请提高更多的信息，或者关闭issue。
