### ISSUE TITLE
data loader for 'MS' task

### ISSUE THREAD

**Issue by qideng7** [zhouhaoyi/Informer2020#168]
Hi,

I think there is a minor error in data_loader.py. For 'MS' (multivariate predicts univariate) task, seq_y should be extracted from the target column not whole data. As a proof, check the code below using the example notebook you provided. Only 'arg.features' was change from 'M' to 'MS'. batch_y should have shape of [batch, label_len+pred_len, 1]. Am I making a mistake here?

Thank you!
![screenshot](https://user-images.githubusercontent.com/35273269/121270218-235e2280-c876-11eb-8a9d-c62bafacb58f.png)

**Comment by cookieminions** [comment]
Hi,

In our code `exp/exp_informer.py`, we choose the last dimension of batch_y as the final label.

https://github.com/zhouhaoyi/Informer2020/blob/4f1d35d152f4855694905cbd3b184fc93ffca480/exp/exp_informer.py#L286-L287
