### ISSUE TITLE
训练loss不怎么改变的问题

### ISSUE THREAD

**Issue by Nanxiaohu666** [zhouhaoyi/Informer2020#169]
你好，想问下， 我拿出模型的encoder的部分，给入序列输入，在训练过程中，loss一直在一个很小的范围内变化，遇到这样的不学习的问题，有什么好的解决方法吗？

**Comment by cookieminions** [comment]
你好，你所说的拿出模型的encoder部分是怎么训练的，是利用我们的代码框架训练的吗？

**Comment by Nanxiaohu666** [comment]
是的  现在怀疑造成这个原因是这句警告：UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead.，这是发生在ProbAttn模块内的

**Comment by Nanxiaohu666** [comment]
不知道是否是因为ProbAttn这部分有不可微的操作？希望得到大佬的回答， 感谢啦！

**Comment by zhouhaoyi** [comment]
你可以把错误定位再发得详细一点。目前informer框架没有出现过这样的情况，理论上不存在叶子节点访问问题。
另外ProbAttn里面会有一些赋值操作，不知道是否和你的模型里面的梯度传递又不兼容的情况。
