### ISSUE TITLE
自定义数据集

### ISSUE THREAD

**Issue by xinchenxy** [zhouhaoyi/Informer2020#171]
自定义的单指标数据集，一列date 一列值 如何使用现有参数 进行预测，求教

**Comment by cookieminions** [comment]
请参考代码`main_informer.py`，其中有关于各个参数的描述，根据你的具体需求，指定和任务有关的seq_len，label_len，pred_len等参数，也可以指定和模型有关的诸如d_model，d_ff，e_layers，d_layers等参数
