### ISSUE TITLE
关于数据集scale的问题

### ISSUE THREAD

**Issue by siwang2011** [zhouhaoyi/Informer2020#172]
使用您定义的数据集对象时，Minute or Hour or Custom，他们都是计算了train_data的mean 和std，再放缩整体数据，但是Dataset_Pred 却是计算了整体数据的mean，std 再放缩整体数据，两个DataSet对象使用的文件相同，这样是否对预测结果有影响呢？

**Comment by siwang2011** [comment]
还有，请教一下为什么在encoder的前向传播里面，最后又穿过了EncoderLayer的最后一层？
encoder.py  71行
x, attn = self.attn_layers[-1](x, attn_mask=attn_mask)

**Comment by cookieminions** [comment]
> 使用您定义的数据集对象时，Minute or Hour or Custom，他们都是计算了train_data的mean 和std，再放缩整体数据，但是Dataset_Pred 却是计算了整体数据的mean，std 再放缩整体数据，两个DataSet对象使用的文件相同，这样是否对预测结果有影响呢？

Dataset_Pred考虑的场景是已有了全部数据，然后在模型的具体应用中传来了一个序列，利用此序列进行预测，因此计算的是全部序列的mean和std，并不关心这个全部数据哪些用来做train，vali和test




> 还有，请教一下为什么在encoder的前向传播里面，最后又穿过了EncoderLayer的最后一层？
> encoder.py 71行
> x, attn = self.attn_layers[-1](x, attn_mask=attn_mask)

因为conv layer相比attention layer少一层，所以在zip循环后还需要再经过最后一层attention layer

**Comment by siwang2011** [comment]
原来如此，感谢您的解答。还有个疑问关于参数mix的，它是用来在decoder中启用两种Attention吗？如果是这样它好像并没有起作用。

**Comment by cookieminions** [comment]
> 原来如此，感谢您的解答。还有个疑问关于参数mix的，它是用来在decoder中启用两种Attention吗？如果是这样它好像并没有起作用。

是两种attention，请参考代码`models/attn.py`和`models/model.py`，如果你认为没有发挥作用，请提交更多实验结果或者引用代码来说明

https://github.com/zhouhaoyi/Informer2020/blob/4f1d35d152f4855694905cbd3b184fc93ffca480/models/attn.py#L159-L161

https://github.com/zhouhaoyi/Informer2020/blob/4f1d35d152f4855694905cbd3b184fc93ffca480/models/model.py#L47-L62

**Comment by siwang2011** [comment]
感谢您的帮助，期待您对模型的继续更新。
