### ISSUE TITLE
Where is the code for running the experiments on the other (non ETT) datasets?

### ISSUE THREAD

**Issue by Horse7354** [zhouhaoyi/Informer2020#173]
Could you please include the code used for the other experimental results

**Comment by cookieminions** [comment]
HI, if you want to use other dataset, you can download the data according to our paper and use `Dataset_Custom` in code `data/dataloader.py` for data loading.

**Comment by zhouhaoyi** [comment]
Besides, the ECL can be easily acquired and implemented within our framework.
