### ISSUE TITLE
关于scale种类的问题

### ISSUE THREAD

**Issue by dengpy** [zhouhaoyi/Informer2020#174]
作者您好，除了StandScale()这种归一化方式之外，是否应该再增加可选的MinMaxScale()等可供选择的其他数据归一化方式？这样对应用于多种数据场景

**Comment by cookieminions** [comment]
你好，我们在论文中使用的是StandardScaler进行的数据标准化，如果你需要使用其他数据归一化或标准化方式，可以根据自己所要使用的具体的公式进行实现，实现可以参考代码`utils/tools.py`中的StandardScaler，我们进行了numpy和torch数据类型的适配

https://github.com/zhouhaoyi/Informer2020/blob/4f1d35d152f4855694905cbd3b184fc93ffca480/utils/tools.py#L56-L73
