### ISSUE TITLE
enc_in、dec_in、c_out值设定

### ISSUE THREAD

**Issue by lalalabobobo** [zhouhaoyi/Informer2020#175]
请问enc_in、dec_in、c_out是如何设定的？如果要换成自定义的数据集，这些参数与数据集的特征数量有关嘛？

**Comment by cookieminions** [comment]
你好，enc_in代表encoder的输入数据的维度，即batch_x的维度；dec_in代表decoder的输入数据的维度，即dec_inp的维度（基本和batch_y相同，也可以自己调整），c_out是输出数据的维度，可以自己决定

**Comment by SSSUNSHINNING** [comment]
enc_in理解为输入特征维度对吗？

**Comment by zhouhaoyi** [comment]
> enc_in理解为输入特征维度对吗？

是的
