### ISSUE TITLE
关于无时间特征但有时间前后关系的数据模型调整

### ISSUE THREAD

**Issue by SSSUNSHINNING** [zhouhaoyi/Informer2020#176]
在无明确时间数据特征的数据集中，是否可以继续使用TemporalEmbedding，TimeFeatureEmbedding。

**Comment by SSSUNSHINNING** [comment]
seq_x_mark， seq_y_mark类似后缀带mark的是否都与时间相关，都需要删掉

**Comment by cookieminions** [comment]
你好，如果没有时间特征，可以不使用TemporalEmbedding和TImeFeatureEmbedding
后缀带有mark的都是时间编码的数据，你可以将其删掉，也可以在数据加载时用None代替，然后在`models/embed.py`中注释掉temporal_embedding相关的使用

https://github.com/zhouhaoyi/Informer2020/blob/4f1d35d152f4855694905cbd3b184fc93ffca480/models/embed.py#L106-L109

**Comment by SSSUNSHINNING** [comment]
好的，谢谢。

**Comment by SSSUNSHINNING** [comment]
作者你好，我将所有涉及时间数据处理的代码全都注释掉，但在运行过程中遇到一个问题
TypeError: forward() missing 2 required positional arguments: 'x_dec' and 'x_mark_dec'
出现位置：
Traceback (most recent call last):
  File "/workspace/Informer/main_informer.py", line 145, in <module>
    exp.train(setting)
  File "/workspace/Informer/exp/exp_informer.py", line 228, in train
    outputs = self.model(batch_x, dec_inp)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)

**Comment by SSSUNSHINNING** [comment]
RuntimeError: Given groups=1, weight of size [512, 3, 3], expected input[64, 4, 130] to have 3 channels, but got 4 channels instead
每次都得重新修改，不知道为什么总是还会变，这个问题

**Comment by cookieminions** [comment]
> 作者你好，我将所有涉及时间数据处理的代码全都注释掉，但在运行过程中遇到一个问题
> TypeError: forward() missing 2 required positional arguments: 'x_dec' and 'x_mark_dec'
> 出现位置：
> Traceback (most recent call last):
> File "/workspace/Informer/main_informer.py", line 145, in
> exp.train(setting)
> File "/workspace/Informer/exp/exp_informer.py", line 228, in train
> outputs = self.model(batch_x, dec_inp)
> File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
> result = self.forward(*input, **kwargs)


你好，请注意模型方面只需要修改embed.py的内容，但是模型依然需要mark输入，只是将其设置为None即可
