### ISSUE TITLE
train loss在快速降到一个值后，不再下降

### ISSUE THREAD

**Issue by EdwinDong704** [zhouhaoyi/Informer2020#178]
您好，在我们的实验中，在MS任务中，只放缩X而不放缩Y的情况下，观察到Loss 会很快的下降到一个值，之后再不下降，由于我的Y是个100左右的三位数，观察到LOSS固定时模型的输出几乎全为108，如图所示。图为运行的参数，启用mix，启用distill，时间编码为TimeF，13期预测12期，label_len为6，损失函数为MAE，优化器为Adam，学习率固定在0.001或者0.0001。谢谢！
![微信图片_20210624111539](https://user-images.githubusercontent.com/62461735/123197386-05cbc280-d4de-11eb-81bc-2d1a2be06755.png)
![微信图片_20210624111548](https://user-images.githubusercontent.com/62461735/123197387-06fcef80-d4de-11eb-9527-51d2d58d89d3.png)

**Comment by cookieminions** [comment]
你好，请先尝试使用全部缩放的设置，并且使用更长的encoder输入
