### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by SSSUNSHINNING** [zhouhaoyi/Informer2020#179]
实验过程中把7维转化为512维能这么做吗？
encoder输入包含了target，那最终学习时是通过哪些值对比，全部7维还是针对target

**Comment by cookieminions** [comment]
> 实验过程中把7维转化为512维能这么做吗？
> encoder输入包含了target，那最终学习时是通过哪些值对比，全部7维还是针对target

1. 能这么做
2. 模型使用了数据的全部维度

**Comment by SSSUNSHINNING** [comment]
请问，编解码器的输入维度都是七维，这七个特征值是不包含时间但是包含target的七个维度，还是包含时间但是不包含target的七个特征。

**Comment by cookieminions** [comment]
> 请问，编解码器的输入维度都是七维，这七个特征值是不包含时间但是包含target的七个维度，还是包含时间但是不包含target的七个特征。

这个七个维度是包含了target的，但是不包括时间编码，时间编码会根据时间戳和设置的freq来生成，具体可以参考代码`models/embed.py`

**Comment by SSSUNSHINNING** [comment]
谢谢
