### ISSUE TITLE
实验效果问题

### ISSUE THREAD

**Issue by ballZing** [zhouhaoyi/Informer2020#180]
你好，我运行你们给出的main_informer.py的文件后，按照colaboratory给出可视化模型训练后results中的pred和true感觉两条线拟合情况不客观，是需要进行调整吗（没有改动代码，单纯运行）

**Comment by cookieminions** [comment]
你好，ETT数据的预测相对来说是存在难度的，无法保证所有的时间段都预测准确，可以通过调整d_ff，e_layers和d_layers，以及输入数据的长度seq_len来调整模型预测效果

**Comment by ballZing** [comment]
还有一个问题就是用原模型跑出来的MSE和MAE与论文中结果也有较大差距，是否也需要调整，谢谢

**Comment by cookieminions** [comment]
> 还有一个问题就是用原模型跑出来的MSE和MAE与论文中结果也有较大差距，是否也需要调整，谢谢

如果需要对论文实验结果进行复现，可以参考scripts下的参数设置，但是由于中途的代码变更可能也需要一些调整，如果有较大差距，请给出具体参数设置和实验结果

**Comment by SunJiaYuuuuu** [comment]
> 你好，我运行你们给出的main_informer.py的文件后，按照colaboratory给出可视化模型训练后results中的pred和true感觉两条线拟合情况不客观，是需要进行调整吗（没有改动代码，单纯运行）

您好，您后来有没有得到可观的可视化曲线？
