### ISSUE TITLE
一个实验效果问题

### ISSUE THREAD

**Issue by XionZi** [zhouhaoyi/Informer2020#181]
你好，我使用如下参数对ETTm1数据在源代码上作测试：
`--model informer --data ETTm1 --attn prob --freq t --features MS --inverse`
即在示例上增加了--inverse以及指定任务为MS，但是我得到了比较糟糕的效果，Train Loss不下降，以及MAE看起来比较差：
`
Args in experiment:
Namespace(activation='gelu', attn='prob', batch_size=32, c_out=1, checkpoints='./checkpoints/', cols=None, d_ff=2048, d_layers=1, d_model=512, data='ETTm1', data_path='ETTm1.csv', dec_in=7, des='test', detail_freq='t', devices='0,1,2,3', distil=True, do_predict=False, dropout=0.05, e_layers=2, embed='timeF', enc_in=7, factor=5, features='MS', freq='t', gpu=0, inverse=True, itr=2, label_len=48, learning_rate=0.0001, loss='mse', lradj='type1', mix=True, model='informer', n_heads=8, num_workers=0, output_attention=False, padding=0, patience=3, pred_len=24, root_path='./data/ETT/', s_layers=[3, 2, 1], seq_len=96, target='OT', train_epochs=6, use_amp=False, use_gpu=True, use_multi_gpu=False)
Use GPU: cuda:0
>>>>>>>start training : informer_ETTm1_ftMS_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34441
val 11497
test 11497
	iters: 100, epoch: 1 | loss: 152.2266846
	speed: 0.0588s/iter; left time: 373.6103s
	iters: 200, epoch: 1 | loss: 146.4018555
	speed: 0.0490s/iter; left time: 306.7787s
	iters: 300, epoch: 1 | loss: 125.8660355
	speed: 0.0606s/iter; left time: 372.8373s
	iters: 400, epoch: 1 | loss: 151.5177155
	speed: 0.0602s/iter; left time: 364.7523s
	iters: 500, epoch: 1 | loss: 144.5212708
	speed: 0.0535s/iter; left time: 318.4894s
	iters: 600, epoch: 1 | loss: 204.5040894
	speed: 0.0592s/iter; left time: 346.9051s
	iters: 700, epoch: 1 | loss: 151.1262054
	speed: 0.0604s/iter; left time: 347.8092s
	iters: 800, epoch: 1 | loss: 170.5814362
	speed: 0.0581s/iter; left time: 328.8299s
	iters: 900, epoch: 1 | loss: 149.8657227
	speed: 0.0542s/iter; left time: 301.2970s
	iters: 1000, epoch: 1 | loss: 160.3296967
	speed: 0.0608s/iter; left time: 331.8077s
Epoch: 1 cost time: 62.131378173828125
Epoch: 1, Steps: 1076 | Train Loss: 166.9791773 Vali Loss: 122.2448425 Test Loss: 22.8475361
Validation loss decreased (inf --> 122.244843).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 134.8055725
	speed: 0.3081s/iter; left time: 1626.8222s
	iters: 200, epoch: 2 | loss: 173.8392792
	speed: 0.0609s/iter; left time: 315.5191s
	iters: 300, epoch: 2 | loss: 208.9087677
	speed: 0.0607s/iter; left time: 308.3952s
	iters: 400, epoch: 2 | loss: 87.4278717
	speed: 0.0557s/iter; left time: 277.3004s
	iters: 500, epoch: 2 | loss: 174.6997681
	speed: 0.0580s/iter; left time: 283.0386s
	iters: 600, epoch: 2 | loss: 146.3993073
	speed: 0.0612s/iter; left time: 292.3914s
	iters: 700, epoch: 2 | loss: 174.7928619
	speed: 0.0605s/iter; left time: 283.0608s
	iters: 800, epoch: 2 | loss: 164.3915405
	speed: 0.0529s/iter; left time: 242.5099s
	iters: 900, epoch: 2 | loss: 78.3305359
	speed: 0.0616s/iter; left time: 275.9314s
	iters: 1000, epoch: 2 | loss: 157.4100189
	speed: 0.0628s/iter; left time: 275.0374s
Epoch: 2 cost time: 63.10358428955078
Epoch: 2, Steps: 1076 | Train Loss: 165.4048057 Vali Loss: 122.8380890 Test Loss: 22.8909321
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 139.3562012
	speed: 0.3129s/iter; left time: 1315.8718s
	iters: 200, epoch: 3 | loss: 178.4656677
	speed: 0.0612s/iter; left time: 251.4205s
	iters: 300, epoch: 3 | loss: 172.4003601
	speed: 0.0586s/iter; left time: 234.8111s
	iters: 400, epoch: 3 | loss: 141.3972321
	speed: 0.0584s/iter; left time: 227.9862s
	iters: 500, epoch: 3 | loss: 166.5056305
	speed: 0.0617s/iter; left time: 234.9548s
	iters: 600, epoch: 3 | loss: 124.4208527
	speed: 0.0616s/iter; left time: 228.1932s
	iters: 700, epoch: 3 | loss: 135.5853424
	speed: 0.0520s/iter; left time: 187.3506s
	iters: 800, epoch: 3 | loss: 191.7234039
	speed: 0.0568s/iter; left time: 199.0823s
	iters: 900, epoch: 3 | loss: 152.3232269
	speed: 0.0614s/iter; left time: 208.9166s
	iters: 1000, epoch: 3 | loss: 146.7405243
	speed: 0.0621s/iter; left time: 205.2817s
Epoch: 3 cost time: 63.501322746276855
Epoch: 3, Steps: 1076 | Train Loss: 164.8514987 Vali Loss: 122.8712234 Test Loss: 24.9088078
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 142.8764954
	speed: 0.3149s/iter; left time: 985.3939s
	iters: 200, epoch: 4 | loss: 119.5951614
	speed: 0.0623s/iter; left time: 188.7687s
	iters: 300, epoch: 4 | loss: 193.5370026
	speed: 0.0554s/iter; left time: 162.3558s
	iters: 400, epoch: 4 | loss: 192.4806671
	speed: 0.0602s/iter; left time: 170.3219s
	iters: 500, epoch: 4 | loss: 189.6722565
	speed: 0.0623s/iter; left time: 169.9076s
	iters: 600, epoch: 4 | loss: 125.4635468
	speed: 0.0617s/iter; left time: 162.3205s
	iters: 700, epoch: 4 | loss: 188.2871704
	speed: 0.0571s/iter; left time: 144.4151s
	iters: 800, epoch: 4 | loss: 155.1622314
	speed: 0.0638s/iter; left time: 155.0459s
	iters: 900, epoch: 4 | loss: 182.0247040
	speed: 0.0621s/iter; left time: 144.5167s
	iters: 1000, epoch: 4 | loss: 188.3115234
	speed: 0.0547s/iter; left time: 121.8341s
Epoch: 4 cost time: 64.97165560722351
Epoch: 4, Steps: 1076 | Train Loss: 164.6074390 Vali Loss: 123.0661774 Test Loss: 25.1486931
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : informer_ETTm1_ftMS_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11497
test shape: (359, 32, 24, 7) (359, 32, 24, 1)
test shape: (11488, 24, 7) (11488, 24, 1)
mse:22.845273971557617, mae:4.014171600341797
Use GPU: cuda:0
>>>>>>>start training : informer_ETTm1_ftMS_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_1>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34441
val 11497
test 11497
	iters: 100, epoch: 1 | loss: 155.1072845
	speed: 0.0621s/iter; left time: 395.0683s
	iters: 200, epoch: 1 | loss: 145.9850464
	speed: 0.0660s/iter; left time: 413.2536s
	iters: 300, epoch: 1 | loss: 182.9360352
	speed: 0.0612s/iter; left time: 376.7965s
	iters: 400, epoch: 1 | loss: 185.9349213
	speed: 0.0608s/iter; left time: 368.2621s
	iters: 500, epoch: 1 | loss: 182.0100403
	speed: 0.0610s/iter; left time: 363.2801s
	iters: 600, epoch: 1 | loss: 156.9793549
	speed: 0.0627s/iter; left time: 367.1179s
	iters: 700, epoch: 1 | loss: 139.3752289
	speed: 0.0542s/iter; left time: 312.2967s
	iters: 800, epoch: 1 | loss: 186.9904633
	speed: 0.0607s/iter; left time: 343.4948s
	iters: 900, epoch: 1 | loss: 131.1087952
	speed: 0.0603s/iter; left time: 335.3548s
	iters: 1000, epoch: 1 | loss: 198.9570160
	speed: 0.0570s/iter; left time: 311.2413s
Epoch: 1 cost time: 64.47201752662659
Epoch: 1, Steps: 1076 | Train Loss: 166.8984173 Vali Loss: 122.4779968 Test Loss: 24.6036320
Validation loss decreased (inf --> 122.477997).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 129.5883179
	speed: 0.1952s/iter; left time: 1030.8373s
	iters: 200, epoch: 2 | loss: 148.2936096
	speed: 0.0367s/iter; left time: 190.3159s
	iters: 300, epoch: 2 | loss: 182.1906738
	speed: 0.0375s/iter; left time: 190.7370s
	iters: 400, epoch: 2 | loss: 148.4026031
	speed: 0.0373s/iter; left time: 186.0139s
	iters: 500, epoch: 2 | loss: 171.6380157
	speed: 0.0368s/iter; left time: 179.5402s
	iters: 600, epoch: 2 | loss: 160.3579865
	speed: 0.0365s/iter; left time: 174.4449s
	iters: 700, epoch: 2 | loss: 133.9833374
	speed: 0.0371s/iter; left time: 173.7118s
	iters: 800, epoch: 2 | loss: 144.4552155
	speed: 0.0369s/iter; left time: 168.8261s
	iters: 900, epoch: 2 | loss: 153.3327484
	speed: 0.0366s/iter; left time: 163.8577s
	iters: 1000, epoch: 2 | loss: 169.5141449
	speed: 0.0366s/iter; left time: 160.2276s
Epoch: 2 cost time: 39.67424511909485
Epoch: 2, Steps: 1076 | Train Loss: 165.4046655 Vali Loss: 122.4873962 Test Loss: 23.7448025
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 193.4881439
	speed: 0.1786s/iter; left time: 751.1129s
	iters: 200, epoch: 3 | loss: 141.7926941
	speed: 0.0365s/iter; left time: 149.6403s
	iters: 300, epoch: 3 | loss: 178.6730347
	speed: 0.0366s/iter; left time: 146.4975s
	iters: 400, epoch: 3 | loss: 137.7987213
	speed: 0.0367s/iter; left time: 143.3517s
	iters: 500, epoch: 3 | loss: 148.4951019
	speed: 0.0365s/iter; left time: 139.0471s
	iters: 600, epoch: 3 | loss: 161.0871124
	speed: 0.0366s/iter; left time: 135.4592s
	iters: 700, epoch: 3 | loss: 137.2433472
	speed: 0.0366s/iter; left time: 131.9057s
	iters: 800, epoch: 3 | loss: 153.6789093
	speed: 0.0366s/iter; left time: 128.1894s
	iters: 900, epoch: 3 | loss: 220.3687744
	speed: 0.0368s/iter; left time: 125.3540s
	iters: 1000, epoch: 3 | loss: 190.7306824
	speed: 0.0367s/iter; left time: 121.3379s
Epoch: 3 cost time: 39.40951442718506
Epoch: 3, Steps: 1076 | Train Loss: 164.8179706 Vali Loss: 123.0351791 Test Loss: 24.6039639
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 133.7309418
	speed: 0.1788s/iter; left time: 559.3451s
	iters: 200, epoch: 4 | loss: 114.8488693
	speed: 0.0366s/iter; left time: 110.9018s
	iters: 300, epoch: 4 | loss: 161.6715546
	speed: 0.0370s/iter; left time: 108.2439s
	iters: 400, epoch: 4 | loss: 182.7237244
	speed: 0.0389s/iter; left time: 110.1205s
	iters: 500, epoch: 4 | loss: 156.6800232
	speed: 0.0373s/iter; left time: 101.7531s
	iters: 600, epoch: 4 | loss: 197.1692810
	speed: 0.0370s/iter; left time: 97.1497s
	iters: 700, epoch: 4 | loss: 186.4999847
	speed: 0.0364s/iter; left time: 92.0635s
	iters: 800, epoch: 4 | loss: 169.8154144
	speed: 0.0378s/iter; left time: 91.7122s
	iters: 900, epoch: 4 | loss: 169.8283844
	speed: 0.0383s/iter; left time: 89.1005s
	iters: 1000, epoch: 4 | loss: 124.5307159
	speed: 0.0372s/iter; left time: 82.9720s
Epoch: 4 cost time: 40.13660287857056
Epoch: 4, Steps: 1076 | Train Loss: 164.5792226 Vali Loss: 123.3762436 Test Loss: 23.4083824
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : informer_ETTm1_ftMS_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_1<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11497
test shape: (359, 32, 24, 7) (359, 32, 24, 1)
test shape: (11488, 24, 7) (11488, 24, 1)
mse:24.605026245117188, mae:4.018425464630127
`

注意，我在数据集和代码上均未做更改，仅仅修改了执行参数。是否在进行inverse时代码有错误，或者是我指定了错误的参数？期待您的解答。

**Comment by siwang2011** [comment]
如果不启用inverse效果会怎样？

**Comment by siwang2011** [comment]
@XionZi 如果不启用inverse，效果会怎样？

**Comment by XionZi** [comment]
`Args in experiment:
Namespace(activation='gelu', attn='prob', batch_size=32, c_out=1, checkpoints='./checkpoints/', cols=None, d_ff=2048, d_layers=1, d_model=512, data='ETTm1', data_path='ETTm1.csv', dec_in=7, des='test', detail_freq='t', devices='0,1,2,3', distil=True, do_predict=False, dropout=0.05, e_layers=2, embed='timeF', enc_in=7, factor=5, features='MS', freq='t', gpu=0, inverse=False, itr=2, label_len=48, learning_rate=0.0001, loss='mse', lradj='type1', mix=True, model='informer', n_heads=8, num_workers=0, output_attention=False, padding=0, patience=3, pred_len=24, root_path='./data/ETT/', s_layers=[3, 2, 1], seq_len=96, target='OT', train_epochs=6, use_amp=False, use_gpu=True, use_multi_gpu=False)
Use GPU: cuda:0
>>>>>>>start training : informer_ETTm1_ftMS_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34441
val 11497
test 11497
	iters: 100, epoch: 1 | loss: 0.0739355
	speed: 0.0554s/iter; left time: 352.3906s
	iters: 200, epoch: 1 | loss: 0.0667499
	speed: 0.0370s/iter; left time: 231.2189s
	iters: 300, epoch: 1 | loss: 0.0452041
	speed: 0.0369s/iter; left time: 227.3020s
	iters: 400, epoch: 1 | loss: 0.0324618
	speed: 0.0361s/iter; left time: 218.9176s
	iters: 500, epoch: 1 | loss: 0.1012765
	speed: 0.0368s/iter; left time: 219.4173s
	iters: 600, epoch: 1 | loss: 0.0624711
	speed: 0.0371s/iter; left time: 217.5448s
	iters: 700, epoch: 1 | loss: 0.0430421
	speed: 0.0365s/iter; left time: 210.0914s
	iters: 800, epoch: 1 | loss: 0.0524006
	speed: 0.0368s/iter; left time: 208.3549s
	iters: 900, epoch: 1 | loss: 0.0582483
	speed: 0.0370s/iter; left time: 205.5419s
	iters: 1000, epoch: 1 | loss: 0.0382510
	speed: 0.0361s/iter; left time: 197.0134s
Epoch: 1 cost time: 41.351871967315674
Epoch: 1, Steps: 1076 | Train Loss: 0.0636874 Vali Loss: 0.0365332 Test Loss: 0.0449056
Validation loss decreased (inf --> 0.036533).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.0311312
	speed: 0.1893s/iter; left time: 999.5904s
	iters: 200, epoch: 2 | loss: 0.0326586
	speed: 0.0392s/iter; left time: 203.1723s
	iters: 300, epoch: 2 | loss: 0.0335899
	speed: 0.0389s/iter; left time: 197.5752s
	iters: 400, epoch: 2 | loss: 0.0497710
	speed: 0.0377s/iter; left time: 187.6139s
	iters: 500, epoch: 2 | loss: 0.0393664
	speed: 0.0385s/iter; left time: 187.9696s
	iters: 600, epoch: 2 | loss: 0.0356391
	speed: 0.0368s/iter; left time: 176.1740s
	iters: 700, epoch: 2 | loss: 0.0239275
	speed: 0.0371s/iter; left time: 173.8330s
	iters: 800, epoch: 2 | loss: 0.0476961
	speed: 0.0366s/iter; left time: 167.6340s
	iters: 900, epoch: 2 | loss: 0.0350205
	speed: 0.0363s/iter; left time: 162.5192s
	iters: 1000, epoch: 2 | loss: 0.0211665
	speed: 0.0362s/iter; left time: 158.6052s
Epoch: 2 cost time: 40.404855251312256
Epoch: 2, Steps: 1076 | Train Loss: 0.0326831 Vali Loss: 0.0465332 Test Loss: 0.0415254
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.0232927
	speed: 0.1786s/iter; left time: 751.0705s
 	iters: 200, epoch: 3 | loss: 0.0200565
	speed: 0.0366s/iter; left time: 150.2977s
	iters: 300, epoch: 3 | loss: 0.0300343
	speed: 0.0378s/iter; left time: 151.2923s
	iters: 400, epoch: 3 | loss: 0.0197790
	speed: 0.0366s/iter; left time: 142.7758s
	iters: 500, epoch: 3 | loss: 0.0154047
	speed: 0.0368s/iter; left time: 140.1135s
	iters: 600, epoch: 3 | loss: 0.0207844
	speed: 0.0377s/iter; left time: 139.5281s
	iters: 700, epoch: 3 | loss: 0.0295983
	speed: 0.0370s/iter; left time: 133.2172s
	iters: 800, epoch: 3 | loss: 0.0233034
	speed: 0.0374s/iter; left time: 131.1104s
	iters: 900, epoch: 3 | loss: 0.0142650
	speed: 0.0383s/iter; left time: 130.4278s
	iters: 1000, epoch: 3 | loss: 0.0199512
	speed: 0.0469s/iter; left time: 155.1399s
Epoch: 3 cost time: 42.7647807598114
Epoch: 3, Steps: 1076 | Train Loss: 0.0232264 Vali Loss: 0.0506027 Test Loss: 0.0921009
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.0178373
	speed: 0.3087s/iter; left time: 965.8327s
	iters: 200, epoch: 4 | loss: 0.0163518
	speed: 0.0537s/iter; left time: 162.5196s
	iters: 300, epoch: 4 | loss: 0.0256630
	speed: 0.0594s/iter; left time: 174.0777s
	iters: 400, epoch: 4 | loss: 0.0193147
	speed: 0.0600s/iter; left time: 169.6396s
	iters: 500, epoch: 4 | loss: 0.0144769
	speed: 0.0595s/iter; left time: 162.4415s
	iters: 600, epoch: 4 | loss: 0.0184719
	speed: 0.0566s/iter; left time: 148.9229s
	iters: 700, epoch: 4 | loss: 0.0178807
	speed: 0.0597s/iter; left time: 150.8671s
	iters: 800, epoch: 4 | loss: 0.0215849
	speed: 0.0596s/iter; left time: 144.7023s
	iters: 900, epoch: 4 | loss: 0.0237131
	speed: 0.0519s/iter; left time: 120.8910s
	iters: 1000, epoch: 4 | loss: 0.0204452
	speed: 0.0592s/iter; left time: 131.9432s
Epoch: 4 cost time: 62.592782497406006
Epoch: 4, Steps: 1076 | Train Loss: 0.0183285 Vali Loss: 0.0464598 Test Loss: 0.0612588
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : informer_ETTm1_ftMS_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11497
test shape: (359, 32, 24, 1) (359, 32, 24, 1)
test shape: (11488, 24, 1) (11488, 24, 1)
mse:0.04498550295829773, mae:0.1629386991262436
Use GPU: cuda:0
>>>>>>>start training : informer_ETTm1_ftMS_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_1>>>>>>>>>>>>>>>>>>>>>>>>>>
train 34441
val 11497
test 11497
	iters: 100, epoch: 1 | loss: 0.1144440
	speed: 0.0605s/iter; left time: 384.9125s
	iters: 200, epoch: 1 | loss: 0.0534577
	speed: 0.0585s/iter; left time: 365.7327s
	iters: 300, epoch: 1 | loss: 0.0496696
	speed: 0.0536s/iter; left time: 330.2416s
	iters: 400, epoch: 1 | loss: 0.0537069
	speed: 0.0601s/iter; left time: 363.8195s
	iters: 500, epoch: 1 | loss: 0.0368729
	speed: 0.0599s/iter; left time: 356.6992s
	iters: 600, epoch: 1 | loss: 0.0392666
	speed: 0.0539s/iter; left time: 315.5696s
	iters: 700, epoch: 1 | loss: 0.0431956
	speed: 0.0594s/iter; left time: 341.9844s
	iters: 800, epoch: 1 | loss: 0.0426026
	speed: 0.0600s/iter; left time: 339.1963s
	iters: 900, epoch: 1 | loss: 0.0348830
	speed: 0.0584s/iter; left time: 324.5725s
	iters: 1000, epoch: 1 | loss: 0.0291075
	speed: 0.0574s/iter; left time: 313.3950s
Epoch: 1 cost time: 62.901647090911865
Epoch: 1, Steps: 1076 | Train Loss: 0.0664861 Vali Loss: 0.0368277 Test Loss: 0.0573292
Validation loss decreased (inf --> 0.036828).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.0425394
	speed: 0.3123s/iter; left time: 1649.1009s
	iters: 200, epoch: 2 | loss: 0.0271984
	speed: 0.0589s/iter; left time: 305.2578s
	iters: 300, epoch: 2 | loss: 0.0422022
	speed: 0.0575s/iter; left time: 292.0115s
	iters: 400, epoch: 2 | loss: 0.0312095
	speed: 0.0620s/iter; left time: 308.8798s
	iters: 500, epoch: 2 | loss: 0.0183277
	speed: 0.0640s/iter; left time: 312.3651s
	iters: 600, epoch: 2 | loss: 0.0489771
	speed: 0.0556s/iter; left time: 265.6044s
	iters: 700, epoch: 2 | loss: 0.0264719
	speed: 0.0630s/iter; left time: 294.6804s
	iters: 800, epoch: 2 | loss: 0.0203969
	speed: 0.0624s/iter; left time: 285.9170s
	iters: 900, epoch: 2 | loss: 0.0459487
	speed: 0.0599s/iter; left time: 268.2705s
	iters: 1000, epoch: 2 | loss: 0.0243728
	speed: 0.0590s/iter; left time: 258.2760s
Epoch: 2 cost time: 65.23918104171753
Epoch: 2, Steps: 1076 | Train Loss: 0.0329389 Vali Loss: 0.0451683 Test Loss: 0.0466809
EarlyStopping counter: 1 out of 3
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.0164188
	speed: 0.3221s/iter; left time: 1354.2418s
	iters: 200, epoch: 3 | loss: 0.0189686
	speed: 0.0564s/iter; left time: 231.7138s
	iters: 300, epoch: 3 | loss: 0.0273023
	speed: 0.0630s/iter; left time: 252.2471s
	iters: 400, epoch: 3 | loss: 0.0192126
	speed: 0.0648s/iter; left time: 253.0731s
	iters: 500, epoch: 3 | loss: 0.0236887
	speed: 0.0595s/iter; left time: 226.2805s
	iters: 600, epoch: 3 | loss: 0.0164324
	speed: 0.0603s/iter; left time: 223.4446s
	iters: 700, epoch: 3 | loss: 0.0211598
	speed: 0.0624s/iter; left time: 224.8135s
	iters: 800, epoch: 3 | loss: 0.0202358
	speed: 0.0639s/iter; left time: 223.9808s
	iters: 900, epoch: 3 | loss: 0.0246818
	speed: 0.0567s/iter; left time: 192.9845s
	iters: 1000, epoch: 3 | loss: 0.0278338
	speed: 0.0629s/iter; left time: 207.8592s
Epoch: 3 cost time: 66.1902425289154
Epoch: 3, Steps: 1076 | Train Loss: 0.0229042 Vali Loss: 0.0560980 Test Loss: 0.0820333
EarlyStopping counter: 2 out of 3
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.0142473
	speed: 0.3142s/iter; left time: 983.0390s
	iters: 200, epoch: 4 | loss: 0.0155744
	speed: 0.0583s/iter; left time: 176.7175s
	iters: 300, epoch: 4 | loss: 0.0129383
	speed: 0.0592s/iter; left time: 173.4962s
	iters: 400, epoch: 4 | loss: 0.0255556
	speed: 0.0582s/iter; left time: 164.6306s
	iters: 500, epoch: 4 | loss: 0.0132246
	speed: 0.0500s/iter; left time: 136.3285s
	iters: 600, epoch: 4 | loss: 0.0224775
	speed: 0.0380s/iter; left time: 99.8677s
	iters: 700, epoch: 4 | loss: 0.0174184
	speed: 0.0367s/iter; left time: 92.7976s
	iters: 800, epoch: 4 | loss: 0.0162512
	speed: 0.0363s/iter; left time: 88.1351s
	iters: 900, epoch: 4 | loss: 0.0204799
	speed: 0.0367s/iter; left time: 85.3874s
	iters: 1000, epoch: 4 | loss: 0.0153137
	speed: 0.0369s/iter; left time: 82.1466s
Epoch: 4 cost time: 49.183128356933594
Epoch: 4, Steps: 1076 | Train Loss: 0.0182969 Vali Loss: 0.0487170 Test Loss: 0.0723432
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : informer_ETTm1_ftMS_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_1<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11497
test shape: (359, 32, 24, 1) (359, 32, 24, 1)
test shape: (11488, 24, 1) (11488, 24, 1)
mse:0.05746546760201454, mae:0.19079384207725525
`
不加--reverse的效果是这样的。

**Comment by siwang2011** [comment]
@XionZi 您好，在我自己的实践中，我更换了自己的数据集，也只不放缩Y，预测任务是MS的情况下，效果也很差。

**Comment by XionZi** [comment]
@siwang2011 这可能是因为你的数据集不是长序列预测，我在这个issue中其实是想询问作者是否inverse存在bug。事实上，我的数据集上较短的时间序列预测性能也不理想，但是这是可以理解的，毕竟这不是这个repo或者paper的focus。

**Comment by siwang2011** [comment]
@XionZi 您好，您可以关注一下data_loader的73行，和exp_infor的283行，在我的理解里，一旦启用Inverse，他的decoder的输入无论X还是Y都未经过放缩，而Encoder的输入全部进过放缩，在正向传播的最后，使用定义的放缩函数inverse了输出，这似乎有问题。

**Comment by siwang2011** [comment]
@XionZi 您好，您可以关注一下data_loader的73行，和exp_infor的283行，在我的理解里，一旦启用Inverse，他的decoder的输入无论X还是Y都未经过放缩，而Encoder的输入全部进过放缩，在正向传播的最后，使用定义的放缩函数inverse了输出，这似乎不太合理。

**Comment by cookieminions** [comment]
@XionZi  你好，目前inverse部分的代码确实存在 @siwang2011 所说的问题，我们会在之后做出修改，当然也欢迎大家提供pull request

**Comment by siwang2011** [comment]
> @XionZi 你好，目前inverse部分的代码确实存在 @siwang2011 所说的问题，我们会在之后做出修改，当然也欢迎大家提供pull request
您好，感谢您对informer的辛苦付出，期待您对模型的进一步完善。
