### ISSUE TITLE
关于实验效果的提问

### ISSUE THREAD

**Issue by SSSUNSHINNING** [zhouhaoyi/Informer2020#184]
您在进行数据结果对比时都是运用别人的模型运行效果进行对比试验，是否有关于数据集的对比效果。例如，那些论文与您使用了相同的数据集获得什么样的效果。

**Comment by SSSUNSHINNING** [comment]
还有有一个问题，在没有时间这一维度数据时，不产生时间编码，这对最后解码长序列生成式输出会产生什么影响，如果修改为之前一步一步的生成方式。

**Comment by zhouhaoyi** [comment]
关于第一个问题：我们使用了多个数据集、多个任务、多种方法的对比。你可以follow一些后续cite我们文章的工作，有进一步的对比。
关于第二个问题：没有时间维度的话，会reduce成一个回归问题。跟传统方式一样的话，可能也会存在累计误差放大问题。

**Comment by SSSUNSHINNING** [comment]
能帮忙指出修改哪个位置可以还原成以前的解码方式吗？在不使用时间编码的情况下结果确实不太好。谢谢

**Comment by zhouhaoyi** [comment]
可以参照原始Transformer实现，修改decoder.py可以还原为原始的step-by-step解码。另外时间编码不一定一直需要是时间，只要有先后关系就可以进行编码处理。
