### ISSUE TITLE
实验效果问题

### ISSUE THREAD

**Issue by YZZhong** [zhouhaoyi/Informer2020#186]
我们在复现您的Informer工作时，遇到了一些问题：

1. 对代码未做修改，运行scripts中ETTh1.sh中在单变量S的实验设置下，发现在seq_len=720, label_len=336, pred_len=720上实验效果显著超过论文公布结果。

运行参数命令为：python -u main_informer.py --model informer --data ETTh1 --features S --seq_len 720 --label_len 336 --pred_len 720 --e_layers 2 --d_layers 1 --attn prob --des 'Exp' --itr 5

运行结果为：
>>>>>>>testing : informer_ETTh1_ftS_sl720_ll336_pl720_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_Exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2161
test shape: (67, 32, 720, 1) (67, 32, 720, 1)
test shape: (2144, 720, 1) (2144, 720, 1)
mse:0.09923858940601349, mae:0.24683846533298492

>>>>>>>testing : informer_ETTh1_ftS_sl720_ll336_pl720_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_Exp_1<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2161
test shape: (67, 32, 720, 1) (67, 32, 720, 1)
test shape: (2144, 720, 1) (2144, 720, 1)
mse:0.07728786021471024, mae:0.21628843247890472

>>>>>>>testing : informer_ETTh1_ftS_sl720_ll336_pl720_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_Exp_2<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2161
test shape: (67, 32, 720, 1) (67, 32, 720, 1)
test shape: (2144, 720, 1) (2144, 720, 1)
mse:0.07652604579925537, mae:0.21382276713848114

>>>>>>>testing : informer_ETTh1_ftS_sl720_ll336_pl720_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_Exp_3<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2161
test shape: (67, 32, 720, 1) (67, 32, 720, 1)
test shape: (2144, 720, 1) (2144, 720, 1)
mse:0.0869656354188919, mae:0.23821184039115906

>>>>>>>testing : informer_ETTh1_ftS_sl720_ll336_pl720_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_Exp_4<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2161
test shape: (67, 32, 720, 1) (67, 32, 720, 1)
test shape: (2144, 720, 1) (2144, 720, 1)
mse:0.07417270541191101, mae:0.21247518062591553

比起论文公布的MSE: 0.269, MAE: 0.435，运行结果有点好的离谱。对此，我想咨询一下这个原因是因为我在运行中有些错漏吗？或者说ETTh1数据集存在一些问题呢？

2. 关于模型结构，论文中写的是：Informer contains a 3-layer stack and a 1-layer stack (1/4 input) in the encoder, and a 2-layer decoder. 这个意思是论文实验是基于代码中的informerstack 模型而不是informer模型使用scripts超参数设置的实验结果吗？对此，我是否误解了文章意思？
期待得到您的解答，期待后续更完备的代码公布。

**Comment by zhouhaoyi** [comment]
你好！

1. 因为自从项目开源以来，我们也对于原始代码进行了多次的调整和升级。如果想回溯老版本的性能表现，可以退回到之前的一些commit。你选择的是输入输出都比较长的case，你可以关注一下后续follow或者cite我们工作的一些文章，看是否有类似的情况。我们也会再去关注这个性能表现。

2. 论文的实验使用了1/4L+L组合的informerstack模型。

后续我们会持续更新代码和调优，欢迎关注。
