### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by zengpengyu-student** [zhouhaoyi/Informer2020#188]
能问下ECL数据集里一共有四年的数据但只用了两年的数据，能问下是哪两年吗？15/3/4的数据分别是哪个月的数据？以及能否告知下这个数据集上超参数的选择。
论文下方的weather数据集链接好像失效了，能否提供下新链接。

**Comment by cookieminions** [comment]
1. 我们使用的是从 https://github.com/laiguokun/multivariate-time-series-data 处获得的经过处理的ECL数据集，其中2011由于缺失较多未使用，使用的是2012至2014年的数据，train，validation和test的切分按照6/2/2来切分。感谢提醒，我们会修正Arxiv上的论文版本中对数据集描述的问题
2. weather数据集原链接已经失效了，但是仍然可以从 https://www.ncei.noaa.gov/data/local-climatological-data/ 获取NOAA's dataset的LCD data

**Comment by RuiruiKang** [comment]
如果使用自己的数据集的话，代码中需要修改哪些地方？

**Comment by zhouhaoyi** [comment]
> 如果使用自己的数据集的话，代码中需要修改哪些地方？

请参考我们的colab例子。

**Comment by RuiruiKang** [comment]
好的 多谢


---------------- 

---------- Origin message ----------
>From："Haoyi" ***@***.***>
>To："zhouhaoyi/Informer2020" ***@***.***>
>Subject：Re:_[zhouhaoyi/Informer2020]_数据集的问题_(#188)
>Date：2021-07-12 20:21:25> 如果使用自己的数据集的话，代码中需要修改哪些地方？

请参考我们的colab例子。
