### ISSUE TITLE
关于Colab上提供的代码无法运行的问题

### ISSUE THREAD

**Issue by xaingyuwei** [zhouhaoyi/Informer2020#189]
你好，我想尝试一下该代码在colab上的运行，但发现“Experiments: Train and Test”部分中的   
# train
 exp.train(setting)
部分存在Error，名为：
ImportError: cannot import name 'values_from_object' from 'pandas._libs.lib' (/usr/local/lib/python3.7/dist-packages/pandas/_libs/lib.cpython-37m-x86_64-linux-gnu.so)
请问如何使得该代码可以在您提供的环境下运行？谢谢！

**Comment by cookieminions** [comment]
你好，我们在运行colab时并没有发现这个问题，请按照colab中原本的代码严格执行，或者提供更多的说明
