### ISSUE TITLE
Is there a way to exclude using target as a feature in training?

### ISSUE THREAD

**Issue by BenjiKCF** [zhouhaoyi/Informer2020#190]
So currently I am training a model with 
[date, id, feature1, feature2, feature3, target] in the training set and 
[date, id, feature1, feature2, feature3] in the testing set.

I want to predict the target, however I don't have the target in the testing set and I cannot use it to forecast the next target.
Is there a way I can exclude a certain class in the csv for training?

**Comment by BenjiKCF** [comment]
I found the following code
```
class Dataset_Custom(Dataset):
    def __init__(self, root_path, flag='train', size=None, 
                 features='S', data_path='ETTh1.csv', 
                 target='OT', scale=True, inverse=False, timeenc=0, freq='h', cols=None):
```

and in args.cols, I can include the column that I want. Thanks a lot.

**Comment by zhouhaoyi** [comment]
Please refer to the --cols option in our parameters.
