### ISSUE TITLE
Loss parameter is fixed to MSE

### ISSUE THREAD

**Issue by joaquincabezas** [zhouhaoyi/Informer2020#192]
Hello and thanks for you impressive work.

In the list of parameters there is a reference to the loss function, which defaults to MSE. In the example notebook there is a line to set the loss function with "args.loss", but in the code the criterion is fixed (line 109 of exp_informer.py") and "args.loss" is never used.

The parameter should be removed until the function is taking it into account.

Best,
Joaquín.

**Comment by cookieminions** [comment]
Thanks for your reminder, we will improve this part in the future commits.

**Comment by joaquincabezas** [comment]
Thanks for your answer, will keep an eye to the changes.
