### ISSUE TITLE
Is there a way to get attention maps for each input feature?

### ISSUE THREAD

**Issue by AtrCheema** [zhouhaoyi/Informer2020#194]
Hello thank you for your code. I have a multivariate time series prediction problem. The input features are >1 while the target/output feature is 1. Is there a way we can use Informer to get feature importance/attention map for each input feature? I am interested to know, which time step of which input was more relevant in prediction.

Thank you in advance.

**Comment by cookieminions** [comment]
Hi, maybe you can refer to our colab example to get more information, we provide a visulization of attention map at different layers of Informer.
