### ISSUE TITLE
weather数据集预处理问题

### ISSUE THREAD

**Issue by zengpengyu-student** [zhouhaoyi/Informer2020#195]
请问我们获取了2010-2013中72462703011里4年的数据，但时间数据是每隔20分钟的数据而非每小时的数据。在数据集中HourlyWindDirection和HourlyWindSpeed特征中每个小时中的三个数据均不相同，所以请问下是怎么对weather数据集进行预处理的，或者能否提供下处理后的Weather数据集供参考。以及能否说一下Weather数据集下在’模型整体效果表‘中Informer模型的超参数选择。感谢

**Comment by cookieminions** [comment]
我们将会在近期提供已处理的Weather数据集并发布该数据集下的模型训练超参数，谢谢关注
