### ISSUE TITLE
what does  'M':[7,7,7],'S':[1,1,1],'MS':[7,7,1] mean ?

### ISSUE THREAD

**Issue by 694376965** [zhouhaoyi/Informer2020#196]
data_parser = {
    'ETTh1':{'data':'ETTh1.csv','T':'OT','M':[7,7,7],'S':[1,1,1],'MS':[7,7,1]},
    'ETTh2':{'data':'ETTh2.csv','T':'OT','M':[7,7,7],'S':[1,1,1],'MS':[7,7,1]},
    'ETTm1':{'data':'ETTm1.csv','T':'OT','M':[7,7,7],'S':[1,1,1],'MS':[7,7,1]},
    'ETTm2':{'data':'ETTm2.csv','T':'OT','M':[7,7,7],'S':[1,1,1],'MS':[7,7,1]},
    'WTH':{'data':'WTH.csv','T':'WetBulbCelsius','M':[12,12,12],'S':[1,1,1],'MS':[12,12,1]},
    'ECL':{'data':'ECL.csv','T':'MT_320','M':[321,321,321],'S':[1,1,1],'MS':[321,321,1]},
    'Solar':{'data':'solar_AL.csv','T':'POWER_136','M':[137,137,137],'S':[1,1,1],'MS':[137,137,1]},
}

in the first line,  'ETTh1':{'data':'ETTh1.csv','T':'OT','M':[7,7,7],'S':[1,1,1],'MS':[7,7,1]},
I know that the meaning of [M, S, MS] .  
M:multivariate predict multivariate, S:univariate predict univariate, MS:multivariate predict univariate')
But what does the sentence  ( 'M':[7,7,7],'S':[1,1,1],'MS':[7,7,1] )   mean?  the “7” and "1" respectively represents what？

**Comment by PhilJou** [comment]
For the M case you have 7 features as input always and also 7 features are predicted, namely "HUFL", "HULL", "MUFL", "MULL", "LUFL", "LULL" and "OT" for the ETT data set. For the S case you have only one of the features as inputs, also predicting 1. And for the MS case, you could take 7 features (or less) as inputs when wanting to predict only one of them.

**Comment by 694376965** [comment]
> For the M case you have 7 features as input always and also 7 features are predicted, namely "HUFL", "HULL", "MUFL", "MULL", "LUFL", "LULL" and "OT" for the ETT data set. For the S case you have only one of the features as inputs, also predicting 1. And for the MS case, you could take 7 features (or less) as inputs when wanting to predict only one of them.

OK. Thank you very much!

**Comment by 694376965** [comment]
> For the M case you have 7 features as input always and also 7 features are predicted, namely "HUFL", "HULL", "MUFL", "MULL", "LUFL", "LULL" and "OT" for the ETT data set. For the S case you have only one of the features as inputs, also predicting 1. And for the MS case, you could take 7 features (or less) as inputs when wanting to predict only one of them.

OK. Thank you very much!

I have another question: if I have many stores and the daily sales data of these stores。if my train data like this:  store ID, date, sales quantity. And I want to predict the daily sales quantity for every store. The store ID is a Categorical Feature，Can the Informer model deal with Categorical Feature ? If it can't, must I train model for every store respectively?

**Comment by cookieminions** [comment]
> > For the M case you have 7 features as input always and also 7 features are predicted, namely "HUFL", "HULL", "MUFL", "MULL", "LUFL", "LULL" and "OT" for the ETT data set. For the S case you have only one of the features as inputs, also predicting 1. And for the MS case, you could take 7 features (or less) as inputs when wanting to predict only one of them.
> 
> OK. Thank you very much!
> 
> I have another question: if I have many stores and the daily sales data of these stores。if my train data like this: store ID, date, sales quantity. And I want to predict the daily sales quantity for every store. The store ID is a Categorical Feature，Can the Informer model deal with Categorical Feature ? If it can't, must I train model for every store respectively?

Hi, Informer can deal with Categorical Feature, you can use an Embedding Layer to transform the categorical feature into contiguous vector before feed the features into the model.

**Comment by 694376965** [comment]
> For the M case you have 7 features as input always and also 7 features are predicted, namely "HUFL", "HULL", "MUFL", "MULL", "LUFL", "LULL" and "OT" for the ETT data set. For the S case you have only one of the features as inputs, also predicting 1. And for the MS case, you could take 7 features (or less) as inputs when wanting to predict only one of them.

For the M case 'M':[7,7,7],  the first '7' means the number of features as input , the last '7' means the number of features to be predicted. What's the middle '7' means?

**Comment by PhilJou** [comment]
I think its the number of input features for the decoder, correct me if I am wrong.

**Comment by cookieminions** [comment]
> I think its the number of input features for the decoder, correct me if I am wrong.

Accurate.
`[7,7,7]` means `[encoder input dim, decoder input dim, decoder output dim]`.

**Comment by lifhdf** [comment]
Excuse me, would you please tell me if my data is input x1, x2, x3, x4, x5, x6, x7, x8, x9, hope the output for the x7,x8, x9, so where I need to modify the code

**Comment by kenouye** [comment]
> Excuse me, would you please tell me if my data is input x1, x2, x3, x4, x5, x6, x7, x8, x9, hope the output for the x7,x8, x9, so where I need to modify the code

Hi, I also have the same problem. Do you have a solution? If possible, could you share your experience? Thank you for your contribution
