### ISSUE TITLE
Metric calculation with normalization

### ISSUE THREAD

**Issue by Daikon-Sun** [zhouhaoyi/Informer2020#197]
Hi,

I am trying to figure out how is the metric calculated with normalization.
From what I see from the code,
(1) First, the standard normalization is calculated per series.
(2) Then, as mentioned in the paper, the model takes the normalized data as input.
(3) Finally, during training and testing, the MAE and MSE scores are calculated on the "normalized" data.

Correct me if I am wrong. Thanks!

**Comment by cookieminions** [comment]
> Hi,
> 
> I am trying to figure out how is the metric calculated with normalization.
> From what I see from the code,
> (1) First, the standard normalization is calculated per series.
> (2) Then, as mentioned in the paper, the model takes the normalized data as input.
> (3) Finally, during training and testing, the MAE and MSE scores are calculated on the "normalized" data.
> 
> Correct me if I am wrong. Thanks!

Accurate

**Comment by mw66** [comment]
> ... From what I see from the code, (1) First, the standard normalization is calculated per series. (2) Then, as mentioned in the paper, the model takes the normalized data as input.

The data is normalized as a *whole* (the whole training / validation / test series as a whole, could be of multiple years' data). I'm just wondering if the data is normalized window by window (i.e `seq_len + pred_len`), will the result be better? i.e for each data *point* (X, y):

```
  self.scaler.fit(X)
  self.scaler.transform(y)
```

Thoughts?
