### ISSUE TITLE
prediction length=24,48,168，Encoder input 分别是多少

### ISSUE THREAD

**Issue by 13121283123** [zhouhaoyi/Informer2020#199]
大佬，我看到表3中只是列出了prediction length是336 和720的时候的 Encoder input，那么prediction length为24 48 168的时候的Encoder input是多少呢

**Comment by cookieminions** [comment]
你好，请问你说的表3是指什么
关于不同预测长度的Encoder Input，可以参考 scripts/ 下的训练参数设置

**Comment by 13121283123** [comment]
好的 非常感谢我看到了 谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhouhaoyi/Informer2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月30日(星期五) 上午10:20
***@***.***&gt;;
抄送:&nbsp;"Changxia ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhouhaoyi/Informer2020] prediction length=24,48,168，Encoder input 分别是多少 (#199)





 
你好，请问你说的表3是指什么
 关于不同预测长度的Encoder Input，可以参考 scripts/ 下的训练参数设置
