### ISSUE TITLE
Ignoring target variable in MS forecast case?

### ISSUE THREAD

**Issue by 777udo** [zhouhaoyi/Informer2020#200]
Is it sufficient, to edit only the following lines in the "main_informer.py" file when wanting to do a univariate forecast with multivariate input, but a target variable other than "OT"? :
![image](https://user-images.githubusercontent.com/40930484/127739441-195be5b0-00d3-4b61-b30f-9918ffbb1335.png)

and
![image](https://user-images.githubusercontent.com/40930484/127739450-71509253-6fba-49f9-acda-b1d9396855a0.png)

I did some experiments using the MS setting and found the ground truth plots in the visualization part a bit suspiciously looking. Then I replaced (it does not make sense, but only for visualization) the HUFL column in the ETTh1 data set with a simple series that looks like this:
![image](https://user-images.githubusercontent.com/40930484/127739530-7cf6703b-2f8b-4082-98a2-5a9dd9503b55.png)

and that repeats periodically every 20 data points. But plotting preds and trues after training and testing gives this result as ground truth:
![image](https://user-images.githubusercontent.com/40930484/127739675-c7d008de-ef6a-4cf8-8ced-45185ec0bc94.png)

Are there more settings to be changed inside other modules?

**Comment by 777udo** [comment]
It seems as if always the last column of the csv file is taken as target, independent of what was actually set as target column. Tried it by swapping the modified (as mentioned above) HUFL and OT column.

![image](https://user-images.githubusercontent.com/40930484/127889751-02d4cf82-78a0-4194-ab62-b81a5f46998e.png)

After swapping HUFL and OT columns the expected ground truth is plotted:

![image](https://user-images.githubusercontent.com/40930484/127890795-e8a2960e-9721-4dd6-a6cd-dfbdadf3a480.png)

**Comment by cookieminions** [comment]
Hi, if you want to change the predict target, you can try to modify code of func `_process_one_batch` in `exp/exp_informer.py`

https://github.com/zhouhaoyi/Informer2020/blob/b5f671f86744c82c5d11d21f107eeca6f2cc3f92/exp/exp_informer.py#L286-L287

**Comment by 777udo** [comment]
@cookieminions 
I see. Here, with f_dim = -1 always the last column is used. Is this not a problem, because in that way it doesn't matter which column you set as `args.target `? 
`_process_one_batch` is also called in the train function in `exp_informer.py`, which in the "MS" case would mean that here also always the last column is used, whether you have set it as target or not, right?

I see that in the "M" and "S" feature settings `f_dim = 0` works, because there is either only one feature column, or you want to predict all of them. However, I still do not see how setting `args.target` is linked correctly with the code in `exp_informer.py`, so that in training and testing the target column is actually used as `trues`.

**Comment by cookieminions** [comment]
If you use `Dataset_Custom` and set `target`, the target feature will be set as the last column.

https://github.com/zhouhaoyi/Informer2020/blob/b5f671f86744c82c5d11d21f107eeca6f2cc3f92/data/data_loader.py#L218-L231

If you use `Dataset_ETTh`, change `target` will not work.

**Comment by 777udo** [comment]
> If you use Dataset_ETTh, change target will not work.

That's it, thanks. Could be missleading when working with ETTh data sets and MS setting, though. Especially with scaled data it's hard to recognize in the plots which column has been actually used.
