### ISSUE TITLE
您处理weather 数据以及ECL数据的代码

### ISSUE THREAD

**Issue by 13121283123** [zhouhaoyi/Informer2020#201]
大佬您好请问您可否公开一下您处理weather 数据以及ECL数据的代码

**Comment by cookieminions** [comment]
处理weather数据代码是零散的需要整理，不过我们在之后会发布我们使用的WTH数据。ECL数据可以直接使用https://github.com/laiguokun/multivariate-time-series-data 下的代码，只需要加入适当的表头和日期即可

**Comment by wzhSteve** [comment]
这个数据集中的ECL跑过之后的结果要比论文中给的数据好很多呀，请问原数据用的就是链接中的数据集么 @cookieminions

**Comment by 13121283123** [comment]
请问 表头的话应该是MT_001";"MT_002";"MT_003";"MT_004";"MT_005";"MT_006";"MT_007" ..."MT_321" 那日期是多少呢 ？ 是从2012-01-01，00:00:00 到2014-12-31,00:00:00 是吗。或者您具体的时间范围是多少，还请大佬告知一下

**Comment by cookieminions** [comment]
> 这个数据集中的ECL跑过之后的结果要比论文中给的数据好很多呀，请问原数据用的就是链接中的数据集么 @cookieminions

是该链接中使用的数据

**Comment by cookieminions** [comment]
> 请问 表头的话应该是MT_001";"MT_002";"MT_003";"MT_004";"MT_005";"MT_006";"MT_007" ..."MT_321" 那日期是多少呢 ？ 是从2012-01-01，00:00:00 到2014-12-31,00:00:00 是吗。或者您具体的时间范围是多少，还请大佬告知一下

我们会将使用到的ECL数据和WTH数据一起公布

**Comment by zhouhaoyi** [comment]
已经公开数据集，关闭该issue。
