### ISSUE TITLE
Why 672 seq_len is needed to predict 24 pred_len for ETTm1 dataset?

### ISSUE THREAD

**Issue by ts-kim** [zhouhaoyi/Informer2020#202]
I found that for ETTm1 dataset, you uses --seq_len 672 --label_len 96 --pred_len 24 for multivariate prediction setting. 
I think seq_len should be shorter than the other cases. ( pred_len = {48, 96, 288, 672} ) 

I want to know this is a typo or what the authors intended.

**Comment by cookieminions** [comment]
This is just the parameter that we recorded in the experiment which leads to better results, you can try other `seq_len` in your personal data.
