### ISSUE TITLE
关于解码器的两个疑问

### ISSUE THREAD

**Issue by Armilius** [zhouhaoyi/Informer2020#205]
1.generative decoder的第一个注意力中的mix attention是何用意？
2.在做针对generative decoder的消融研究时，作为对比的dynamic decoding阶段的输入数据的长度和具体的step-by-step的方式是什么？
非常感谢

**Comment by houkai** [comment]
第一个疑问，我也不明白。
正常的操作是将 B*L*H*K的tensor 进行 review 得到 B*L*(H*K)的 形状。
mix是做了transpose， B*L*H*K 变为 B*H*L*K然后再review为B*L*(H*K)。
mix操作后，T时刻不同的head其实是来自多个时刻了。为什么要这样操作呢，同问有参考文章吗 😀

**Comment by cookieminions** [comment]
> 1.generative decoder的第一个注意力中的mix attention是何用意？
> 2.在做针对generative decoder的消融研究时，作为对比的dynamic decoding阶段的输入数据的长度和具体的step-by-step的方式是什么？
> 非常感谢

> 第一个疑问，我也不明白。
> 正常的操作是将 B_L_H_K的tensor 进行 review 得到 B_L*(H_K)的 形状。 mix是做了transpose， B_L_H_K 变为 B_H_L_K然后再review为B_L*(H*K)。
> mix操作后，T时刻不同的head其实是来自多个时刻了。为什么要这样操作呢，同问有参考文章吗 😀

1. 第一个问题我们的mix处理算是一个trick，我们通过实验发现，最后输出的Attention在最后的维度上如果包含了不同时刻的信息，对于生成式的Decoder效果更好，在ETT这样预测难度相对ECL更大的数据集上也很明显，这可能是与Self-Attention结构之后的position-wised FeedForward Network提取特征有一定关系
2. 具体的step-by-step方法与NLP中常用的step-by-step相同，即给一个start token（我们选择预测序列的前一个时间点的值），然后每次生成一个预测值，将其作为真实值与之前得到的结果拼接，然后作为输入再次丢到Decoder中
