### ISSUE TITLE
关于seq_len label_len pred_len取值的问题

### ISSUE THREAD

**Issue by wzhSteve** [zhouhaoyi/Informer2020#207]
你好，我想问一下seq_len label_len pred_len在实验中是如何取值的？论文中Table2的多元变量预测中，这三个参数分别是多少？

**Comment by cookieminions** [comment]
你好，关于实验参数设置可以参考`scripts/`下配置文件中的内容

**Comment by wzhSteve** [comment]
好的，谢谢
