### ISSUE TITLE
about the distilling process

### ISSUE THREAD

**Issue by rouniuyizu** [zhouhaoyi/Informer2020#21]
From your paper I read "To enhance the robustness of the distilling operation, we build halving replicas of the main stackand progressively decrease the number of self-attention dis-tilling layers by dropping one layer at a time, like a pyramidin Fig.(3), such that their output dimension is aligned. Thus,we concatenate all the stacks’ outputs and have the final hid-den representation of encoder." Somehow I failed to locate the corresponding code sections (also as black-boxed in pic below), though I do notice maxpool here which I believe is part of the upper portion op: https://github.com/zhouhaoyi/Informer2020/blob/956ac31c4d0c752b5b71d8884ed5384e88676a11/models/encoder.py#L15
Any clue?

![image](https://user-images.githubusercontent.com/7133753/108028158-56ca3680-7066-11eb-92ea-f5008aed5e14.png)

**Comment by cookieminions** [comment]
The current version of this framework on github is a simple and fast implementation, without adding stack structure.
We have found in some experiments that adding stack structure can improve the performance of experiments, especially for short-period data.
We will add stack structure on github later, and we will update a new time encoding and a faster implementation of probsparse attention, please look forward to it.

**Comment by rouniuyizu** [comment]
Awesome. Pls keep me posted. Thank you,
