### ISSUE TITLE
预测结果问题

### ISSUE THREAD

**Issue by 925hawoo** [zhouhaoyi/Informer2020#210]
为什么我的MSE只有0.016左右但是预测结果却不好呢？
![Figure_1](https://user-images.githubusercontent.com/87347922/129501527-bf661871-ce42-4d90-9cd3-c4cf11bff385.png)

**Comment by jkarolczak** [comment]
I'm not the author, but this question seems to be quite general, not only related to the Informer.
MSE is a measure that is data-sensitive. It means, that its value depends on the data range. In this particular case, it seems to be small but the data is standardized by Informer by default (a normal distribution with mean=0 and std=1), which makes its values (somehow, relatively) small too. If you want to have an interpretable measure look for other metrics like [MAPE](https://en.wikipedia.org/wiki/Mean_absolute_percentage_error).
If you want to know how your predictions deviate from original data in original units (not in percents like in MAPE) and you require using MSE, undo the standardization and then compute the error. This operation may be done following the pattern: `train_dataset.inverse_transform(predictions)`. Later on, compute MSE on original data. At the end take a square root of the MSE, as it's a squared error. 
The obtained error may be used as an interpretable version of MSE expressed in original values. However, it's not convenient and I would rather recommend using MAPE (if an error in percent works for you) or MAE (if you want to know the deviation in original units). MSE is a greate measure for optimizers but it's hardly interpretable for humans.

**Comment by MAZiqing** [comment]
我也遇到了相同的问题，这一段的mse=0.048 。因为预测实验的true value本身就是一个很小的数，接近-1加减0.2 。所以MSE等于0.02-0.08也是一个几乎不可以接受的误差？
![image](https://user-images.githubusercontent.com/44238026/129530289-064a9787-3c1e-4738-827a-32321d78fc9d.png)

**Comment by cookieminions** [comment]
Hi, 请问使用的是什么数据集以及画图时使用的是什么特征
我们在过去的实验分析时也发现，ETTh数据集的预测难度相对是更高的，尤其是ETTh2的画图效果并不理想，而其他频率相对更高的数据，以及ECL等公开数据集画图效果则相对更好，但也与具体特征有关

下图是我们在ECL数据集上随机选取sample和特征的结果
![image](https://user-images.githubusercontent.com/18379035/129827582-4266938a-adfa-487f-bb7d-b431d7fe0f72.png)

下图是我们在ETTh1数据集上随机选取sample的结果
![image](https://user-images.githubusercontent.com/18379035/129827633-84fc1ac5-ecaf-4312-babe-d6b36aea9cfd.png)

**Comment by 925hawoo** [comment]
> Hi, 请问使用的是什么数据集以及画图时使用的是什么特征
> 我们在过去的实验分析时也发现，ETTh数据集的预测难度相对是更高的，尤其是ETTh2的画图效果并不理想，而其他频率相对更高的数据，以及ECL等公开数据集画图效果则相对更好，但也与具体特征有关
> 
> 下图是我们在ECL数据集上随机选取sample和特征的结果
> ![image](https://user-images.githubusercontent.com/18379035/129827582-4266938a-adfa-487f-bb7d-b431d7fe0f72.png)
> 
> 下图是我们在ETTh1数据集上随机选取sample的结果
> ![image](https://user-images.githubusercontent.com/18379035/129827633-84fc1ac5-ecaf-4312-babe-d6b36aea9cfd.png)

我采用的是自己的数据集，具体是NASA的B0018号电池容量数据。为什么对于不同特征的预测效果是不同的呢？

**Comment by zhouhaoyi** [comment]
从向量数据输入的角度看，不同特征处于输入的不同维度。每个维度的相互关联，以及与预测任务的gap程度都不一样，这会导致相同的处理手段（比如本算法）所给出的预测效果不同。这个是跟特征的实际物理意义有关联。以我们的ETT数据为例，各种载荷的预测是相对关联性强的（容易预测的），但是油温是一个依赖载荷不断累积的一个过程，所以是一个相对难建模和预测的维度。
