### ISSUE TITLE
有关ProbAttention模型

### ISSUE THREAD

**Issue by zoro-1215** [zhouhaoyi/Informer2020#211]
' M = Q_K_sample.max(-1)[0] - torch.div(Q_K_sample.sum(-1), L_K)', 为啥是L_K，而不是sample_k呢？

**Comment by cookieminions** [comment]
你好，非常感谢对我们工作的关注，这里的确可以使用sample_k来达到求平均的目的，不过由于最终结果是寻找其中的top-u个，使用L_K或sample_k对选择结果并无太大影响。
