### ISSUE TITLE
当seq_len=336, label_len=336, pred_len=168时结果与Figure 5中不一致

### ISSUE THREAD

**Issue by Zhazhan** [zhouhaoyi/Informer2020#212]
非常感谢你们的优秀工作，最近我正在跑这个repository的代码来复现此github页面上Figure 5中多变量长程预测的结果，使用的命令均为./scripts中的命令。

在ETTh1上，运行这些命令都能得到与Figure 5中相近的结果（在预测长度变长时可能需要将模型从informer替换为informerstack）。然而在ETTh2上进行长度为168的长程预测时，我得到最好的MSE都在5左右，多次运行得到的均值在6左右，和Figure 5中的3.489相去甚远。此外，我也尝试了完全使用本仓库中的dataloader，确保数据一致的情况下测试其它方法（如LogTrans），得到的MSE也在5以上。

因此Figure 5中各个方法在ETTh2上预测未来168个点时得到的结果是否有误？或者是
python -u main_informer.py --model informer --data ETTh2 --features M --seq_len 336 --label_len 336 --pred_len 168 --des 'Exp' --itr 5
这条命令有误？

**Comment by zhouhaoyi** [comment]
邮件已经讨论。
