### ISSUE TITLE
Do you have a comment version of the source code?

### ISSUE THREAD

**Issue by chenruhai** [zhouhaoyi/Informer2020#213]
Like my title

**Comment by cookieminions** [comment]
Sorry, we do not have a comment version now.

**Comment by zhouhaoyi** [comment]
Some comment versions are available on Zhihu (in Chinese). I just give an example: https://zhuanlan.zhihu.com/p/374936725.
I hope it may help.

**Comment by chenruhai** [comment]
> Some comment versions are available on Zhihu (in Chinese). I just give an example: https://zhuanlan.zhihu.com/p/374936725.
> I hope it may help.

thank you
