### ISSUE TITLE
ECL data hyperparameters

### ISSUE THREAD

**Issue by jimgoo** [zhouhaoyi/Informer2020#214]
Hi,

Great paper! I was hoping to get the hyperparameters to reproduce the ECL dataset experiments in the paper, similar to what's in the `scripts` folder for ETT and WTH datasets.

Also, for the WTH script (https://github.com/zhouhaoyi/Informer2020/blob/main/scripts/WTH.sh), was it intentional to vary `--d_layers`  and `--e_layers` across different runs? I couldn't tell from the paper if the hyperparameter tuning was done separately for each `--pred_len` setting or not, but that would explain the difference.

Thanks!

**Comment by cookieminions** [comment]
Hi, thanks for your attention to our work.

We will sort out the hyperparameter settings of the experiment on the ECL dataset.
We usually do `--e_layers 3 --d_layers 2` and `--e_layers 2 --d_layers 1` search on all `pred_len` setting.

**Comment by albertfgu** [comment]
Hi, have the hyperparameters been released? At minimum, can the sequence lengths be specified?
