### ISSUE TITLE
Univariate setting

### ISSUE THREAD

**Issue by Daikon-Sun** [zhouhaoyi/Informer2020#215]
I am trying to figure out the univariate setting.
So in the ETT dataset, there are 7 series, namely HUFL, HULL, MUFL, MULL, LUFL, LULL, OT.
For the univariate setting in the paper, the model takes in one series and predict future of that series.
Does the number reported in the paper averaged over all 7 series, or only calculated on the OT series?
Thank you!

**Comment by cookieminions** [comment]
Hi, only calculated on the OT series.
