### ISSUE TITLE
远期mse比较低，不符合直觉

### ISSUE THREAD

**Issue by JNUpython** [zhouhaoyi/Informer2020#218]
我我预测未来18期，按照18个时间
![image](https://user-images.githubusercontent.com/32349843/130782348-ab0b4d0a-253a-44fd-853f-582407605a73.png)
段将所有数据分类，发现离预测点远的期数mse比较低

**Comment by JNUpython** [comment]
有人遇到同样情况吗

**Comment by cookieminions** [comment]
你好，请问你所指的是预测点离真实值越远mse越小吗

**Comment by JNUpython** [comment]
是的目前看来预测值越远mse约小
