### ISSUE TITLE
Is it possible to combine ETTh1 and ETTh2 data to predict them simultaneously

### ISSUE THREAD

**Issue by turmeric-blend** [zhouhaoyi/Informer2020#22]
Is it possible to combine ETTh1 and ETTh2 data to predict them simultaneously? so the output shape would be something like (batch_size, prediction_length, feature, 2), where 2 is ETTh1 and ETTh2.

**Comment by zhouhaoyi** [comment]
I think this idea is interesting. Maybe we can try it on ETT-large with more power stations.

**Comment by turmeric-blend** [comment]
yeah in a way that the correlation between the stations can be modeled and help prediction

**Comment by zhouhaoyi** [comment]
But I recommend reformulating this problem into a spatiotemporal one. If you are interested in this topic, we recently proposed a new method for this problem. And it will be online soon.

Thanks for your discussion. I will close this issue in 12h.

**Comment by turmeric-blend** [comment]
I see, do tag me here when you its released. Thank you.
