### ISSUE TITLE
weather 数据集疑问

### ISSUE THREAD

**Issue by ZhaoShengjian** [zhouhaoyi/Informer2020#221]
在论文中您的描述用的是2010-2013年的数据，但在github 网盘链接中只给了一个demo数据，并且两个数据的部分label有区别。
      所以有三个问题：
      1. 您paper中的实验结果是2010-2013年的数据还是demo的数据结果？
      2. 如果是2010-2013年的数据，此时有接近1600个位置点数据，模型预测时每个位置点数据单独预测最后对结果求均值，还是1600个位置点文件可以用模型同时预测？
      3. 问题2中如果是第一种情况计算会不会太麻烦了，如果是第二种情况，模型多了位置这个维度，模型还适用吗？

**Comment by cookieminions** [comment]
你好，我们在论文中使用的数据就是github网盘链接中的数据，数据在原始链接中的数据基础上经过了处理，选择的是其中一个位置点的数据，论文原本的数据链接已经失效，我们提供了补充的数据链接

**Comment by somethingforheheda** [comment]
> 

可以分享一下天气数据的全部数据吗，这里给的只有一个位置点的数据 我需要全部1600个点的所有数据 或者分享一下原数据的网站链接 感谢！！
