### ISSUE TITLE
About multivariate prediction

### ISSUE THREAD

**Issue by nnnwyn** [zhouhaoyi/Informer2020#222]
Hello, if i want to make a multivariate prediction, should the target be like this(in a list form)?
args.target = ['ws10_real', 'dir10_real', 'ws32_real', 'direction32_real', 'ws31_real', 'direction31_real']

**Comment by cookieminions** [comment]
Hi, if you want to make a multivariate prediction, you just need to set `--features M`, and the model will predict all input features.
