### ISSUE TITLE
关于seq_len的变化

### ISSUE THREAD

**Issue by KylinMoriarty** [zhouhaoyi/Informer2020#225]
作者您好，我在看您视频讲解的时候说到历史长度L会逐步的对半减少最后变为L/4，但是我在运行代码的时候发现当L为12的时候encoder之后为5,L为24的时候encoder之后为8，这是为什么呢？

**Comment by zhouhaoyi** [comment]
你好，这个最终的长度取决于网络结构（多少层网络）和中间1维卷积的参数设置（而且不同pytorch版本的1维卷积进行滑动窗口的方式发生过变化，你可以注意到我们code里面对于版本的处理）。你可以注意一下这两点。

**Comment by KylinMoriarty** [comment]
好的，感谢您的回答！
