### ISSUE TITLE
if self.mix: out = out.transpose(2,1).contiguous()

### ISSUE THREAD

**Issue by MingtianLi** [zhouhaoyi/Informer2020#229]
hi~ What is the use of this code: 
"
if self.mix: 
    out = out.transpose(2,1).contiguous()
" 
in class AttentionLayer(nn.Module) ?

In parameter description：
”parser.add_argument('--mix', action='store_false', help='use mix attention in generative decoder', default=True)“

Can you give a more detailed explanation, many thanks!

**Comment by cookieminions** [comment]
Hi, it's a trick to mix information of different time step and provide different data perspectives for the following FFN. It's also our next research direction.

**Comment by zhouhaoyi** [comment]
If you found the model easily converge to some local minima. You can just disable this feature by setting --mix to FALSE.
