### ISSUE TITLE
Inconsistent with the original paper?

### ISSUE THREAD

**Issue by PKUZHOU** [zhouhaoyi/Informer2020#23]
Hello:

Thank you for your work. During my study I find it confusing that in your code (line 68 in atten.py)

`            V_sum = V.sum(dim=-2)`

you directly sum up V for those flatten attention matrix lines. However, in your original paper you use the average value of V, which is more reasonable for me. Which way is correct？

<img width="620" alt="image" src="https://user-images.githubusercontent.com/25677298/108303418-d9770100-71e0-11eb-96f4-a526f20748d2.png">

Thank you!

**Comment by cookieminions** [comment]
Thanks for your attention to our work. 
Using average value of V is correct, which is intended to be consistent with the original attention for comparison. We simplified the implementation by using `sum` instead, and each encoder layer has a layernorm to normalize the values, so the impact is not significant. If you want to avoid the risk, you can  also use `mean` in this part.
Thanks for your comments!

**Comment by PKUZHOU** [comment]
Thank you for your reply!
I do find that using mean instead of sum will produce lower mse value in the provided example ETTh1. (0.50 vs 0.56)

**Comment by cookieminions** [comment]
You are welcome! We will continue to improve our work.

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion. I will close this issue in 12h.
