### ISSUE TITLE
exp_informer的vali里面为什么要调用self.model.train()？

### ISSUE THREAD

**Issue by lzmax888** [zhouhaoyi/Informer2020#231]
https://github.com/zhouhaoyi/Informer2020/blob/f22f199faa2943731de183ad66f478ca4eb3748e/exp/exp_informer.py#L122

不明白这里为什么要调用它？注释掉也没有区别。谢谢

**Comment by cookieminions** [comment]
你好，感谢关注我们的工作和代码，此处的确没有区别，可以注释掉
