### ISSUE TITLE
Question about data standardization

### ISSUE THREAD

**Issue by TrevorIkky** [zhouhaoyi/Informer2020#233]
Hello, I plotted a kde plot and noticed that the features of the ETTh1 dataset are following a normal distribution. Is that the reason why in the code a StandardScaler is used? If my custom dataset has features with different data distributions is it advisable to use the MinMaxScaler as opposed the StandardScaler ? (I also changed the default scaler in the code to a MinMax scaler and noticed significant reduction in the loss metrics).

**Comment by zhouhaoyi** [comment]
One of the reasons for selecting StandardScaler is the data distribution. You could notice that we let the placeholder for unpredicted value as zero. This is also a natural result of applying StandardScaler. For MinMaxSclar, you can try to set that value as the average value of the whole dataset (quite similar to the image processing in CV). The default guesses for the future should be as general as possible. There may be other reasons for the loss reduction, like embedding layer, optimizer, and loss.

**Comment by TrevorIkky** [comment]
After plotting the results of the ground truth values and the predicted values. The graphs were almost **identical to the ones as provided in Colab. The loss appeared smaller because the values were tightly bound between 0 and 1. Thank you in advance.
