### ISSUE TITLE
I want to ask a question about the predictive function part of the model (an important but confusing question)

### ISSUE THREAD

**Issue by chenruhai** [zhouhaoyi/Informer2020#235]
Question:
In your code, I see that you split the data into 7:2:1, and then I see that you use Dataset_Pred, but the __read_data__ method in Dataset_Pred seems to use the total data set as input to the prediction function entirely. But from the perspective of the predicted shape, it is the same as the shape of the test set, so I think you used the test set as the input shape of the prediction function. Since I'm a TensorFlow user, I can't understand this code. So just to get to the point: Does Informer's prediction feature use test sets as input or does it use all the data as input? Or is it a prediction of future time at points not in the data set?

Question:
在您的代码中，我看到您将数据拆分为7:2:1，然后在进行预测的时候我看到您使用了Dataset_Pred，但是Dataset_Pred里面的 __read_data__方法却好像完全用了总数据集作为输入数据输入到预测功能中，但是从预测出来的shape来看，该shape是和测试集的shape是一样的，所以我又觉得是您使用了测试集作为预测功能的输入shape。由于我是平时用TensorFlow的，对这段代码看不太懂。所以想更加直入主题的问一下：informer的预测功能是使用了测试集作为输入呢还是将全部数据作为输入呢？又或者是对不在数据集的时间点的未来时间进行了预测呢？ 

我疑惑的问题在这里：https://blog.csdn.net/qq_42658739/article/details/118928809

**Comment by Tangxian17** [comment]
> Question: In your code, I see that you split the data into 7:2:1, and then I see that you use Dataset_Pred, but the **read_data** method in Dataset_Pred seems to use the total data set as input to the prediction function entirely. But from the perspective of the predicted shape, it is the same as the shape of the test set, so I think you used the test set as the input shape of the prediction function. Since I'm a TensorFlow user, I can't understand this code. So just to get to the point: Does Informer's prediction feature use test sets as input or does it use all the data as input? Or is it a prediction of future time at points not in the data set?
> 
> Question: 在您的代码中，我看到您将数据拆分为7:2:1，然后在进行预测的时候我看到您使用了Dataset_Pred，但是Dataset_Pred里面的 __read_data__方法却好像完全用了总数据集作为输入数据输入到预测功能中，但是从预测出来的shape来看，该shape是和测试集的shape是一样的，所以我又觉得是您使用了测试集作为预测功能的输入shape。由于我是平时用TensorFlow的，对这段代码看不太懂。所以想更加直入主题的问一下：informer的预测功能是使用了测试集作为输入呢还是将全部数据作为输入呢？又或者是对不在数据集的时间点的未来时间进行了预测呢？
> 
> 我疑惑的问题在这里：https://blog.csdn.net/qq_42658739/article/details/118928809
您好，我与您有同样的疑惑，请问您最后的得到的答案是啥哇？
