### ISSUE TITLE
关于M(q,K)的近似计算

### ISSUE THREAD

**Issue by zhanchey** [zhouhaoyi/Informer2020#238]
您好，论文中有一处不太明白，选取TOP u个query来近似Q矩阵，从而减少attention计算的开销。但是通过计算M矩阵来选取TOP u个query的事后，也用了近似计算，只计算LlnL个点，其他点用0代替，文中的解释是说“Under the long tail distribution, we only need randomly sample U = LQ lnLK dot-product pairs to calculate the M(qi, K),i.e. filling other pairs with zero.”
请问这个有数学上的计算证明吗

**Comment by Zero-coder** [comment]
It's a log-sum-exp question for solving numercial unstable problem,
please refer to this link:
https://zhuanlan.zhihu.com/p/153535799
