### ISSUE TITLE
ｔｒａｉｎ　ｍｙ　　ｄａｔａ

### ISSUE THREAD

**Issue by czczmr** [zhouhaoyi/Informer2020#240]
ｃａｎ　ｉ　ｕｓｅ　ｔｈｅ　ｐｒｏｊｅｃｔ　ｔｏ　ｔｒａｉｎ　ｍｙ　ｏｗｎ　ｄａｔａ　
ｓｈｏｗ　ｉ　ｍａｋｅ　ｓｏｍｅ　ｃｈａｎｇｅ？

**Comment by zhouhaoyi** [comment]
Please follow the Colab example in usage.
