### ISSUE TITLE
Ask: where is the parameter initialization of the model done? How do you define it?

### ISSUE THREAD

**Issue by chenruhai** [zhouhaoyi/Informer2020#245]
Dear author, I am studying your paper and model now. In terms of parameters of the model, I can't find anything related to parameter initialization of each layer of the model in main_informer. Since you have not learned the contents of the Model folder, I would like to ask you where the parameter initialization of your model is set. Are random seeds fixed?

**Comment by chenruhai** [comment]
> > > There is no random seed that has to be fixed to acquire the experiment results.
> > 
> > 
> > But if the random seed is not fixed, then if the result is good in the sixth experiment, but the experiment and the result cannot be replicated. If you want to fix the initial parameters each time, do you want to change the initialization parameters of each Layer in the encoder. Py and decoder.py classes?
> 
> Which result? and your experiment results? I could not understand the meaning of your last sentence.

**Comment by chenruhai** [comment]
> > > > 无需固定随机种子即可获得实验结果。
> > > 
> > > 
> > > 但是如果随机种子不固定，那么如果第六次实验结果好，但是实验和结果无法复制。如果每次都想固定初始参数，要不要改变encoder中每个Layer的初始化参数。Py 和decoder.py 类？
> > 
> > 
> > 哪个结果？和你的实验结果？我无法理解你最后一句话的意思。

**Comment by chenruhai** [comment]
> > > There is no random seed that has to be fixed to acquire the experiment results.
> > 
> > 
> > But if the random seed is not fixed, then if the result is good in the sixth experiment, but the experiment and the result cannot be replicated. If you want to fix the initial parameters each time, do you want to change the initialization parameters of each Layer in the encoder. Py and decoder.py classes?
> 
> Which result? and your experiment results? I could not understand the meaning of your last sentence.

That is, every experiment I run has a very different prediction, and if I want every experiment run to have the same result, do I have to initialize the parameters consistently for every experiment?

中文问题：
就是我运行出的每个实验结果的预测相差甚远，如果我想让每次实验运行的结果都差不多，是要进行每次实验的参数初始化一致吗？

**Comment by cookieminions** [comment]
> > > > There is no random seed that has to be fixed to acquire the experiment results.
> > > 
> > > 
> > > But if the random seed is not fixed, then if the result is good in the sixth experiment, but the experiment and the result cannot be replicated. If you want to fix the initial parameters each time, do you want to change the initialization parameters of each Layer in the encoder. Py and decoder.py classes?
> > 
> > 
> > Which result? and your experiment results? I could not understand the meaning of your last sentence.
> 
> That is, every experiment I run has a very different prediction, and if I want every experiment run to have the same result, do I have to initialize the parameters consistently for every experiment?
> 
> 中文问题： 就是我运行出的每个实验结果的预测相差甚远，如果我想让每次实验运行的结果都差不多，是要进行每次实验的参数初始化一致吗？

出了考虑参数初始化之外，在probsparse attention代码实现中有随机算子也可能导致实验结果出现一定偏差

**Comment by chenruhai** [comment]
> > > > > There is no random seed that has to be fixed to acquire the experiment results.
> > > > 
> > > > 
> > > > But if the random seed is not fixed, then if the result is good in the sixth experiment, but the experiment and the result cannot be replicated. If you want to fix the initial parameters each time, do you want to change the initialization parameters of each Layer in the encoder. Py and decoder.py classes?
> > > 
> > > 
> > > Which result? and your experiment results? I could not understand the meaning of your last sentence.
> > 
> > 
> > That is, every experiment I run has a very different prediction, and if I want every experiment run to have the same result, do I have to initialize the parameters consistently for every experiment?
> > 中文问题： 就是我运行出的每个实验结果的预测相差甚远，如果我想让每次实验运行的结果都差不多，是要进行每次实验的参数初始化一致吗？
> 
> 除了考虑参数初始化之外，在probsparse attention代码实现中有随机算子也可能导致实验结果出现一定偏差

那我去改改随机算子。
