### ISSUE TITLE
Why the calculated score dimension in FullAttention is (32, 8, 96, 96)

### ISSUE THREAD

**Issue by zxhjames** [zhouhaoyi/Informer2020#250]
hello,Dr.Zhou,Can you explain in detail the calculation process of the formula for calculating score in fulllattention?
```python
scores = torch.einsum("blhe,bshe->bhls", queries, keys)
```

**Comment by zhouhaoyi** [comment]
This is the standard calculation of attention score between Query and Key. The torch.einsum() tells how to match the correct multiplication. Am I missing anything?

**Comment by zxhjames** [comment]
> This is the standard calculation of attention score between Query and Key. The torch.einsum() tells how to match the correct multiplication. Am I missing anything?

Thanks for the reply, of course not, maybe I should be familiar with this concise usage, thanks
