### ISSUE TITLE
nan loss when input is not normalized/standardized 

### ISSUE THREAD

**Issue by puzzlecollector** [zhouhaoyi/Informer2020#251]
@zhouhaoyi 
When the input values are kind of large (in the 10,000 range - I am trying to make a gas supply demand forecasting model) and if I input these values into the Informer without any normalization/standardization, I get nan loss during training. However, if I normalize the values to be in [0,1] or if I standardize the train set, then I do not encounter this issue. Would you be able to provide me a possible explanation as to why this could be happening? (I am guessing it is some form of gradient explosion... by the way there are no nan values in my train set).

**Comment by puzzlecollector** [comment]
<img width="1016" alt="Screen Shot 2021-11-01 at 10 30 10 AM" src="https://user-images.githubusercontent.com/15623464/139609472-50275d7d-88f9-4341-bc49-310f4f3e598c.png">

Specifically, this is the error that I am getting (by the way this is what happened even after I standardized). 

The model seemed to train well, but then during the training it encounters that error and I end up with nan losses.

**Comment by puzzlecollector** [comment]
Perhaps the best thing to do is to min-max normalize so that the values are within the range of [0,1], and then do zero-mean normalization as suggested in the experiment setup in the Informer paper. Then I guess I will not encounter nan losses during training. 

Or maybe I can try doing zero-mean normalization and then min-max normalization. Or even something like standardization then min-max normalization.

**Comment by puzzlecollector** [comment]
Perhaps the nans are due to the mixed precision library in pytorch.... after getting rid of it training seems more stable??

**Comment by zhouhaoyi** [comment]
Thanks for your searching on this problem. From the model design perspective, I think the zero-mean normalization will perform better, but it may depend on the dataset. If you use min-max normalization, please refer to #233 for more details.

As for the mixed-precision, I suspect it relates to the precision of zero. So the zero-mean standardization will have more problems on computing the attention score, leading to undesirable nan.

**Comment by puzzlecollector** [comment]
@zhouhaoyi 
I just want to clarify a few things 
1. Zero-mean normalization is basically (train - mean(train)) / standard_deviation(train) right? 
2. Also if I input N different time series (all of which are of different scale, for example one time series has values in the range of 10~30 whereas the other has values in the range 1000~10000) is it ideal to perform zero-mean normalization on each individual time series separately, or should I apply it on the whole dataset? So in other words would it be better to do train = (train - np.mean(train)) / np.std(train) or should I instead do 

```
for i in range(N): 
    mu = np.mean(data[:,:,i]) 
    std = np.std(data[:,:,i]) 
    data[:,:,i] = (data[:,:,i] - mu) / std 
```
where data is of shape (batch, series, features), where features = N (so N time series are being used as input). 

Experimentally, it seemed better to perform zero-mean normalization on the entire dataset instead of applying this standardization separately on each input series.

**Comment by MountVoom** [comment]
The answer to question one is yes.
The two ways of question two are the same in my understanding.
