### ISSUE TITLE
当我使用自己的数据集时，cross_attention会出现维度问题

### ISSUE THREAD

**Issue by RuiStarlit** [zhouhaoyi/Informer2020#252]
当我使用自己的数据集时，除非Batch size设置为256.其他情况下cross_attention貌似不能正常工作
RuntimeError                              Traceback (most recent call last)
<ipython-input-90-f60c48391e9e> in <module>
     15 y = torch.from_numpy(Y)
     16 print(y.shape)
---> 17 pred,Y = process_one_batch(x, y)
     18 print(pred.shape)
     19 pred = pred.squeeze(2)

<ipython-input-61-372571fb110a> in process_one_batch(batch_x, batch_y)
      5     dec_inp = torch.cat([batch_y[:,:label_len], dec_inp], dim=1).float().to(device)
      6     # encoder - decoder
----> 7     outputs = model(batch_x, dec_inp)
      8     batch_y = batch_y[:,-out_len,:].to(device)
      9 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

/home/jovyan/quant/informer/models/model.py in forward(self, x_enc, x_dec, enc_self_mask, dec_self_mask, dec_enc_mask)
     71 
     72         dec_out = self.dec_embedding(x_dec)
---> 73         dec_out = self.decoder(dec_out, enc_out, x_mask=dec_self_mask, cross_mask=dec_enc_mask)
     74         dec_out = self.projection(dec_out)
     75 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

/home/jovyan/quant/informer/models/decoder.py in forward(self, x, cross, x_mask, cross_mask)
     44     def forward(self, x, cross, x_mask=None, cross_mask=None):
     45         for layer in self.layers:
---> 46             x = layer(x, cross, x_mask=x_mask, cross_mask=cross_mask)
     47 
     48         if self.norm is not None:

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

/home/jovyan/quant/informer/models/decoder.py in forward(self, x, cross, x_mask, cross_mask)
     27         x = x + self.dropout(self.cross_attention(
     28             x, cross, cross,
---> 29             attn_mask=cross_mask
     30         )[0])
     31 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

/home/jovyan/quant/informer/models/attn.py in forward(self, queries, keys, values, attn_mask)
    148 
    149         queries = self.query_projection(queries).view(B, L, H, -1)
--> 150         keys = self.key_projection(keys).view(B, S, H, -1)
    151         values = self.value_projection(values).view(B, S, H, -1)
    152 

RuntimeError: shape '[512, 5, 2, -1]' is invalid for input of size 12800

**Comment by cookieminions** [comment]
你好，请给出更多关于参数的详细设定以便定位错误
