### ISSUE TITLE
关于argparse里面的模型参数的问题

### ISSUE THREAD

**Issue by chenruhai** [zhouhaoyi/Informer2020#253]
尊敬的作者大大您好，请教一下，这个在main_informer文件里面的参数（enc_in、dec_in、c_out、d_model、n_heads、e_layers、d_layers、s_layers、d_ff、factor、padding、distil、attn、embed、activation、output_attention）各代表了什么功能（我知道它代表了什么意思，但是我不知道在informer模型中它的作用和功能是什么，所以想请教一下作者大大）；
使用小数据集（几百条或者几千条）的单变量建模预测的时候应该怎么设置比较好呢？

代码部分：

`parser.add_argument('--enc_in', type=int, default=7, help='encoder input size')
parser.add_argument('--dec_in', type=int, default=7, help='decoder input size')
parser.add_argument('--c_out', type=int, default=7, help='output size')
parser.add_argument('--d_model', type=int, default=512, help='dimension of model')
parser.add_argument('--n_heads', type=int, default=8, help='num of heads')
parser.add_argument('--e_layers', type=int, default=2, help='num of encoder layers')
parser.add_argument('--d_layers', type=int, default=1, help='num of decoder layers')
parser.add_argument('--s_layers', type=str, default='3,2,1', help='num of stack encoder layers')
parser.add_argument('--d_ff', type=int, default=2048, help='dimension of fcn')
parser.add_argument('--factor', type=int, default=5, help='probsparse attn factor')
parser.add_argument('--padding', type=int, default=0, help='padding type')
parser.add_argument('--distil', action='store_false', help='whether to use distilling in encoder, using this argument means not using distilling', default=True)
parser.add_argument('--dropout', type=float, default=0.05, help='dropout')
parser.add_argument('--attn', type=str, default='prob', help='attention used in encoder, options:[prob, full]')
parser.add_argument('--embed', type=str, default='timeF', help='time features encoding, options:[timeF, fixed, learned]')
parser.add_argument('--activation', type=str, default='gelu',help='activation')
parser.add_argument('--output_attention', action='store_true', help='whether to output attention in ecoder')`

**Comment by cookieminions** [comment]
enc_in: informer的encoder的输入维度
dec_in: informer的decoder的输入维度
c_out: informer的decoder的输出维度
d_model: informer中self-attention的输入和输出向量维度
n_heads: multi-head self-attention的head数
e_layers: informer的encoder的层数
d_layers: informer的decoder的层数
d_ff: self-attention后面的FFN的中间向量表征维度
factor: probsparse attention中设置的因子系数
padding: decoder的输入中，作为占位的x_token是填0还是填1
distil: informer的encoder是否使用注意力蒸馏
attn: informer的encoder和decoder中使用的自注意力机制
embed: 输入数据的时序编码方式
activation: informer的encoder和decoder中的大部分激活函数
output_attention: 是否选择让informer的encoder输出attention以便进行分析

小数据集的预测可以先使用默认参数或适当减小d_model和d_ff的大小

**Comment by chenruhai** [comment]
> enc_in: informer的encoder的输入维度 dec_in: informer的decoder的输入维度 c_out: informer的decoder的输出维度 d_model: informer中self-attention的输入和输出向量维度 n_heads: multi-head self-attention的head数 e_layers: informer的encoder的层数 d_layers: informer的decoder的层数 d_ff: self-attention后面的FFN的中间向量表征维度 factor: probsparse attention中设置的因子系数 padding: decoder的输入中，作为占位的x_token是填0还是填1 distil: informer的encoder是否使用注意力蒸馏 attn: informer的encoder和decoder中使用的自注意力机制 embed: 输入数据的时序编码方式 activation: informer的encoder和decoder中的大部分激活函数 output_attention: 是否选择让informer的encoder输出attention以便进行分析
> 
> 小数据集的预测可以先使用默认参数或适当减小d_model和d_ff的大小

非常感谢
