### ISSUE TITLE
__len__() should return >= 0

### ISSUE THREAD

**Issue by Erickurashi** [zhouhaoyi/Informer2020#255]
您好，
非常感谢您分享出来的代码，我尝试着用自己的数据，但是会出现__len__() should return >= 0的报错，请问如何解决。
谢谢
Use GPU: cuda:0
>>>>>>>start training : informer_ETTh1_ftM_sl200_ll100_pl100_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 6101
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-50ab8c1f413c> in <module>()
     10     # train
     11     print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
---> 12     exp.train(setting)
     13 
     14     # test

1 frames
/content/Informer2020/exp/exp_informer.py in train(self, setting)
    125     def train(self, setting):
    126         train_data, train_loader = self._get_data(flag = 'train')
--> 127         vali_data, vali_loader = self._get_data(flag = 'val')
    128         test_data, test_loader = self._get_data(flag = 'test')
    129 

/content/Informer2020/exp/exp_informer.py in _get_data(self, flag)
     93             cols=args.cols
     94         )
---> 95         print(flag, len(data_set))
     96         data_loader = DataLoader(
     97             data_set,

ValueError: __len__() should return >= 0

**Comment by zhouhaoyi** [comment]
你好，可以检查一下你的数据list是否为空。

**Comment by cookieminions** [comment]
你好，请确保seq_len，label_len，pred_len等设置满足data_loader中的`__len__()`方法中的返回值大于0

**Comment by kuraoumu** [comment]
@Erickurashi 你好，我也遇到了和你一样的问题，想问下你是怎么解决的呢？

**Comment by kuraoumu** [comment]
@cookieminions 您好，我观察到data_loader中的seq_len，label_len，pred_len都是默认值，应该怎样修改呢？是直接在informer.ipynb中修改参数就可以吗？以及问题报错点来自exp_informer.py，还需要进行别的操作吗？

**Comment by yangzhan111** [comment]
您好 我也遇到了同样的问题 请问下如何解决那

**Comment by Monday0423** [comment]
你好 ，我也遇到了同样的问题，检查过数据list不为空，请问应该怎么解决呢？

**Comment by king571834** [comment]
我也遇到一樣問題

**Comment by Monday0423** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在玩。可能晚一些回复==

**Comment by noviceor** [comment]
我也有这样问题请问怎么解决

**Comment by Monday0423** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在玩。可能晚一些回复==
