### ISSUE TITLE
ECL和weather数据集划分

### ISSUE THREAD

**Issue by xiaohuihui1234-2** [zhouhaoyi/Informer2020#256]
作者你好，我在使用ECL和Weather数据集时，看你论文里划分是按月进行划分，代码给的部分在自定义数据集里是按训练0.7，测试0.2，验证0.1进行划分的，该部分划分是否要按照月份来呢

**Comment by cookieminions** [comment]
可以按照月来划分，代码中的自定义数据集也可以自行修改划分区间
