### ISSUE TITLE
你好，请问当我使用我自己的数据集的时候，我应该如何处理数据

### ISSUE THREAD

**Issue by zulihit** [zhouhaoyi/Informer2020#259]

**Comment by zulihit** [comment]
我希望通过前6列的数据来预测最后一列的数据，我尝试把数据格式做成和ETTh1相同的，但是输入模型的时候依旧会出现问题，请问我应该如何使用呢，希望可以得到帮助
![image](https://user-images.githubusercontent.com/68625084/142092081-138179a5-fd2d-4e85-a8f0-8138d47707ad.png)

**Comment by zhouhaoyi** [comment]
请参考colab中给出的example
