### ISSUE TITLE
Informer for sequence classification and masking ... thanks

### ISSUE THREAD

**Issue by junyongyou** [zhouhaoyi/Informer2020#261]
I am trying to use Informer in sequence classification, and I saw there were some issues before. So I post my approach here, and hope the authors @zhouhaoyi and others have any suggestions.

My problem is to classify sequences with different lengths. Informer can actually handle variable input lengths. However, when we put sequences in a batch, we have to pad them and then need to consider masking the sequences.

I am following the idea in BERT/ViT using the Encoder for classification only. Maybe I should also use Decoder? Any suggestions here?

For classification, there can be two approaches: 1) following BERT/Vit, adding a CLS token in the beginning, and then using only the first column of the encoded output, following by a linear head; 2) not adding the CLS token, instead, using the mean of the encoded output along dim=1, and then followed by a linear head. In my case, it seems the approach 1 works a bit better. If one add a CLS token, then then mask below should also be adjusted.

For masking, I am not using the original ProbMask. Instead, I generated a mask for each padded sequence, in which the mask value for the original sequence is 0 and the padded part is set to -Inf (or a very large negative number). Then I passed the mask to the Encoder, added it to the scores, as following:

`scores = torch.add(scores, mask)
attn = torch.softmax(scores, dim=-1)` 

The idea is to keep the scores of the original sequence, while the padded part will become very small. After softmax, the padded part will be 0. This idea is still following the original Transformer. In order to handle the dimension mismatch issue, as in the ConvLayer, a maxPool with stride=2 is used, `self.maxPool = nn.MaxPool1d(kernel_size=3, stride=2, padding=1)`, I have changed the stride to 1. Of course, one can also maxPool the mask.

However, the above approach must have lost the idea of ProbMask. So I don't how it would damage the performance of Informer.

If the authors or others can give some guidance, that is highly appreciated. 

Any suggestions and discussions are highly welcome, as this should be an interesting topic. Thanks a lot.

**Comment by zhouhaoyi** [comment]
Thanks for the constructive sharing. I think the current mask implementation is cool. And for the ProbMask, I think the performance damage will be limited.
Personally, I believe the masking strategy and the token technique will be re-designed for the time-series problems.
I am looking forward to further discussion on this topic.
