### ISSUE TITLE
关于预测值的masking

### ISSUE THREAD

**Issue by qsd4014** [zhouhaoyi/Informer2020#263]
请问如果是'MS'的任务即多个features对应一个output，那：

1. 此时在encoder中的输入是不是同时包括着feature和output？也就是在encoder中output也会被考虑在内？
2. decoder中的masking将预测部分mask了，看代码这个mask是同时mask了features以及output，然后是对所有的features以及output进行预测，能不能将feature部分作为已知信息只mask output部分呢？（假设output和其他features具有相关性）
3. mask的只用0或者1替代，如果在原数据集中有大量0，1或者0，1具有具体的数值含义，是不是会对模型的训练造成影响？如果有的话，有什么好的避免方法么？

感谢

**Comment by cookieminions** [comment]
1. 如果我没理解错的话，你说的features应该是指除了需要预测的特征之外的其他特征，output是指需要预测的特征；如果是这样的话，encoder确实是都包括了的，因为encoder中需要预测特征的历史序列，而decoder会预测未来序列，当然你也可以通过修改代码使encoder不输入output特征
2. 我们的代码在decoder部分是同时mask掉了所有的特征，因为mask考虑的是时序上的关系而不是特征之间的关系
3. 我们的mask不是在输入上使用0或1进行代替，在具体实现上主要在self-attention内部，你说的应该是指decoder的输入是由start token和一段全0的序列拼接组成；这部分应该不会造成太大影响

**Comment by samuel01028** [comment]
您好题主和作者，关于MS任务：
1. 如果希望模型输入不包括output特征，为什么作者说修改encoder？  不应该是修改传入每次model的数据吗？
2. 在encoder输入部分特定feture，encoder能输入特定feature+output变量，这时encoder和decoder处理的维度在embedding后仍要相同吧？ 这是否可行呢？
