### ISSUE TITLE
The size of tensor mismatch

### ISSUE THREAD

**Issue by mixcheck** [zhouhaoyi/Informer2020#264]
When I try to this script, I have a problem.

**cmd:** 
python -u main_informer.py --model informer --data ETTh1 --features M --seq_len 48 --label_len 48 --pred_len 24 --e_layers 2 --d_layers 1 --attn prob --des 'Exp' --itr 5 --factor 3

**Error msg:**
Args in experiment:
Namespace(activation='gelu', attn='prob', batch_size=32, c_out=7, checkpoints='./checkpoints/', cols=None, d_ff=2048, d_layers=1, d_model=512, data='ETTh1', data_path='ETTh1.csv', dec_in=7, des='Exp', detail_freq='h', devices='0,1,2,3', distil=True, do_predict=False, dropout=0.05, e_layers=2, embed='timeF', enc_in=7, factor=3, features='M', freq='h', gpu=0, inverse=False, itr=5, label_len=48, learning_rate=0.0001, loss='mse', lradj='type1', mix=True, model='informer', n_heads=8, num_workers=0, output_attention=False, padding=0, patience=3, pred_len=24, root_path='./data/ETT/', s_layers=[3, 2, 1], seq_len=48, target='OT', train_epochs=6, use_amp=False, use_gpu=True, use_multi_gpu=False)
Use GPU: cuda:0
>>>>>>>start training : informer_ETTh1_ftM_sl48_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc3_ebtimeF_dtTrue_mxTrue_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8569
val 2857
test 2857
Traceback (most recent call last):
  File "main_informer.py", line 104, in <module>
    exp.train(setting)
  File "/home/jovyan/myspace/SDCFCST/Informer2020-main/exp/exp_informer.py", line 155, in train
    pred, true = self._process_one_batch(
  File "/home/jovyan/myspace/SDCFCST/Informer2020-main/exp/exp_informer.py", line 283, in _process_one_batch
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/myspace/SDCFCST/Informer2020-main/models/model.py", line 69, in forward
    enc_out = self.enc_embedding(x_enc, x_mark_enc)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/myspace/SDCFCST/Informer2020-main/models/embed.py", line 107, in forward
    x = self.value_embedding(x) + self.position_embedding(x) + self.temporal_embedding(x_mark)
RuntimeError: The size of tensor a (50) must match the size of tensor b (48) at non-singleton dimension 1

My environment is below:

OS: Ubuntu 20.04.3 LTS
GPU: NVIDIA A100
CUDA: 11.4
NVIDIA Driver: 470.63
pyTorch: 1.10.0
python: 3.8.10

Do I match the version of CUDA, pyTorch, or python with your library dependency or requirement?
Python 3.6
matplotlib == 3.1.1
numpy == 1.19.4
pandas == 0.25.1
scikit_learn == 0.21.3
torch == 1.8.0

Unfortunately, some environments are the company's internal default environments and I cannot change them.... (CUDA, Driver Version and so on)

How can I fix Tensor size mismatch errors?

**Comment by mixcheck** [comment]
I'm not sure..............

I modify here:

$INFORMER_ROOT/models/embed.py:

class TokenEmbedding(nn.Module):
    def __init__(self, c_in, d_model):
        super(TokenEmbedding, self).__init__()
        padding = 1 if torch.__version__>='1.5.0' else 2
        self.tokenConv = nn.Conv1d(in_channels=c_in, out_channels=d_model, 
                                    # kernel_size=3, padding=padding) Fix Here..
                                    **kernel_size=5**, padding=padding)
        for m in self.modules():
            if isinstance(m, nn.Conv1d):
                nn.init.kaiming_normal_(m.weight,mode='fan_in',nonlinearity='leaky_relu')

Originally, the kernel size is 3. Can I Change the kernel_size 3 to 5?
Then the error message  dismisses

Thnks

**Comment by cookieminions** [comment]
Thanks for your attention, this is a problem caused by `Conv1D` using `padding_mode='circular'` in different torch version.
