### ISSUE TITLE
关于使用自定义数据集后，进行多变量预测单变量即MS，训练的时候其输出的pred和true维度不一样的问题

### ISSUE THREAD

**Issue by CLoweW** [zhouhaoyi/Informer2020#265]
感谢作者在百忙之中抽出时间来回答我这个问题，不胜感激，非常感谢。
我的数据集如下：
![image](https://user-images.githubusercontent.com/95207805/143830593-18023701-8d14-45b5-a222-56374769d111.png)
我进行的模型配置如下：
![image](https://user-images.githubusercontent.com/95207805/143830752-84927c63-0905-4207-bb27-e6ad61809c0d.png)

我训练的时候对  `pred, true = self._process_one_batch(train_data, batch_x, batch_y, batch_x_mark, batch_y_mark)` 进行打印pred和true，得到了他们两个是维度不一样的，如下：
![image](https://user-images.githubusercontent.com/95207805/143830894-acfccfd6-5b14-4243-8787-616720d2009e.png)
由于pred和true的维度差异，导致训练的时候loss很高，如下：
![image](https://user-images.githubusercontent.com/95207805/143831148-d8e67107-dc18-440b-971f-dae7ed3770c6.png)

此外，其predict部分的预测的维度大小也不一样，如下：
![image](https://user-images.githubusercontent.com/95207805/143831081-3225222c-4019-4ad5-b69b-c8b76db8f683.png)

您好，能够问一下我该如何去配置该项目，让其训练正常，输出只有一个呢？

**Comment by CLoweW** [comment]
我在colab示例里面查看了对应的代码运行框的内容，同理说、设置为2,2,1 应该没有问题。至于其它其它代码的部分我都是默认的没怎么修改到，我就修改了关键的地方。

**Comment by cookieminions** [comment]
你好，请确认一下模型的`enc_in, dec_in`和`c_out`的设置都是没有问题的，例如你的数据输入是2输出是1，那么模型应该是`enc_in=2, dec_in=2, c_out=1`，你所修改的部分是一个parser，最终还是需要转换到模型的参数上

**Comment by CLoweW** [comment]
> 你好，请确认一下模型的`enc_in, dec_in`和`c_out`的设置都是没有问题的，例如你的数据输入是2输出是1，那么模型应该是`enc_in=2, dec_in=2, c_out=1`，你所修改的部分是一个parser，最终还是需要转换到模型的参数上

是的，我设置的是这样的：
![image](https://user-images.githubusercontent.com/95207805/144369606-a35344d1-8d59-4802-aee8-e52ea26653db.png)

于是，我在代码中加了 ` preds = preds[:, :, -1:] if args.features == 'MS' else preds` 之后，他就正常了，损失计算也是使用的这个目标变量去计算。
在如下位置加的：
![image](https://user-images.githubusercontent.com/95207805/144369932-a8feec14-e930-44d8-a125-039ab6354a28.png)

**Comment by CLoweW** [comment]
> > 你好，请确认一下模型的`enc_in, dec_in`和`c_out`的设置都是没有问题的，例如你的数据输入是2输出是1，那么模型应该是`enc_in=2, dec_in=2, c_out=1`，你所修改的部分是一个parser，最终还是需要转换到模型的参数上
> 
> 是的，我设置的是这样的： ![image](https://user-images.githubusercontent.com/95207805/144369606-a35344d1-8d59-4802-aee8-e52ea26653db.png)
> 
> 于是，我在代码中加了 ` preds = preds[:, :, -1:] if args.features == 'MS' else preds` 之后，他就正常了，损失计算也是使用的这个目标变量去计算。 在如下位置加的： ![image](https://user-images.githubusercontent.com/95207805/144369932-a8feec14-e930-44d8-a125-039ab6354a28.png)

@cookieminions 不知道我加这样的代码上去可不可以

**Comment by cookieminions** [comment]
是可以的，在代码`exp/exp_informer.py`中也有对应的代码

**Comment by CLoweW** [comment]
> 是可以的，在代码`exp/exp_informer.py`中也有对应的代码
嗯嗯，我就是在exp/exp_informer.py中加的。
