### ISSUE TITLE
Prediciton Almost flattened

### ISSUE THREAD

**Issue by PeihanDou** [zhouhaoyi/Informer2020#266]
Hello! Thank you for your well-structured code! I am currently doing some task using Informer. I used same network settings as ETTH dataset. But the output is not making sense to me. It is something like that:

![image](https://user-images.githubusercontent.com/55855936/143868694-9be9ec6a-9094-4a14-8ba4-4c81d8b22b22.png)

Noticing the prediction is almost flattened. Do you have any thoughts about what could be the problem? I think maybe I should adjust the hyperparameters of the network? Do you have any suggestions about that? Thank you very much!

**Comment by cookieminions** [comment]
Thanks for your attention to our work, maybe you can increase the `seq_len` of model, and use multivariate prediction if data allows.
