### ISSUE TITLE
关于论文中的图9的疑惑

### ISSUE THREAD

**Issue by CLoweW** [zhouhaoyi/Informer2020#267]
作者您好，请问论文中的下述结果是基于训练结果做的可视化？还是基于测试集结果做的可视化？还是基于预测未来(predict)的时候做的可视化呢？
![image](https://user-images.githubusercontent.com/95207805/144377730-1fa11814-6269-4b29-a282-dd5a465d5a88.png)

**Comment by zhouhaoyi** [comment]
选取的某次预测的结果进行可视化。
