### ISSUE TITLE
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

### ISSUE THREAD

**Issue by Phil610351** [zhouhaoyi/Informer2020#268]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
你好，大佬，为什么搞这个，
data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

还有你的输入，Xen 代码 长度为96的序列吗

Xde={Xtoken，X0} ,Xtoken和X0 是什么意思？

大佬可否指导一下 。

**Comment by Phil610351** [comment]
X_token 是干啥的？

**Comment by zhouhaoyi** [comment]
> X_token 是干啥的？

作为Decoder的Token，请查阅历史issue，很多次都讨论过这个问题。
