### ISSUE TITLE
Handling multi entity data

### ISSUE THREAD

**Issue by kiddyboots216** [zhouhaoyi/Informer2020#271]
I believe this is similar to #191 but I am going to specify the question in depth a bit. In my dataset I am collecting multiple features from multiple households and I have one target. That is, my features are 'MS' [target, other_features] and I want to predict [target]. This is true for multiple households. So I can make my data look like [timestamp, target_house1, other_features_house1, ..., target_houseN, other_features_houseN]. However, in this case I am not sure whether Informer can handle this data. In the referenced PR, the suggestion is made to make use of embeddings for the multiple features. Could you provide some clarity on this? Thanks

**Comment by cookieminions** [comment]
Maybe you can add a new `embedding and aggregation layer`, so that you can embed `feature1_houseN, ..., featureM_houseN` into `embed1_houseN, ..., embedM_houseN` and then average these embeddings into `embed_avg_houseN`.
