### ISSUE TITLE
What is the purpose of label_len

### ISSUE THREAD

**Issue by kiddyboots216** [zhouhaoyi/Informer2020#272]
I'm trying to understand the purpose of label_len in the code. When we build a batch, label_len does not change X at all, but it does change Y. I know that label_len changes the start token length. It seems to me like increasing label_len should increase the model performance because the decoder gets more context. However, when I do experiments the performance is maximized when label_len=0. 

For the task, I am trying to look back at as much historical data as possible, and then predict the next 24/48 values (hourly). Is label_len=0 reasonable for this task? Thanks.

**Comment by chenruhai** [comment]
I have the same question. When label_len=0, the decoding strategy of the model uses all the information, and then the decoding information is vaguely included in the calculation of loss, which also includes the information when updating parameters, resulting in better effect of the model, but it takes more time to train. I wonder if that's true?

**Comment by cookieminions** [comment]
It's okay to set `label_len=0`.
