### ISSUE TITLE
In ProbAttention, why should we initial context tensor?

### ISSUE THREAD

**Issue by blablahaha** [zhouhaoyi/Informer2020#278]
Thanks for sharing this amazing work!!

In `class ProbAttention` (file models/attn.py), line 90-92 

https://github.com/zhouhaoyi/Informer2020/blob/90e080593e9c345f5f9676359bb3d1618e9aa735/models/attn.py#L90-L92

I'm confused why should we initial context, instead of directly using `attn * v` as context, maybe like:
```python
context_in = torch.matmul(attn, V)
```

Same as pseudo-code (line 8), why cannot just set `S = {S1} `
<img width="518" alt="Screen Shot 2021-12-23 at 12 07 13" src="https://user-images.githubusercontent.com/6917105/147186642-de1d53e4-39bf-448e-833e-c207d590fd38.png">

Please let me know, if I missed some details which was mentioned paper 🤣

**Comment by cookieminions** [comment]
In ProbAttention, we initialize the `context_in` in function `_get_initial_context()` and the shape of `context_in` is `[L, L]`. And we use `Q_K_sample` to calculate `attn`, so the shape of `attn` is `[L, log(L)]`. So we assign the `index` of `context_in` usign `attn * V`.

**Comment by blablahaha** [comment]
> In ProbAttention, we initialize the `context_in` in function `_get_initial_context()` and the shape of `context_in` is `[L, L]`. And we use `Q_K_sample` to calculate `attn`, so the shape of `attn` is `[L, log(L)]`. So we assign the `index` of `context_in` using `attn * V`.

Appreciate for your reply.  

I‘m confused why connot directly use `attn * V` as `context_in` (with shape `[batch_size, top_n, ...]`),  instead of just assigning the `index` of `context_in` (with shape `[batch_size, sequence_length, ...]`)

(Maybe we need to keep same sequence length, in order to pass it to the next layer?)

**Comment by cookieminions** [comment]
> > In ProbAttention, we initialize the `context_in` in function `_get_initial_context()` and the shape of `context_in` is `[L, L]`. And we use `Q_K_sample` to calculate `attn`, so the shape of `attn` is `[L, log(L)]`. So we assign the `index` of `context_in` using `attn * V`.
> 
> Appreciate for your reply.
> 
> I‘m confused why connot directly use `attn * V` as `context_in` (with shape `[batch_size, top_n, ...]`), instead of just assigning the `index` of `context_in` (with shape `[batch_size, sequence_length, ...]`)
> 
> (Maybe we need to keep same sequence length, in order to pass it to the next layer?)

Yes, we need to keep the `context_in` as shape `[B, L, ...]`.

**Comment by blablahaha** [comment]
>> > In ProbAttention, we initialize the `context_in` in function `_get_initial_context()` and the shape of `context_in` is `[L, L]`. And we use `Q_K_sample` to calculate `attn`, so the shape of `attn` is `[L, log(L)]`. So we assign the `index` of `context_in` using `attn * V`.
>> 
>>  Appreciate for your reply.
>> 
>>  I‘m confused why connot directly use `attn * V` as `context_in` (with shape `[batch_size, top_n, ...]`), instead of just assigning the `index` of `context_in` (with shape `[batch_size, sequence_length, ...]`)
>> 
>>  (Maybe we need to keep output of `AttentionLayer` has same shape with sequence length, in order that pass it to the next layer?)
>
> Yes, we need to keep the context_in as shape [B, L, ...].

After attention layer, we use `Conv1d` as next layer, and do 1D convolution (kernel width=3) on time dimension, it will finally reduce time dimension. So...why should we keep `context_in` as shape [B, L, ...], instead of reducing time dimension in this step?

Maybe keep original shape (use more sequence information?) can improve accuracy? (Sorry if I bothered you...

**Comment by zhouhaoyi** [comment]
Actually, the `Conv1d` will turn down the information faucet from the self-attention block. We believe it is affordable in performing long-term forecasting. But it may help in the short-term cases if we keep the original shape.
