### ISSUE TITLE
作者您好，有个代码细节引发的思考想问一下，就是exp_informer里面的drop_last变量。

### ISSUE THREAD

**Issue by chenruhai** [zhouhaoyi/Informer2020#279]
就是代码中这句代码：
`        else:
            shuffle_flag = False; drop_last = False; batch_size = args.batch_size; freq=args.freq`

这句代码的drop_last 如果为True的话是不是就将最后不满足一个batch的数据给丢掉，然后再训练。如果最后的数据确实不满足一个batch的话设为drop_last =False的话会报错吗？

**Comment by cookieminions** [comment]
设置`drop_last=True`是为了保证代码中一些tensor的shape不会引发错误，如果设置`drop_last=False`可能会引起问题
如果是为了保证test数据集或者predict数据集不丢失任何样例，可以设置`batch_size=1`

**Comment by chenruhai** [comment]
> 设置`drop_last=True`是为了保证代码中一些tensor的shape不会引发错误，如果设置`drop_last=False`可能会引起问题 如果是为了保证test数据集或者predict数据集不丢失任何样例，可以设置`batch_size=1`

作者您好，你说的我能理解。就是如果训练集上使用drop_last = False的时候，会有一些数据由于不够一个batch_size然后shape发生错误是吗？

就是假如想要保留这份不够一个batch的数据的话，是不是需要补0操作呢？

**Comment by zhouhaoyi** [comment]
如果要保留的话，就正常补0。
