### ISSUE TITLE
测试集训练结果

### ISSUE THREAD

**Issue by GalanPei** [zhouhaoyi/Informer2020#280]
作者您好，因为项目需要，我们想要看一下全部测试集的训练情况，所以需要做一张所有测试集的pred和true的图。但是发现在train时，训练集是被打乱的，所以没有办法获得原顺序的数据，请问有办法可以将打乱的数据reorder吗？万分感谢！

**Comment by Tangxian17** [comment]
> 作者您好，因为项目需要，我们想要看一下全部测试集的训练情况，所以需要做一张所有测试集的pred和true的图。但是发现在train时，训练集是被打乱的，所以没有办法获得原顺序的数据，请问有办法可以将打乱的数据reorder吗？万分感谢！

您好，请问您解决了么？
