### ISSUE TITLE
能不能在国内资源上传个运行教程，Colab Examples国内访问不了，得梯子才行

### ISSUE THREAD

**Issue by junjie2008v** [zhouhaoyi/Informer2020#281]
周老师，您好，能否在国内的一些资源上放置Examples，在colab.research.google.com上的Colab Examples，国内无法访问，非常不利于学习您的这个模型

**Comment by zhouhaoyi** [comment]
你好，国内比较难找一个提供运行资源的平台。我们正在和一些平台接洽，希望能顺利。
