### ISSUE TITLE
Informer when it comes to variable selection? 

### ISSUE THREAD

**Issue by puzzlecollector** [zhouhaoyi/Informer2020#284]
@zhouhaoyi 
In your opinion is the informer effective in deciding which variables are useful and which are not? 
So in other words, is it good at variable selection when there are many features that are being input into the model?

**Comment by zhouhaoyi** [comment]
I think self-attention is a mechanism that selects the most relevant and robust relationship in the inputs for the latter inner layer to learn. For Informer, the ProbSparse attention helps to select the most significant pairs. If you find some sparse pattern useful in a particular dataset, I believe this could be a solution for variable selection.
