### ISSUE TITLE
Fail to reproduce the results. 

### ISSUE THREAD

**Issue by MarcAntoineAlex** [zhouhaoyi/Informer2020#285]
I've used the latest version of your code, and got the following results which are quite weird
pred_len 24: mse:0.4061545729637146, mae:0.4404798150062561
pred_len 48: mse:0.48272132873535156, mae:0.46404534578323364
pred_len 168: mse:0.49321380257606506, mae:0.48073211312294006
pred_len 336: mse:0.5146851539611816, mae:0.4921443462371826
pred_len 720: mse:0.49855655431747437, mae:0.5004686117172241

Also, why the performance of informer in your paper is different from that in the original paper ?

**Comment by zhouhaoyi** [comment]
Please clarify the dataset and scripts. You can follow the Colab example, and follow the training scripts in /scripts.

**Comment by MarcAntoineAlex** [comment]
I've found the problem, thanks !
