### ISSUE TITLE
请问间隔时序序列对于数据集的调整部分主要在哪块实现呢

### ISSUE THREAD

**Issue by AndrewD1024** [zhouhaoyi/Informer2020#286]
作者大大您好，我想请问下，如果是一个间隔的时间序列，比如以3h为间隔的10天的连续序列，终止在2000/5/16 18:00:00，然后到了下一个连续时间2000/5/17 06:00开始7天的连续序列，再到其他时间。也就是说，整个时间序列不是连续的而是一段一段的，那么是否需要在Data_custom中进行时序数据训练集、验证、测试集的重新构造？
![image](https://user-images.githubusercontent.com/55874632/150058824-9dfcbc88-a884-4996-82b3-dda4b89bcfad.png)

**Comment by zhouhaoyi** [comment]
如果是date上面有间断，可以通过对time stamp进行表征，作为一种特殊的positinal embedding加入就可以，设计方式可以借鉴我们对于不同周期的token处理。从这一点上来说，肯定要修改data_loader的。

**Comment by kuraoumu** [comment]
@AndrewD1024 你好，我的时间序列也是一段一段的，想请教下你是怎么修改的呢？

**Comment by Xxlx5649** [comment]
@

> @AndrewD1024 你好，我的时间序列也是一段一段的，想请教下你是怎么修改的呢？

您好，请问问题解决了吗，我的时间戳是毫秒级别且不同间隔的

**Comment by samuel01028** [comment]
> @
> 
> > @AndrewD1024 你好，我的时间序列也是一段一段的，想请教下你是怎么修改的呢？
> 
> 您好，请问问题解决了吗，我的时间戳是毫秒级别且不同间隔的

您好，我也有同样的问题，数据精确到秒，但是间隔并不固定，请问直接是否能直接设置freq=s？
