### ISSUE TITLE
Weather Dataset

### ISSUE THREAD

**Issue by Big-Tree** [zhouhaoyi/Informer2020#287]
Hi, thank you very much for putting your code on GitHub.  In the paper you mention that the weather dataset consists of 1600 locations, however, the [link](https://drive.google.com/drive/folders/1ohGYWWohJlOlb2gsGTeEq3Wii2egnEPR?usp=sharing) in the README.md contains just one location.  To reproduce the results from the paper was the model trained on the data you link to or all locations?

**Comment by zhouhaoyi** [comment]
The data we linked. Thanks.
