### ISSUE TITLE
关于预测时报错__len__() should return >= 0的问题

### ISSUE THREAD

**Issue by kuraoumu** [zhouhaoyi/Informer2020#288]
作者大大新年快乐！我在用自己的数据做预测时，在模型训练步骤时报错：__len__() should return >= 0，请问这是因为我的数据有问题嘛？这是我的数据：
[1.csv](https://github.com/zhouhaoyi/Informer2020/files/7980622/1.csv)

**Comment by kuraoumu** [comment]
关于colab里给的custom data部分，我只需要修改这两个地方的参数吗？我改了之后再训练模型，问题依旧存在
<img width="924" alt="微信截图_20220203173922" src="https://user-images.githubusercontent.com/75313084/152317621-59033ac3-8776-4942-a619-b1bd088e0b4d.png">
![image](https://user-images.githubusercontent.com/75313084/152318087-94fb156d-f4d9-4eed-b01a-ebdd4e654310.png)
以及关于custom data部分的代码应该放在哪里呢？感谢！

**Comment by wjmbalala** [comment]
请问解决了吗？能解释一下吗

**Comment by roeyjob** [comment]
请问len() should return >= 0这个问题怎么解决呢？
