### ISSUE TITLE
请问这个只将训练集进行了标准化吗？

### ISSUE THREAD

**Issue by somethingforheheda** [zhouhaoyi/Informer2020#289]
Dataset_ETT_hour有个参数scale控制train的标准化 但是也只是将训练集标准化了 问下测试集和验证集也标准化了吗 如果标准化了 麻烦告诉一下在哪里标准化的 还有这个scale我试了如果设为false 训练集也不标准化了 loss就很大

**Comment by zhouhaoyi** [comment]
训练和测试集都是从这个数据集里面split取出来的。

**Comment by somethingforheheda** [comment]
再问问 这个exp_informer中early_stopping = EarlyStopping(patience=self.args.patience, verbose=True) 的EarlyStopping有什么作用吗 我没看懂 感觉好像是loss达到某个条件就会停止这次的训练 这样会不会导致对比实验的时候不严谨啊 这个参数patience怎么设置可以不让它更早的停止 感谢指导！！！

**Comment by somethingforheheda** [comment]
可以在问一下，weather数据集是哪里来的吗 我看了weather数据的链接不知道怎么下。我看了之前的issues，发现你们关于weather数据的回答很模糊，可以直接把weather，和ECL的数据都放到github中吗 或者不能放的话 邮件发给我 1484410245@qq.com 如果不方便给的话 也给我回应一下 感谢！
