### ISSUE TITLE
Little problem in utils/masking.py 

### ISSUE THREAD

**Issue by wangxiongts** [zhouhaoyi/Informer2020#29]
Line 15 in utils/masking.py should be dtype=torch.bool, not dytpe=torch.bool. ^-^

**Comment by cookieminions** [comment]
Thank you very much! We will correct this soon.  (-^〇^-)

**Comment by zhouhaoyi** [comment]
This problem has been pushed. So I will close this issue.

**Comment by chenjuncc** [comment]
你好，我还是出现这个错误File "D:\Informer2020-main\utils\masking.py", line 15, in __init__
    _mask = torch.ones(L, scores.shape[-1], dtype=torch.bool).triu(1)
RuntimeError: "triu" not implemented for 'Bool'

**Comment by guozaimian** [comment]
您好，同样想问一下，我也是出现了 line 15, in __init__mask = torch.ones(L, scores.shape[-1], dtype=torch.bool).to(device).triu(1)
RuntimeError: name not implemented for 'Bool'这个错误，是如何解决的呢？
