### ISSUE TITLE
TimeFeatures - Ordinality?

### ISSUE THREAD

**Issue by santoshreddappa** [zhouhaoyi/Informer2020#291]
Does encoding time features between 0.5 and -0.5 introduce unnecessary ordinality?

For example, Sunday is encoded as -0.5, Monday is encoded as 0.5, and Thursday as 0.0

Similarly, with other time features like the day of the week, and the minute of the hour.

**Comment by zhouhaoyi** [comment]
Yeah, actually they should be treated equivalently. But we just test that this kind of encoding performs fine. Maybe other methods could be introduced here.
