### ISSUE TITLE
关于数据集最短长度的问题

### ISSUE THREAD

**Issue by kuraoumu** [zhouhaoyi/Informer2020#292]
我自己的数据集在训练过程中出现__len__() should return >= 0问题，因为我的数据集为股市日度数据，长度较短，所以我尝试将原数据集ETTh1缩短寻找问题，发现原本train+val+test的长度为8521+2857+2857，当数据集长度大于该值时train、val、test长度不变，小于该值时train、val不变，test缩短，继续缩短数据集长度到小于8521+2857时，训练同样报错__len__() should return >= 0，请问这是因为模型已经规定了数据集的最短长度了吗？有没有哪些参数可以修改改变这一现状呢？

**Comment by zhouhaoyi** [comment]
你可以修改def __len__(self)这个函数，或者调整ETT数据集里面的size参数。

**Comment by kuraoumu** [comment]
> 你可以修改def **len**(self)这个函数，或者调整ETT数据集里面的size参数。

请问应该在哪里修改呢？我没有找到这个函数的位置或是size参数……

**Comment by wjmbalala** [comment]
请问解决了吗？能解释一下为什么长度固定吗？

**Comment by rintoo** [comment]
我也遇到这个问题，数据集过短导致的，seq_len和pred_len有限制，你的数据集大小应该符合下面情况：
custom模式下
[train, test, vail] ->[data70%, test20%, vail 剩下的 ]
border1s=[0, train-seq_len, data-test-seq_len]
border2s=[train, train+vail, data]
最终在len输出时候还要满足：
三划分之一的长度 - seq_len - pred_len +1 >0

所以你应该在main_informer里修改这三个参数的大小
`parser.add_argument('--seq_len', type=int, default=24, help='input sequence length of Informer encoder')
parser.add_argument('--label_len', type=int, default=16, help='start token length of Informer decoder')
parser.add_argument('--pred_len', type=int, default=24, help='prediction sequence length')`

**Comment by MountVoom** [comment]
也可以考虑修改DatasetCustom部分的代码
