### ISSUE TITLE
大佬您好，如何修改informer的模型用于单变量预测呢

### ISSUE THREAD

**Issue by wyz123341** [zhouhaoyi/Informer2020#293]
项目的数据集由两列组成 第一列是日期 第二列是值

**Comment by 943fansi** [comment]
> 项目的数据集由两列组成 第一列是日期 第二列是值

Have you solved this problem ?

**Comment by wyz123341** [comment]
将main_informer.py中的[7,7,7]改成[1，1,1]即可




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月26日(星期六) 中午12:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhouhaoyi/Informer2020] 大佬您好，如何修改informer的模型用于单变量预测呢 (Issue #293)





  
项目的数据集由两列组成 第一列是日期 第二列是值
  
Have you solved this problem ?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wuyimeng888** [comment]
do predict 会报错啊

**Comment by YLscnu** [comment]
> do predict 会报错啊

可以的，我这边就可以run起来

**Comment by 852597930** [comment]
> 将main_informer.py中的[7,7,7]改成[1，1,1]即可
> […](#)

您好，您的单变量预测，args.target用的是S是吗？

**Comment by YLscnu** [comment]
s是单预测单，ms是多预测单，m是多预测多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月18日(周三) 上午10:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 大佬您好，如何修改informer的模型用于单变量预测呢 (Issue #293)




  
将main_informer.py中的[7,7,7]改成[1，1,1]即可
 …
  
您好，您的单变量预测，args.target用的是S是吗？

**Comment by 943fansi** [comment]
> s是单预测单，ms是多预测单，m是多预测多
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月18日(周三) 上午10:19 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zhouhaoyi/Informer2020] 大佬您好，如何修改informer的模型用于单变量预测呢 (Issue #293) 将main_informer.py中的[7,7,7]改成[1，1,1]即可 … 您好，您的单变量预测，args.target用的是S是吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

多预测单是什么情况？输入输出维度不是一样的吗

**Comment by 943fansi** [comment]
@YLscnu 好的，非常感谢您的解答。
