### ISSUE TITLE
请问论文中label_len是如何对应seq_len和label_len的？

### ISSUE THREAD

**Issue by somethingforheheda** [zhouhaoyi/Informer2020#295]
seq_len label_len pred_len有3个参数 当论文实验结果对比的表格中 第二列 ETTh1 预测长度（应该是预测长度吧） 从24，48...到720 那么它此时对应的输入长度和token长度是多少呢（也就是seq_len，label_len）？ 可以把你们实验表格中的这3个参数一一对应发出来可以吗？ 感谢！比如这个代码原本3个参数分别是 96，48，24  那么当24变成48时，前面2个参数是多少呢？ 可以的话，把5个数据集得到mse mae结果的那个表当时对应的这3个参数都罗列出来  可以吗！！  感谢！！！！

**Comment by zttyyds** [comment]
请问您解决了嘛，我也想知道这个问题

**Comment by somethingforheheda** [comment]
没解决 这只有他们做实验的才知道了

**Comment by Zero-coder** [comment]
How could you close this without answering it?Could you please respond a little bit?Please~~~
