### ISSUE TITLE
Train, Val, Test dataset leakage

### ISSUE THREAD

**Issue by Big-Tree** [zhouhaoyi/Informer2020#297]
Hi, thanks for making your code public!  It's great for the forecasting community and research.

I am unsure about how you create your train, val and test splits.  The splits seem to be overlapping with a length of `self.seq_len`, see the code snippets below.

https://github.com/zhouhaoyi/Informer2020/blob/90e080593e9c345f5f9676359bb3d1618e9aa735/data/data_loader.py#L236-L239
https://github.com/zhouhaoyi/Informer2020/blob/90e080593e9c345f5f9676359bb3d1618e9aa735/data/data_loader.py#L258

If `self.seq_len` is longer than `self.pred_len` then sequences that the model is trained on will be present in validation split.  Data used for validation would also be present in the test split.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest. 

(1) I think this dataset splitting is right. You can understand this in the following two views.
- From the deep learning view, for a forecasting task, the key point is to not leak future information. The overlapping only happens on the encoder input. Thus, although the train, validation and test sets have the overlap with length `self.seq_len`, they will not affect the model learning and evaluation.
- From the application view, say you only have `num_train+num_vali` time points. If you want to evaluate the model performance in the future `num_test` time points, you will have to refer to the past `self.seq_len` in `num_train+num_vali` to obtain the first `self.pred_len` forecasting.
From the above two views, this splitting is reasonable.

(2) I don't understand the condition "If self.seq_len is longer than self.pred_len". Would you please explain it to me in more detail?
- Note that the dataset splitting is only about `self.seq_len`. The `self.pred_len` does not appear.
- In line 285 of `data_loader.py`, the dataset length is set to `len(self.data_x) - self.seq_len - self.pred_len + 1`. Thus, I do not find any unreasonable design.

**Comment by zhouhaoyi** [comment]
Some previous issue has discussed this problem. We may consider reproducing this part to avoid `undesired leakage`. Our scripts will not cause this problem.
