### ISSUE TITLE
关于实际洪水中长期径流预报

### ISSUE THREAD

**Issue by zhang-tuantuan** [zhouhaoyi/Informer2020#301]
老师您好，我有一个应用问题，比如我有10000条日洪水流量数据，要预测未来30天的流量，我的编码器输入长度是30，解码器的输入长度是15，是不是意味着我可以通过informer这个模型不断抽取长度为30条的数据，然后可以对未来15（30-15=15）天的流量进行预测呢？如果要未来预测30天的流量，是不是编码器和解码器的差要大于等于30，我的理解对吗?

**Comment by fankfurtlong** [comment]
你好，想请问一下自定义数据集里面date那一栏如果不是2016/07/01 00:00:00这种时间戳格式，而就是普通数字比如1-10000，代码怎么改呢？

**Comment by zhang-tuantuan** [comment]
这个我没有做过，我只是举了一个例子。

**Comment by wjmbalala** [comment]
请问你解决了吗？不用时间戳格式可以吗？

**Comment by zhouhaoyi** [comment]
> 

这个预测未来多少天是解码器的填0值决定的。
