### ISSUE TITLE
How was the ARIMA model evaluated?

### ISSUE THREAD

**Issue by zhangzw16** [zhouhaoyi/Informer2020#302]
Hello, I want to know how the baseline experiment of ARIMA is designed in the univariate experimental part?

Especially in test evaluation, how do you use ARIMA to produce, say, L length output? Is it done in an autoregressive way, or use ARIMA to output L variables at one time? And do you re-fit the ARIMA model for every test batch (or step)?

**Comment by cookieminions** [comment]
> Hello, I want to know how the baseline experiment of ARIMA is designed in the univariate experimental part?
> 
> Especially in test evaluation, how do you use ARIMA to produce, say, L length output? Is it done in an autoregressive way, or use ARIMA to output L variables at one time? And do you re-fit the ARIMA model for every test batch (or step)?

Hi, we fix the input length of model, and refit the ARIMA model to get prediction with output length for every test step.

**Comment by c-lyu** [comment]
> > Hello, I want to know how the baseline experiment of ARIMA is designed in the univariate experimental part?
> > Especially in test evaluation, how do you use ARIMA to produce, say, L length output? Is it done in an autoregressive way, or use ARIMA to output L variables at one time? And do you re-fit the ARIMA model for every test batch (or step)?
> 
> Hi, we fix the input length of model, and refit the ARIMA model to get prediction with output length for every test step.

Could you also provide some details on the parameter settings of the ARIMA model?

**Comment by Dont-Care-Didnt-Ask** [comment]
Hi!
I am also interested about parameter settings of ARIMA model.

**Comment by thanasisT** [comment]
Hello, 
Anyone has any inside of the parameters used for each dataset(at least ETTh1) for the ARIMA model? After my analysis of the dataset, the parameters i chose gave a mean mse of 3.03 which is way of the one in their tables
