### ISSUE TITLE
关于多序列预测部分多序列疑问

### ISSUE THREAD

**Issue by Tangxian17** [zhouhaoyi/Informer2020#303]
您好，非常感谢您们团队的优秀成果，通过阅读文章和浏览github上的提问，我发现“features=M”表示预测全部序列（特征），如果我上述理解正确，那么请问我的target feature是多列（比如数据总序列是10列，我的target feature是后三列），需要改进哪部分程序？或者“features=M”就可以满足上述要求呢？再次感谢您百忙之中回答我的问题。

**Comment by zhouhaoyi** [comment]
可以features=M，您取最后3列的结果就行。

**Comment by MountVoom** [comment]
您可以参考一下dataload.py，是用之前一段时间的数据(seq_len)预测接下来一段时间的数据(pred_len)。以ETTh数据集的实验为例，就是用seq_len*7的数据去预测pred_len*7的数据。

**Comment by 1348598339** [comment]
您好，请问您的第二个问题解决了吗

**Comment by MountVoom** [comment]
是输入一段时间序列然后预测接下来的一段时间序列，这段序列可以是单变量的(S)也可以是多变量的(M)。
模型是需要输入的，您可以参考一下dataloader相关的代码，以ETTh1数据集为例，训练和测试时使用Dataset_ETT_hour，预测时使用Dataset_Pred，预测的时候会选取数据集的最后一段作为输入对未来进行预测。

**Comment by KevinGuang1** [comment]
我想问下如果是“m”的多变量预测，label_len设置多少是不是就无所谓了？
