### ISSUE TITLE
关于在ECL数据集上实验复现的问题

### ISSUE THREAD

**Issue by Armilius** [zhouhaoyi/Informer2020#307]
您好！想请教一下有关在ECL数据集上复现的问题。ECL中包含370个用户的用电数据集，每隔15min采集一次数据。具体问题如下：
1.代码中的数据输入维度是321，target是MT_320，而原始数据是370维，请问是去掉了那些维度呢？
2.您论文中提到将原数据集转化为每一个小时采样的数据，所以是将四个相邻时间点的数据直接相加吗？
3.我取了ECL数据集中前321维进行训练，用您的代码和代码中原定的超参数进行训练，结果显示损失函数为nan，模型崩溃。请问是什么原因呢？
如能得以解答上述问题，万分感谢！！！

**Comment by zhouhaoyi** [comment]
1. 可以对比我们处理好的dataset。
2. 这个是直接取的。你可以按自己方便方式处理。
3. 应该是你的数据处理问题。同1。
