### ISSUE TITLE
args.data in Colab Example

### ISSUE THREAD

**Issue by HeroadZ** [zhouhaoyi/Informer2020#31]
Thank you for the excellent work! and sorry to bother you again. 😃 
Since the Colab Example is used for custom data, why should we input the data-name "ETTh1"? 
And I found the code `d_inp = 4 if data=='ETTh' else 5` in `models/embed.py`. Does it mean `ETTh` for (Y, M, W, D) while `ETTm` needs additional Minute? But this is unfriendly for the custom data, at least a little bit confusing.
Also, I found you add the `freq` to set the dimensionality of the timestamp, isn't it enough to get the time features? 

What I want to say is that I don't understand why parameter `data` should be sent into the model and DataEmbed Class.
Data is independent of model in my opinion.

**Comment by cookieminions** [comment]
Thank you very much for your careful checking.
It was a problem with our code logic, indeed we just need `freq` to define the time feature embedding. Now we update a new version of the code and replace `data` with `freq`. It will be more friendly to custom data and the logic of the code is more reasonable.

**Comment by HeroadZ** [comment]
Sorry, I tried a daily dataset, and there exists something incomplete.
In the `models/embed.py` line 89, `freq_map = {'h':4, 't':5}`, there is no support for daily or other options. But Dataset_Custom actually supports different date types.

**Comment by HeroadZ** [comment]
Also, in the exp/exp_informer.py line 74, the `Dataset_Custom` Class needs the parameter `target`, otherwise, line 218 in `data/data_loader.py` will raise an error `ValueError: list.remove(x): x not in list`

**Comment by cookieminions** [comment]
Thank you very much for your careful checking again! It helped our work a lot, and we have fix the errors in the new commit.

**Comment by Hezhexi2002** [comment]
> Also, in the `exp/exp_informer.py` line 74, please add `target=args.target`. otherwise, line 218 in `data/data_loader.py` will raise an error `ValueError: list.remove(x): x not in list` because the target will always be "OT".

@cookieminions Hi,sorry to bother you,I still meet this error when I train on my custom dataset as below:
![image](https://user-images.githubusercontent.com/53631206/183400329-c797285d-bdfc-4c28-b1d9-91b7bc61a858.png)
I clone the latest repo,so did you correct the problem in the code or I miss something important?

**Comment by KerwinFuyihang** [comment]
@Hezhexi2002 Hi there, just wonder if you fix this issue? Can you share how you figure it out?
