### ISSUE TITLE
反归一化之后，预测值会出现往上跑，漂移的现象

### ISSUE THREAD

**Issue by wjmbalala** [zhouhaoyi/Informer2020#310]
![1](https://user-images.githubusercontent.com/61644613/162354312-c143d9df-102c-414e-aa69-fd4c60cfd292.jpg)
作者大神你好呀，我用了informer，最后反归一化后进行可视化发现预测值会出现漂移的现象，如下图，不知道是什么原因呢？希望大神能够解答，谢谢谢谢

**Comment by zhouhaoyi** [comment]
可以提供一些sample数据和相关的code吗？可以尝试定位一下可能的问题。

**Comment by wjmbalala** [comment]
嗯嗯可以的，大佬你好，我把代码放在这里https://github.com/wjmbalala/wjm_test，我的数据集是data/ETT/xixia_ms.csv，如果找到原因大神能否及时告知我呢，感谢，我的邮箱是1621099083@qq.com

**Comment by MountVoom** [comment]
可以提供一下运行时使用的命令吗？

**Comment by LCZ2815** [comment]
> 嗯嗯可以的，大佬你好，我把代码放在这里[https://github.com/wjmbalala/wjm_test，我的数据集是data/ETT/xixia_ms.csv，如果找到原因大神能否及时告知我呢，感谢，我的邮箱是1621099083@qq.com](https://github.com/wjmbalala/wjm_test%EF%BC%8C%E6%88%91%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E6%98%AFdata/ETT/xixia_ms.csv%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%89%BE%E5%88%B0%E5%8E%9F%E5%9B%A0%E5%A4%A7%E7%A5%9E%E8%83%BD%E5%90%A6%E5%8F%8A%E6%97%B6%E5%91%8A%E7%9F%A5%E6%88%91%E5%91%A2%EF%BC%8C%E6%84%9F%E8%B0%A2%EF%BC%8C%E6%88%91%E7%9A%84%E9%82%AE%E7%AE%B1%E6%98%AF1621099083@qq.com)
请问您的漂移问题解决了么？是什么原因呢？

**Comment by jwee-star** [comment]
我在预测自己数据的时候，也遇到了同样的问题，感觉曲线整体上移一些，效果会更好，但就是不知道这个移动的距离和什么有关。
![1](https://user-images.githubusercontent.com/57666493/185831023-b09003e6-9e55-4262-a9b2-d3247c79ad51.png)

**Comment by MountVoom** [comment]
您好，预测值漂移和是否反归一化没有关系，反归一化前后的相对大小、趋势都是不变的，可能需要对参数进行一些调整。

根据您的代码我没有跑出来您的结果，如果方便的话可以给一个可复现的ipynb？

您的数据有较为明显的周期性，我自己进行实验得到的结果是这样的：
![res3](https://user-images.githubusercontent.com/33650160/188048872-e90159d1-3801-4787-b083-ceac87fe653f.png)

简略参数是这样的：informer_ETTh1_ftM_sl580_ll290_pl580_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_exp_0
