### ISSUE TITLE
训练集的真实值预测值对比效果图

### ISSUE THREAD

**Issue by Layfeng** [zhouhaoyi/Informer2020#312]
您好，请问我们这个程序代码里面可以实现训练集中真实值和预测值的效果对比图吗？这样看一下有没有意义？对我自定义的数据集来说看模型的好坏

**Comment by zhouhaoyi** [comment]
在主页里面的Colab example里面有相关对比的示例代码。

**Comment by Layfeng** [comment]
还有 一个问题 作者您这个代码是一次预测24个数据吗？那么是不是就相当于每个数据都被预测了24次？我理解的对吗？如果是这样？为什么呢

**Comment by zhouhaoyi** [comment]
可以参考论文中decoder的设计，是一步forward实现数据预测。

**Comment by Layfeng** [comment]
一步预测24个 那是不是就相当于每个数据都被预测了24次？
![image](https://user-images.githubusercontent.com/98027497/163177334-87e809b3-afb7-4740-9431-c27b0b18f07b.png)

**Comment by MountVoom** [comment]
以pred_len=24为例，是一次预测24个数据。训练和测试主要是建立和验证输入和输出之间的联系，判断我们根据输入对未来这24个点预测的能力好坏程度，最终预测的时候只会对未来预测一次。
