### ISSUE TITLE
为什么这里构造item时，x和y数据有交叉是为什么

### ISSUE THREAD

**Issue by miaolynn** [zhouhaoyi/Informer2020#315]
def __getitem__(self, index):
        s_begin = index
        s_end = s_begin + self.seq_len
        r_begin = s_end - self.label_len 
        r_end = r_begin + self.label_len + self.pred_len

        seq_x = self.data_x[s_begin:s_end]
        if self.inverse:
            seq_y = np.concatenate([self.data_x[r_begin:r_begin+self.label_len], self.data_y[r_begin+self.label_len:r_end]], 0)
        else:
            seq_y = self.data_y[r_begin:r_end]
        seq_x_mark = self.data_stamp[s_begin:s_end]
        seq_y_mark = self.data_stamp[r_begin:r_end]

        return seq_x, seq_y, seq_x_mark, seq_y_mark

小白一个，不懂就问，希望方便的时候回复下

**Comment by Zero-coder** [comment]
你怎么理解的呢，请回答下

**Comment by JayGrieve** [comment]
Am also curious as to why there is an overlap. Any insight would be much appreciated!
