### ISSUE TITLE
about my custom dataset

### ISSUE THREAD

**Issue by chostorjax** [zhouhaoyi/Informer2020#317]
Thank you for making such a great contribution to the LSTF！I have some questions during using your model and need your help

(1) :  I use the setting for my data（Wind power generation power）:

  python -u main_informer.py --model informer --data ETTh1 --features S --seq_len 720 --label_len 336 --pred_len 168 --e_layers 2 --d_layers 1 --attn prob --des 'Exp' --itr 5

and my pred is bad,can you tell me Is my hyperparametres were wrong or my dataset has some issue?
![Figure_1](https://user-images.githubusercontent.com/102529524/163713883-7af1518c-24ce-4dc4-b0b3-989c131110eb.png)

（2）：I want to know that what does the --freq refer to? If --freq=h,which means dataloader  extracts data on an hourly basis and puts it into the encoder?And freq=t,which means dataloader  extracts data on an minute basis and puts it into the encoder?

**Comment by zhouhaoyi** [comment]
(1) For problem 1, we have corrected an issue about this, you can give another trail.
(2) The freq indicates how we treat the individual inputs, especially for the time lag.
