### ISSUE TITLE
关于train_epochs的问题

### ISSUE THREAD

**Issue by AirZWH** [zhouhaoyi/Informer2020#318]
作者您好，我在训练自己的数据集时，inverse后发现预测值与真实值曲线相差较远，于是我想着增加训练的轮数，在命令中添加参数后发现实际训练轮数并未增加，请问是我哪里弄错了吗谢谢。

**Comment by AirZWH** [comment]
您好，
python -u main_informer.py --model informer --data Stock  --attn prob --freq d --root_path ./data/stock --data_path 603659.SH.csv --pred_len 50 --train_epochs 50 --inverse

**Comment by fdcqqqq** [comment]
估计早停机制的问题
