### ISSUE TITLE
Questions about whether different transformer data are distinguished during training?

### ISSUE THREAD

**Issue by xiaoyangyang2** [zhouhaoyi/Informer2020#322]
Hello, From the code, is it possible that the data from the 39 Electricity Transformers were not differentiated during the training, but put together for the model training?

**Comment by zhouhaoyi** [comment]
What do you mean by 39 Electricity Transformers?

**Comment by xiaoyangyang2** [comment]
Thank you for your reply. The specific questions are:
1. In the experiment, there are many data generated by different machines at different sites. When training the model, do you train a model for each machine?
2. If not, is the data collected from all different sites used to train the same one  model?



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月10日 21:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zhouhaoyi/Informer2020] Questions about whether different transformer data are distinguished during training? (Issue #322) |

What do you mean by 39 Electricity Transformers?

**Comment by MountVoom** [comment]
The way I understand it is to train a model for each machine.
