### ISSUE TITLE
本科小白求大佬指点：如何绘制出预测的结果？

### ISSUE THREAD

**Issue by DomineeringDragon** [zhouhaoyi/Informer2020#323]
在下在论文里看到预测结果图十分漂亮，但是不知道如何绘制出来，能指点一下吗？谢谢！

**Comment by zhouhaoyi** [comment]
在colab里面有示例的example code。

**Comment by yimuu** [comment]
> 在colab里面有示例的example code。
为什么我没有看到

**Comment by MountVoom** [comment]
colab里的Visualization部分有一些将结果可视化的code

**Comment by zhanmen1** [comment]
import os
import matplotlib.pyplot as plt

setting = 'informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_exp_0'
exp = Exp(args)
exp.predict(setting, True)
prediction = np.load('./results/'+setting+'/real_prediction.npy')
plt.figure()
plt.plot(prediction[0,:,-1], label='Prediction')
plt.legend()
plt.show()
您好我想用上面代码做预测结果可视化但是一直报错求怎末解决

**Comment by MountVoom** [comment]
> import os import matplotlib.pyplot as plt
> 
> setting = 'informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_exp_0' exp = Exp(args) exp.predict(setting, True) prediction = np.load('./results/'+setting+'/real_prediction.npy') plt.figure() plt.plot(prediction[0,:,-1], label='Prediction') plt.legend() plt.show() 您好我想用上面代码做预测结果可视化但是一直报错求怎末解决

请问报的什么错，能截个图或者复制一下吗

**Comment by zhanmen1** [comment]
> > import os import matplotlib.pyplot as plt
> > setting = 'informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_exp_0' exp = Exp(args) exp.predict(setting, True) prediction = np.load('./results/'+setting+'/real_prediction.npy') plt.figure() plt.plot(prediction[0,:,-1], label='Prediction') plt.legend() plt.show() 您好我想用上面代码做预测结果可视化但是一直报错求怎末解决
> 
> 

> > import os import matplotlib.pyplot as plt
> > setting = 'informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_exp_0' exp = Exp(args) exp.predict(setting, True) prediction = np.load('./results/'+setting+'/real_prediction.npy') plt.figure() plt.plot(prediction[0,:,-1], label='Prediction') plt.legend() plt.show() 您好我想用上面代码做预测结果可视化但是一直报错求怎末解决
> 
> 请问报的什么错，能截个图或者复制一下吗

已经解决了，但是我想知道的是informer是否并不适用于水文径流预测这类不稳定数据，我的数据还进行了插补，数据本身的季节性趋势性和缺失是否会极大影响结果。我的预测结果峰值波动处拟合的非常不好，如下
![删除插值96-48-24验证](https://user-images.githubusercontent.com/115549169/228185246-18263308-42a8-457d-94fe-40d28b94499e.png)

**Comment by FrankZhao1999** [comment]
您好，您这个预测的图像，时间周期这么长，是修改pred_len吗？

**Comment by zhanmen1** [comment]
我是调用了包括模拟值在内的数据与真实值绘制的拟合曲线

**Comment by FrankZhao1999** [comment]
不好意思，还是不太懂具体是怎么操作的，是在test的预测过程中把ground_truth和pred都记录下来吗


> 我是调用了包括模拟值在内的数据与真实值绘制的拟合曲线

**Comment by nixcty** [comment]
> 我调用了包括模拟值表达式的数据与真实值相似的轮廓曲线
您好，可以详细讲解一下是如何操作的吗？
