### ISSUE TITLE
作者您好，想咨询一下，我使用自己的数据集效果很差，这该如何解决哩

### ISSUE THREAD

**Issue by taogege68** [zhouhaoyi/Informer2020#327]
![~({HBR {LPV 8UQPHD21P6](https://user-images.githubusercontent.com/56571787/168721898-f96e5f71-37df-43dc-80ca-420831c5f936.png)
![QKG9S1(FA@OSYX{F5S 5EDL](https://user-images.githubusercontent.com/56571787/168721905-0e05018e-8bb2-41d5-aacf-748fe6d95339.png)

[使用方法是M，多步多变量预测，预测最后一列数据o，可为什么训练出来效果很差？]
[con_total.csv](https://github.com/zhouhaoyi/Informer2020/files/8704847/con_total.csv)

**Comment by zhouhaoyi** [comment]
这个可以先尝试再调整一下参数，我们会check一下你提供的数据。

**Comment by LCZ2815** [comment]
> ![~({HBR {LPV 8UQPHD21P6](https://user-images.githubusercontent.com/56571787/168721898-f96e5f71-37df-43dc-80ca-420831c5f936.png) ![QKG9S1(FA@OSYX{F5S 5EDL](https://user-images.githubusercontent.com/56571787/168721905-0e05018e-8bb2-41d5-aacf-748fe6d95339.png)
> 
> [使用方法是M，多步多变量预测，预测最后一列数据o，可为什么训练出来效果很差？] [con_total.csv](https://github.com/zhouhaoyi/Informer2020/files/8704847/con_total.csv)

请问您的结果调好了么？主要是调整哪些参数呢？

**Comment by MountVoom** [comment]
您好，我是用默认参数进行实验，使用的data_loader是Dataset_Custom，得到的结果大概是这个样子
![res2](https://user-images.githubusercontent.com/33650160/188047189-bc82a70e-769b-4bdd-8864-8a4d2eba26ec.png)

**Comment by TJiaR** [comment]
您好，您的问题成功解决了嘛，我也是多步多变量预测最后一列数据，在传入自己的数据时报错，方便加q请教一下嘛，我的联系方式是1432187256。万分感激！

**Comment by taogege68** [comment]
> 您好，您的问题成功解决了嘛，我也是多步多变量预测最后一列数据，在传入自己的数据时报错，方便加q请教一下嘛，我的联系方式是1432187256。万分感激！

他这个代码跑可以跑通，但是效果始终没有论文里面的好。您报错可能是您数据传的路径不对，您仔细检查一下吧
