### ISSUE TITLE
quadratic computation

### ISSUE THREAD

**Issue by moze-zhang** [zhouhaoyi/Informer2020#330]
学长您好，我最近刚刚接触到将transformer用到长序列预测的研究，我有一个问题，就是通常我们认为一个算法能达到多项式的复杂度就已经很好了，何况还是二次。为什么在transformer中二次计算复杂度会成为它的瓶颈呢？您能帮忙解答一下，或者推荐一些论文来解释一下吗？感谢

**Comment by zhouhaoyi** [comment]
这个二次计算复杂度是针对计算attention来说的，计算一次self-attention的feature map，对于输入长度为L的数据，需要计算L*L次的query和key之间的dot-product。其实每一次dot-product，都是矩阵计算，这个也是有复杂度的，是O(L)。举这个例子，就是想说，整个复杂度其实更加复杂，只是我们关注里面二次这个，可能相对复杂度比较高的环节。
