### ISSUE TITLE
multivariate预测univariate的问题

### ISSUE THREAD

**Issue by chooron** [zhouhaoyi/Informer2020#332]
作者你好，首先非常感谢你对informer模型的工作。我目前需要通过multivariate时间序列来预测univariate时间序列，也即MS情况；但作者代码中是将multivariate时间序列最后一列作为预测目标，如exp_informer在209-210左右的内容。
` f_dim = -1 if self.args.features == 'MS' else 0`
`batch_y = batch_y[:, -self.args.pred_len:, f_dim:].to(self.device)`
而我需要解决的问题是，所需要预测的univariate时间序列并不能作为模型的输入，只能用于计算模型的损失函数，因此我比较困惑，在decoder模块应该输入什么数据？

**Comment by zhouhaoyi** [comment]
如果只是计算损失函数的话，也需要占位符作为placeholder输入到decoder里面（里面的PE来表明是未来的值）。

**Comment by chooron** [comment]
> 如果只是计算损失函数的话，也需要占位符作为placeholder输入到decoder里面（里面的PE来表明是未来的值）。

好的，谢谢您的指点！
