### ISSUE TITLE
关于num_train，num_vali和seq_len，pred_len的关系

### ISSUE THREAD

**Issue by ydd-coder** [zhouhaoyi/Informer2020#334]
data_loader中的
num_train = int(len(df_raw)*0.7)
num_test = int(len(df_raw)*0.2)
num_vali = len(df_raw) - num_train - num_test 三种数据，和seq_len，pred_len有什么关联。

**Comment by LadiesMan924** [comment]
> data_loader中的 num_train = int(len(df_raw)*0.7) num_test = int(len(df_raw)*0.2) num_vali = len(df_raw) - num_train - num_test 三种数据，和seq_len，pred_len有什么关联。

这之间没有什么关联。num_train，num_test, num_vali是对你的数据集进行划分，划分成训练集、测试集和验证集，也就是对原始数据的train_test_split。而seq_len是你在训练和预测时输入的序列长度，pred_len是你希望得到的预测结果的序列长度。

**Comment by helloworldzwz** [comment]
> 

您好，请教一下，我看作者提供的ETTh1数据集有1万个数据，使用github上提供的命令进行训练，得出的true_prediction预测序列24个，意思是对这么多数据做拟合，预测了接下来的24个时刻点数据吗。请问是需要这么大量的数据才能预测出这么短的序列吗

**Comment by SimyokH** [comment]
> 

同问，请问您解决了吗？

**Comment by SimyokH** [comment]
> > 
> 
> 您好，请教一下，我看作者提供的ETTh1数据集有1万个数据，使用github上提供的命令进行训练，得出的true_prediction预测序列24个，意思是对这么多数据做拟合，预测了接下来的24个时刻点数据吗。请问是需要这么大量的数据才能预测出这么短的序列吗

同问这个问题，请问您解决了吗？

**Comment by MountVoom** [comment]
模型其实是不断的通过训练建立输入和输出的关系，pred_len也可以不止设置成24，Informer提供的就有预测长度为720的实验结果。当然通常来说用于训练的数据肯定是多一点会更好。
