### ISSUE TITLE
Conv1d layer error

### ISSUE THREAD

**Issue by sabahatijaz** [zhouhaoyi/Informer2020#336]
Hey, I have looked into your code. Its really awesome. Highly, appreciate your efforts. I am trying to apply this model on my data set that is related to time series as well. I am using custom data set function to create data set and dataLoaer. But moving forward in _process_one_batch function it gives following error.

RuntimeError: Given groups=1, weight of size [512, 7, 3], expected input[32, 25, 98] to have 7 channels, but got 25 channels instead

**Comment by bieyaowo** [comment]
I have the same problem as you, I solved it by adjusting the parameters of enc_in and dec_in parameters, if your data input is 25 dimensions, you can try to set them to 25

**Comment by sabahatijaz** [comment]
Yeah! i have resolved it in same way. Thanks for your response. Could you please guide me how to tune it for custom data set, i have read research paper and tried to tune it in that way but still getting high error in forecast up to 60 days.

**Comment by bieyaowo** [comment]
Sorry, I'm using my own dataset and I'm trying to debug the code

**Comment by sabahatijaz** [comment]
ok. i am also using my dataset but stuck in parameter tuning. Thanks for the help!
