### ISSUE TITLE
Pred

### ISSUE THREAD

**Issue by vivva** [zhouhaoyi/Informer2020#344]
作者，您好，我想问一下：为什么pred只能得到进行数据缩放之后的结果呢，如果我想得到真实的预测结果，该怎么办呢？尝试将StandardScaler加入pred的代码，但是mean=0，std=1。

**Comment by vivva** [comment]
作者，您好，我想问一下：为什么pred只能得到进行数据缩放之后的结果呢，如果我想得到真实的预测结果，该怎么办呢？尝试将StandardScaler加入pred的代码，但是mean=0，std=1。

**Comment by zhouhaoyi** [comment]
因为对输入数据进行了正则化，可以使用reverse功能进行反正则化。

**Comment by MountVoom** [comment]
可以直接在命令加上--inverse
