### ISSUE TITLE
有关多变量预测单变量

### ISSUE THREAD

**Issue by bieyaowo** [zhouhaoyi/Informer2020#346]
作者您好，首先非常感谢您对时序数据预测所作的贡献，我有个问题，就是有关多变量预测单变量，既“MS”，有关“MS”，我没看到需要设置的超参数文件，只有“S”和“M”的，可否提供有关MS的超参数

**Comment by zhouhaoyi** [comment]
多变量预测单变量不在文章实验范围内，所以也没有标准的超参数。

**Comment by bieyaowo** [comment]
> 多变量预测单变量不在文章实验范围内，所以也没有标准的超参数。

非常感谢作者的回答，我我还有个问题，有关seq_len和lable_len，他们的设置是否有要求，比如我自己的数据是利用前三列预测第四列（最后一列），也就是多变量预测单变量，我的lable_len与seq_len应该是什么样的关系，感谢作者

**Comment by MountVoom** [comment]
他们的设置建议根据数据选择一些具有实际意义的数值，label_len不能超过seq_len。
