### ISSUE TITLE
有关论文Fig.9的问题

### ISSUE THREAD

**Issue by haoanaoah** [zhouhaoyi/Informer2020#347]
请问作者，对比论文中Fig.9给出的结果，在colab上给出的实验结果来看，效果不是特别理想的，那么论文中Fig.9对应的实验参数设置是什么呢？
![0a6f3c5205a59ae6f5b953b51f424c2](https://user-images.githubusercontent.com/32609632/176390858-252e7c1b-cd67-46a7-bea9-8061d7a0ce02.png)

**Comment by zhouhaoyi** [comment]
Fig.9 对应的就是scripts里面提供的实验参数。
