### ISSUE TITLE
Set freq to 15min

### ISSUE THREAD

**Issue by ricokoff** [zhouhaoyi/Informer2020#349]
Hi, 

I am trying to run the model with a custom dataset, which has a 15min timeframe. However, if I set --freq = '15min' or --freq = '15t', I get the following error: "KeyError: '15min'" (or "KeyError: '15t'". How can I set the frequency such that it can handle 15 min data?

**Comment by zhouhaoyi** [comment]
Could you please provide a sample of the dataset, it may help us locate the problem.

**Comment by ricokoff** [comment]
I am currently using this dataset [BTC_USD_BITSTAMP_15m.csv](https://github.com/zhouhaoyi/Informer2020/files/9188429/BTC_USD_BITSTAMP_15m.csv)

**Comment by zzzertion** [comment]
Hey folks, same issue.. I don't know how to use 15min as my freq...

> I am currently using this dataset [BTC_USD_BITSTAMP_15m.csv](https://github.com/zhouhaoyi/Informer2020/files/9188429/BTC_USD_BITSTAMP_15m.csv)

Hey folks, same issue.. I don't know how to use 15min as my freq...

**Comment by ricokoff** [comment]
@zhouhaoyi I was wondering if you located the problem already. If you need other data please let me know.

**Comment by ethanZh0515** [comment]
@ricokoff 
Set args.detail_freq = '15min' in line 90, main_informer.py.
And feed --freq t when run the model. Or you can set args.freq = 't' and leave the parameter --freq.

**Comment by MountVoom** [comment]
You can feed --freq 15t when run the model.
