### ISSUE TITLE
模型输出值的反归一化

### ISSUE THREAD

**Issue by WangZiNi** [zhouhaoyi/Informer2020#350]
请问要进行模型输出值的反归一化，直接调用对应的数据集的方法inverse_transform，输入参数data直接传入模型输出量吗，是否需要别的处理呢？

**Comment by LCZ2815** [comment]
> 请问要进行模型输出值的反归一化，直接调用对应的数据集的方法inverse_transform，输入参数data直接传入模型输出量吗，是否需要别的处理呢？

main_informer文件里有参数'--inverse'，调这个就可以了。程序里有调用反归一的功能，不用你自己调用函数，调参数就可以了。

**Comment by WangZiNi** [comment]
好的，谢谢啦

**Comment by Orange-Juicee** [comment]
> 

请问你是，--inverse里面设置成了true，但是训练后导出数据却是归一化后的，这种情况吗，怎么解决的呢

**Comment by Orange-Juicee** [comment]
> 

请问--inverse里面设置成了true，但是训练后导出数据却是归一化后的，这种情况怎么解决的呢

**Comment by liuweishuo** [comment]
> > 
> 
> 请问--inverse里面设置成了true，但是训练后导出数据却是归一化后的，这种情况怎么解决的呢

data_loader.py 中Dataset_pred类中的__getitem__方法中 seq_y的获取逻辑调换一下

**Comment by higherthanfly** [comment]
请问能否具体一点呢？就是seq_y的获取逻辑该怎么调换呢？

**Comment by higherthanfly** [comment]
> > > 
> > 
> > 
> > 请问--inverse里面设置成了true，但是训练后导出数据却是归一化后的，这种情况怎么解决的呢
> 
> data_loader.py 中Dataset_pred类中的__getitem__方法中 seq_y的获取逻辑调换一下

请问能否具体一点呢？就是seq_y的获取逻辑该怎么调换呢？

**Comment by MountVoom** [comment]
可以检查一下里面判断是否inverse相关的语句

**Comment by Seb5Vet** [comment]
我把inverse这个参数改成true之后损失函数巨大，有几千万，用false就0.几，很正常

**Comment by Seb5Vet** [comment]
> > 请问要进行模型输出值的反归一化，直接调用对应的数据集的方法inverse_transform，输入参数data直接传入模型输出量吗，是否需要别的处理呢？
> 
> main_informer文件里有参数'--inverse'，调这个就可以了。程序里有调用反归一的功能，不用你自己调用函数，调参数就可以了。

我把inverse这个参数改成true之后损失函数巨大，有几千万，用false就0.几，很正常

**Comment by Echollllll** [comment]
> > > 请问要进行模型输出值的反归一化，直接调用对应的数据集的方法inverse_transform，输入参数data直接传入模型输出量吗，是否需要别的处理呢？
> > 
> > 
> > main_informer文件里有参数'--inverse'，调这个就可以了。程序里有调用反归一的功能，不用你自己调用函数，调参数就可以了。
> 
> 我把inverse这个参数改成true之后损失函数巨大，有几千万，用false就0.几，很正常

请问解决了吗
