### ISSUE TITLE
兄弟你看到了吗？我也没找到> 在colab里面有示例的example code。

### ISSUE THREAD

**Issue by jin521-qing** [zhouhaoyi/Informer2020#352]
> 在colab里面有示例的example code。
为什么我没有看到

_Originally posted by @yimuu in https://github.com/zhouhaoyi/Informer2020/issues/323#issuecomment-1129890806_

**Comment by zhouhaoyi** [comment]
是需要找example code的哪个部分呢？

**Comment by Hezhexi2002** [comment]
![image](https://user-images.githubusercontent.com/53631206/183418720-e321a737-e2fd-43a8-a17a-60eb536f4290.png)
为什么colab的example一直加载打不开呢？

**Comment by MountVoom** [comment]
> ![image](https://user-images.githubusercontent.com/53631206/183418720-e321a737-e2fd-43a8-a17a-60eb536f4290.png) 为什么colab的example一直加载打不开呢？

可能需要一些科学上网

**Comment by MountVoom** [comment]
> > 在colab里面有示例的example code。
> > 为什么我没有看到
> 
> _Originally posted by @yimuu in [#323 (comment)](https://github.com/zhouhaoyi/Informer2020/issues/323#issuecomment-1129890806)_

colab里的Visualization部分有一些将结果可视化的code，您具体需要什么部分的代码呢

**Comment by Hezhexi2002** [comment]
> > ![image](https://user-images.githubusercontent.com/53631206/183418720-e321a737-e2fd-43a8-a17a-60eb536f4290.png) 为什么colab的example一直加载打不开呢？
> 
> 可能需要一些科学上网

额，我已经挂了代理了，我就是纳闷为什么挂了代理还打不开，不过现在不需要了，已经找到一份了
