### ISSUE TITLE
作者您好，请问输入的特征是不是全是历史实测数据，是不是没有天气预报数据？是只用历史实测值去预测未来值？decoder的这部分有作用吗？

### ISSUE THREAD

**Issue by BUQIdawang** [zhouhaoyi/Informer2020#355]
1、请问输入的特征是不是全是历史实测数据，没有天气预报数据？
2、只用历史实测值去预测未来值？
3、decoder的这部分输入有作用吗？
![Inkedinformer](https://user-images.githubusercontent.com/87692719/180598716-be82cb36-197b-4457-aaf2-d301e5a63c00.jpg)

**Comment by zhouhaoyi** [comment]
1.输入的均为历史值。
2.是的
3.decoder是一个启动子的作用，可以看最后一个ablation study实验

**Comment by BUQIdawang** [comment]
decoder输入的右半部分（画红框的部分）不就相当于是未来值了吗？

> 1.输入的均为历史值。 2.是的 3.decoder是一个启动子的作用，可以看最后一个ablation study实验

**Comment by zhouhaoyi** [comment]
这个请对照论文阅读，那个部分只是填充了0值和PE组成。预测结果是从0值推断出来的。

**Comment by BUQIdawang** [comment]
好的谢谢
