### ISSUE TITLE
流量预测误差大问题

### ISSUE THREAD

**Issue by lyn-11** [zhouhaoyi/Informer2020#356]
您好，我在使用informer进行网站日常流量预测，有几个问题想请教下，感谢~
1、白天预测效果比较好，晚上误差非常大，比真实流量高一倍
2、个别整点有尖峰预测不到，尝试对整点加特征，效果也不理想
3、训练数据10min粒度，过去一年的数据去掉个别月异常，大概4w条，这个时间有断点的问题搜了下之前的issue，请问有解决方案或参考示例吗？

**Comment by zhouhaoyi** [comment]
1. 这个可能和数据分布有一些关系，可以分白天和晚上进行自相关性的分析。
2. 尖峰值预测一直是时序预测的难点，大部分模型还是关注change point的预测。Informer算是一种对于尖峰值比较敏感的模型，需要特别好的效果，建议首先尝试特征工程和修改loss入手。
3. 如果只是训练数据的话，可以直接去掉，然后正常放入训练流程就可以。

**Comment by lyn-11** [comment]
3、使用无间断数据训练的结果要好很多，感觉晚上误差大的问题是这个导致的，不知道具体原因是？
另外还想问下label_len设置多少合理呢？与seq_len长度有关不？谢谢啦

**Comment by MountVoom** [comment]
label_len的设置不能超过seq_len，一般根据想要预测的长度pred_len来设置一些具有一定实际意义的数值。
