### ISSUE TITLE
修改WTH数据集预测Target为windspeed等变量

### ISSUE THREAD

**Issue by viodmain** [zhouhaoyi/Informer2020#358]
作者您好，我在使用WTH数据集复现代码时，尝试将Target从默认的WetBulbCelsius更改为WindSpeed，在单因素模式下MSE和MAE会上升到0.9左右，loss感觉也降不下来，但是预测Target为DryBulbCelsius也能取得较好的结果，因此向请教一下对于WTH数据集，我这样直接更改预测Target的做法是不是存在什么问题。非常感谢。

**Comment by zhouhaoyi** [comment]
WTH数据集不同的target，预测难度也略有差异。可以根据测试需要，自行选择。

**Comment by viodmain** [comment]
好的，非常感谢
