### ISSUE TITLE
单变量预测单变量问题

### ISSUE THREAD

**Issue by zzzertion** [zhouhaoyi/Informer2020#359]
嗨作者大大，感谢详细的example文档，我在学习过程中遇到了一些小问题想请教：

1.我想用单一变量来预测自己，比如用太阳辐射预测太阳辐射，那我应该直接用S来做还是说我自己添加一些我认为关键的Feature，比如time of a day, day of a week.这种时间变量是在S中能自己学习出来的呢还是说我自己添加后用MS会效果更好

2.还有一个就是别人问过的问题，在example中有说可以自定义15min或3h，但是我用15min, 15t, 15T均失败了，请问有什么好的办法么

谢谢！

**Comment by zhouhaoyi** [comment]
1.可以先用单变量预测进行添加尝试，但是目前开源的Informer，没有针对多变量进行特异性处理，依靠的是inner layer进行自动拟合。
2. 这个主要是涉及到添加的embedding的相关代码，可以自行添加不同的时间标签计算和embeding方法。

**Comment by Cyue0316** [comment]
2. 可能是时间列没有正确命名，一般需要命名为date

>
