### ISSUE TITLE
关于模型训练的问题

### ISSUE THREAD

**Issue by Qinbf** [zhouhaoyi/Informer2020#36]
你好，我在使用程序训练模型时遇到一个情况比较疑惑。虽然设置了训练6个epochs，不过基本上都是只训练了1个epochs，模型的val loss和test loss就无法继续降低了（最多训练2个epochs），最后训练的结果也不算特别好。    

我尝试了几个不同的数据集ETTh1，ETTm1和另外两个天气的数据集。参数使用的基本都是默认参数，程序基本上也没有太多改动。    

我感觉有可能是哪里我没有做对，希望可以得到一些优化建议，谢谢。

**Comment by cookieminions** [comment]
如果使用的是默认参数的话，那么预测结果是多变量预测结果，结果请参考图5，如pred_len=24，mae和mse在0.5左右
关于训练的epochs，当调小参数量或数据更复杂时，训练轮数将会增加，earlystop将会发挥作用

**Comment by Qinbf** [comment]
请问如果是MS预测，参数和训练上有什么特别的讲究吗

**Comment by cookieminions** [comment]
很抱歉，MS预测是我们前两天根据需求加上的形式，目前代码中的设置是encoder和decoder的输入都是多变量，只有decoder输出是单变量，并没有经过充分的实验。个人建议可以使用M进行多变量预测取输出的最后一维（即目标维），或者使用S进行单变量预测（设置embed为fixed）

**Comment by Qinbf** [comment]
我做的刚好就是MS预测，我试试你说的做法看，谢谢

**Comment by cookieminions** [comment]
不客气，之后我们会尽力完善MS预测

**Comment by Qinbf** [comment]
好的，期待
