### ISSUE TITLE
Issues With Prediction: Forward()

### ISSUE THREAD

**Issue by CoolShadows521** [zhouhaoyi/Informer2020#360]
Hello. 

I trained a model on predicting a certain target with several variables. I am trying to use that model to predict through using a different dataset, which has the same variables but lacks the target. For example, this would be like predicting OT with a csv with the date, HUFL,HULL,MUFL,MULL,LUFL,LULL variables for the ETTH1 dataset.

Therefore, I am first trying to initialize the model by doing:

`model = Informer(13, 13, 13, 96, 48, 24)`
assuming out_len is the same is pred_len. 

When I try to predict using:

`model(df)`

I receive the error: 

> forward() missing 3 required positional arguments: 'x_mark_enc', 'x_dec', and 'x_mark_dec'

I know that I have to use the dataframe to create the arguments 'x_enc', 'x_mark_enc', 'x_dec', and 'x_mark_dec'. However, I thought that there would be a way that the Informer would already be able to do this. 

May I have assistance in resolving this? How do I run inference with my model?

**Comment by zhouhaoyi** [comment]
The Transformer model requires positional embedding to locate the time-series sequences, which also applies to Informer. And we have provided an embedding example in the repo. We are planning to build a universal tool to handle this problem.
If you want to fix this problem now, I suggest referring to our datalaoder for more details.
