### ISSUE TITLE
关于informer对周期性波动股票时间序列预测的一些问题?

### ISSUE THREAD

**Issue by Hezhexi2002** [zhouhaoyi/Informer2020#361]
作者大佬你好，首先感谢你们杰出的工作并且开源，我是一名大二本科生，正在准备今年数学建模国赛，学校给我们发了几道练习题做，其实就是今年华中杯b题，2，3问回涉及到股票时间序列的分析，第1问我们首先是通过随机森林做了特征重要度分析，提取出来了与数字经济板块相关的一些指标，然后出去时间那列总共有10个变量，现在就是要求我们利用这个数据训练模型并预测，最开始我们尝试了多变量LSTM多步预测，数据是按每5分钟间隔排列的，总共6240行，其中前面5238行作为训练集，后面912行作为测试集来预测，是按照这篇文章的思路写的：https://zhuanlan.zhihu.com/p/191211602，但是最后我们在可视化预测结果后发现预测值在峰值处与实际值相差比较多如下图：
![$OO5%HW0GM{GVKH`@3430{9](https://user-images.githubusercontent.com/53631206/183396448-8eb283eb-f6e9-4e42-bdb6-ca765b86653e.png)
后来我尝试增加LSTM cell数量以及增大units数量，但提升都微乎其微，后来我在另一篇博客里看到了informer这个模型，对长序列预测似乎效果很不错，于是我现在想尝试用你们的repo训练试试，但是我不知道对于这种周期性波动的序列效果怎样，尤其是不知道怎样调节超参数，所以希望大佬能够给予一些指导

**Comment by zhouhaoyi** [comment]
股票的预测，其实和预测目标选择有比较强烈的关系。建议还是先进行时间平稳性、相关性的检验，然后做一些因素分析后，再根据波动程度，选择合理的模型。Informer主要是针对长周期的时间序列进行分析，我们也给出了文章涉及数据的参数调节样例。针对竞赛所涉及到的具体问题，建议先进行一些实验后，交流起来比较有针对性。

**Comment by bolinzhou6** [comment]
作者你好，想问您，我有一个自己的数据集想做多变量时间序列预测单变量，我是需要选取相关性大的序列构成多变量输入还是选取相关性小的序列，因为我用网上数据集作相关性分析的时候，发现其他序列与预测序列相关性都不大。

**Comment by MountVoom** [comment]
可以尝试选择相关性相对较大的部分序列进行尝试
