### ISSUE TITLE
关于论文中结果的问题

### ISSUE THREAD

**Issue by cybisolated** [zhouhaoyi/Informer2020#362]
作者好，感谢你们的工作和开源精神！
我想请问论文中的MSE和MAE指标结果是否都是根据归一化后的数据计算的呢？也就是说，MSE和MAE的计算是不是没有调用inverse_transform方法呢？期待解答！

**Comment by zhouhaoyi** [comment]
是的，MSE和MAE都是计算的归一化后的数据。
