### ISSUE TITLE
Getting predictions of similar values

### ISSUE THREAD

**Issue by WillZ00** [zhouhaoyi/Informer2020#363]
Hi authors,

Thank you for organizing this repo! I have built a model using the informer architecture on my custom time series dataset. However, I'm getting predictions of very similar values or even basically the same values across the entire forecast horizon. 

Have you encountered similar issues? Or was this merely due to the nature of the dataset/model?

Thank you for your time.

**Comment by zhouhaoyi** [comment]
Actually, we have received reports of similar issues on specific datasets. And we are investigating this problem, I hope you can watch this repo for updates.
