### ISSUE TITLE
预测总是超前一些怎么办？

### ISSUE THREAD

**Issue by SQY2021** [zhouhaoyi/Informer2020#367]
![1](https://user-images.githubusercontent.com/81226844/188105611-d3b2164b-9521-498f-a434-32c6832fb815.png)
![2](https://user-images.githubusercontent.com/81226844/188105654-c428ad8b-71af-478c-af1d-231f6287fdc6.png)
我的预测结果总是超前一些，怎么办？就是完全按照informer模型跑的，96-48-720的参数，用的是https://github.com/thuml/Autoformer里面的informer模型。

**Comment by MountVoom** [comment]
您可以尝试调整一下参数

**Comment by Kai744** [comment]
这是滞后了吧，我个人的理解是模型没收敛，上一时刻的真实值权重太大了，预测结果基本相当于上一时刻的真实值+一个很小的预测偏差。
