### ISSUE TITLE
如何获取paper中的补充材料？

### ISSUE THREAD

**Issue by GN222A222** [zhouhaoyi/Informer2020#368]
想要通过补充材料具体了解关于长尾分布以及随机选取L*log L个键值对就能够替代计算全部L*L键值对的理论补充

**Comment by zhouhaoyi** [comment]
近期工作比较忙，回复比较晚。
在arxiv上面有一些补充材料。关于这一块的理论分析，正在期刊评审中，我们会尽快release出来。
