### ISSUE TITLE
关于pred和truth结果

### ISSUE THREAD

**Issue by zs-3180104538** [zhouhaoyi/Informer2020#371]
大佬您好，我在自己电脑跑完后result里的pred.npy和truth.npy结果如下，请问为什么truth是一条直线啊
![image](https://user-images.githubusercontent.com/64792328/189943603-692fcdfa-9bee-42ec-8324-422b28c46ab8.png)

**Comment by randomcollegegirl** [comment]
我也遇到这个问题，请问您怎么解决了呢

**Comment by peiuu** [comment]
我也出现了相同的问题。能给我一个提示吗？不尽感激

**Comment by lycprimer** [comment]
请问解决了吗？我也碰到了相同的问题
