### ISSUE TITLE
间断的时间序列数据训练

### ISSUE THREAD

**Issue by wangchen-it** [zhouhaoyi/Informer2020#372]
作者你好 我的数据是间断的，比如今天1~3点有连续的时间序列，4~7点有一组连续序列，且每天的数据区间是随机的。这样的数据用informer训练时怎么保证时间窗口的划分不会跨区间（窗口内的时间连续）呢？谢谢

**Comment by zhouhaoyi** [comment]
如果是这样的数据，可以重新改写一下PE的附加规则，进行动态的时间窗口划分。建议预测的时候还是连续的PE。
