### ISSUE TITLE
进行Predict时候 每次结果不一样

### ISSUE THREAD

**Issue by team11-zhangkun** [zhouhaoyi/Informer2020#378]
有没有人遇到过在用训练好的模型，进行predict的时候，同样的输入数据，每次运行输出的结果不一样的情况。求大佬们解答。

**Comment by zhouhaoyi** [comment]
这个和prob的seed有关，如果固定了全部的seed，可以保证结果。

**Comment by team11-zhangkun** [comment]
感谢大佬的回复，respect。我还想请教下加这个随机seed的是为随机生成K防止过拟合么。这样的话论文里面的结果是训练5次然后取平均么。

**Comment by zhouhaoyi** [comment]
这个是Prob的定义带来的随机性，足够多的heads下这个影响比较弱。不过也许可以有更好的分布来做选择。论文里面的结果是多次训练后的平均。不过现在这个github的步进版本，可能和论文里面的原始实现已经有一些不同了。

**Comment by team11-zhangkun** [comment]
> 这个是Prob的定义带来的随机性，足够多的heads下这个影响比较弱。不过也许可以有更好的分布来做选择。论文里面的结果是多次训练后的平均。不过现在这个github的步进版本，可能和论文里面的原始实现已经有一些不同了。

明白了，谢谢大佬的答疑。感谢大佬做出的模型！yyds
