### ISSUE TITLE
只预测下一时刻，是不是把pred_len设为1即可？

### ISSUE THREAD

**Issue by zhanggongkai123** [zhouhaoyi/Informer2020#383]
如题

**Comment by 1915982017** [comment]
我认为应该是这样的

**Comment by MountVoom** [comment]
> > 我认为应该是这样的
> 
> 那回归问题该怎么设置呢？也就是一个样本对应一个同时刻的输出那种，多特征输入单特征输出

是知道某一个时间的其他信息想要对target信息进行预测吗？

**Comment by LY-must-win** [comment]
> > > 我认为应该是这样的
> > 
> > 
> > 那回归问题该怎么设置呢？也就是一个样本对应一个同时刻的输出那种，多特征输入单特征输出
> 
> 是知道某一个时间的其他信息想要对target信息进行预测吗？

对，输入和输出是同时刻的映射关系，不是上下时刻的映射关系

**Comment by MountVoom** [comment]
我觉得可以考虑修改一下_process_one_batch中对于decoder_input(dec_inp)的操作，生成式解码器是用0填充，您也可以改成用已知的数据去填充。

**Comment by LY-must-win** [comment]
> > > 我认为应该是这样的
> > 
> > 
> > 那回归问题该怎么设置呢？也就是一个样本对应一个同时刻的输出那种，多特征输入单特征输出
> 
> 是知道某一个时间的其他信息想要对target信息进行预测吗？

作者本身的模型是时间序列预测模型吧，不是回归预测模型吧？

**Comment by MountVoom** [comment]
是的，是时序预测模型，您这个问题感觉可以考虑XGBoost之类的模型

**Comment by LY-must-win** [comment]
本模型不适合吗？



---原始邮件---
发件人: "Siyang ***@***.***&gt;
发送时间: 2023年3月28日(周二) 中午11:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 只预测下一时刻，是不是把pred_len设为1即可？ (Issue #383)




 
是的，是时序预测模型，您这个问题感觉可以考虑XGBoost之类的模型

**Comment by MountVoom** [comment]
我认为不太合适，Informer主要还是针对预测问题进行的设计

**Comment by LY-must-win** [comment]
autoformer是不是也如此了？



---原始邮件---
发件人: "Siyang ***@***.***&gt;
发送时间: 2023年3月28日(周二) 中午11:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 只预测下一时刻，是不是把pred_len设为1即可？ (Issue #383)




 
我认为不太合适，Informer主要还是针对预测问题进行的设计

**Comment by MountVoom** [comment]
是的
