### ISSUE TITLE
Informer模型中mask attention的mask矩阵为什么是NONE呢

### ISSUE THREAD

**Issue by chenshimao** [zhouhaoyi/Informer2020#384]
Informer模型中mask attention的mask矩阵为什么是NONE呢？在NLP中，mask矩阵不是一个下三角矩阵嘛

**Comment by FangBo-0219** [comment]
我看源码也注意到这个问题，decoder中的self-attention中的mask_flag始终是false，即不会使用mask策略。不懂。。。。。

**Comment by chenshimao** [comment]
您的邮件我已收到。

**Comment by MountVoom** [comment]
我认为mask只是在init的时候默认设置成了None，实际运行的时候会有参数传入，其实不是None
Decoder的self-attention的mask_flag设置的是True，可以参考models/model.py
`AttentionLayer(Attn(True, factor, attention_dropout=dropout, output_attention=False), 
                                d_model, n_heads, mix=mix)`

**Comment by chenshimao** [comment]
您的邮件我已收到。
