### ISSUE TITLE
Problems with TemporalEmbedding class in models.embed

### ISSUE THREAD

**Issue by pikapi12321** [zhouhaoyi/Informer2020#385]
`class TemporalEmbedding(nn.Module):
    def __init__(self, d_model, embed_type='fixed', freq='h'):
        super(TemporalEmbedding, self).__init__()

        minute_size = 4; hour_size = 24
        weekday_size = 7; day_size = 32; month_size = 13

        Embed = FixedEmbedding if embed_type=='fixed' else nn.Embedding
        if freq=='t':
            self.minute_embed = Embed(minute_size, d_model)
        self.hour_embed = Embed(hour_size, d_model)
        self.weekday_embed = Embed(weekday_size, d_model)
        self.day_embed = Embed(day_size, d_model)
        self.month_embed = Embed(month_size, d_model)`

1. I think the minute size is supposed to be 60 instead of 4. 
2. Frequency of seconds is not supported.

**Comment by zhouhaoyi** [comment]
the minute size is set to 4 due to the ETT dataset.
You could add the seconds as you like, bro.
