### ISSUE TITLE
如何换成自己的数据集？

### ISSUE THREAD

**Issue by Fandier** [zhouhaoyi/Informer2020#386]
作者以及各位伙伴大家好，我最近在关注informer这个网络内容。有几个问题想求助一下大家。我想把相关时间序列的数据集换成更加细致的数据（时间上以秒、甚至更小为单位，其实就是很小的一段时程），我想知道这种情况下相应的时间序列是不是失去了以年、月、日为排布的意义？如果是这样的话，我如何换成自己的数据集，由于初学Python，可能相应的内容不是很熟悉，希望有熟知的伙伴可以互相讨论，帮忙指导一下，我的v：17660687963。谢谢各位

**Comment by gq165118** [comment]
建议还是需要将整个代码debug一边，重点了解数据是什么处理的，模型是怎么实现的。

**Comment by frankwangtoronto** [comment]
同问，有什么进展吗？加你v了 要不要一起研究一下

**Comment by frankwangtoronto** [comment]
同问，有什么进展吗？加你v了 要不要一起研究一下

**Comment by MountVoom** [comment]
如果时间间隔非常小的的话，比如所有的年，月，日都一样，那么他们就没有太大的意义了。换成自己的数据集可以参考一下WTH数据集的调用流程，利用DatasetCustom来完成。
