### ISSUE TITLE
Colab error on ETTm1

### ISSUE THREAD

**Issue by thisiscam** [zhouhaoyi/Informer2020#39]
Hi,

I was trying to run the model on the provided Colab with the ETTm1 dataset.
And I run into the error **RuntimeError: mat1 dim 1 must match mat2 dim 0**:

```
/content/Informer2020/exp/exp_informer.py in train(self, setting)
    171                     outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)[0]
    172                 else:
--> 173                     outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
    174 
    175                 f_dim = -1 if self.args.features=='MS' else 0

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/content/Informer2020/models/model.py in forward(self, x_enc, x_mark_enc, x_dec, x_mark_dec, enc_self_mask, dec_self_mask, dec_enc_mask)
     67     def forward(self, x_enc, x_mark_enc, x_dec, x_mark_dec, 
     68                 enc_self_mask=None, dec_self_mask=None, dec_enc_mask=None):
---> 69         enc_out = self.enc_embedding(x_enc, x_mark_enc)
     70         enc_out, attns = self.encoder(enc_out, attn_mask=enc_self_mask)
     71 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/content/Informer2020/models/embed.py in forward(self, x, x_mark)
    105 
    106     def forward(self, x, x_mark):
--> 107         x = self.value_embedding(x) + self.position_embedding(x) + self.temporal_embedding(x_mark)
    108 
    109         return self.dropout(x)

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/content/Informer2020/models/embed.py in forward(self, x)
     92 
     93     def forward(self, x):
---> 94         return self.embed(x)
     95 
     96 class DataEmbedding(nn.Module):

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py in forward(self, input)
     91 
     92     def forward(self, input: Tensor) -> Tensor:
---> 93         return F.linear(input, self.weight, self.bias)
     94 
     95     def extra_repr(self) -> str:

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in linear(input, weight, bias)
   1690         ret = torch.addmm(bias, input, weight.t())
   1691     else:
-> 1692         output = input.matmul(weight.t())
   1693         if bias is not None:
   1694             output += bias

RuntimeError: mat1 dim 1 must match mat2 dim 0
```

All I changed was:
```python
args.data = 'ETTm1' # data
```

Am I missing anything in the configuration?

**Comment by thisiscam** [comment]
Hmm, I think the problem was with `args.freq = 'h'`. 
I wonder what each of these mean? https://github.com/zhouhaoyi/Informer2020/blob/main/models/embed.py#L89

Perhaps they corresponds to something related to Appendix B?

**Comment by cookieminions** [comment]
You can refer to `utils/timefeatures.py` to get more information about `freq`, the optional settings of `freq` are: `t`:minutely, `h`: hourly, `d`: daily, `b`:business days, `w`: weekly, `m`:monthly. We will update the `freq` description in next commit.

**Comment by thisiscam** [comment]
Thanks for the fast response!

To clarify, these describe the frequency of the input dataset right?
Is it the case that `freq` needs to be lower than the resolution of the dataset?
For example, for ETTm1, since it's a 15min dataset, it uses `freq="t"` (per minute) as its resolution? 
What would the code do if I use `ETTh1` dataset with `freq="t"`?

**Comment by cookieminions** [comment]
1. Yes, `freq` describes the frequency of the input data.
2. No, you can customize the `freq` as long as you provide the feature `date` in your data. So it's OK to use `freq='t'` with `ETTh` or `freq='h'` with `ETTm`. However, we fix `freq='h'` in `Dataset_ETT_hour` and `freq='t'` in `Dataset_ETT_minute` in code `data/data_loader.py` line 73 and 157. You can modify the code about `freq` or use `Dataset_Custom`.

**Comment by thisiscam** [comment]
>  So it's OK to use freq='t' with ETTh or freq='h' with ETTm. 

I see.

> However, we fix freq='h' in Dataset_ETT_hour and freq='t' in Dataset_ETT_minute in code data/data_loader.py line 73 and 157.

To clarify (and getting back to this issue's original question), this is the cause of the error `RuntimeError: mat1 dim 1 must match mat2 dim 0` am I correct?

**Comment by cookieminions** [comment]
Yes, `freq='h'` will make the dimension of linear in embed be 4 while the data_stamp output dimension of `Dataset_ETT_minute` is 5 because of the fixed `freq='t'`.

**Comment by thisiscam** [comment]
Thanks! 

Nice work and congrats on the Best Paper!

**Comment by Qiuzhuang** [comment]
> Dataset_ETT_minute



> You can refer to `utils/timefeatures.py` to get more information about `freq`, the optional settings of `freq` are: `t`:minutely, `h`: hourly, `d`: daily, `b`:business days, `w`: weekly, `m`:monthly. We will update the `freq` description in next commit.

This should also update command in readme with python -u main_informer.py --model informer --data ETTm1 --attn prob --freq t instead for minute interval.

**Comment by cookieminions** [comment]
> > Dataset_ETT_minute
> 
> > You can refer to `utils/timefeatures.py` to get more information about `freq`, the optional settings of `freq` are: `t`:minutely, `h`: hourly, `d`: daily, `b`:business days, `w`: weekly, `m`:monthly. We will update the `freq` description in next commit.
> 
> This should also update command in readme with python -u main_informer.py --model informer --data ETTm1 --attn prob --freq t instead for minute interval.

Thanks for your remind, we will fix this problem.
