### ISSUE TITLE
informer 和 informer stack 的区别

### ISSUE THREAD

**Issue by 1085733665** [zhouhaoyi/Informer2020#390]
作者您好，有两个问题想请教下您

1、我在代码中看到了informer 和 informer stack  ，这俩模型的区别是什么呢，可以都看做informer么。因为在我的数据集中，informerstack 效果比较好，那么写文章的时候是写informer 呢还是 informer stack呢 

2、关于调整超参数的设置，有什么经验可以参考么

**Comment by zhouhaoyi** [comment]
1、都可以看作informer，只是是否有堆叠问题。
2、超参数在script里面有介绍
