### ISSUE TITLE
train_data = df_data[border1s[0]:border2s[0]]

### ISSUE THREAD

**Issue by Z-Tong** [zhouhaoyi/Informer2020#391]
data_loader.py文件中，

if self.scale: 
            train_data = df_data[border1s[0]:border2s[0]] #对应flag='train'时的数据归一化，而flag != 'train' 时，这样归一化处理是否不妥？
            #train_data = df_data[border1:border2] # 将上述代码改为此是否正确？
            self.scaler.fit(train_data.values)
            data = self.scaler.transform(df_data.values)

**Comment by zhouhaoyi** [comment]
这个与读入的数据格式有关。
