### ISSUE TITLE
when i use the ETTH1 dataset for training model ,it shows ValueError like this,how to fix it?

### ISSUE THREAD

**Issue by roeyjob** [zhouhaoyi/Informer2020#393]
Traceback (most recent call last):
  File "F:\Program Files\JetBrains\PyCharm Community Edition 2022.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "F:\Program Files\JetBrains\PyCharm Community Edition 2022.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/ziyu/Desktop/Informer2020-main/main_informer.py", line 104, in <module>
    exp.train(setting)
  File "C:\Users\ziyu\Desktop\Informer2020-main\exp\exp_informer.py", line 127, in train
    vali_data, vali_loader = self._get_data(flag = 'val')
  File "C:\Users\ziyu\Desktop\Informer2020-main\exp\exp_informer.py", line 95, in _get_data
    print(flag, len(data_set))
ValueError: __len__() should return >= 0

**Comment by YLscnu** [comment]
Hello, I found a solution, because you may have used the time accurate to minutes to do it. The author's dataset is not more than 17000, but more than 60000. So you may have exceeded the range according to the author's index. It is recommended to change it to your own index。
` def __read_data__(self):
        self.scaler = StandardScaler()
        df_raw = pd.read_csv(os.path.join(self.root_path,
                                          self.data_path))

        border1s = [0, 12*30*24*4 - self.seq_len, 12*30*24*4+4*30*24*4 - self.seq_len]
        border2s = [12*30*24*4, 12*30*24*4+4*30*24*4, 12*30*24*4+8*30*24*4]
        border1 = border1s[self.set_type]
        border2 = border2s[self.set_type]
        
        if self.features=='M' or self.features=='MS':
            cols_data = df_raw.columns[1:]
            df_data = df_raw[cols_data]
        elif self.features=='S':
            df_data = df_raw[[self.target]]

        if self.scale:
            train_data = df_data[border1s[0]:border2s[0]]
            self.scaler.fit(train_data.values)
            data = self.scaler.transform(df_data.values)
        else:
            data = df_data.values
            
        df_stamp = df_raw[['date']][border1:border2]
        df_stamp['date'] = pd.to_datetime(df_stamp.date)
        data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)
        
        self.data_x = data[border1:border2]
        if self.inverse:
            self.data_y = df_data.values[border1:border2]
        else:
            self.data_y = data[border1:border2]
        self.data_stamp = data_stamp
    `

**Comment by roeyjob** [comment]
Thank you for your explanation,I fix this problem successfully &nbsp;by using your solution.



------------------ Original ------------------
From: YL ***@***.***&gt;
Date: Thu,Nov 17,2022 2:08 PM
To: zhouhaoyi/Informer2020 ***@***.***&gt;
Cc: Giovo Leonie ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zhouhaoyi/Informer2020] when i use the ETTH1 dataset fortraining model ,it shows ValueError like this,how to fix it? (Issue #393)





 
Hello, I found a solution, because you may have used the time accurate to minutes to do it. The author's dataset is not more than 17000, but more than 60000. So you may have exceeded the range according to the author's index. It is recommended to change it to your own index。
 ` def read_data(self):
 self.scaler = StandardScaler()
 df_raw = pd.read_csv(os.path.join(self.root_path,
 self.data_path))
     border1s = [0, 12*30*24*4 - self.seq_len, 12*30*24*4+4*30*24*4 - self.seq_len]     border2s = [12*30*24*4, 12*30*24*4+4*30*24*4, 12*30*24*4+8*30*24*4]     border1 = border1s[self.set_type]     border2 = border2s[self.set_type]          if self.features=='M' or self.features=='MS':         cols_data = df_raw.columns[1:]         df_data = df_raw[cols_data]     elif self.features=='S':         df_data = df_raw[[self.target]]     if self.scale:         train_data = df_data[border1s[0]:border2s[0]]         self.scaler.fit(train_data.values)         data = self.scaler.transform(df_data.values)     else:         data = df_data.values              df_stamp = df_raw[['date']][border1:border2]     df_stamp['date'] = pd.to_datetime(df_stamp.date)     data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)          self.data_x = data[border1:border2]     if self.inverse:         self.data_y = df_data.values[border1:border2]     else:         self.data_y = data[border1:border2]     self.data_stamp = data_stamp `
