### ISSUE TITLE
为啥我设了 参数--use_gpu True --gpu 0  运行的时候还是显示 use  cpu呢？

### ISSUE THREAD

**Issue by frankwangtoronto** [zhouhaoyi/Informer2020#395]

**Comment by zxc262403** [comment]
配好环境默认是会使用GPU的，可能是你使用的pytorch环境问题，可以打印一下torch.cuda.is_available()这个值看看是不是True

**Comment by aanxud888** [comment]
我也是，vscode和pycharm下都不行，不想重装环境了，cuda为True也不能运行

**Comment by chyaou** [comment]
看看自己的pytorch是不是cpu版本
