### ISSUE TITLE
简单的AR模型预测性能优于Informer？

### ISSUE THREAD

**Issue by iorange-1014** [zhouhaoyi/Informer2020#396]
在公开的几个数据集上分别采用简单的AR模型实现单变量的多步时间序列预测，多步预测方式为output multi-step predictions in one forward operation而非teacher forcing strategy。AR模型的预测性能会大大优于Informer性能。数据集划分方式和公开代码中相同，请问一下，有发现这类问题么？还是我的实现方式有问题？代码粘贴如下：
`import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import os

path = "./results_AR"
if not os.path.exists(path):
    os.makedirs(path)
res = open("./results_AR/data.txt", 'w+')

seq_lens = 168
pred_lens = 24

df_raw = pd.read_csv('./datasets/ETTh1.csv', index_col='date', parse_dates=True)
data = df_raw[['OT']]

train_slice = slice(None, 12*30*24)
valid_slice = slice(12*30*24 - seq_lens, 12*30*24+4*30*24)
test_slice = slice(12*30*24+4*30*24 - seq_lens, 12*30*24+8*30*24)

scaler = StandardScaler().fit(data[train_slice])
data = scaler.transform(data)

step = 1
print('step = ', step, file=res)

train_set = data[train_slice]
valid_set = data[valid_slice]
test_set = data[test_slice]

train_data = []
train_label = []
for i in range(0, len(train_set)-seq_lens-pred_lens+1, step):
    train_data.append(train_set[i: i + seq_lens])
    train_label.append(train_set[i + seq_lens: i + seq_lens + pred_lens])
train_data = np.squeeze(np.array(train_data))
train_label = np.squeeze(np.array(train_label))
print('train shape: ', file=res)
print(train_data.shape, file=res) # (8449, 168)
print(train_label.shape, file=res) # (8449, 24)

valid_data = []
valid_label = []
for i in range(0, len(valid_set)-seq_lens-pred_lens+1, step):
    valid_data.append(valid_set[i: i + seq_lens])
    valid_label.append(valid_set[i + seq_lens: i + seq_lens + pred_lens])
valid_data = np.squeeze(np.array(valid_data))
valid_label = np.squeeze(np.array(valid_label))
print('\nvalid shape: ', file=res)
print(valid_data.shape, file=res) # (2857, 168)
print(valid_label.shape, file=res) # (2857, 24)

test_data = []
test_label = []
for i in range(0, len(test_set)-seq_lens-pred_lens+1, step):
    test_data.append(test_set[i: i + seq_lens])
    test_label.append(test_set[i + seq_lens: i + seq_lens + pred_lens])
test_data = np.squeeze(np.array(test_data))
test_label = np.squeeze(np.array(test_label))
print('\ntest shape: ', file=res)
print(test_data.shape, file=res) # (2857, 168)
print(test_label.shape, file=res) # (2857, 24)

print('\nmodel......', file=res)
lr = LinearRegression()
lr.fit(train_data, train_label)
test_pred = lr.predict(test_data)

print('\nnormalized mse = ', np.mean((test_pred-test_label)**2), file=res)
print('\nnormalized mae = ', np.mean(np.abs(test_pred-test_label)), file=res)`

**Comment by zhouhaoyi** [comment]
ETTh-small的自回归性还是比较强的，可以参考数据集那个repo。可以关注后续数据集的更新。
