### ISSUE TITLE
关于frequency参数选择business day（工作日）的问题

### ISSUE THREAD

**Issue by spielbergli** [zhouhaoyi/Informer2020#398]
请问一下，如果frequency参数设置时，选择business day，如何考虑不同日历的问题（比如国内和国外的假期不同，导致国内外的工作日不同）？谢谢！
parser.add_argument('--freq', type=str, default='b', help='freq for time features encoding, options:[s:secondly, t:minutely, h:hourly, d:daily, b:business days, w:weekly, m:monthly])

**Comment by zhouhaoyi** [comment]
如果是不同的日历，我建议是不同的embeeding来表示就行。
