### ISSUE TITLE
Test Loss: nan，mse:nan, mae:nan

### ISSUE THREAD

**Issue by dspiderd** [zhouhaoyi/Informer2020#402]
用自己的数据集，出现Test Loss: nan，mse:nan, mae:nan，请问是什么原因？

**Comment by Misaka10046** [comment]
Maybe there is 'nan' in your data set.

**Comment by tomatoes-dinner** [comment]
> 
你看看自己数据集是不是有问题  我之前的数据集有很多0 test loss就是nan

**Comment by Williams-wlc** [comment]
那请问怎么解决呢  0可以换成什么 或者不要那个特征了吗？

**Comment by zhouhaoyi** [comment]
看能不能给一些数据，我们来进行测试。

**Comment by MountVoom** [comment]
可以考虑使用别的归一化方法或者删除该列
