### ISSUE TITLE
换成自己的数据 出错如下

### ISSUE THREAD

**Issue by frankwangtoronto** [zhouhaoyi/Informer2020#405]
date,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT
0.000000,91.919998,-101.830002,131.100006,-0.350000,60.570004,157.600006,0.666435
0.050000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
0.100000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
0.150000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
0.200000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
0.250000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
0.300000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
0.350000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
0.400000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
0.450000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
0.500000,91.919968,-101.830055,131.099976,-0.350003,60.570091,157.600021,0.666435
。。。
6.800000,98.062393,-99.714577,130.433640,-0.732773,57.756462,151.801453,0.708826
6.850000,100.903755,-98.370834,129.816452,-0.715802,56.997658,149.024323,0.729587
6.900000,104.520103,-96.480568,128.863037,-0.695320,56.021904,145.493591,0.757491
6.950000,108.850647,-93.832153,127.341286,-0.674072,54.853241,141.274658,0.793716
7.000000,113.777695,-90.231728,124.964798,-0.657428,53.588310,136.490509,0.839770
7.050000,119.092422,-85.501366,121.346329,-0.654544,52.441460,131.356049,0.897287
7.100000,124.525459,-79.497154,115.981667,-0.678022,51.777882,126.146629,0.968025
7.150000,124.782227,-79.325104,115.548500,-0.681243,52.038109,125.900124,0.971725
7.200000,124.780861,-79.324120,115.547333,-0.681278,52.038307,125.901505,0.971720
7.250000,124.780807,-79.317932,115.552856,-0.681219,52.026592,125.901588,0.971720
7.300000,124.780411,-79.268471,115.596939,-0.680746,51.933067,125.902214,0.971720
7.350000,124.779045,-79.100960,115.745300,-0.679161,51.617237,125.904366,0.971716
7.400000,124.775848,-78.699722,116.093079,-0.675489,50.868301,125.909470,0.971698
7.450000,124.769623,-77.896324,116.754623,-0.668710,49.403522,125.919617,0.971638
7.500000,124.759018,-76.442413,117.837814,-0.658383,46.866676,125.937721,0.971476
7.550000,124.743256,-73.838646,119.273201,-0.649408,42.827908,125.969727,0.971720
7.600000,124.721794,-69.598465,121.035011,-0.648676,36.826427,126.024078,0.971719

出错如下：咋办呀？

Args in experiment:
Namespace(model='informer', data='ETTh1', root_path='./data/ETT/', data_path='ETTh1.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=24, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, s_layers=[3, 2, 1], d_ff=2048, factor=5, padding=0, distil=True, dropout=0.05, attn='prob', embed='timeF', activation='gelu', output_attention=False, do_predict=False, mix=True, cols=None, num_workers=0, itr=2, train_epochs=6, batch_size=32, patience=3, learning_rate=0.0001, des='test', loss='mse', lradj='type1', use_amp=False, inverse=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3', detail_freq='h')
Use GPU: cuda:0
>>>>>>>start training : informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8521
val 1989
Traceback (most recent call last):
  File "/data/run01/scz1285/Informer2020-main/main_informer.py", line 105, in <module>
    exp.train(setting)
  File "/data/run01/scz1285/Informer2020-main/exp/exp_informer.py", line 128, in train
    test_data, test_loader = self._get_data(flag = 'test')
  File "/data/run01/scz1285/Informer2020-main/exp/exp_informer.py", line 95, in _get_data
    print(flag, len(data_set))
ValueError: __len__() should return >= 0
True
Args in experiment:
Namespace(model='informer', data='ETTh2', root_path='./data/ETT/', data_path='ETTh2.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=24, enc_in=7, dec_in=7, c_out=7, d_model=512, n_heads=8, e_layers=2, d_layers=1, s_layers=[3, 2, 1], d_ff=2048, factor=5, padding=0, distil=True, dropout=0.05, attn='prob', embed='timeF', activation='gelu', output_attention=False, do_predict=False, mix=True, cols=None, num_workers=0, itr=2, train_epochs=6, batch_size=32, patience=3, learning_rate=0.0001, des='test', loss='mse', lradj='type1', use_amp=False, inverse=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3', detail_freq='h')
Use GPU: cuda:0
>>>>>>>start training : informer_ETTh2_ftM_sl96_ll48_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8521
val 1989
Traceback (most recent call last):
  File "/data/run01/scz1285/Informer2020-main/main_informer.py", line 105, in <module>
    exp.train(setting)
  File "/data/run01/scz1285/Informer2020-main/exp/exp_informer.py", line 128, in train
    test_data, test_loader = self._get_data(flag = 'test')
  File "/data/run01/scz1285/Informer2020-main/exp/exp_informer.py", line 95, in _get_data
    print(flag, len(data_set))
ValueError: __len__() should return >= 0

**Comment by frankwangtoronto** [comment]
我的时间间隔是50ms， 这个问题是时间间隔不匹配 还是我的数据集过长？

**Comment by Kai744** [comment]
我是在exp-informer里把我的数据集字典对应的函数设置成了Dataset_Custom，就跑通了，还不明白原理。
def _get_data(self, flag):
        args = self.args

        data_dict = {
            'ETTh1':Dataset_ETT_hour,
            'ETTh2':Dataset_ETT_hour,
            'ETTm1':Dataset_ETT_minute,
            'ETTm2':Dataset_ETT_minute,
            'WTH':Dataset_Custom,
            'ECL':Dataset_Custom,
            'Solar':Dataset_Custom,
            'custom':Dataset_Custom,
            "ETTh3":Dataset_Custom,
        }

**Comment by 852597930** [comment]
> 

您好，可以教教我自定义自己的数据吗，我按照他的照猫画虎不行啊，可以有偿

**Comment by MountVoom** [comment]
和自己数据集的长度有关，自定义数据集建议使用DatasetCustom，其余两个数据集根据数据特征对训练集测试集验证集进行了划分，自己的数据集可能会因为长度不够导致划分出来的集合为空，DatasetCustom则是按照比例划分。使用自己的数据集大概需要增加data_dict的字典，修改一下路径参数，可以参考一下使用ECL数据集实验的流程。
