### ISSUE TITLE
为啥我的groundtrue 是一条直线呀 嘤嘤嘤

### ISSUE THREAD

**Issue by frankwangtoronto** [zhouhaoyi/Informer2020#407]
![图片](https://user-images.githubusercontent.com/57983182/203480253-a2ac4cea-2759-45f9-8030-b464a374c694.png)

**Comment by frankwangtoronto** [comment]
![图片](https://user-images.githubusercontent.com/57983182/203689847-2a834ca4-0d16-4f99-90d1-1aaa8320803a.png)

哭死了  groundtrue 为什么始终是一条直线？ 我把数据在一个文件里复制了三遍 要不数据不够长  是这原因吗？

**Comment by AndyRyuu** [comment]
我和你相反，我的预测值总是趋于一条直线。

**Comment by jieruwei** [comment]
请问解决了吗

**Comment by AndyRyuu** [comment]
没有   可能是数据集不行  也可能是对于informer的使用还没完全理解   预测结果就总是一个没有什么变化的  数值不大的直线

2022年12月9日(金) 17:35 jieruwei ***@***.***>:

**Comment by zhouhaoyi** [comment]
这个一般是你的数据集的embedding设置不合理造成的。

**Comment by MountVoom** [comment]
一般和数据以及参数的设置关系比较大
