### ISSUE TITLE
作者在公开的代码中decoder的self-attention是未使用到mask吗？

### ISSUE THREAD

**Issue by FangBo-0219** [zhouhaoyi/Informer2020#408]
我在看源码时发现，decode的mask掩码好像一直是false，是没用到这个mask吗，这样是否和时间序列预测的理论有点冲突。期待作者解惑。

**Comment by zhouhaoyi** [comment]
从NLP的任务来看，这个影响是比较大的，似乎在informer的架构下，这个mask影响没有那么显著。
