### ISSUE TITLE
A question about scaling data.

### ISSUE THREAD

**Issue by lk1983823** [zhouhaoyi/Informer2020#41]
In your model code, I find you used data scaler for train\val\test dataset separately. However, I think you probably use future information during validating and testing process. Because, during the online prediction, we can't get the whole data in advance. In addition, I didn't find inverse transformation, which is important to show the real model performance for testing dataset.  Can you give more information as to how to deal with data scaling and inverse transformation? Thanks.

**Comment by cookieminions** [comment]
Thank you very much for your reminder, train data should be used to calculate mean and std when scaling data, while validation data and test data should only be scaled.

We will fix the above problems and the `inverse_transform` problem immediately.

Thanks!

**Comment by lk1983823** [comment]
> Thank you very much for your reminder, train data should be used to calculate mean and std when scaling data, while validation data and test data should only be scaled.
> 
> We will fix the above problems and the `inverse_transform` problem immediately.
> 
> Thanks!

Thanks, could you remind me an update if it is done?

**Comment by cookieminions** [comment]
Thanks for your attention! We have updated the code about data scaling.
