### ISSUE TITLE
关于iter超参数的问题

### ISSUE THREAD

**Issue by ZiciuCanJustus** [zhouhaoyi/Informer2020#411]
Hello，非常感谢你们的分享，我再进行代码测试的时候有一些不是特别理解的问题：
主要是关于args.itr这个超参数的。我很奇怪这部分既然setup了random seed保证结果可复现性后，为何还需要进行多次的iter times呢？如果我们从外部直接卡住随机种子进行训练，多次进行训练似乎也是个可行方案。谢谢

**Comment by zhouhaoyi** [comment]
informer本身的方法里面带有一些随机性，早期的pytorch似乎不太处理得特别好，所以设置了重复训练。
