### ISSUE TITLE
为什么我按着要求输入参数了，run后还是提示输入model和data

### ISSUE THREAD

**Issue by jieruwei** [zhouhaoyi/Informer2020#412]
为什么我按着要求输入参数了，run后还是提示输入model和data

**Comment by lujyou** [comment]
需要配置参数，在Pycharm的编辑设置，加上–-model --data

**Comment by jieruwei** [comment]
我调通了，非常感谢你，不知道您有兴趣一块探讨一下不
















在 2022-12-07 16:44:15，"lujyou" ***@***.***> 写道：

需要配置参数，在Pycharm的编辑设置，加上–-model --data

**Comment by lujyou** [comment]
可以啊 但是我跑出来的结果也不好发自我的手机-------- 原始邮件 --------发件人： jieruwei ***@***.***>日期： 2022年12月7日周三 16:46收件人： zhouhaoyi/Informer2020 ***@***.***>抄送： lujyou ***@***.***>, Comment ***@***.***>主    题： Re: [zhouhaoyi/Informer2020] 为什么我按着要求输入参数了，run后还是提示输入model和data (Issue #412)

我调通了，非常感谢你，不知道您有兴趣一块探讨一下不

































在 2022-12-07 16:44:15，"lujyou" ***@***.***> 写道：



需要配置参数，在Pycharm的编辑设置，加上–-model --data

**Comment by jieruwei** [comment]
我觉得可以一起探讨一下，我前几天自己调通了，也换了自己的数据，加v吧v：2079382492



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月07日 17:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhouhaoyi/Informer2020] 为什么我按着要求输入参数了，run后还是提示输入model和data (Issue #412) |

可以啊 但是我跑出来的结果也不好发自我的手机-------- 原始邮件 --------发件人： jieruwei ***@***.***>日期： 2022年12月7日周三 16:46收件人： zhouhaoyi/Informer2020 ***@***.***>抄送： lujyou ***@***.***>, Comment ***@***.***>主 题： Re: [zhouhaoyi/Informer2020] 为什么我按着要求输入参数了，run后还是提示输入model和data (Issue #412)
我调通了，非常感谢你，不知道您有兴趣一块探讨一下不
















在 2022-12-07 16:44:15，"lujyou" ***@***.***> 写道：

需要配置参数，在Pycharm的编辑设置，加上–-model --data

**Comment by jieruwei** [comment]
还在吗



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月07日 17:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhouhaoyi/Informer2020] 为什么我按着要求输入参数了，run后还是提示输入model和data (Issue #412) |

可以啊 但是我跑出来的结果也不好发自我的手机-------- 原始邮件 --------发件人： jieruwei ***@***.***>日期： 2022年12月7日周三 16:46收件人： zhouhaoyi/Informer2020 ***@***.***>抄送： lujyou ***@***.***>, Comment ***@***.***>主 题： Re: [zhouhaoyi/Informer2020] 为什么我按着要求输入参数了，run后还是提示输入model和data (Issue #412)
我调通了，非常感谢你，不知道您有兴趣一块探讨一下不
















在 2022-12-07 16:44:15，"lujyou" ***@***.***> 写道：

需要配置参数，在Pycharm的编辑设置，加上–-model --data

**Comment by 0Stephen2** [comment]
你可以直接将module和date那一行的request=True去掉就好了

**Comment by jieruwei** [comment]
> 

你好，你有没有遇到过这种情况：参数没变的情况下，重复运行几次的结果去完全不一样

**Comment by 0Stephen2** [comment]
每次应该结果差不会太多，你这个我不知道为什么

**Comment by MountVoom** [comment]
模型运行是会有随机性的，比如dropout是随机的，参数的初始化是随机的，想要重复结果可以考虑固定随机种子。
seq_len的设置一般根据数据的特点来设置比如一周或者一个月等等。
