### ISSUE TITLE
读取自己的数据集出错

### ISSUE THREAD

**Issue by liangchengyu123** [zhouhaoyi/Informer2020#413]
def __read_data__(self):
        self.scaler = StandardScaler()#标准化
        df_raw = pd.read_csv(os.path.join(self.root_path,
                                          self.data_path))
        '''
        df_raw.columns: ['date', ...(other features), target feature]
        '''
        # cols = list(df_raw.columns); 
        if self.cols:
            cols=self.cols.copy()
            cols.remove(self.target)
        else:
            cols = list(df_raw.columns); cols.remove(self.target); cols.remove('time')#读取列名 去标签，日期
        df_raw = df_raw[['time']+cols+[self.target]]

这部分我只把去标签那行的date改成time 但是运行后还是提示x not in list debug发现去标签的操作运行了两次 第二次因为没有标签所以出错是为啥呢

**Comment by jieruwei** [comment]
解决了嘛

**Comment by liangchengyu123** [comment]
> 解决了嘛

嗯，已解决

**Comment by yingdd0** [comment]
具体是怎么解决的呢，我的情况也和你一样

**Comment by cangguhuang** [comment]
怎么搞定的
