### ISSUE TITLE
拟合效果很差，跟论文中的 结果不一致

### ISSUE THREAD

**Issue by 0Stephen2** [zhouhaoyi/Informer2020#414]
![image](https://user-images.githubusercontent.com/111976971/206661439-de32ac66-cee6-4a8f-b6fd-49a0f582529a.png)
按照原始参数跑出来，效果和原文不一样 该如何解决

**Comment by 0Stephen2** [comment]
这种属于效果很差吗，有没有哪位帮我回答一下，如果是很差的话，该如何解决呢

**Comment by zhouhaoyi** [comment]
可以看一下scripts文件夹，有一些参数提示。

**Comment by 0Stephen2** [comment]
> 可以看一下scripts文件夹，有一些参数提示。

好的好的我解决掉了 谢谢

**Comment by oushilin** [comment]
请问是这么解决的呢？我跑自己的数据集出来的图像拟合效果也很差

**Comment by MountVoom** [comment]
跑自己的数据集可以试着调调参数，可以参考一下一些其他issue的类似问题
