### ISSUE TITLE
为什么squ_len输入的值不一样，train的数据集数量也会发生变化？

### ISSUE THREAD

**Issue by jieruwei** [zhouhaoyi/Informer2020#415]
为什么squ_len输入的值不一样，train的数据集数量也会发生变化？不是说train是数据的70%吗，这个train的数量不是固定的吗

**Comment by zhouhaoyi** [comment]
seq_len是不同的划分方式，数量自然会变化。

**Comment by LY-must-win** [comment]
> seq_len是不同的划分方式，数量自然会变化。

是不是相当于一种滑动窗取值？

**Comment by MountVoom** [comment]
是的，是一种滑动窗取值
