### ISSUE TITLE
自己的数据集训练时候输入的序列长度不一样，但是我看到有seq_len这个限制条件，如果数据不到seq_len是会自己填充吗

### ISSUE THREAD

**Issue by wukaii** [zhouhaoyi/Informer2020#417]
自己的数据集训练时候输入的序列长度不一样，但是我看到有seq_len这个限制条件，如果数据不到seq_len是会自己填充吗

**Comment by zhouhaoyi** [comment]
这个长度不一样，是指每个seq的长度不均匀吗？如果是这样的话，可能要自己设定一些填充方案。

**Comment by wukaii** [comment]
是的，谢谢了

**Comment by wukaii** [comment]
是的，谢谢了

**Comment by wukaii** [comment]
我填充可以是0吗，因为我看到decode就是填充了0

**Comment by MountVoom** [comment]
可以的，也可以尝试均值，ffill，bfill之类的方式
