### ISSUE TITLE
伟大的作者，你好，您提供的数据的训练数据的标签是怎么规定的，怎么算是一个样本

### ISSUE THREAD

**Issue by wukaii** [zhouhaoyi/Informer2020#418]
伟大的作者，你好，您提供的数据的训练数据的标签是怎么规定的，怎么算是一个样本

**Comment by zhouhaoyi** [comment]
目前的几个数据集应该都没有标签，直接进行mse或者mae等指标的回归。

**Comment by wukaii** [comment]
那batch_y和batch_x数据的内容具体有啥区别呀

**Comment by MountVoom** [comment]
您可以参考一下dataloader.py里的代码，采取的和常用时序预测数据构建类似的方式，选取一段作为一个样本，并把接下来的一段作为预测的标签

**Comment by wukaii** [comment]
你好作者，三个数据处理类型有啥区别



---原始邮件---
发件人: "Siyang ***@***.***&gt;
发送时间: 2022年12月15日(周四) 中午11:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 伟大的作者，你好，您提供的数据的训练数据的标签是怎么规定的，怎么算是一个样本 (Issue #418)




 
您可以参考一下dataloader.py里的代码，采取的和常用时序预测数据构建类似的方式，选取一段作为一个样本，并把接下来的一段作为预测的标签

**Comment by MountVoom** [comment]
主要是针对不同的数据频率设计的数据集划分的方式不同，没有什么较大的区别
