### ISSUE TITLE
你好，你有没有遇到过这种情况：参数没变的情况下，重复运行几次的结果去完全不一样

### ISSUE THREAD

**Issue by jieruwei** [zhouhaoyi/Informer2020#421]
你好，你有没有遇到过这种情况：参数没变的情况下，重复运行几次的结果去完全不一样，mse和mae的值也一直变，预测的数据值也一直变

**Comment by zhouhaoyi** [comment]
根据Informer的原理，里面probsparse存在一定的随机性。这个和head性能也有关系。
