### ISSUE TITLE
我看完了代码，还是不能理解informer训练的过程batch和batchy，如果lable和seqlen是一样的，batchy比batch多了一列pre，decode多了一列padding，那么时间序列的预测是怎么体现的呢，按照我的理解本来标签和输入应该是要有一个错位才对

### ISSUE THREAD

**Issue by wukaii** [zhouhaoyi/Informer2020#424]

**Comment by MountVoom** [comment]
您可以参考一下`exp_informer.py`里`_process_one_batch`部分的代码。Informer是生成式解码器，`dec_inp`作为decoder的输入，由batch_y的label_len部分和长度为的pred_len的填充组成，需要预测的就是pred_len这一部分，batch_y的pred_len部分也就是实际的标签。

结合`data_loader.py`的代码，假设用区间来代表一段时间序列，seq_len=96, label_len=48, pred_len=24时，batch_x是[1, 96]，batch_y是[49, 120]。[97, 120]这一段对应了标签。

**Comment by Malibu351** [comment]
> 

您好，请问我可以这样理解吗：
模型用feature+label作为输入，预测一个同样长度的数据，只不过需要预测的部分(batch_y)中label使用长度为pred_len填充了。

以及我有一个疑问：
为什么计算损失的时候不是pred和true的label部分计算mseloss，而是全部的feature+label部分共同计算loss呢

**Comment by Malibu351** [comment]
> batch_x

您好，请问我可以这样理解吗：
模型用feature+label作为输入，预测一个同样长度的数据，只不过需要预测的部分(batch_y)中label使用长度为pred_len填充了。

以及我有一个疑问：
为什么计算损失的时候不是pred和true的label部分计算mseloss，而是全部的feature+label部分共同计算loss呢

**Comment by Malibu351** [comment]
您好，请问我可以这样理解吗：
模型用feature+label作为输入，预测一个同样长度的数据，只不过需要预测的部分(batch_y)中label使用长度为pred_len填充了。

以及我有一个疑问：
为什么计算损失的时候不是pred和true的label部分计算mseloss，而是全部的feature+label部分共同计算loss呢

**Comment by MountVoom** [comment]
需要预测的label是不会作为模型输入的，这一部分的长度是pred_len，label_len是decoder输入的长度。计算loss的pred和true是对模型的输出进行了截断的，取的最后pred_len部分。
