### ISSUE TITLE
关于超长时序预测问题

### ISSUE THREAD

**Issue by SimyokH** [zhouhaoyi/Informer2020#426]
求问各位大佬，我打算用10年逐时资料预测未来2-5年的数据，不知可行性如何？

**Comment by wukaii** [comment]
太长了吧，，，估计准确率很低

**Comment by SimyokH** [comment]
> 太长了吧，，，估计准确率很低

如果换成是3年预测1年呢，数据有较强的时间相关性的

**Comment by wukaii** [comment]
你动手试试，按照你的要求没有更好的模型了，你知道，三种数据处理类有啥区别不



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月17日(周六) 上午10:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 关于超长时序预测问题 (Issue #426)




  
太长了吧，，，估计准确率很低
  
如果换成是3年预测1年呢，数据有较强的时间相关性的

**Comment by zhouhaoyi** [comment]
这个关键是看数据的可分析性问题，是什么领域呢？

**Comment by SimyokH** [comment]
> 这个关键是看数据的可分析性问题，是什么领域呢？

海洋工程领域，日月年的时间相关性很大

**Comment by SimyokH** [comment]
> 你动手试试，按照你的要求没有更好的模型了，你知道，三种数据处理类有啥区别不
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年12月17日(周六) 上午10:29 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于超长时序预测问题 (Issue #426) 太长了吧，，，估计准确率很低 如果换成是3年预测1年呢，数据有较强的时间相关性的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的好的，三种数据处理类区别我还在研究
