### ISSUE TITLE
decoder without prob attention

### ISSUE THREAD

**Issue by aloyschen** [zhouhaoyi/Informer2020#43]
论文整体的模型结构图里decoder部分是有prob attention的，但是看代码实现都是使用的full attention
   DecoderLayer(
                    AttentionLayer(FullAttention(True, factor, attention_dropout=dropout, output_attention=False), 
                                d_model, n_heads),
                    AttentionLayer(FullAttention(False, factor, attention_dropout=dropout, output_attention=False)
![image](https://user-images.githubusercontent.com/18731105/110088151-72a43b00-7dcf-11eb-902f-330e15591931.png)
想问下为什么这么做呢

**Comment by zhouhaoyi** [comment]
Please refer to https://github.com/zhouhaoyi/Informer2020/issues/38. We will provide a performance comparison soon @cookieminions.

**Comment by cookieminions** [comment]
我们已经更新了代码，目前Decoder中self-attention将会与Encoder保持一致，并且调整了默认参数设置，Decoder中使用ProbSparse Attention的效果与使用Full Attention差别不大，详细的对比我们在不久后会出一个实验结果表格，也欢迎更多实验。同时我们在https://github.com/zhouhaoyi/Informer2020/issues/44中还给出了一组Decoder使用ProbSparse Attention下再ETTh2上的结果，也欢迎查看。
