### ISSUE TITLE
train中的test_data和test中的data

### ISSUE THREAD

**Issue by wuxian-oss** [zhouhaoyi/Informer2020#435]
您好，请教一下，在train函数中的test_data![image](https://user-images.githubusercontent.com/74282334/209522897-77655a47-e686-495c-94c6-47489f2f6f76.png)与test函数中
![image](https://user-images.githubusercontent.com/74282334/209522978-d8804b46-07bf-4698-aaca-b3ca380fce34.png)
的data是否一样？如果是一样的话，那么test得到的指标数据是否不够准确。希望得到您的回复。感谢。

**Comment by Aaralshin** [comment]
这两个是一样的。test得到的指标数据是否不够准确是指什么？

**Comment by wuxian-oss** [comment]
在另一个提问中您的回答帮助我解决了我的疑惑，感谢您！
