### ISSUE TITLE
运行自己的数据集报错

### ISSUE THREAD

**Issue by 0Stephen2** [zhouhaoyi/Informer2020#439]
![image](https://user-images.githubusercontent.com/111976971/209941807-664c73ce-1c11-4db5-9941-13d4b483a7c6.png)
运行自己的数据集这样报错是因为什么呢

**Comment by tiechitongyajixiaogang** [comment]
我也是这个报错，请问你解决了吗

**Comment by LovePolaBear** [comment]
> 我也是这个报错，请问你解决了吗

没有日期，数据集需要有一列date

**Comment by 852597930** [comment]
> > 我也是这个报错，请问你解决了吗
> 
> 没有日期，数据集需要有一列date
如果只有date和y值，而没有x值，只输入y和date也能用这个模型吗？

**Comment by 0Stephen2** [comment]
> > > 我也是这个报错，请问你解决了吗
> > 
> > 
> > 没有日期，数据集需要有一列日期 如果只有date和y值，而没有x值，只输入y和date也能用这个模型吗？

应该是不可以的吧，这是时间序列预测模型.

**Comment by 852597930** [comment]
您好！您自己的数据集可以正常运行吗？我这边自己的数据集出了点儿问题，能否指教一下，谢谢您


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhouhaoyi/Informer2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月17日(星期二) 晚上11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhouhaoyi/Informer2020] 运行自己的数据集报错 (Issue #439)





    
我也是这个报错，请问你解决了吗
  
没有日期，数据集需要有一列日期 如果只有date和y值，而没有x值，只输入y和date也能用这个模型吗？
   
应该是不可以的吧，这是时间序列预测模型.

**Comment by MountVoom** [comment]
`date`列是必要的
