### ISSUE TITLE
关于seq_len、label_len和pred_len以及border列表询问

### ISSUE THREAD

**Issue by tongji11** [zhouhaoyi/Informer2020#441]
老师您好，我在学习代码的时候有如下两个问题可否请老师解答一下呀？一个就是data_loader的时候，这里seq_len、label_len和pred_len是被重新赋了一个新的值嘛？跟原来的96、48、24参数不一样了。二是Dataset_ETT_hour类里的border1s和border2s的两个列表，里面的这些数值为什么会选12*30*24这几个数值相乘呀？我看下面作者定义的dataset_custom里，70%的数据量作为训练集的话也不对呀，就感觉挺疑惑的，可否请老师解答一下呀？谢谢老师！

**Comment by Aaralshin** [comment]
1.原来的参数指的是哪里的参数？
2.12月*30天*24小时

**Comment by tongji11** [comment]
我已经弄清楚了，谢谢老师的解答！

**Comment by ShanLan-123** [comment]
我也遇到了同样的问题，可以告诉我怎么解决的吗？
