### ISSUE TITLE
换用自己的数据集效果不好

### ISSUE THREAD

**Issue by hjblearning** [zhouhaoyi/Informer2020#445]
大佬您好，想请教一个问题。为什么使用我自己的数据集效果这么差呢？调整了很多超参数效果还是不好，差不多就是一条直线，但是可以预测出趋势。我觉得是过拟合，是不是主要还是因为数据集本身的问题呢？还是说应该怎么调整参数呢？麻烦大佬空闲的时候能够指点一二，多谢！
![1](https://user-images.githubusercontent.com/62193211/212613818-2bac88bd-c980-407a-a900-5f7c87603ce0.png)
![2](https://user-images.githubusercontent.com/62193211/212613824-58c96303-ec4d-42fd-a5bf-ab43bb64fbd1.png)

**Comment by Aaralshin** [comment]
可以参考 #444
