### ISSUE TITLE
自己的数据集总报错，有没有大佬可以指教一下

### ISSUE THREAD

**Issue by 852597930** [zhouhaoyi/Informer2020#446]
我自己的文件是a57，和ETTH1的一样，少了两列数据，但是替换后，总是出问题
![image](https://user-images.githubusercontent.com/66360048/213102664-188fc28b-136b-4c5a-9196-e722b7e00543.png)

**Comment by learncpppytorch** [comment]
看下exp_informer里的get_data有没有添加
