### ISSUE TITLE
数据集报错问题

### ISSUE THREAD

**Issue by 0Stephen2** [zhouhaoyi/Informer2020#449]
![image](https://user-images.githubusercontent.com/111976971/216240104-ddd282d8-1260-4512-b56a-5363610fd647.png)
各位有没有谁是这个问题，请问是什么原因呢 该怎样解决，谢谢！

**Comment by Aaralshin** [comment]
数据集可能没有正确加载

**Comment by MountVoom** [comment]
看起来是数据集没有`date`这一列
