### ISSUE TITLE
predict 的时候引入了随机性的问题，每次重跑预测结果会不一样

### ISSUE THREAD

**Issue by xhqing** [zhouhaoyi/Informer2020#450]

**Comment by MountVoom** [comment]
有随机性很正常，想结果一样可以固定随机种子

**Comment by daihaozxn** [comment]
> 有随机性很正常，想结果一样可以固定随机种子

您好，请问，具体需要如何固定随机种子，我使用了下面3行语句试图固定随机种子，
random.seed(fix_seed)
torch.manual_seed(fix_seed)
np.random.seed(fix_seed)
但参数相同时，每组（一组3次）预测后的指标仍然不尽相同，有时差别还挺大的。谢谢解答！
