### ISSUE TITLE
论文中的指标相关问题

### ISSUE THREAD

**Issue by wuxian-oss** [zhouhaoyi/Informer2020#453]
作者您好，我是初学者，想请教一下以下问题。
①请问一下论文中的指标结果是根据results中的true和pred直接得出的嘛？
②在exp_informer文件中的train和test函数，都存在test_data和test_loader，这两部分得到的数据是一致的嘛？如果是一致的话，那么是否存在模型训练期间已经知道了模型test阶段的数据，从而在test阶段出现数据泄露的问题？

**Comment by Aaralshin** [comment]
1.是的。
2.尽管train函数中存在test_data和test_loader，但仅用于打印结果，既不会参与模型训练，也不参与earlystopping，因此不存在数据泄露的问题。

**Comment by wuxian-oss** [comment]
感谢您的回复，这对我很有帮助，谢谢您！
