### ISSUE TITLE
求解Run中出现的问题

### ISSUE THREAD

**Issue by ChenYiHao1203** [zhouhaoyi/Informer2020#456]
main_informer.py: error: the following arguments are required: --model, --data
![image](https://user-images.githubusercontent.com/104145760/219824839-71592a13-f42e-4fba-8c4c-97bf781933d4.png)

**Comment by Alio-D** [comment]
https://blog.csdn.net/qq_20144897/article/details/127298319

**Comment by Alio-D** [comment]
# 选择模型(去掉required参数，选择informer模型)
parser.add_argument('--model', type=str, default='informer',help='model of experiment, options: [informer, informerstack, informerlight(TBD)]')

# 数据选择(去掉required参数)
parser.add_argument('--data', type=str, default='WTH', help='data')
————————————————
版权声明：本文为CSDN博主「羽星_s」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/qq_20144897/article/details/127298319

**Comment by Alio-D** [comment]
你好，邮件已收到（自动回复邮件）。Hello, email received (auto reply email).
