### ISSUE TITLE
About ECL dataset  in your paper

### ISSUE THREAD

**Issue by 296894139** [zhouhaoyi/Informer2020#46]
Congratulations on the best paper award!

We collected the ECL data set and found that it contained a total of 370 clients. However, in the experimental part of the paper, you said "It collects the electricity consumption (Kwh) of 321 clients" and "set ‘MT 320’ as the target value". How do you determine the target value? Can you provide the data of these 321 clients? Thank you。

**Comment by cookieminions** [comment]
Thanks for your attention to our work!

We follow the same data preprocessing as LSTnet, you can get the ECL data from here: [multivariate-time-series-data](https://github.com/laiguokun/multivariate-time-series-data).

**Comment by oremnirv** [comment]
Thank you for the GitHub repo and paper.

Can you please clarify what you mean by "set ‘MT 320’ as the target value"?

Thank you
