### ISSUE TITLE
Validation loss decreased (nan --> nan).

### ISSUE THREAD

**Issue by goodlucky111** [zhouhaoyi/Informer2020#461]
训练的时候损失一直是nan到nan

**Comment by ywljiayou** [comment]
> 训练的时候损失一直是nan到nan

您好，我也是这个问题，请问您解决了吗

**Comment by YUAN0620** [comment]
> 

你好，我如果对数据集进行一些插补，也会出现这个问题，请问您解决了吗

**Comment by MountVoom** [comment]
可能是数据集有缺失值或者在归一化计算之后出现了nan，可以从这两个角度去看一下？
