### ISSUE TITLE
只想使用自己的数据训练好的模型test我自己的测试集，该怎么改写呢？测试集是一些新的数据！

### ISSUE THREAD

**Issue by 237014845** [zhouhaoyi/Informer2020#462]

**Comment by MountVoom** [comment]
可以利用Dataset Custom将自己的数据加入进去，然后在exp_informer里增加对自定义数据的调用，可以参考ETTh1数据集的调用流程

**Comment by 77coming** [comment]
> 可以利用Dataset Custom将自己的数据加入进去，然后在exp_informer里增加对自定义数据的调用，可以参考ETTh1数据集的调用流程

请问具体是改哪些地方呢
