### ISSUE TITLE
切序列的時候的shift是1嘛

### ISSUE THREAD

**Issue by wayne9756** [zhouhaoyi/Informer2020#463]
RT,如果我要切訓練資料，兩筆訓練資料是間隔會是1呢？還是會是prediction的長度？

**Comment by wayne9756** [comment]
如果是間隔1個時間單位的話，那在prediction的結果是會有重疊的部份，是怎麼處理的？

**Comment by MountVoom** [comment]
間隔是1，測試的時候是會有重叠的部分，預測的時候只會預測一次，不會重叠
