### ISSUE TITLE
间断时间序列问题

### ISSUE THREAD

**Issue by 11wwAD** [zhouhaoyi/Informer2020#464]
是这样的，我有多个多变量时间序列，单个时间序列200个数据点左右，在时间上是连续的，但是每个时间序列与每个时间序列之间不存在时间上的连续性。例如，一个样本为一个CSV文件，200行（序列长度），17列（特征数），拥有300个这样的CSV文件，每个CSV文件是相互独立的。请问这样的数据集，我该如何应用，期望各位大佬的解答

**Comment by 11wwAD** [comment]
这些短序列是由相同的过程产生的水下机器人的状态数据

**Comment by 11wwAD** [comment]
我的目的是在这些时间序列上估计相同的一个模型

**Comment by Sakura-Qy** [comment]
> 是这样的，我有多个多变量时间序列，单个时间序列200个数据点左右，在时间上是连续的，但是每个时间序列与每个时间序列之间不存在时间上的连续性。例如，一个样本为一个CSV文件，200行（序列长度），17列（特征数），拥有300个这样的CSV文件，每个CSV文件是相互独立的。请问这样的数据集，我该如何应用，期望各位大佬的解答

我也做类似的预测，我准备在获取每一个batch的时候控制batch的开始和结束都是在同一个csv中的数据，这样在每一次训练时时间序列上是连续的

**Comment by 11wwAD** [comment]
>

**Comment by 11wwAD** [comment]
> > 是这样的，我有多个多变量时间序列，单个时间序列200个数据点左右，在时间上是连续的，但是每个时间序列与每个时间序列之间不存在时间上的连续性。例如，一个样本为一个CSV文件，200行（序列长度），17列（特征数），拥有300个这样的CSV文件，每个CSV文件是相互独立的。请问这样的数据集，我该如何应用，期望各位大佬的解答
> 
> 我也做类似的预测，可以试试在DataLoader中使用sampler参数实现

首先十分感谢您的回答，那我是不是，得先把这些csv文件合并成一个csv文件，然后sampler参数我该怎么选呢，可以稍微具体的讲一下吗

**Comment by Sakura-Qy** [comment]
可以合成一个文件再导入python，但更建议通过python处理多个文件，提取数据，制作自己的数据。sampler参数是传入一个迭代器，DataLoader会根据你的迭代器来选择数据，形成一个batch，更具体的建议去看pytorch的文档

**Comment by 11wwAD** [comment]
> 可以合成一个文件再导入python，但更建议通过python处理多个文件，提取数据，制作自己的数据。sampler参数是传入一个迭代器，DataLoader会根据你的迭代器来选择数据，形成一个batch，更具体的建议去看pytorch的文档

是不是可以这样理解，首先通过Python处理多个文件，每个csv文件可以制作一部分训练集，最后将所有制作好的数据集传入DataLoader。但是有一点想不通的就是，我这个制作好的数据集，将以什么样的形式存储在硬盘里，便于下一步的读取操作

**Comment by Sakura-Qy** [comment]
按照原程序的是采用pd.read_csv()读取数据，所有可以使用csv格式，当然也可以按照pkl的形式，只需要写自己的Dataset_Custom类就行

**Comment by KEEPASBEGINNER** [comment]
您好，这个问题对我有非常大的帮助，感谢！但我还有一个问题不太明白。请问分批导入多个cvs进行模型训练，在时间编码上是否会自动连续处理？比如说这个例子中，我有多个水下机器人同时采集数据，实际开始时间与实际结束时间分别为2023-7-27 10:35:00与2023-7-27 10:40:00。但训练完第一个cvs训练集后，模型训练第二个cvs训练时，开始时间会是实际开始时间(2023-7-27 10:35:00)吗？还是会继续从2023-7-27 10:40:00向后训练？
