### ISSUE TITLE
关于输出的preds和trues数据尺度问题

### ISSUE THREAD

**Issue by IrisHerro** [zhouhaoyi/Informer2020#465]
作者您好，我想请问一下，输出的pred.npy和true.npy里的数据尺度需要进行什么还原操作吗？不管是用您的数据集还是用我自己的数据集，输出的pred.npy和true.npy画图时数值似乎都不是原始数据的尺度，并且似乎不是因为没有反归一的原因，因为我自己数据集的输出数值有些是大于一的......

**Comment by YUAN0620** [comment]
您好，冒昧打扰，我也想请教一下这个问题，请问您有解决了吗

**Comment by IrisHerro** [comment]
> 您好，冒昧打扰，我也想请教一下这个问题，请问您有解决了吗
还没有 :( ，如果以后你解决了的话希望可以交流一下

**Comment by IrisHerro** [comment]
目前还没有，这个问题我看挺久了，源码里是有反归一这一步操作的，实在是不知道哪里出了问题……
如果后面你解决了的话希望可以交流一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月5日(周日) 下午2:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465)




 
您好，冒昧打扰，我也想请教一下这个问题，请问您有解决了吗

**Comment by YUAN0620** [comment]
好的，谢谢。

**Comment by MountVoom** [comment]
您运行代码时候有--inverse吗，或者能提供更详细的问题描述吗

**Comment by IrisHerro** [comment]
我看源码的exp_informer里是有inverse的步骤的，所以没有自己做额外的inverse

但是我在输出的时候发现数据变成了奇怪的维度，范围大概在0到3之间，而我的数据集尺度大概是在1.4到1.7之间的……这个尺度差距不像是因为没有反归一，不知道问题出在哪里

&nbsp;


iris&nbsp;herro
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Siyang ***@***.***&gt;; 
发送时间: 2023年3月14日(星期二) 中午1:23
收件人: ***@***.***&gt;; 
抄送: "iris ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465)





 
您运行代码时候有--inverse吗，或者能提供更详细的问题描述吗

**Comment by YUAN0620** [comment]
> 我看源码的exp_informer里是有inverse的步骤的，所以没有自己做额外的inverse 但是我在输出的时候发现数据变成了奇怪的维度，范围大概在0到3之间，而我的数据集尺度大概是在1.4到1.7之间的……这个尺度差距不像是因为没有反归一，不知道问题出在哪里 &nbsp; iris&nbsp;herro ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Siyang ***@***.***&gt;; 发送时间: 2023年3月14日(星期二) 中午1:23 收件人: ***@***.***&gt;; 抄送: "iris ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465) 您运行代码时候有--inverse吗，或者能提供更详细的问题描述吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个真实值，我是把inverse那个参数改成Ture，就可以了，要自己改一下，它default值是False

**Comment by IrisHerro** [comment]
好的，问题解决了，非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月14日(周二) 下午5:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465)




  
我看源码的exp_informer里是有inverse的步骤的，所以没有自己做额外的inverse 但是我在输出的时候发现数据变成了奇怪的维度，范围大概在0到3之间，而我的数据集尺度大概是在1.4到1.7之间的……这个尺度差距不像是因为没有反归一，不知道问题出在哪里 &nbsp; iris&nbsp;herro @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Siyang @.&gt;; 发送时间: 2023年3月14日(星期二) 中午1:23 收件人: @.&gt;; 抄送: "iris @.&gt;; @.&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465) 您运行代码时候有--inverse吗，或者能提供更详细的问题描述吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
这个真实值，我是把inverse那个参数改成Ture，就可以了，要自己改一下，它default值是False

**Comment by YUAN0620** [comment]
> 好的，问题解决了，非常感谢！
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月14日(周二) 下午5:30 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465) 我看源码的exp_informer里是有inverse的步骤的，所以没有自己做额外的inverse 但是我在输出的时候发现数据变成了奇怪的维度，范围大概在0到3之间，而我的数据集尺度大概是在1.4到1.7之间的……这个尺度差距不像是因为没有反归一，不知道问题出在哪里 &nbsp; iris&nbsp;herro @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Siyang @.&gt;; 发送时间: 2023年3月14日(星期二) 中午1:23 收件人: @.&gt;; 抄送: "iris @.&gt;; @.&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465) 您运行代码时候有--inverse吗，或者能提供更详细的问题描述吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 这个真实值，我是把inverse那个参数改成Ture，就可以了，要自己改一下，它default值是False — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我有些其他问题想请教，是关于loss：nan的，方便的话可以加个qq（651667985）细聊吗？万分感谢！

**Comment by IrisHerro** [comment]
哈哈哈哈我也就是本科生写毕业论文才开始了解这个算法的，可能也帮不上太多忙，可以先邮件联系看看问题呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月14日(周二) 晚上8:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465)




  
好的，问题解决了，非常感谢！
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年3月14日(周二) 下午5:30 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465) 我看源码的exp_informer里是有inverse的步骤的，所以没有自己做额外的inverse 但是我在输出的时候发现数据变成了奇怪的维度，范围大概在0到3之间，而我的数据集尺度大概是在1.4到1.7之间的……这个尺度差距不像是因为没有反归一，不知道问题出在哪里 &nbsp; iris&nbsp;herro @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Siyang @.&gt;; 发送时间: 2023年3月14日(星期二) 中午1:23 收件人: @.&gt;; 抄送: "iris @.&gt;; @.&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于输出的preds和trues数据尺度问题 (Issue #465) 您运行代码时候有--inverse吗，或者能提供更详细的问题描述吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 这个真实值，我是把inverse那个参数改成Ture，就可以了，要自己改一下，它default值是False — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我有些其他问题想请教，是关于loss：nan的，方便的话可以加个qq（651667985）细聊吗？万分感谢！
