### ISSUE TITLE
求解，用Pycharm在进行Colab实例的预测的时候，为什么报错predict函数出现AttributeError

### ISSUE THREAD

**Issue by jiyunfei12138** [zhouhaoyi/Informer2020#466]
模型能跑完，好像是result文件夹中无法生成real_prediction.npy文件，只有metrics,pred,true,具体报错如下
![image](https://user-images.githubusercontent.com/106957845/223063773-07d4ecc0-cf2c-434c-b9a4-0a4b125b4f21.png)

**Comment by YUAN0620** [comment]
你好，应该是在pycharm模型训练之前将参数'--do_predict'由'store_true'变为'store_false'，这样在代码运行完以后results文件夹中会多出一个文件real_prediction.npy
我想请教一下，最后绘制出来的图片的纵坐标怎样得到真实值呢？如您有解决方法，望交流一下，谢谢！

**Comment by MountVoom** [comment]
如果需要得到真实值，在训练的时候加上--inverse就可以了，可以看一下inverse这个参数

不修改'store_ture'也可以，只需要训练的命令加上--do_predict

**Comment by K2333IWI** [comment]
我第一次用colab，请问 这样该怎么解决鸭？
![image](https://user-images.githubusercontent.com/93861298/225195920-4b2d0d62-e417-4a45-a247-f8823868452d.png)

**Comment by YUAN0620** [comment]
> 我第一次用colab，请问这样应该怎么解决决定鸭？ ![图像](https://user-images.githubusercontent.com/93861298/225195920-4b2d0d62-e417-4a45-a247-f8823868452d.png)

要先导入github里面作者的源码，然后切换根目录

**Comment by jiyunfei12138** [comment]
我之前出现那个报错应该是pandas版本和作者的一样但是和本机不兼容，升级了之后就解决了，--inverse反转输出结果应该就是真实值，但是我用的数据集结果不太理想可能还要调整一下参数
