### ISSUE TITLE
预测问题+参数问题

### ISSUE THREAD

**Issue by codeMa99** [zhouhaoyi/Informer2020#467]
作者您好，想请教两个基础的问题
1.预测问题
假设我的数据一共有5列。第一列是日期，我想用2--4列来预测第五列，但是debug过程，我发现总是用2---5列来预测第五列，这个需要修改哪些部分？还望指教
2.des参数问题
这个参数有哪些备选选项？目前我只发现两个备选项。一个‘exp’和‘test’，这两个参数的含义是什么呢？对模型训练的效果有作用吗

**Comment by Xjt128** [comment]
改一下参数

**Comment by codeMa99** [comment]
> 改一下参数

您好，是要修改parser.add_argument('--cols'。。。。)这个参数吗，具体修改成什么呢？
还需要修改代码其他部分吗？

**Comment by MountVoom** [comment]
--des参数是对这次实验的描述，对训练没有作用

用2--4列预测第五列是指什么呢？第五列的信息不输入的话看起来更像一个回归问题？如果要改可以试着修改一下dataloader部分

**Comment by codeMa99** [comment]
> --des参数是对这次实验的描述，对训练没有作用
> 
> 用2--4列预测第五列是指什么呢？第五列的信息不输入的话看起来更像一个回归问题？如果要改可以试着修改一下dataloader部分

谢谢大佬
我想用2--4列作为特征，第5列为目标。我自己试试改改dataloader，非常感谢回复
