### ISSUE TITLE
结果输出有问题

### ISSUE THREAD

**Issue by LCY000117** [zhouhaoyi/Informer2020#468]
我用np.savetxt("True", true.squeeze(), delimiter=',')保存结果，跟我真实数据完全对不上

**Comment by MountVoom** [comment]
可能没有将数据反归一化？能否提供更详细的问题描述呢

**Comment by LCY000117** [comment]
![09d55660bdd3da336c3cfeed55ad8ff](https://user-images.githubusercontent.com/127083757/224911965-3bc65090-c31e-44d3-bd91-55c4c3134301.png)
这个结果为什么会这样，正常吗？train loss下降，Vali Loss反而上升，test loss不下降

**Comment by MountVoom** [comment]
是正常的，会有一些波动，也可能是过拟合了，代码会通过earlystop来控制。

**Comment by Seb5Vet** [comment]
> 可能没有将数据反归一化？能否提供更详细的问题描述呢

数据怎么才能反归一化啊，把inverse变成true的话损失函数特别大
