### ISSUE TITLE
训练自己数据集的问题

### ISSUE THREAD

**Issue by ArcMonDol** [zhouhaoyi/Informer2020#469]
![$3UUQ7X(G}IG~6QCCL%M235](https://user-images.githubusercontent.com/127604677/224486146-32969dae-25ab-407c-9385-6e7758ea4188.png)
![1LVCCTP_`O7 A56@S~2${(7](https://user-images.githubusercontent.com/127604677/224486151-6b5bb964-01af-478c-90e3-ec89793281ec.png)
我的数据集时间间隔是15min，只在main_informer.py里修改了，还有哪里需要修改吗

**Comment by ArcMonDol** [comment]
![image](https://user-images.githubusercontent.com/127604677/224494118-dff96789-3f1a-4786-8177-cb1cfae39732.png)
调试错误在这里

**Comment by ArcMonDol** [comment]
上面的错误把15min改成t就不报错了。
我遇到的新问题:
跑数据时第一轮loss：nan，调试后错误在这里。

**Comment by ArcMonDol** [comment]
现在调好了，mse很高,输入18个（风力、湿度等），输出电力，3万多条数据
我的间隔是15min，预测一天是96条，请问该如何降低mse值
![46MCYIMTZYVH@M}O2LHHM9](https://user-images.githubusercontent.com/127604677/224525682-c8d307eb-f694-428a-a9ab-51eccf3991df.png)
![image](https://user-images.githubusercontent.com/127604677/224525690-9ec8c859-b7a0-45e0-a375-8731fc041358.png)
![image](https://user-images.githubusercontent.com/127604677/224525756-69e2ca91-8f1f-42da-b0da-08694d6b2f4b.png)

**Comment by oushilin** [comment]
我想问一下是改成15t还是只有t呢，我的数据集间隔也是15分钟一次

**Comment by ArcMonDol** [comment]
> 我想问一下是改成15t还是只有t呢，我的数据集间隔也是15分钟一次
> 
> I would like to ask whether to change to 15t or only T, my data set interval is also 15 minutes

只有t

**Comment by oushilin** [comment]
我看help里说t是minutely每分钟的；
改成15t程序也可以正常运行

**Comment by MountVoom** [comment]
出现loss可能是数据归一化的时候出现了loss，可以检查一下这一部分或者检查一下数据

**Comment by MountVoom** [comment]
> 现在调好了，mse很高,输入18个（风力、湿度等），输出电力，3万多条数据 我的间隔是15min，预测一天是96条，请问该如何降低mse值 ![46MCYIMTZYVH@M}O2LHHM9](https://user-images.githubusercontent.com/127604677/224525682-c8d307eb-f694-428a-a9ab-51eccf3991df.png) ![image](https://user-images.githubusercontent.com/127604677/224525690-9ec8c859-b7a0-45e0-a375-8731fc041358.png) ![image](https://user-images.githubusercontent.com/127604677/224525756-69e2ca91-8f1f-42da-b0da-08694d6b2f4b.png)

试着调整一下参数？可以根据数据的性质特征等设置参数

**Comment by YUAN0620** [comment]
> 出现loss可能是数据归一化的时候出现loss，可以检查一下这一部分或者检查一下数据

感谢回复！数据中有大量0值，但是0值表示的是当时节点没有降雨，数据归一化时出现loss:nan？请问作者具体应该咋操作呢？数据集截图如下
![04b95ab352a72b5974043b524b4735a](https://user-images.githubusercontent.com/83199494/224907513-5161ef52-a8c8-402d-bc4b-0084af8dd22a.png)
[hkws_qixiang.csv](https://github.com/zhouhaoyi/Informer2020/files/10964544/hkws_qixiang.csv)

**Comment by ArcMonDol** [comment]
![image](https://user-images.githubusercontent.com/127604677/224969503-ad29672d-0b5b-42ed-ab8a-e0730c8ce370.png)
预测中的错误：读取训练好的checkpoint，我的数据是1列date+17列输入+1列输出组成，batch_X中存放的权重是17列输入+1列输出的，不是date+17列输入的{batch_X的倒数第二列是nan，是17列输入的最后一列}，我多次训练后这一列依旧是nan，未解决，可能是训练数据的问题

**Comment by ArcMonDol** [comment]
> > 出现loss可能是数据归一化的时候出现loss，可以检查一下这一部分或者检查一下数据
> 
> 感谢回复！数据中有大量0值，但是0值表示的是当时节点没有降雨，数据归一化时出现loss:nan？请问作者具体应该咋操作呢？数据集截图如下 ![04b95ab352a72b5974043b524b4735a](https://user-images.githubusercontent.com/83199494/224907513-5161ef52-a8c8-402d-bc4b-0084af8dd22a.png) [hkws_qixiang.csv](https://github.com/zhouhaoyi/Informer2020/files/10964544/hkws_qixiang.csv)

https://www.bilibili.com/video/BV1mK4y1b73Y/?spm_id_from=333.337.search-card.all.click
用这个删除空值试试，我的数据也有很多0，不会报nan

**Comment by YUAN0620** [comment]
> > > 出现loss可能是数据归一化的时候出现loss，可以检查一下这一部分或者检查一下数据
> > 
> > 
> > 感谢回复！数据中有大量0值，但是0值表示的是当时节点没有降雨，数据归一化时出现loss:nan？请问作者具体应该咋操作呢？数据集截图如下 ![04b95ab352a72b5974043b524b4735a](https://user-images.githubusercontent.com/83199494/224907513-5161ef52-a8c8-402d-bc4b-0084af8dd22a.png) [hkws_qixiang.csv](https://github.com/zhouhaoyi/Informer2020/files/10964544/hkws_qixiang.csv)
> 
> https://www.bilibili.com/video/BV1mK4y1b73Y/?spm_id_from=333.337.search-card.all.click 用这个删除空值试试，我的数据也有很多0，不会报nan

这个0表示这个时间点的降雨量为0，就是没下雨，不是空值的意思，这种情况咋办呢

**Comment by YUAN0620** [comment]
> > > 出现loss可能是数据归一化的时候出现loss，可以检查一下这一部分或者检查一下数据
> > 
> > 
> > 感谢回复！数据中有大量0值，但是0值表示的是当时节点没有降雨，数据归一化时出现loss:nan？请问作者具体应该咋操作呢？数据集截图如下 ![04b95ab352a72b5974043b524b4735a](https://user-images.githubusercontent.com/83199494/224907513-5161ef52-a8c8-402d-bc4b-0084af8dd22a.png) [hkws_qixiang.csv](https://github.com/zhouhaoyi/Informer2020/files/10964544/hkws_qixiang.csv)
> 
> https://www.bilibili.com/video/BV1mK4y1b73Y/?spm_id_from=333.337.search-card.all.click 用这个删除空值试试，我的数据也有很多0，不会报nan

方便的话可以加个qq（651667985）细聊吗？万分感谢！

**Comment by YUAN0620** [comment]
> > > 出现loss可能是数据归一化的时候出现loss，可以检查一下这一部分或者检查一下数据
> > 
> > 
> > 感谢回复！数据中有大量0值，但是0值表示的是当时节点没有降雨，数据归一化时出现loss:nan？请问作者具体应该咋操作呢？数据集截图如下 ![04b95ab352a72b5974043b524b4735a](https://user-images.githubusercontent.com/83199494/224907513-5161ef52-a8c8-402d-bc4b-0084af8dd22a.png) [hkws_qixiang.csv](https://github.com/zhouhaoyi/Informer2020/files/10964544/hkws_qixiang.csv)
> 
> https://www.bilibili.com/video/BV1mK4y1b73Y/?spm_id_from=333.337.search-card.all.click 用这个删除空值试试，我的数据也有很多0，不会报nan

方便的话可以加个qq（651667985）细聊吗？万分感谢！

**Comment by ArcMonDol** [comment]
![image](https://user-images.githubusercontent.com/127604677/225187806-c8d9a2de-d98b-45d4-9710-fb4df20f29ff.png)
![image](https://user-images.githubusercontent.com/127604677/225187849-6e944dcb-e1e5-4068-b722-381fdb644dea.png)
![image](https://user-images.githubusercontent.com/127604677/225187929-26c287d5-15c0-4523-9aa9-ddd739210869.png)

现在跑自己预测的问题：预测值是归一化后的。
在其他问题评论的方法：inverse改成true，调换seq_y逻辑，都没有效果

**Comment by ArcMonDol** [comment]
![{V C05_W)MW5RUU881I6`7R](https://user-images.githubusercontent.com/127604677/225242273-846c1736-ed37-46b6-a352-fac310de20cc.png)
在main-informer里把inverse改成true后训练，得到正常值
![7CJ3T Q($PUQIBVBTG%HO_M](https://user-images.githubusercontent.com/127604677/225242252-e7aa5a42-e908-4e3d-9a2e-59ef8234e313.png)
![image](https://user-images.githubusercontent.com/127604677/225242603-3cb6c171-069a-41a7-ae29-921f64c36f24.png)
在predict里用模型跑，得到的还是归一化后的，设置inverse也是true

**Comment by ypsysz** [comment]
> 现在调好了，mse很高,输入18个（风力、湿度等），输出电力，3万多条数据 我的间隔是15min，预测一天是96条，请问该如何降低mse值 ![46MCYIMTZYVH@M}O2LHHM9](https://user-images.githubusercontent.com/127604677/224525682-c8d307eb-f694-428a-a9ab-51eccf3991df.png) ![image](https://user-images.githubusercontent.com/127604677/224525690-9ec8c859-b7a0-45e0-a375-8731fc041358.png) ![image](https://user-images.githubusercontent.com/127604677/224525756-69e2ca91-8f1f-42da-b0da-08694d6b2f4b.png)

我也是运行自己的数据集，出现nan问题，请问学长你的是从哪个方面修改成功的？

**Comment by ArcMonDol** [comment]
![image](https://user-images.githubusercontent.com/127604677/225833316-d7d91f86-7cbb-43fc-9b03-1f97719aca21.png)
预测也改好了，感谢作者分享

**Comment by boris-lb** [comment]
> ![image](https://user-images.githubusercontent.com/127604677/225833316-d7d91f86-7cbb-43fc-9b03-1f97719aca21.png) 预测也改好了，感谢作者分享

大佬，我的loss一直下不去是什么情况呀，我用的是1date+28输入，预测后面时间段的这28个输入值：Epoch: 919, Steps: 153 | Train Loss: 838.2778292 Vali Loss: 21938.6875000 Test Loss: 12767.0908203

**Comment by boris-lb** [comment]
> ![image](https://user-images.githubusercontent.com/127604677/225833316-d7d91f86-7cbb-43fc-9b03-1f97719aca21.png) 预测也改好了，感谢作者分享

大佬，我的loss一直下不去是什么情况呀，我用的是1date+28输入，预测后面时间段的这28个输入值，有什么可能存在的原因嘛？数据类似这样：
![image](https://github.com/zhouhaoyi/Informer2020/assets/39977498/ccac4398-d678-429e-848d-d1f9c4dfeaa4)

log如下：
```
Epoch: 915 cost time: 8.273383140563965
Epoch: 915, Steps: 153 | Train Loss: 838.6419534 Vali Loss: 22288.1269531 Test Loss: 13408.7802734
EarlyStopping counter: 261 out of 3
Updating learning rate to 7.220777503459319e-280
	iters: 100, epoch: 916 | loss: 1423.6833496
	speed: 0.0943s/iter; left time: 1217.0741s
Epoch: 916 cost time: 8.255328178405762
Epoch: 916, Steps: 153 | Train Loss: 846.5157211 Vali Loss: 22320.8281250 Test Loss: 12989.9003906
EarlyStopping counter: 262 out of 3
Updating learning rate to 3.6103887517296593e-280
	iters: 100, epoch: 917 | loss: 906.3619995
	speed: 0.1027s/iter; left time: 1309.3628s
Epoch: 917 cost time: 8.958439350128174
Epoch: 917, Steps: 153 | Train Loss: 838.1002086 Vali Loss: 22116.3066406 Test Loss: 12964.9941406
EarlyStopping counter: 263 out of 3
Updating learning rate to 1.8051943758648297e-280
	iters: 100, epoch: 918 | loss: 870.8149414
	speed: 0.1028s/iter; left time: 1295.4325s
Epoch: 918 cost time: 8.797924041748047
Epoch: 918, Steps: 153 | Train Loss: 844.1663699 Vali Loss: 21629.6132812 Test Loss: 13250.8154297
EarlyStopping counter: 264 out of 3
Updating learning rate to 9.025971879324148e-281
	iters: 100, epoch: 919 | loss: 655.4920044
	speed: 0.0951s/iter; left time: 1183.3071s
Epoch: 919 cost time: 8.036654949188232
Epoch: 919, Steps: 153 | Train Loss: 838.2778292 Vali Loss: 21938.6875000 Test Loss: 12767.0908203
EarlyStopping counter: 265 out of 3
Updating learning rate to 4.512985939662074e-281
	iters: 100, epoch: 920 | loss: 1074.1713867
	speed: 0.1022s/iter; left time: 1256.3354s
Epoch: 920 cost time: 8.968003749847412
Epoch: 920, Steps: 153 | Train Loss: 839.0584882 Vali Loss: 22185.9843750 Test Loss: 13146.6054688
EarlyStopping counter: 266 out of 3
Updating learning rate to 2.256492969831037e-281
	iters: 100, epoch: 921 | loss: 1094.3326416
	speed: 0.1049s/iter; left time: 1273.4197s
Epoch: 921 cost time: 8.731737613677979
Epoch: 921, Steps: 153 | Train Loss: 840.0161280 Vali Loss: 22073.3750000 Test Loss: 12772.1591797
EarlyStopping counter: 267 out of 3
Updating learning rate to 1.1282464849155185e-281
	iters: 100, epoch: 922 | loss: 593.5154419
	speed: 0.1031s/iter; left time: 1236.0055s
Epoch: 922 cost time: 8.848804235458374
Epoch: 922, Steps: 153 | Train Loss: 838.9144155 Vali Loss: 21783.1914062 Test Loss: 13003.1787109
EarlyStopping counter: 268 out of 3
Updating learning rate to 5.641232424577593e-282
	iters: 100, epoch: 923 | loss: 772.8519897
	speed: 0.1005s/iter; left time: 1189.3597s
Epoch: 923 cost time: 8.786641836166382
Epoch: 923, Steps: 153 | Train Loss: 838.6477099 Vali Loss: 21692.1230469 Test Loss: 12811.6904297
EarlyStopping counter: 269 out of 3
Updating learning rate to 2.8206162122887963e-282
	iters: 100, epoch: 924 | loss: 632.0617676
	speed: 0.1052s/iter; left time: 1229.2591s
Epoch: 924 cost time: 9.02480936050415
Epoch: 924, Steps: 153 | Train Loss: 836.1907428 Vali Loss: 21822.7792969 Test Loss: 12966.8369141
EarlyStopping counter: 270 out of 3
Updating learning rate to 1.4103081061443982e-282
	iters: 100, epoch: 925 | loss: 1023.4541626
	speed: 0.0979s/iter; left time: 1128.2653s

```
