### ISSUE TITLE
OOM后继续训练

### ISSUE THREAD

**Issue by lzmax888** [zhouhaoyi/Informer2020#47]
首先感谢您的分享。

我在训练你的模型时，使用了不同的参数和数据集。有时候训练到一半，会出现OOM，不知道能不能接着上一个checkpoint，继续train这个model，不用重新开始？

我调用train(settings)会重新开始训练。

**Comment by cookieminions** [comment]
感谢你对我们工作的关注。

我们的代码目前并没有提供在OOM之后继续训练的功能，不过你可以尝试修改`exp/exp_informer.py`下的代码，加载上一次训练保存的checkpoint.pth（只要参数一致，则会生成相同的settings来定位保存模型文件的位置）。

此外可以检查数据中是否有nan数据，或者调小训练参数中的batch_size（默认是32）来避免出现OOM。

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion, I will close the issue now.
