### ISSUE TITLE
单变量时间序列预测，训练集损失很低，验证集损失一直是nan，测试集损失很高

### ISSUE THREAD

**Issue by goodlucky111** [zhouhaoyi/Informer2020#474]
单变量时间序列预测，训练集损失很低，验证集损失一直是nan，测试集损失很高

**Comment by WE1321254775** [comment]
我也要用单变量做预测，试了informer，autoformer，FEDfor可以加个联系方式交流吗

**Comment by luxury-jr** [comment]
> 单变量时间顺序列表预测，训练集损损失很低，试验证明集损损失一直是nan，测试集损损失很高

**Comment by luxury-jr** [comment]
> 单变量时间顺序列表预测，训练集损损失很低，试验证明集损损失一直是nan，测试集损损失很高

我的也发现了nan，后面发现有一些数据是空白的，没有有价值的原因

**Comment by luxury-jr** [comment]
> 单变量时间序列预测，训练集损失很低，验证集损失一直是nan，测试集损失很高
我的遇到了loss为nan的情况，后面发现有一些数据是空白，没有值的原因

**Comment by yangzhan111** [comment]
交流一下 您好

**Comment by KeYanMingGong** [comment]
Hello, have you solved this problem? My data is also this problem

**Comment by gaochonghan** [comment]
可以检查一下验证集和测试集，是否有缺失值，是否格式有问题等

**Comment by gaochonghan** [comment]
另外测试集效果不好可能是过拟合导致的，可以在每个epoch之后看一下测试集的loss。可以通过调整early stop参数避免过拟合

**Comment by notyourcai** [comment]
您好，可以请教一下怎么做单变量的预测吗
