### ISSUE TITLE
args = parser.parse_args()报错怎么办

### ISSUE THREAD

**Issue by Lionss423** [zhouhaoyi/Informer2020#477]
<img width="757" alt="截屏2023-03-23 16 16 57" src="https://user-images.githubusercontent.com/88503880/227143449-b8a80c98-7c42-47e3-9135-2b80b2acea7e.png">

**Comment by SainScarlet** [comment]
`parser.add_argument('--model', type=str, default='informer', help='model of experiment, options: [informer, informerstack, informerlight(TBD)]')
parser.add_argument('--data', type=str, default='WTH', help='data')`

模型和数据中去掉required=true

**Comment by gaochonghan** [comment]
model 和 data参数为必须参数
