### ISSUE TITLE
样本分割的问题

### ISSUE THREAD

**Issue by caesaryang06** [zhouhaoyi/Informer2020#478]
在分割样本的时候 ETT分割方式【12/4/4】；ECL分割方式【15/3/4】; Weather分割方式【28/10/10】而提供的自定义分割方式是按照比例进行分割的；基于此我是不是可以认为不同的样本数据分割方式是不同的 ；您在分割样本的时候是有什么考量呢  我们又该如何划分自己的样本数据；以期达到一个好的预期效果

**Comment by gaochonghan** [comment]
一般来说数据集分割主要和数据集容量有关和数据周期性有关。一般来说，周期性越强，数据集越大，训练集占比越大。具体分割比例以实验为主
