### ISSUE TITLE
set --freq to ’4h‘, 上报 "KeyError: '4h'"

### ISSUE THREAD

**Issue by Lunar-123** [zhouhaoyi/Informer2020#483]
如果数据集是每隔4个小时的监测样本，在--freq的时候是否就不可以再使用'h'的参数了，如果需要定义比如4h这样的参数，我理解需要自己代码实现时间戳这块的处理？

**Comment by keyanxiaoba** [comment]
您好，请问您这个4h怎么实现的

**Comment by Lunar-123** [comment]
detail_freq设置为4h
