### ISSUE TITLE
如何对时间间隔为1s的自定义序列数据进行预测

### ISSUE THREAD

**Issue by MaleicAcid** [zhouhaoyi/Informer2020#49]
感谢大佬们做了如此惊艳的工作！

我想问一下，我的自定义数据集的序列时间间隔是1s, 我看到freq选项好像仅支持到分钟，我要怎么修改才能用于对间隔为秒的序列进行预测呢。

另外我想问一下，预测时，输入的序列可以是不定长度的吗，比如预测时，不论是输入前60秒还是前40秒的轨迹，都固定预测后续60秒的轨迹
提前感谢大佬 :)

**Comment by cookieminions** [comment]
如果你使用的是秒级别的数据，我的建议是你可以增加一个 class SecondOfMinute，然后返回index.second/59.0-0.5，将数据映射到-0.5-0.5之间

此外在features_by_offsets中增加一个offset.Second，其中使用的特征可以由你自己定义，如果你只想使用秒而不想使用其他诸如月或者周的信息话，你可以只留下SecondOfMinute，否则可以在offset.Minute的基础上增加SecondOfMinute，这样就是6维时间特征

需要注意的是，如果你自定义的offset.Second包括了[SecondOfMinute,MinuteOfHour,HourOfDay,DayOfWeek,DayOfMonth,DayOfYear]的话，你还需要在embed.py中的timeF embedding的freq map中增加一个 's':6，因为这是6维的时间特征，如果你只使用了SecondOfMinute，你需要在freq map中增加's':1，然后在参数中使用freq='s'

关于输入的序列长度问题，Informer模型参数其实并没有用到seq_len，虽然我们的实验是固定长度的输入，但是在实际使用中，只要你修改data_loader中的数据加载方式，模型是可以接收不通长度的输入的

**Comment by MaleicAcid** [comment]
太感谢大佬了！还是第一次炼丹，想再请教一下，示例里的都是每次只用了一个数据集，
如果我采集到小车的早上，中午和晚上一共3段轨迹，我想让模型学习前两段轨迹，并在第三段轨迹上进行预测，是否意味着我需要遍历./data/trainData/1.csv, 2.csv  里的这两个csv文件然后训练这个模型两次？

**Comment by MaleicAcid** [comment]
太感谢大佬了！我还想问一下，如果我的数据集里有多个csv文件，是应该把exp_informer.py里def _get_data(self, flag): 方法的原dataset赋值语句进行替换吗，类似这样
`class Exp_Informer(Exp_Basic):
    ......
    def _get_data(self, flag):
        # 原来的
        # data_set = Data(root_path=args.root_path, data_path=args.data_path,...)
        # 我想替换成一个ConcatDataset()
        mydata_sets = []
        for file_name in args.file_name_list:
                 mydata_sets.append(Data(root_path=args.root_path, data_path=file_name ,...))
        data_set = ConcatDataset(mydata_sets)
`
大佬，是应该在这里像这样修改吗

**Comment by cookieminions** [comment]
我想使用多个csv文件应该有多种方式，如果你是想要用早中的数据预测晚的数据，那么使用ConcatDataset可能还需要修改`data/data_loader.py`中的相关Dataset，因为目前代码中不同的flag(trian, vali, test)加载出来的是单个csv数据的不同部分，你可以尝试丢掉`data/data_loader.py`中Dataset的flag，让他加载csv数据中的全部数据，然后在`_get_data`中根据flag选择不同的csv文件

**Comment by halozyhgo** [comment]
我想将时间间隔更改为15min请问在那个地方修改？
