### ISSUE TITLE
the weather dataset

### ISSUE THREAD

**Issue by jerryuestc** [zhouhaoyi/Informer2020#50]
The weather dataset's link on your paper has been unavailable for sometime. Is there other ways to download the data or is it possible for you to provide the weather data on github? Thanks

**Comment by cookieminions** [comment]
The link of weather data in our paper is from here: https://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/quality-controlled-local-climatological-data-qclcd, but now it's invalid.

But you can still get LCD data from NOAA's dataset, here is the link: https://www.ncei.noaa.gov/data/local-climatological-data/.

**Comment by jerryuestc** [comment]
Thank you for your prompt reply. However, from the second link https://www.ncei.noaa.gov/data/local-climatological-data/, we can see that there have been access and archive data and in the access data, there are many dozens of csv files corresponding to one year. So could you provide any detail on which data is exactly used in your paper. Thank you very much.

**Comment by cookieminions** [comment]
We use the data with WBAN==72462703011 and date from 2010-01-01 00:00 to 2013-12-31 23:00, and select features [Visibility, DryBulbFarenheit, DryBulbCelsius, WetBulbFarenheit, DewPointFarenheit, DewPointCelsius, RelativeHumidity, WindSpeed, WindDirection, StationPressure, Altimeter, WetBulbCelsius]. They are all hourly data and we use the previous value to fill the missing data.

**Comment by cuiyuebing** [comment]
https://www.ncei.noaa.gov/data/local-climatological-data/ The dataset in above link doesn't seem to be perfectly the same as the dataset you use, especially in sampling rate. For example, the first four time-stamps of the year 2010 are 2010-01-01T00:12:00, 2010-01-01T00:32:00, 2010-01-01T00:54:00 and 2010-01-01T01:12:00, which is basically saying the data was not hourly sampled. To obtain hourly data, did you also first get raw data like this and then preprocessed it? If so, it would be appreciated if you could let me know how to implement the preprocessing. Thanks!
