### ISSUE TITLE
关于自己的数据找不到date列的问题

### ISSUE THREAD

**Issue by Chao2MAX** [zhouhaoyi/Informer2020#505]
使用自己数据时，有date这一项，但是代码运行到提取date时报错说list.remove(x): x not in list。请问是数据的问题吗？
![image](https://user-images.githubusercontent.com/129569033/234011891-1a340c25-e0dc-4ec3-920c-1715559765b3.png)
![image](https://user-images.githubusercontent.com/129569033/234011938-f9dba192-36d3-446f-a7ab-87368df76779.png)

**Comment by Chao2MAX** [comment]
时间单位是秒（S）

**Comment by wisest-cui** [comment]
别的数据的date都是按照 “2020.01.02”等python可以处理的datetime的格式来的

**Comment by Chao2MAX** [comment]
> 

谢谢,把date处理了之后，问题解决了~

**Comment by hyw-freeway** [comment]
请问您把数据处理成什么样啦？我的也是s为单位个格式

**Comment by wisest-cui** [comment]
date裂的数据应该是python里datetime库可以识别的字符串。类似20220506 08:00:04 这种。当然有很多格式可以自己查查



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月5日(周五) 晚上9:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 关于自己的数据找不到date列的问题 (Issue #505)




 
请问您把数据处理成什么样啦？我的也是s为单位个格式

**Comment by Chao2MAX** [comment]
> 请问您把数据处理成什么样啦？我的也是s为单位个格式

![image](https://user-images.githubusercontent.com/129569033/236609430-27e990ec-cfb1-4353-9058-ef75d2b5fb4f.png)
处理成这样子就可以了

**Comment by hyw-freeway** [comment]
谢谢，但是我有个疑问，我的数据时间间隔是0.00001s，这种应该不能改成图上这种吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月6日(周六) 下午3:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhouhaoyi/Informer2020] 关于自己的数据找不到date列的问题 (Issue #505)




  
请问您把数据处理成什么样啦？我的也是s为单位个格式
  

 处理成这样子就可以了

**Comment by Chao2MAX** [comment]
> 谢谢，但是我有个疑问，我的数据时间间隔是0.00001s，这种应该不能改成图上这种吧？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年5月6日(周六) 下午3:19 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zhouhaoyi/Informer2020] 关于自己的数据找不到date列的问题 (Issue #505) 请问您把数据处理成什么样啦？我的也是s为单位个格式 处理成这样子就可以了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

是的，最小频率是1s，但是也可以处理，只不过数据量应该很大，如果你的数据有10几秒的话。

**Comment by 721chenjie** [comment]
为啥我处理了还是没用 我预测一列就不会出现这个报错 预测两列就有这个报错了

**Comment by 77coming** [comment]
我处理了也还是不行呢
