### ISSUE TITLE
The GroundTruth is a straight line when i use my dataset,why and how to fix it?

### ISSUE THREAD

**Issue by roeyjob** [zhouhaoyi/Informer2020#509]
![image](https://user-images.githubusercontent.com/102798272/235575730-e2e9b334-73d4-40e3-a833-bff0e5dbd3d9.png)

**Comment by ezelanza** [comment]
Hey there, I've got the same error. Could you please share more details

**Comment by roeyjob** [comment]
I think the reason for this problem is that my target feature data is too flat. Because its line is zigzag when i use other dataset.Maybe this is also the case with your dataset.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhouhaoyi/Informer2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月3日(星期三) 中午11:08
***@***.***&gt;;
抄送:&nbsp;"Roey ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhouhaoyi/Informer2020] The GroundTruth is a straight line when i use my dataset,why and how to fix it? (Issue #509)





 
Hey there, I've got the same error. Could you please share more details
