### ISSUE TITLE
How use the network to predict future data.

### ISSUE THREAD

**Issue by QLaHPD** [zhouhaoyi/Informer2020#51]
I don't understand how to use the net to predict future data, there’s no example code to predict unseen data, I want to pass X previous values and predict the next values.

**Comment by cookieminions** [comment]
In fact, the test process is to predict unseen data (in code `exp/exp_informer.py` function `test`), the groundtruth (`batch_y`) is only used when calculating the metrics.

So if you do not have the real data in the future, I suggest you can modify the code `data/data_loader.py` to make the returned `batch_y` meaningless data, and then only use the output predicted by the model.

The Informer repo provides the code for training and testing experiments, so you may need to modify the code according to your actual needs.
