### ISSUE TITLE
inverse=True时候，所有评价指标test loss， mae， mse都大大上升了。这是为什么

### ISSUE THREAD

**Issue by wenrutong** [zhouhaoyi/Informer2020#514]
inverse=True时候，所有评价指标test loss， mae， mse都大大上升了。这是为什么
![image](https://github.com/zhouhaoyi/Informer2020/assets/114452159/1396b91f-c8f3-4ecb-8736-0c7a836e8d0a)

inverse=False时候
![894e686365480d0d8950c938e44ba6f](https://github.com/zhouhaoyi/Informer2020/assets/114452159/def60dc3-6464-43d9-b279-a2ce87a86bef)

**Comment by randomcollegegirl** [comment]
我的也是这样，false的时候只有零点几，true的时候有几万。。

**Comment by wenrutong** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhouhaoyi/Informer2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月25日(星期四) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhouhaoyi/Informer2020] inverse=True时候，所有评价指标test loss， mae， mse都大大上升了。这是为什么 (Issue #514)





 
我的也是这样，false的时候只有零点几，true的时候有几万。。
 
—直接false训练，然后自己修改归一化数据

**Comment by randomcollegegirl** [comment]
可以大致讲一下怎么自己做反归一吗

**Comment by wenrutong** [comment]
去训练的那个函数One_Batch改一下inverse函数就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月29日(星期一) 上午10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhouhaoyi/Informer2020] inverse=True时候，所有评价指标test loss， mae， mse都大大上升了。这是为什么 (Issue #514)





 
可以大致讲一下怎么自己做反归一吗

**Comment by randomcollegegirl** [comment]
懂了，直接output那里即使inverse=False也反归一是吧？ 这样他可以归一化train， 反归一输出？

**Comment by zhongmengyi** [comment]
你好，可以具体说一下归一化train，反归一化输出具体怎么修改的吗？

**Comment by Seb5Vet** [comment]
> One_Batch

感觉不行啊，这样损失函数变小了，但是还是比False的时候大

**Comment by Echollllll** [comment]
> 懂了，直接output那里即使inverse=False也反归一是吧？ 这样他可以归一化train， 反归一输出？

解决了吗？如何修改process onbatch 函数可以说一下嘛

**Comment by Gandalf112233** [comment]
你好，我也遇到了同样的问题，请问你这边解决了吗，如何修改呢？感谢！
