### ISSUE TITLE
关于预测结果里的real_prediction.npy里的数据是标准化的，我要如何反标准化？（Regarding the real in the prediction results_ The data in prediction.npy is standardized. How can I de standardize it?）

### ISSUE THREAD

**Issue by 2921113436** [zhouhaoyi/Informer2020#516]

**Comment by luxury-jr** [comment]
> 

感恩

**Comment by Med-Rokaimi** [comment]
> 哈哈，我懂了，属于自问自答了，希望帮到有缘人。parser.add_argument('--inverse', action='store_true', help='inverse output data', default=False)将这行代码的default=False改为True

Hey, thank you.
May you please explain more ? where to put this line of code? I'm using my own custom data set.

**Comment by at915** [comment]
十分感谢

**Comment by at915** [comment]
改完后mse值会变得很大，请问是什么问题？

**Comment by MountVoom** [comment]
> 改完后mse值会变得很大，请问是什么问题？

因为反归一化后，mse就使用真实值在计算，和真实值本身的大小有很大关系。

**Comment by Seb5Vet** [comment]
> 改完后mse值会变得很大，请问是什么问题？

我的也是这个问题，请问解决了吗

**Comment by at915** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
