### ISSUE TITLE
仍然是问一个使用自定义数据集的问题

### ISSUE THREAD

**Issue by jushuaZZC1992** [zhouhaoyi/Informer2020#518]
各位：我的数据集名称为QAR.csv,看了之前加载自己数据集问题的提问，已经手动将数据集第一列添加了date列，格式为年月日时分秒（我的时间序列间隔为1秒），然后更改了main_informer的参数，也在exp_informer中的get_data中增加了Dataset_Custom类，还是报错如下，怎么解决呢？是不是遗漏了什么地方要改？
![image](https://github.com/zhouhaoyi/Informer2020/assets/96620804/7386cc00-7fd4-4b41-9002-a2c14ee3c3dd)
上述提到的加载自己数据集的设置我更改如下图：
1.在exp_informer中的get_data中增加了Dataset_Custom类：
![image](https://github.com/zhouhaoyi/Informer2020/assets/96620804/f3cfe0d6-c0c7-4f2b-a074-1b847fe911cf)
2.main_informer的一些开头的参数设置：
![image](https://github.com/zhouhaoyi/Informer2020/assets/96620804/58e5ccbb-2c90-40a7-8016-dfa4a37ead2a)
![image](https://github.com/zhouhaoyi/Informer2020/assets/96620804/f584d642-c7ba-4d7d-bfd3-f413b97d5d0a)

**Comment by jushuaZZC1992** [comment]
已解决

**Comment by Rusullhu** [comment]
请问是如何解决的呢@
