### ISSUE TITLE
Poor documentation on how to predict on new data

### ISSUE THREAD

**Issue by left-brain** [zhouhaoyi/Informer2020#52]
I trained the model but I have no idea how to use it to predict new data, I would like to pass a csv with two columns: "dates" and "past values" to predict the next values using the model, but from what I understand it is not possible to do this without entering in the source code. The colab example also does not provide any specific code or comment on how to do this.

By the way, what exactly is "batch_x", "batch_y, "batch_x_mark, "batch_y_mark"? Which ones I have to pass to the informer to predict the next values?

**Comment by cookieminions** [comment]
Thanks for your suggestion.

`batch_x` and `batch_y` mean `encoder_input` and `prediction`, `batch_x_mark` and `batch_y_mark` mean `timestamp of encoder_input` and `timestamp of prediction`, maybe you can read code `data/data_loader.py` to get more information at present.

And we will update the colab later to make it more convenient for people to use our model.

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion. I will close now.
