### ISSUE TITLE
Prediction values are negative !

### ISSUE THREAD

**Issue by SRDdev** [zhouhaoyi/Informer2020#522]
# Why Negative values are forecasted for positive input ?

The input data to my model is single colummn with values ranging from 0 to 8. 
The model predictions for this generates values which are bothh negative , meaning the input column which must be positive also becomes negative and the prediction is also negative. 

**Is this due to Scaling or Inverse transform ? I could not understand how the ground truth values are also converted into negative values ?**

![image](https://github.com/zhouhaoyi/Informer2020/assets/84516626/d19b62a6-f1af-46f9-89ce-d14e1cf6b852)

Please help !

**Comment by PYtaton** [comment]
Hello! 
Did you solve your issue? Cause I am having the same problem. Thanks.
