### ISSUE TITLE
为什么设置了train_epochs为100，但是只训练了8次就结束了

### ISSUE THREAD

**Issue by zhoudq1025** [zhouhaoyi/Informer2020#527]

**Comment by zhoudq1025** [comment]
在参数parser.add_argument('--train_epochs', type=int, default=100, help='train epochs')设置了100，但是并没有训练100次，调试的时候只训练了15次，运行的时候训练了8次

**Comment by zhoudq1025** [comment]
已解决

**Comment by hackerhackerhacker** [comment]
想问下你是怎么解决的

**Comment by a1240282289** [comment]
想问一下您是怎么解决的

**Comment by dengdeng886** [comment]
> 已解决

请问是怎么解决的，我也遇到了同样的问题

**Comment by MountVoom** [comment]
在训练时设置了Early Stop防止过拟合，所以可能会提前停止。
可以考虑注释掉训练代码中：
```python
if early_stopping.early_stop:
    print("Early stopping")
    break
```
或者将`patience`参数设置的非常大。

**Comment by zhoudq1025** [comment]
我就将patience设置大一些就行了
