### ISSUE TITLE
多变量预测多变量

### ISSUE THREAD

**Issue by zhongmengyi** [zhouhaoyi/Informer2020#529]
你好，我想进行多变量预测多变量，想输出正确的loss和反归一化后的预测结果，但是选择多变量预测多变量模式后，直接将--inverse设置为True，输出的loss大概在二三十左右，该如何进行修改呢，有什么好的建议吗

**Comment by hackerhackerhacker** [comment]
同问

**Comment by boris-lb** [comment]
同问，我的训练集loss三四千，测试集loss直接十几万

**Comment by MountVoom** [comment]
可以对结果单独进行反归一化：
```python
outputs = dataset_object.inverse_transform(outputs)
```
比如想得到真实的test结果，可以使用：
```python
preds = test_data.inverse_transform(preds)
```

**Comment by CovergilLee** [comment]
楼主您好。
我同样使用多变量预测多变量，但是不明白该如何修改命令行指令。
我得数据集是使用前三列来预测后两列的数据。
想跟您请教一下该如何写命令行的指令，同时代码该如何修改。
万分感谢！

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！

**Comment by 721chenjie** [comment]
预测两列就报错啊

**Comment by kirito5206** [comment]
> 您好，您的邮件我已收到，稍后会给您回复，谢谢！

同问这个多变量预测多变量应该怎么设置·

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！

**Comment by fenixzml** [comment]
请问可以分享一下代码吗，我也是多变量预测多变量，fenix69636@gmail.com

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！

**Comment by fenixzml** [comment]
> 同问，我的训练集loss三四千，测试集loss直接十几万

请问您现在解决了吗，可以分享一下代码吗 fenix69636@gmail.com

**Comment by ShanLan-123** [comment]
楼主我也有同样的问题，怎么才能多变量预测多变量啊？

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！

**Comment by Gao570549** [comment]
请问可以分享一下多变量预测多变量的代码吗，我对于代码的修改也有一些问题

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！

**Comment by lzh01993** [comment]
请问预测多变量的c_out怎么设置

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！

**Comment by simple123456T** [comment]
> 楼主您好。 我同样使用多变量预测多变量，但是不明白该如何修改命令行指令。 我得数据集是使用前三列来预测后两列的数据。 想跟您请教一下该如何写命令行的指令，同时代码该如何修改。 万分感谢

大佬你好，我也是这种情况，该怎么修改代码呀

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！
