### ISSUE TITLE
RuntimeError when e_layers>3 ?

### ISSUE THREAD

**Issue by lzmax888** [zhouhaoyi/Informer2020#53]
感谢您的分享。

当我尝试e_layers=4或者更大的时候，训练总会出现错误，无法进行。调用exp.train(settings).

e_layers=3或者更少，都正常。不明白为什么？

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-98-b0d55694c914> in <module>
     13 # train
     14 print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
---> 15 exp.train(setting)
     16 
     17 # test

~/max/Informer2020/exp/exp_informer.py in train(self, setting)
    169                 # encoder - decoder
    170                 if self.args.output_attention:
--> 171                     outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)[0]
    172                 else:
    173                     outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/max/Informer2020/models/model.py in forward(self, x_enc, x_mark_enc, x_dec, x_mark_dec, enc_self_mask, dec_self_mask, dec_enc_mask)
    145                 enc_self_mask=None, dec_self_mask=None, dec_enc_mask=None):
    146         enc_out = self.enc_embedding(x_enc, x_mark_enc)
--> 147         enc_out, attns = self.encoder(enc_out, attn_mask=enc_self_mask)
    148 
    149         dec_out = self.dec_embedding(x_dec, x_mark_dec)

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/max/Informer2020/models/encoder.py in forward(self, x, attn_mask)
     94                 inp_len = inp_len//2
     95                 continue
---> 96             x, attn = encoder(x[:, -inp_len:, :])
     97             x_stack.append(x); attns.append(attn)
     98             inp_len = inp_len//2

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/max/Informer2020/models/encoder.py in forward(self, x, attn_mask)
     65         if self.conv_layers is not None:
     66             for attn_layer, conv_layer in zip(self.attn_layers, self.conv_layers):
---> 67                 x, attn = attn_layer(x, attn_mask=attn_mask)
     68                 x = conv_layer(x)
     69                 attns.append(attn)

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/max/Informer2020/models/encoder.py in forward(self, x, attn_mask)
     43         new_x, attn = self.attention(
     44             x, x, x,
---> 45             attn_mask = attn_mask
     46         )
     47         x = x + self.dropout(new_x)

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/max/Informer2020/models/attn.py in forward(self, queries, keys, values, attn_mask)
    151             keys,
    152             values,
--> 153             attn_mask
    154         )
    155         out = out.view(B, L, -1)

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/max/Informer2020/models/attn.py in forward(self, queries, keys, values, attn_mask)
    109         u = self.factor * np.ceil(np.log(L_Q)).astype('int').item() # c*ln(L_q)
    110 
--> 111         scores_top, index = self._prob_QK(queries, keys, sample_k=U_part, n_top=u)
    112 
    113         # add scale factor

~/max/Informer2020/models/attn.py in _prob_QK(self, Q, K, sample_k, n_top)
     58         # find the Top_k query with sparisty measurement
     59         M = Q_K_sample.max(-1)[0] - torch.div(Q_K_sample.sum(-1), L_K)
---> 60         M_top = M.topk(n_top, sorted=False)[1]
     61 
     62         # use the reduced Q to calculate Q_K

RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26

**Comment by cookieminions** [comment]
这应该是因为注意力蒸馏操作会导致每一层的输入减半，当输入的长度不够长，而e_layers>4时，在高层的输入长度会变得很小，导致probsparse attention在选择LlogL*factor个点积对时会大于L*L的点积对总数，从而导致报错

因此解决方法为：1. 增大输入长度；2. 如果输入长度不够而layers比较大，那么可以减小factor数，默认是5，可以用 `--factor 3`将其减小

我们之后会修复这个可能导致报错的问题，感谢你的提醒
