### ISSUE TITLE
运行结果问题请教

### ISSUE THREAD

**Issue by ihepf** [zhouhaoyi/Informer2020#534]
为什么每次运行后，results都会有两个文件informer_ETTh1_ftM_sl48_ll24_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_0和informer_ETTh1_ftM_sl48_ll24_pl24_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_test_1，麻烦可以请教一下。这两个文件有啥区别吗？

**Comment by ihepf** [comment]
已经解决啦，谢谢啦

**Comment by hackerhackerhacker** [comment]
为啥呀

**Comment by a1240282289** [comment]
为啥呀

**Comment by hackerhackerhacker** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！

**Comment by 77coming** [comment]
您好，请问运行自己的数据集后哪里可以查看模型训练结果呀
