### ISSUE TITLE
为什么作者的dataset(WTH)效果很好，自己的dataset偏差很大？

### ISSUE THREAD

**Issue by themashu** [zhouhaoyi/Informer2020#538]
WTH:

![Figure_1](https://github.com/zhouhaoyi/Informer2020/assets/72458622/57ca2bb3-9f00-491d-971a-e19aeb9ab0a5)

自己的dataset(BTC-H):

![Figure_2](https://github.com/zhouhaoyi/Informer2020/assets/72458622/27cb07a5-ed01-4cfa-980f-88ae0f182027)

照道理来说我这个dataset里面的数据是比较有关联性的呀，就是每个小时的BTC价格，大概长这样：

![image](https://github.com/zhouhaoyi/Informer2020/assets/72458622/8dc614b8-15c2-4164-99e9-998d30fd2412)

为什么差距好大呀 mse也好大 哪位大哥能说说该怎么调整参数吗？谢谢. 给您磕一个 (:

**Comment by ZWT2002** [comment]
对于金融数据来说，最容易犯下的问题就是仅仅把金融数据当作时间序列数据来处理，金融数据，不仅仅是时序数据，单纯的调参是不能解决问题的

**Comment by elseboy** [comment]
> 对于金融数据来说，最容易犯下的问题就是仅仅把金融数据当作时间序列数据来处理，金融数据，不仅仅是时序数据，单纯的调参是不能解决问题的

老哥有啥推荐可以做这种数据集的吗？

**Comment by ZWT2002** [comment]
> 

比特币这种虚拟货币的数据集，个人感觉，应该完全没办法从单纯的时序数据上入手，单纯价格数据的参考价值并不大，因为比特币时间太短，价格变动并没有什么太多的规律，受社会层面的影响更大一些，

**Comment by elseboy** [comment]
> > 
> 
> 比特币这种虚拟货币的数据集，个人感觉，应该完全没办法从单纯的时序数据上入手，单纯价格数据的参考价值并不大，因为比特币时间太短，价格变动并没有什么太多的规律，受社会层面的影响更大一些，

[我看过几篇论文看人家整的挺好，](https://arxiv.org/pdf/2305.14382.pdf) 难搞

**Comment by elseboy** [comment]
> > 
> 
> 比特币这种虚拟货币的数据集，个人感觉，应该完全没办法从单纯的时序数据上入手，单纯价格数据的参考价值并不大，因为比特币时间太短，价格变动并没有什么太多的规律，受社会层面的影响更大一些，

我看到几篇论文人家整挺好，[https://arxiv.org/pdf/2305.14382.pdf](url)，哎难搞

**Comment by elseboy** [comment]
> > > > 
> > > 
> > > 
> > > 比特币这种虚拟货币的数据集，个人感觉，应该完全没办法从单纯的时序数据上入手，单纯价格数据的参考价值并不大，因为比特币时间太短，价格变动并没有什么太多的规律，受社会层面的影响更大一些，
> > 
> > 
> > 我看到几篇论文人家整挺好，[https://arxiv.org/pdf/2305.14382.pdf](url)，哎难搞
> 
> 我大致看了一下这篇论文，关于Informer模型的超参数和所用的数据都给出来了，可以尝试复现一下这篇论文的内容。这篇论文的效果确实有些出人意料，因为这篇论文中所用的数据仅仅只有最高最低开盘收盘四个价格和成交量和换手率

参数被我调烂了，效果也不是很理想，最近在整Autoformer, 我在想是不是我这数据集没什么规律的问题，它那个WTH数据看着挺平时整齐的，我这个只想预测下close，但是历史数据波动太大了，会不会是这个原因呢？
[BTC.csv](https://github.com/zhouhaoyi/Informer2020/files/12015257/BTC.csv)

**Comment by ZWT2002** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 比特币这种虚拟货币的数据集，个人感觉，应该完全没办法从单纯的时序数据上入手，单纯价格数据的参考价值并不大，因为比特币时间太短，价格变动并没有什么太多的规律，受社会层面的影响更大一些，
> > > 
> > > 
> > > 我看到几篇论文人家整挺好，[https://arxiv.org/pdf/2305.14382.pdf](url)，哎难搞
> > 
> > 
> > 我大致看了一下这篇论文，关于Informer模型的超参数和所用的数据都给出来了，可以尝试复现一下这篇论文的内容。这篇论文的效果确实有些出人意料，因为这篇论文中所用的数据仅仅只有最高最低开盘收盘四个价格和成交量和换手率
> 
> 参数被我调烂了，效果也不是很理想，最近在整Autoformer, 我在想是不是我这数据集没什么规律的问题，它那个WTH数据看着挺平时整齐的，我这个只想预测下close，但是历史数据波动太大了，会不会是这个原因呢？ [BTC.csv](https://github.com/zhouhaoyi/Informer2020/files/12015257/BTC.csv)
Informer这篇论文中用到的天气数据确实是有着明显的规律性存在的，autoformer这篇论文，采用了一个汇率的数据集，结果并不理想，我想可能在bitcoin上的结果也不会太理想
值得一提的是，我刚才注意到，你分享的那篇将informer用在股票数据上的论文里面的结果的图片，虽然看着比较理想，但实际效果其实也并不理想。而且有滞后现象，表明了模型其实并没有太多的预测功能

**Comment by elseboy** [comment]
> 

那寄了 想水个论文都找不到方向 烦嗷

**Comment by elseboy** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 比特币这种虚拟货币的数据集，个人感觉，应该完全没办法从单纯的时序数据上入手，单纯价格数据的参考价值并不大，因为比特币时间太短，价格变动并没有什么太多的规律，受社会层面的影响更大一些，
> > > > 
> > > > 
> > > > 我看到几篇论文人家整挺好，[https://arxiv.org/pdf/2305.14382.pdf](url)，哎难搞
> > > 
> > > 
> > > 我大致看了一下这篇论文，关于Informer模型的超参数和所用的数据都给出来了，可以尝试复现一下这篇论文的内容。这篇论文的效果确实有些出人意料，因为这篇论文中所用的数据仅仅只有最高最低开盘收盘四个价格和成交量和换手率
> > 
> > 
> > 参数被我调烂了，效果也不是很理想，最近在整Autoformer, 我在想是不是我这数据集没什么规律的问题，它那个WTH数据看着挺平时整齐的，我这个只想预测下close，但是历史数据波动太大了，会不会是这个原因呢？ [BTC.csv](https://github.com/zhouhaoyi/Informer2020/files/12015257/BTC.csv)
> > Informer这篇论文中用到的天气数据确实是有着明显的规律性存在的，autoformer这篇论文，采用了一个汇率的数据集，结果并不理想，我想可能在bitcoin上的结果也不会太理想
> > 值得一提的是，我刚才注意到，你分享的那篇将informer用在股票数据上的论文里面的结果的图片，虽然看着比较理想，但实际效果其实也并不理想。而且有滞后现象，表明了模型其实并没有太多的预测功能

那寄了，想水个论文都没方向，好不容易从头到尾看了一遍Informer源码，这下又没下文了，老哥有推荐的好水机器学习文章的方向吗

**Comment by ZWT2002** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 比特币这种虚拟货币的数据集，个人感觉，应该完全没办法从单纯的时序数据上入手，单纯价格数据的参考价值并不大，因为比特币时间太短，价格变动并没有什么太多的规律，受社会层面的影响更大一些，
> > > > > 
> > > > > 
> > > > > 我看到几篇论文人家整挺好，[https://arxiv.org/pdf/2305.14382.pdf](url)，哎难搞
> > > > 
> > > > 
> > > > 我大致看了一下这篇论文，关于Informer模型的超参数和所用的数据都给出来了，可以尝试复现一下这篇论文的内容。这篇论文的效果确实有些出人意料，因为这篇论文中所用的数据仅仅只有最高最低开盘收盘四个价格和成交量和换手率
> > > 
> > > 
> > > 参数被我调烂了，效果也不是很理想，最近在整Autoformer, 我在想是不是我这数据集没什么规律的问题，它那个WTH数据看着挺平时整齐的，我这个只想预测下close，但是历史数据波动太大了，会不会是这个原因呢？ [BTC.csv](https://github.com/zhouhaoyi/Informer2020/files/12015257/BTC.csv)
> > > Informer这篇论文中用到的天气数据确实是有着明显的规律性存在的，autoformer这篇论文，采用了一个汇率的数据集，结果并不理想，我想可能在bitcoin上的结果也不会太理想
> > > 值得一提的是，我刚才注意到，你分享的那篇将informer用在股票数据上的论文里面的结果的图片，虽然看着比较理想，但实际效果其实也并不理想。而且有滞后现象，表明了模型其实并没有太多的预测功能
> 
> 那寄了，想水个论文都没方向，好不容易从头到尾看了一遍Informer源码，这下又没下文了，老哥有推荐的好水机器学习文章的方向吗

水论文的话，仿照你刚才发的那篇论文，做一下应用应该可以水一篇吧，按照他那种作图方式，做出来的效果都不会太差

**Comment by elseboy** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 比特币这种虚拟货币的数据集，个人感觉，应该完全没办法从单纯的时序数据上入手，单纯价格数据的参考价值并不大，因为比特币时间太短，价格变动并没有什么太多的规律，受社会层面的影响更大一些，
> > > > > > 
> > > > > > 
> > > > > > 我看到几篇论文人家整挺好，[https://arxiv.org/pdf/2305.14382.pdf](url)，哎难搞
> > > > > 
> > > > > 
> > > > > 我大致看了一下这篇论文，关于Informer模型的超参数和所用的数据都给出来了，可以尝试复现一下这篇论文的内容。这篇论文的效果确实有些出人意料，因为这篇论文中所用的数据仅仅只有最高最低开盘收盘四个价格和成交量和换手率
> > > > 
> > > > 
> > > > 参数被我调烂了，效果也不是很理想，最近在整Autoformer, 我在想是不是我这数据集没什么规律的问题，它那个WTH数据看着挺平时整齐的，我这个只想预测下close，但是历史数据波动太大了，会不会是这个原因呢？ [BTC.csv](https://github.com/zhouhaoyi/Informer2020/files/12015257/BTC.csv)
> > > > Informer这篇论文中用到的天气数据确实是有着明显的规律性存在的，autoformer这篇论文，采用了一个汇率的数据集，结果并不理想，我想可能在bitcoin上的结果也不会太理想
> > > > 值得一提的是，我刚才注意到，你分享的那篇将informer用在股票数据上的论文里面的结果的图片，虽然看着比较理想，但实际效果其实也并不理想。而且有滞后现象，表明了模型其实并没有太多的预测功能
> > 
> > 
> > 那寄了，想水个论文都没方向，好不容易从头到尾看了一遍Informer源码，这下又没下文了，老哥有推荐的好水机器学习文章的方向吗
> 
> 水论文的话，仿照你刚才发的那篇论文，做一下应用应该可以水一篇吧，按照他那种作图方式，做出来的效果都不会太差

好的 我明天尽量复现下他那个试试看
