### ISSUE TITLE
关于double数据类型的问题

### ISSUE THREAD

**Issue by JsonAC** [zhouhaoyi/Informer2020#55]
pytorch默认的是float，速度更快一般精度相对double也差不多，为何代码里都是数据和模型都是double双精度的呢？有其他的考虑吗？谢谢~

**Comment by cookieminions** [comment]
非常感谢你的关注，我们当初使用double主要是考虑到数据缩放和probsparse attention，希望避免计算过程中数值出现问题。

不过我们在下周的更新中默认使用float精度，并提供选项支持使用混合精度。

**Comment by JsonAC** [comment]
好的，谢谢~
