### ISSUE TITLE
Model saved under `checkpoints` cannot be accessed with file browser in Colab example

### ISSUE THREAD

**Issue by Nntraveler** [zhouhaoyi/Informer2020#56]
- After trainning, I can't download checkpoint.pth via file browser panel. 
![image](https://user-images.githubusercontent.com/44135023/111734554-52877800-88b5-11eb-9874-0f5acd05048e.png)

- This is a problem related to Google Colab, which requires using name other than `checkpoints`. refer: https://github.com/googlecolab/colabtools/issues/621
- However, this problem may not affect the execution of the example.

**Comment by cookieminions** [comment]
Thanks for your remind, we will solve this problem in next week's update. 

You can modify code `exp/exp_informer.py` line 138 `path = './checkpoints/'+setting` with other path.

**Comment by Nntraveler** [comment]
Thank you for replying. I tried the solution and it works.
