### ISSUE TITLE
数据问题_len__() should return >= 0

### ISSUE THREAD

**Issue by GAN-AIS** [zhouhaoyi/Informer2020#563]
老师，各位大神，大家好，我的数据只有99行，很小，前期的操作Debug都没有问题，为什么一运行就会返回__len__() should return >= 0？
![f5b3880ccaff8ca04101e3049195764](https://github.com/zhouhaoyi/Informer2020/assets/72728815/b7a5df48-d5da-4ace-a199-d3b8470d7750)
![f0f178d182db6a912619357cafae70f](https://github.com/zhouhaoyi/Informer2020/assets/72728815/9b238e63-95d7-4523-890f-45660bf4d7dd)

**Comment by GAN-AIS** [comment]
自问自答：和自己数据集的长度有关，自己的数据集可能会因为长度不够导致划分出来的集合为空

**Comment by LiLeLeANDZmy** [comment]
现在改好了吗 一样的问题

**Comment by ShanLan-123** [comment]
长度不够？
意思是要扩大数据集的长度吗？
