### ISSUE TITLE
Concatenating Feature maps from encoder

### ISSUE THREAD

**Issue by 18kiran12** [zhouhaoyi/Informer2020#58]
Hi,

I really appreciate you helping others to understand the code by proactively replying to the questions.

While going through the paper and the figure in the paper, it is mentioned that the output from the encoder is a concatenated feature map from each stack.

"we concatenate all the stacks’ outputs and have the final hidden representation of encoder."

But in the code, it seems like only the final encoder representation is used as an input to the decoder (without concatenating  final encoder representation with lower level embedding representations.)

Could you please clarify why do I notice this discrepancy?

Thanks in advance.

**Comment by cookieminions** [comment]
> "we concatenate all the stacks’ outputs and have the final hidden representation of encoder."

Well, this sentence descripts the `InformerStack` model in our code. The single Informer stack follow the canonical Transformer's architecture which input the final encoder layer's output into the decoder. And the InformerStack contains several single Informers, their inputs are halved in turn,  and the number of layers is reduced accordingly, which can make all Informers in InformerStack predict outputs with the same length. And finally we concatenate all Infomers' output in InformerStack and have the final hidden representation of encoder.

Maybe you can refer to these pictures:
![image](https://user-images.githubusercontent.com/18379035/111802362-db7bcf00-8908-11eb-8366-3149fe64784d.png)

![image](https://user-images.githubusercontent.com/18379035/111802389-e2a2dd00-8908-11eb-83b6-01ae5809fbeb.png)


InformerStack in current code is very simple, and we will improve it in future update.

**Comment by 18kiran12** [comment]
Thanks for the quick reply.

That clarifies my question. However, is it safe to assume that all the results as shown in the github as well as in the paper are still using a single informer model rather than a InformerStack model?.

**Comment by cookieminions** [comment]
Thanks for your attention, the results in our paper are mainly produced by isngle Informer, only a few results are produced by InformerStack. And we will update the results in the final version paper using single Informer results. New results and experimental parameters will be updated in a few days (around March 23).

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion. I will close this issue now.
