### ISSUE TITLE
In oder to change the order of dimensions, why is torch.tensor.view used??

### ISSUE THREAD

**Issue by YexuZhou** [zhouhaoyi/Informer2020#59]
Hallo,

thank you for making the code public.

In the code (forward in ProbAttention), you used the tensor.view to change the dimensions.

queries = queries.view(B, H, L_Q, -1)
keys = keys.view(B, H, L_K, -1)
values = values.view(B, H, L_K, -1)

Why do not use permute？Dose View function not break the relationship between heads?
Is the goal of using tensor.view here to change the order of dimensions? If it is, why tensor.view.?

**Comment by YexuZhou** [comment]
the initial dimension of queries is [B,L_Q,H,D] .

**Comment by lanlanlanlanlanlanlan** [comment]
Seems that the authors think .view() can be used to transpose a tensor. Maybe it's a magic😜?

**Comment by cookieminions** [comment]
Thanks for your remind!
We will fix this error immediately.

**Comment by zhouhaoyi** [comment]
We double-checked that, this issue only affects the current branch. The results on arXiv are still reliable and we will update these soon for recent incremental tricks.
