### ISSUE TITLE
MSE与MAE值缩放

### ISSUE THREAD

**Issue by echobito** [zhouhaoyi/Informer2020#604]
请问一下终端输出部分的MAE跟MSE是不是缩放了？为什么导出结果图里的预测值跟真实值差距很小，MAE看上去只有0.01，但是终端输出MAE的是0.1。我没有找到缩放代码TT
![github](https://github.com/zhouhaoyi/Informer2020/assets/112453467/0f767968-e43a-455d-81f2-918708e6c21a)

**Comment by echobito** [comment]
左MSE，中MAE，右RMSE

**Comment by echobito** [comment]
已解决，因为是Z-score缩放，与国外论文中Min-MAX缩放不同，故MSE需除4，MAE与RMSE除2。缩放后的结果再加上两种方法产生的误差，能够完美对应上国外论文实验结果。（谢谢作者的贡献）

**Comment by Echollllll** [comment]
> 已解决，因为是Z-score缩放，与国外论文中Min-MAX缩放不同，故MSE需除4，MAE与RMSE除2。缩放后的结果再加上两种方法产生的误差，能够完美对应上国外论文实验结果。（谢谢作者的贡献）

作者大大 我想问一下 你提供的这张图是反归一化之后的结果吧？请问作者大大是将论文中的反归一化方法改为了Z-score方法，没有用论文原来的反归一化方法对吧？ 可以加联系方式讨论一下嘛：秋秋646447457
