### ISSUE TITLE
About the best result's hyperparameters

### ISSUE THREAD

**Issue by TylerChoi1224** [zhouhaoyi/Informer2020#61]
Hi. 
Thank you for your amazing paper. 
I think your thoughts and this technical structure is so awesome.

I am doing replication your paper, but I have some question.
The prediction(len=336) of Informer's result is very interesting below.
So I want to know below result's more detail hyperparameters.
eg.) seq_len, label_len, pred_len, e_layers, d_layers and other parameters everything.

1. Can you tell me about the specific hyperparameters?
2. How can we use this forecasitng system to anomaly detecion?
 (I just want to know your thoughts.)

Thank you. 非常感谢。

![image](https://user-images.githubusercontent.com/74239291/111929090-c2397500-8af8-11eb-833e-56c034044cca.png)

**Comment by zhouhaoyi** [comment]
Hi,

Thanks for your attention to our work.
1. We will release the revised version of the results and all hyperparameters within this week. Please wait for a moment.
2. From my point of view, the anomaly point should be pre-defined and can be assigned with a specific token. Thus, you can use the forecasting system to predict such tokens, namely the detection in the future. However, if you prefer to perform detections in the historical data, it becomes the scanning procedure. All that matters is the definition of abnormal subjects.

Hope it will help.

**Comment by TylerChoi1224** [comment]
Thank you for so fast answering and your opinion.
I really look forward to your revised version of the result.

So long.
