### ISSUE TITLE
模型测试结果

### ISSUE THREAD

**Issue by Erickurashi** [zhouhaoyi/Informer2020#69]
我尝试着用script里的参数去调试数据，例如
python -u main_informer.py --model informer --data ETTh2 --features S --seq_len 336 --label_len 336 --pred_len 168 --e_layers 2 --d_layers 1 --attn prob --des 'Exp' --itr 5
测试结果是mse:0.25672146677970886, mae:0.43616965413093567
和您更新的结果差的不多
![image](https://user-images.githubusercontent.com/78995667/112183451-39762280-8c39-11eb-9c27-7f8f8a1f31f5.png)
但是图像的预测结果和真实的值相差的很多。请问是我有漏调的参数还是结果就是这样的。
![image](https://user-images.githubusercontent.com/78995667/112184520-3f203800-8c3a-11eb-951c-c205590e9143.png)

[Informer.ipynb - Colaboratory.pdf](https://github.com/zhouhaoyi/Informer2020/files/6191297/Informer.ipynb.-.Colaboratory.pdf)

非常感谢。

**Comment by zhrli** [comment]
是否属于论文里的实验无法复现 ？

**Comment by cookieminions** [comment]
非常感谢关注

1. script中提供的参数只是在调参过程中关注了mse和mae的数值结果，并没有额外考虑画图而统计得来的，只是为复现表格中的结果提供的参考，因此对于画图可能会存在某些问题
2. 这个问题我们在后续的实验中也关注到了，即较小的mse error并不意味着画图表现的曲线准确，这个问题来自于几个方面：1）mse评价指标本身的落后，导致在时序点预测时，无法像DTW那样更加考虑到对应趋势；2）数据的归一化，使得总体误差偏小，再加上mse指标的问题，因此使各种模型在训练时倾向于选择各段曲线内的平均值作为结果，使得误差降低但是曲线本身不准确（我们注意到这个问题对于ARIMA或LSTM等方法同样存在，在画图时将会表现为直线）；3）数据ETTh2存在的一些问题，我注意到你非常关注ETTh2这个数据集，我们同样发现ETTh2在多变量实验中，除OT外的某些其他特征在数据上存在较多异常值以及前后两年数值在尺度上有一个断层的变化，因此在修改数据归一化方式后误差变化较大，而对于单变量实验可能需要调整参数才能得到更好的结果（但如果是实际的应用，我们更加建议使用多变量预测参考更多信息，然后取需要的特征），我们提供了使用script中的参数得到的另一个数据集ETTh1的结果，这说明为了得到ETTh2较好的预测曲线依然需要调整参数，此外附录中的图则是数据集ETTm2（为ETTm2的原因可参考 https://github.com/zhouhaoyi/Informer2020/issues/44 ）的结果，在我们的研究中也发现频率更高的数据如ETTm1和ETTm2预测曲线能够更加准确
3. 结论：1）更高频率的数据可能拥有相对更好的效果；2）基于上述的几个问题，script中的参数只是为复现表格中的结果提供参考，可能还需要继续调整参数才能得到在误差和画图上同样优秀的结果，同时也建议可以使用InformerStack进行实验；3）针对上述问题我们后续也展开了研究，包括：a. 在训练时将数据缩放回原来的尺度，b. 探索mse以外的更合适的点预测评估指标，c. 探索更多数据特性对模型生成结果的影响

再次感谢对我们工作的关注

![image](https://user-images.githubusercontent.com/18379035/112248746-69e9ab00-8c91-11eb-8a7e-e592310f6d7d.png)
![image](https://user-images.githubusercontent.com/18379035/112248776-7bcb4e00-8c91-11eb-9ffb-7b530dd45819.png)

**Comment by Erickurashi** [comment]
非常感谢您的解答！

**Comment by cookieminions** [comment]
非常感谢关注！之后我们的研究进展也会在这个repo继续更新
