### ISSUE TITLE
About the ECL dataset

### ISSUE THREAD

**Issue by cuiyuebing** [zhouhaoyi/Informer2020#74]
Thanks for the code! I noticed that you mentioned in another issue that the ECL dataset used the Informer paper is the same as https://github.com/laiguokun/multivariate-time-series-data. Could you help to specify which column in the electricity dataset corresponds to the target "MT_320"? Thanks!

**Comment by zhouhaoyi** [comment]
The total number of columns in the ECL dataset is 321. And the "MT_320" referring to the last columns, in which the index starts from 0.

**Comment by cuiyuebing** [comment]
Thanks for the information!

**Comment by joelrorseth** [comment]
Hi, I am also trying to reproduce your results for the ECL dataset, and encountered a discrepancy. The preprocessed dataset mentioned by OP (https://github.com/laiguokun/multivariate-time-series-data) omits the "date" column, however your Colab notebook (under Custom Data instructions) and the provided ETT datasets indicate that a "date" column must be provided in the CSV.

Also, this preprocessed version of ECL does not contain column names, which I believe are expected also? Regardless, it is clear that no dates are present in the data, leaving the columns `[MT_000, ..., MT_320]`. The original source dataset is not CSV formatted, so I presume that some further preprocessing was performed on one of these datasets for your experiments.

Could you elaborate on any steps that should be taken to preprocess the ECL dataset, before feeding it to Informer via the `--data ECL` arg? Thanks!
