### ISSUE TITLE
关于 EncoderStack 每个stack的初始输入

### ISSUE THREAD

**Issue by donggoing** [zhouhaoyi/Informer2020#76]
你好我想请问一下论文中每个stack的输入是取上一个stack输入的后半段对吗？还是取上一个stack输出的一部分？因为我看代码里初始输入x貌似会被输出覆盖掉。
https://github.com/zhouhaoyi/Informer2020/blob/c648cc6c9fba4b42b35b891e1837c98a5c0f17f2/models/encoder.py#L96

**Comment by cookieminions** [comment]
非常感谢你的提醒，InformerStack此处实现的确存在问题，stack应该有一个原始输入x，stack中的各部分应该是取原始输入的各部分，我们会立刻修复这个问题

**Comment by donggoing** [comment]
> 非常感谢你的提醒，InformerStack此处实现的确存在问题，stack应该有一个原始输入x，stack中的各部分应该是取原始输入的各部分，我们会立刻修复这个问题

好的，感谢你的答复~

**Comment by QuantHao** [comment]
您好，我看到代码似乎并没有修复？请问为什么close this issue?

**Comment by cookieminions** [comment]
> 您好，我看到代码似乎并没有修复？请问为什么close this issue?

请问你是指哪个部分没有修复，InformerStack的code在`models/encoder.py`中，如果有疑问可以引用指出

**Comment by QuantHao** [comment]
> > 您好，我看到代码似乎并没有修复？请问为什么close this issue?
> 
> 请问你是指哪个部分没有修复，InformerStack的code在`models/encoder.py`中，如果有疑问可以引用指出

哇，您回复好快，比心比心。

https://github.com/zhouhaoyi/Informer2020/blob/c648cc6c9fba4b42b35b891e1837c98a5c0f17f2/models/encoder.py#L96
这里似乎x还是会被覆盖更新，和楼主提问时并没有变化？如果说错的，烦请指正。感谢感谢~

**Comment by cookieminions** [comment]
如果你从楼主引用部分的代码跳入文件将会定位到上一个commit的代码，目前的代码已经更新如下：

https://github.com/zhouhaoyi/Informer2020/blob/99b59c181f871a1521a798a37287a27ba5b742a7/models/encoder.py#L90-L95

你可以确定一下代码版本，或者直接从repo主页进入encoder.py文件

**Comment by QuantHao** [comment]
> 如果你从楼主引用部分的代码跳入文件将会定位到上一个commit的代码，目前的代码已经更新如下：
> 
> https://github.com/zhouhaoyi/Informer2020/blob/99b59c181f871a1521a798a37287a27ba5b742a7/models/encoder.py#L90-L95
> 
> 你可以确定一下代码版本，或者直接从repo主页进入encoder.py文件

原来如此，非常感谢答复，是我疏忽了。great paper and great repo!!
