### ISSUE TITLE
运行ETTm1.sh，使用 --do_predict 参数，预测 --pred_len 672 时出错。

### ISSUE THREAD

**Issue by dyh** [zhouhaoyi/Informer2020#79]
您好，这可能是个bug。

- 数据集：ETTm1.csv

- 复现方式：
python -u main_informer.py --do_predict  --model informer --data ETTm1 --features S --seq_len 384 --label_len 384 --pred_len 672 --e_layers 2 --d_layers 1 --attn prob --des 'Exp' --itr 1

- 错误信息：

>>>>>>>testing : informer_ETTm1_ftS_sl384_ll384_pl672_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_Exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 10849
test shape: (339, 32, 672, 1) (339, 32, 672, 1)
test shape: (10848, 672, 1) (10848, 672, 1)
mse:0.26071080565452576, mae:0.44228261709213257
>>>>>>>predicting : informer_ETTm1_ftS_sl384_ll384_pl672_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_Exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
pred 1
Traceback (most recent call last):
  File "main_informer.py", line 105, in <module>
    exp.predict(setting, True)
  File "/home/Informer2020_main/exp/exp_informer.py", line 343, in predict
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/home/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/Informer2020_main/models/model.py", line 72, in forward
    dec_out = self.dec_embedding(x_dec, x_mark_dec)
  File "/home/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/Informer2020_main/models/embed.py", line 107, in forward
    x = self.value_embedding(x) + self.position_embedding(x) + self.temporal_embedding(x_mark)
RuntimeError: The size of tensor a (768) must match the size of tensor b (1056) at non-singleton dimension 1

- 补充：

1、train、vali、test，没有问题。
2、预测其他长度，96、228 没有问题。
3、--features M，预测--pred_len 672，也有同样问题。

**Comment by cookieminions** [comment]
非常感谢，这个bug会因为预测时，参数设置中pred_len大于label_len引发。

错误定位在code `exp/exp_informer.py` line 330 `dec_inp = torch.zeros_like(batch_y[:,-self.args.pred_len:,:]).float()`。因为在train,vali和test中，加载的batch_y长度是label_len+pred_len，因此可以截取最后pred_len长度的序列来通过zeros_like生成dec_inp，而在predict中，batch_y长度只有label_len，因此dec_inp最大长度只有label_len，所以可能引发错误

我们刚刚已经修复了这个问题，再次感谢提醒

**Comment by dyh** [comment]
好迅速！谢谢！
