### ISSUE TITLE
关于probsparse self-attention的问题

### ISSUE THREAD

**Issue by Sample-design-alt** [zhouhaoyi/Informer2020#80]
你好，我想问一下关于probsparse self-attention的几个问题，
1、算法是先随机选取K个key得到K_sample，然后与所有的Q进行dot-product得到了一个M值，M值进行排序以后得到MTop个Query，用M个query与所有的Key（不是随机的K个key）进行点积得到score嘛？
2、如果1的问题我理解正确的话，那为什么需要随机的选取K个key值呢，我不是很理解这一点，直接所有的query和key计算，然后得到得到Mtop个query，不是更方便一些吗
3、并且如果随机选取k个key值，例如一个句子是‘Today is Tuesday’ ,Q是Tuesday，如果随机选取到的k值是'is'，那显然忽略掉了'today'这个k值了。           
想请您指教一下，谢谢

**Comment by zhouhaoyi** [comment]
你好，欢迎关注我们的工作。
1.并不是随机选取K个key，是对于不同的Q选择了不同的K计算max和mean。
2.不能直接计算所有的key和query，否则复杂度会回到L^2。
3.确实选取Q的可能会忽略一些值，但是我们关注的是max和mean，一般认为mean能够sample出来。而max的话，如果这个Query足够active，虽然取不到最大值，但是一个较大的值也是有更高概率取到（越active这个概率越高）。而且最终计算的时候是选择的Q和所有的Key计算，所以不存在信息损失的问题。另外不同的heads取得Query也不一样，这样也一定程度增强了算法的鲁棒性。

**Comment by Sample-design-alt** [comment]
你好，关于第一个问题，我还是有一些疑惑，我看在code中
https://github.com/zhouhaoyi/Informer2020/blob/99b59c181f871a1521a798a37287a27ba5b742a7/models/attn.py#L53-L55
是随机选取的，并且我在b站上也看到关于你们在AI drive上的分享，
![image](https://user-images.githubusercontent.com/66257621/113652829-2185b080-96c7-11eb-89bd-b0c8aeb5e299.png)
我不知道是不是我错过了哪些细节，我并没有看到计算Max和mean，或者能在code中指出一下吗，谢谢

**Comment by zhouhaoyi** [comment]
就在这个code lines中，你可以看到我们是直接随机的index，这个就意味着并没有确定性地选择哪一位K。
同时，我指的max和mean就是从伪代码的第3-4行，是对选取的这些Q-K的对进行sample score的计算。

**Comment by Sample-design-alt** [comment]
谢谢。我明白了。
