### ISSUE TITLE
mask in encoder and decoder

### ISSUE THREAD

**Issue by sanwei111** [zhouhaoyi/Informer2020#81]
I JUST wonder that in encoder's multi-head attn,it don't use the mask,which padding the Indefinite length sequence？？？and for the second question，did your mask used in decoder‘s first attention means the sequence predict mask ？
thx so much if you can offer me sone tips

**Comment by zhouhaoyi** [comment]
1. We follow the original transformer that there is no mask in the encoder.
2. The mask in the decoder is applied to avoid perturbation from unknown predictions.
Regrds

**Comment by sanwei111** [comment]
> 1. We follow the original transformer that there is no mask in the encoder.
> 2. The mask in the decoder is applied to avoid perturbation from unknown predictions.
>    Regrds

as you see，transformer first used in NLP，so ,it's commonly believed that the corups( each sentence) fed into the encoder have different lengths.in order to fix the question,we have to pad the shorter sentence with zero,so that the sentences fed into encoder all have the same length,which can have some convenience to the latter operation.

**Comment by zhouhaoyi** [comment]
Sure, I know that the padding strategy is applied in the NLP field to support the Indefinite length inputs. However, in the time-series task, the inputs are sampled from the sliding windows on the train set. If you want to try this model in the NLP task, I think the zero-padding could also be used and the ProbSparse Attention is a transparent replacement of the canonical self-attention.

**Comment by sanwei111** [comment]
just one more question，does every data fed into informer‘s encoder’ have same length in the field of time series forcasting.you know,int the field of nlp,every sentence(data) have different sequence usually.

**Comment by zhouhaoyi** [comment]
> just one more question，does every data fed into informer‘s encoder’ have same length in the field of time series forcasting.you know,int the field of nlp,every sentence(data) have different sequence usually.

Sure, each feeding data has the same length. But we have discussed some special cases with indefinite length in medical sequences processing. I think it is interesting to mimic the similar strategy in NLP.

**Comment by sanwei111** [comment]
> > just one more question，does every data fed into informer‘s encoder’ have same length in the field of time series forcasting.you know,int the field of nlp,every sentence(data) have different sequence usually.
> 
> Sure, each feeding data has the same length. But we have discussed some special cases with indefinite length in medical sequences processing. I think it is interesting to mimic the similar strategy in NLP.

thx,Dr.Zhou,you really do me favor.

**Comment by zhouhaoyi** [comment]
You're welcome. Please feel free to contact us.
Suppose there is no more discussion. I will close this issue now.
