### ISSUE TITLE
encoder部分模型架构绘图工具

### ISSUE THREAD

**Issue by Rivers1de** [zhouhaoyi/Informer2020#84]
您好！ 请问论文模型中的encoder架构图(Fig.3)是用什么软件绘制的？感觉效果很不错，方便告诉一下嘛？

**Comment by zhouhaoyi** [comment]
并没有使用画图工具，就是Latex的TikZ package绘制而成。

**Comment by Rivers1de** [comment]
> 并没有使用画图工具，就是Latex的TikZ package绘制而成。

好的，谢谢您的回复。

**Comment by zhouhaoyi** [comment]
别客气，如果想使用的话，欢迎后续讨论。
