### ISSUE TITLE
多站点数据训练

### ISSUE THREAD

**Issue by XinWangTIM** [zhouhaoyi/Informer2020#85]
您好，请教下，你们只是用一个站点的训练数据进行训练评估？能将多个站点的数据用一个模型做训练并做输出吗，多一纬id，代码并没有体现

**Comment by zhouhaoyi** [comment]
目前的https://github.com/zhouhaoyi/ETDataset是单站点的，但是我们很快会realese多个站点的数据。同时我们的模型也会有进一步的更新，欢迎关注我们的后续工作和数据补充。
PS：目前的代码下，部分使用者也提到了如果数据量不足，想多个站点合并训练。可以参考issue #22。

**Comment by XinWangTIM** [comment]
> 目前的数据集是单站点的。https://github.com/zhouhaoyi/ETDataset
> 但是我们很快会realese多个站点的数据。同时我们的模型也会有进一步的更新，欢迎关注我们的后续工作和数据补充。
> PS：目前的代码下，部分使用者也提到了如果数据量不足，想多个站点合并训练。可以参考issue #22。

got it，期待realese新版本包含多站点数据

**Comment by XinWangTIM** [comment]
大概什么时候会realese多个站点的数据联合训练的code，有计划吗

**Comment by zhouhaoyi** [comment]
> 大概什么时候会realese多个站点的数据联合训练的code，有计划吗

顺利的话，应该会在3个月左右。

**Comment by bbzxc** [comment]
是不是到现在还没有release
