### ISSUE TITLE
多变量相关关系

### ISSUE THREAD

**Issue by fengkoushangdeZZX** [zhouhaoyi/Informer2020#86]
您好，非常欣赏您的工作，但是我有几个问题想向您请教，我想问一下您数据集里title包含HUFL,HULL,MUFL,LUFL这些是属于多变量吗？这些变量是否有相关关系？这部分是依靠multi-head机制体现吗？谢谢！

**Comment by cookieminions** [comment]
1. 属于多变量
2. 他们有相互关系，是同一台变压器的高中低有用无用功，关于数据的更多说明可以参考我们的数据repo [ETDataset](https://github.com/zhouhaoyi/ETDataset)
3. 和multi-head没有关系，关于multi-head机制可以参考Transformer本篇论文，可以认为这是增加Transformer表达性的一个机制

**Comment by fengkoushangdeZZX** [comment]
感谢您的回复，我的意思是挖掘这些变量间的相关关系是否对提高模型预测精度有帮助呢？您论文里attention部分计算的是时间维度上的相关性，在变量维度上的相关性在您的数据输入部分是怎么体现的呢？

**Comment by zhouhaoyi** [comment]
> 感谢您的回复，我的意思是挖掘这些变量间的相关关系是否对提高模型预测精度有帮助呢？您论文里attention部分计算的是时间维度上的相关性，在变量维度上的相关性在您的数据输入部分是怎么体现的呢？

变量维度的相关性是通过模型本身来抓取的，这个和一般的统计回归类模型不同。另外我们在输入处有一个简单的conv处理，你可以去查阅相关代码。

**Comment by fengkoushangdeZZX** [comment]
非常感谢您的回复，我会持续关注您的工作，多和您交流学习
