### ISSUE TITLE
informerstack and label_len

### ISSUE THREAD

**Issue by m13ammed** [zhouhaoyi/Informer2020#87]
First thank you for your very neat published code and your paper. I wanted to ask it was not clear for me what is the label_len parameter exactly is in your code. additionally what is the difference between the informer and informerstack models. Thank you again

**Comment by cookieminions** [comment]
`label_len` is the length of decoder start token, which is `X_token` shown in figure 1. We also describe the generation style decoder in our paper.
![image](https://user-images.githubusercontent.com/18379035/114139235-5d2baf00-9941-11eb-84e3-896270a33dd5.png)

`InformerStack` stacks several `Informer Encoder` with different layers, and each `Informer Encoder`  has different input length, you can refer to code `models/encoder.py` to get more information.
https://github.com/zhouhaoyi/Informer2020/blob/99b59c181f871a1521a798a37287a27ba5b742a7/models/encoder.py#L82-L97

**Comment by m13ammed** [comment]
This clears things up. Thank you very much for your thorough and quick explanation
