### ISSUE TITLE
Some questions about  `--features` settings : 'M', 'S', 'MS'

### ISSUE THREAD

**Issue by DAMONYLY** [zhouhaoyi/Informer2020#89]
Hello.
Thank you very much for making your code public as well as your data.
Regarding the `--features` in your code.
`parser.add_argument('--features', type=str, default='MS', help='forecasting task, options:[M, S, MS]; M:multivariate predict multivariate, S:univariate predict univariate, MS:multivariate predict univariate')`
I would like to know if this `MS` is using multivariate inputs to predict univariate results? Is Table 1 in your paper the results from the `MS` setting?
Also in your article I noticed the following sentence:
`Under this setting,each method attains predictions as a single variable over time series.` 
But I was not able to get from the above words whether the univariate task uses univariate inputs or multivariate inputs to predict univariates.
That means I want to know whether you are getting the results in Table 1 with the `MS` or `S` settings.
Also I am in your `.sh` files in the directory `./scripts/`, I also did not find the parameter settings in the case of `--features` set to `MS.`
Thanks in advance.

**Comment by cookieminions** [comment]
We use univariate input to predict univariate output in our experiments, so the `features` will be set to `S`. 

`--features MS` is using multivariate input to predict univariate output, it is an option we added based on the feedback on github, but we do not do enough experiments on it. You can choose `S` or `MS` according to your needs.

**Comment by DAMONYLY** [comment]
Thanks again for your prompt answer and solving the puzzle in my mind. I am now running your code under `MS` settings

**Comment by DAMONYLY** [comment]
Hi, agian.
I have reproduced your code according to your instructions and the results match the results in Table 1. 
However, when I use a simple recurrent neural network network (GRU) instead of Informer to complete the univariate prediction task, I find that the error result is significantly lower than your result, I think I should be wrong somewhere, and I hope you can help me point it out. Here are the results of using GRU for the univariate prediction task.
`>>>>>>>testing : GRU_ETTm1_ftS_sl96_ll24_pl24_dm256_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11497
test shape: (22, 512, 24, 1) (22, 512, 24, 1)
test shape: (11264, 24, 1) (11264, 24, 1)
mse:0.013519544154405594, mae:0.08506175875663757`

`>>>>>>>testing : GRU_ETTm1_ftS_sl96_ll24_pl48_dm256_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11473
test shape: (22, 512, 48, 1) (22, 512, 48, 1)
test shape: (11264, 48, 1) (11264, 48, 1)
mse:0.02977372519671917, mae:0.12998947501182556`

`>>>>>>>testing : GRU_ETTm1_ftS_sl384_ll384_pl96_dm256_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 11425
test shape: (22, 512, 96, 1) (22, 512, 96, 1)
test shape: (11264, 96, 1) (11264, 96, 1)
mse:0.0677323266863823, mae:0.2030424177646637`

**Comment by cookieminions** [comment]
1. In our experiments, we trained the LSTMa by making it predict next 1 point in the future, and then use the step-by-step prediction way to predict the sequence. And LSTMa may have a large variance when using step-by-step to predict long sequences.
2. You can draw the prediction curves after you get the LSTM results, and it may be a straight line in long sequence prediction.

**Comment by Erickurashi** [comment]
> Hi, agian.
> I have reproduced your code according to your instructions and the results match the results in Table 1.
> However, when I use a simple recurrent neural network network (GRU) instead of Informer to complete the univariate prediction task, I find that the error result is significantly lower than your result, I think I should be wrong somewhere, and I hope you can help me point it out. Here are the results of using GRU for the univariate prediction task.
> `>>>>>>>testing : GRU_ETTm1_ftS_sl96_ll24_pl24_dm256_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< test 11497 test shape: (22, 512, 24, 1) (22, 512, 24, 1) test shape: (11264, 24, 1) (11264, 24, 1) mse:0.013519544154405594, mae:0.08506175875663757`
> 
> `>>>>>>>testing : GRU_ETTm1_ftS_sl96_ll24_pl48_dm256_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< test 11473 test shape: (22, 512, 48, 1) (22, 512, 48, 1) test shape: (11264, 48, 1) (11264, 48, 1) mse:0.02977372519671917, mae:0.12998947501182556`
> 
> `>>>>>>>testing : GRU_ETTm1_ftS_sl384_ll384_pl96_dm256_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< test 11425 test shape: (22, 512, 96, 1) (22, 512, 96, 1) test shape: (11264, 96, 1) (11264, 96, 1) mse:0.0677323266863823, mae:0.2030424177646637`

Hi,
May I please ask how do you use the GRU model in the code?
Thank you very much.

**Comment by SSSUNSHINNING** [comment]
你好，我想问一下。在单变量预测任务中，到底预测是数据集中的哪个属性。

**Comment by Erickurashi** [comment]
> 你好，我想问一下。在单变量预测任务中，到底预测是数据集中的哪个属性。

在args.features下一列，args.target后面输入的属性是设置预测属性的地方

**Comment by Amber-LLl** [comment]
请问作者大大，多变量预测多变量features选择“M”，我所有的列都是我想要预测的，也就是说我想要用t时刻之前的所有列的值去预测t时刻之后的所有列的值，这时候的target应该怎么给呢？
