### ISSUE TITLE
Recommendations for Tuning 

### ISSUE THREAD

**Issue by m13ammed** [zhouhaoyi/Informer2020#90]
I am testing your work on my own time series data. However, unlike your datasets in my case increasing the encoder input surprisingly degrades the results  (not I am working with 24h output).  Do you have any recommendation to diagnose this result? 

How do you recommend tuning the seq_in , label_in (token) and maybe the number of encoder and decoder level or the factor? 

Additionally do you have recommendations regarding when to use the normal informer vs the stackInformer? 

Last point, I am having better results when using the univariate predictions, while when trying the MS f the forecasting the results are somehow worse than the S ones, do you have any recommendations to tackle this as well? 

If you recommend a tuning scheme it would save me a lot of time. Thank you for your contribution again.  Finally sorry for the many questions.

**Comment by cookieminions** [comment]
1. We did not do enough experiments on `--features MS`, this option is added based on the feedback from github.
2. MSE metric has some problems in evaluate long sequence prediction, low mse does not mean good prediction curve, maybe you can draw the prediction curve and groundtruth curve to decide whether to use `MS` or `S`.
3. `seq_len` and `label_len` can be set to some meaningful values related to periods such as 24, 48 or 720, you can also use InformerStack and customize the input length in code `models/model.py` line 102 and code `models/encoder.py` line 92 to make model get long input and short input at the same time.

**Comment by m13ammed** [comment]
I will try your recommendations and thank you for your notes.
