### ISSUE TITLE
set features='MS',  calculate loss/metrics using all univarient features

### ISSUE THREAD

**Issue by orydatadudes** [zhouhaoyi/Informer2020#91]
for my understanding , in 'MS' mode we use all columns (except date) and prediction the column we set in "target".
but when i print the shape of batch_y and outputs (during the train/test ) i can see that :
batch_y.shape
torch.Size([64, 24, 1])
outputs.shape
torch.Size([64, 24, 7])
so the loss and the metrics calculated by all columns
what i am missing?
thanks

**Comment by cookieminions** [comment]
Please check the parameter `c_out`, if you use `MS` mode, `c_out` of model should be set to 1.

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion, I will close this issue now.
