### ISSUE TITLE
about the training data timestamp

### ISSUE THREAD

**Issue by quyang950** [zhouhaoyi/Informer2020#92]
I saw your original data in etth1 is continuous.what if the original data  likes  stock price data which timestamp is not continuous,
what affects will occur for the result?

**Comment by cookieminions** [comment]
We did not do experiments on stock data, but you can considered that closing of previous day and opening of the next day are consecutive, and try to use the data directly.

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion, I will close this issue now.
