### ISSUE TITLE
Relationship between seq_len and label_len

### ISSUE THREAD

**Issue by QuantHao** [zhouhaoyi/Informer2020#94]
Hi, thanks for this thoughtful paper and sharing code base.

Based on my understanding, seq_len is used for sequence length of encoder inputs, while label_len is used for sequence length of decoder inputs. More importantly, it seems that seq_len always larger than label_len, such as @cookieminions wonderful graph demonstration at https://github.com/zhouhaoyi/Informer2020/issues/44#issuecomment-798897147, and code base, etc
https://github.com/zhouhaoyi/Informer2020/blob/99b59c181f871a1521a798a37287a27ba5b742a7/data/data_loader.py#L22-L23

However, in other time-series encoder-decoder paper, such as highly-cited one "A Dual-Stage Attention-Based Recurrent Neural Network for Time Series Prediction“ at https://arxiv.org/abs/1704.02971, authors use setting of seq_len == label_len. 

Thus, I am wondering is there any specific reasons for NOT setting seq_len == label_len?? Any help is greatly appreciated.

**Comment by cookieminions** [comment]
The label_len is the length of Decoder start token, it can be any value (greater than 0). Sometimes we may have a very long Encoder input, and set label_len==seq_len may cause large memory cost. So it will be better to set label_len according to the specific tasks.

**Comment by QuantHao** [comment]
Get it.
