### ISSUE TITLE
day_size = 32 and month_size = 13 in TemporalEmbedding 

### ISSUE THREAD

**Issue by QuantHao** [zhouhaoyi/Informer2020#96]
Hi, thanks for this thoughtful paper and sharing code base.

In TemporalEmbedding class, hour_size is set as 24, which is understandable, but I am confused why day_size is set as 32 (31 + 1?) and month_size is set as 13 (12 + 1?).
https://github.com/zhouhaoyi/Informer2020/blob/99b59c181f871a1521a798a37287a27ba5b742a7/models/embed.py#L63-L64

If we need to +1, then why not set hour_size as 25?

**Comment by cookieminions** [comment]
That's because `hour` is from 0 to 23, minute is from 0 to 3 and weekday is from 0 to 6, but we do not process the day and month when loading data, so the day will be 1-31, and month will be 1-12, and the embedding counts from 0.

**Comment by victorxie996** [comment]
> That's because `hour` is from 0 to 23, minute is from 0 to 3 and weekday is from 0 to 6, but we do not process the day and month when loading data, so the day will be 1-31, and month will be 1-12, and `torch.nn.Embedding` counts from 0.

Well explained! Thank you very much for your support

**Comment by zhouhaoyi** [comment]
Suppose there is no more discussion, I will close this issue now.
