### ISSUE TITLE
Dropout is created but never used in ProbAttention

### ISSUE THREAD

**Issue by QuantHao** [zhouhaoyi/Informer2020#97]
Hi, thanks for this thoughtful paper and sharing code base.

In FullAttention, dropout is applied at https://github.com/zhouhaoyi/Informer2020/blob/99b59c181f871a1521a798a37287a27ba5b742a7/models/attn.py#L30

However, in ProbAttention, I notice that dropout is created but never applied on scores
https://github.com/zhouhaoyi/Informer2020/blob/99b59c181f871a1521a798a37287a27ba5b742a7/models/attn.py#L119

Is it a design for specific reason or a negligence? Thanks.

**Comment by cookieminions** [comment]
It's a negligence, thanks for your remind.
Using dropout after we get `attn` in code `models/attn.py` line 88 is okay.

**Comment by QuantHao** [comment]
> It's a negligence, thanks for your remind.
> Using dropout after we get `attn` in code `models/attn.py` line 88 is okay.

Thanks for reply.
