### ISSUE TITLE
temporal_embedding对预测的影响

### ISSUE THREAD

**Issue by Erickurashi** [zhouhaoyi/Informer2020#98]
请问在embed中把**x = self.value_embedding(x) + self.position_embedding(x) + self.temporal_embedding(x_mark)** 改为 **self.value_embedding(x) + self.position_embedding(x)** 后，是否在训练时不在有设定的周期性的影响（例如周月年），而是完全让模型自己去学习。但我发现更改后mae和mse的变化很小，图像也相差不大，我想问一下self.temporal_embedding对模型训练的影响是否不大。谢谢您的建议。

**Comment by QuantHao** [comment]
我们在自己的数据上发现self.temporal_embedding(x_mark)的影响也很小。

**Comment by Erickurashi** [comment]
> 我们在自己的数据上发现self.temporal_embedding(x_mark)的影响也很小。
谢谢，我想请问一下您，无固定周期类型的时序预测，除了lstm和informer，还有其他的多步预测方法吗？

**Comment by cookieminions** [comment]
temporal embedding 是为了给模型提供更多可供参考的时间信息，对于某些与时间编码有强关联的数据可能会提高效果，而positional encoding则是更重要的提供序列前后顺序关系的编码。
我们之后可以做模型分解实验来分析各个embedding中各部分的作用，如果你的数据不添加temporal embedding也是有效的，那说明positional encoding和模型本身都发挥了效果

**Comment by zhouhaoyi** [comment]
需要提醒一点的是，论文中的对比都没有加入event/holiday embedding，为的是公平实验对比。但是实际应用中，特别是股票应用中请务必加入外源事件token。

**Comment by Erickurashi** [comment]
好的 感谢！
