### ISSUE TITLE
一些基础问题

### ISSUE THREAD

**Issue by SSSUNSHINNING** [zhouhaoyi/Informer2020#99]
首先非常感谢作者的分享，受益匪浅。下面我有几个问题想要询问一下，也期待所有看到这个提问的人们一起进行讨论。
1、在数据加载文件中，seq_len, label_len, pred_len这三个属性的设定是否遵循了哪些规则。
2、timeenc这个属性的作用，是在计算时间成本吗？
3、在进行数据集分割中，border1s和border2s的标准是什么，12*30*24是如何得到的。

**Comment by QuantHao** [comment]
Q1 is duplicate of #94

**Comment by cookieminions** [comment]
1. `pred_len` 是预测序列的长度，`label_len`是Decoder的start token的长度，这个的设定根据你的预测任务来，可以自由设定，`seq_len`是Encoder输入序列的长度，同样可以自由设定，建议的输入长度是一些和实际周期有关的数，例如预测24小时的数据，可以使用前一周的数据7*24小时作为`seq_len`，使用前一天的数据24小时作为`label_len`；关于输入可以参考模型结构图
![image](https://user-images.githubusercontent.com/18379035/114534062-2a572300-9c81-11eb-88d5-d24f9f9155b2.png)

2. timeenc只是Dataloader实现时为了区别不同的时间编码方式做的一个标记，不同的timeenc会加载出不同的timestamp
3. `12 * 30 * 24`是为了方便取的12个月每月30天每天24个小时，并不是严格意义的一年

**Comment by fengkoushangdeZZX** [comment]
您好，我还想接着问一下border1s和border2s的含义什么？我没看懂data_loader这里面train，val，test是怎么分割的啊？

**Comment by cookieminions** [comment]
> 您好，我还想接着问一下border1s和border2s的含义什么？我没看懂data_loader这里面train，val，test是怎么分割的啊？

border1s和borders2s只是为了方便train val和test取值，不同数据集的具体分割方式在论文中有提到，如果要从代码理解，建议你阅读`Dataset_Custom`部分，自定义数据集是按照70%，10%和20%分割的

https://github.com/zhouhaoyi/Informer2020/blob/410535ebeb59e526a7402e0454235fe1cab83605/data/data_loader.py#L222-L228

**Comment by SSSUNSHINNING** [comment]
弱弱的问一下，为啥会有inverse的操作

**Comment by cookieminions** [comment]
> 弱弱的问一下，为啥会有inverse的操作

inverse是后面增加的一个功能，是因为github上有人反馈希望可以增加一个将标准化的数值缩放回原来的数据尺度的功能，所以增加的

**Comment by XinWangTIM** [comment]
多个站点的数据序列在Dataset_Custom如何处理呢

**Comment by SSSUNSHINNING** [comment]
if self.inverse:  
            self.data_y = df_data.values[border1:border2]  
        else:
            self.data_y = data[border1:border2]
这段代码在归一化操作后，inverse的真假带来的具体区别是什么，我觉得除了形式不同无区别。若真是形式不同，那么这两种形式的作用是什么。
